/* eslint-disable @atlaskit/editor/no-re-export */
// Entry file in package.json

export {
	akEditorBlockquoteBorderColor,
	akEditorBreakoutPadding,
	akEditorCodeBackground,
	akEditorCodeBlockPadding,
	akEditorCodeFontFamily,
	akEditorCodeInlinePadding,
	akEditorContextPanelWidth,
	akEditorDefaultLayoutWidth,
	akEditorDeleteBackground,
	akEditorDeleteBackgroundWithOpacity,
	akEditorDeleteBorder,
	akEditorDeleteIconColor,
	akEditorFloatingDialogZIndex,
	akEditorFloatingOverlapPanelZIndex,
	akEditorFloatingPanelZIndex,
	akEditorFullPageMaxWidth,
	akEditorFullPageDefaultFontSize,
	akEditorFullPageDenseFontSize,
	akEditorFullWidthLayoutWidth,
	akEditorFullWidthLayoutLineLength,
	akEditorGridLineZIndex,
	akEditorGutterPadding,
	akEditorGutterPaddingDynamic,
	akEditorGutterPaddingReduced,
	akEditorFullPageNarrowBreakout,
	akEditorMediaResizeHandlerPadding,
	akEditorMediaResizeHandlerPaddingWide,
	akEditorMenuZIndex,
	akEditorStickyHeaderZIndex,
	akEditorMobileBreakoutPoint,
	akEditorSelectedBoldBoxShadow,
	akEditorSelectedBorderColor,
	akEditorSelectedBorderBoldSize,
	akEditorSelectedBorderSize,
	akEditorSelectedBorder,
	akEditorSelectedBoxShadow,
	akEditorSelectedBlanketOpacity,
	akEditorSmallZIndex,
	akEditorShadowZIndex,
	akEditorSubtleAccent,
	akEditorSwoopCubicBezier,
	akEditorTableBorder,
	akEditorTableBorderRadius,
	akEditorTableBorderSelected,
	akEditorTableCellBackgroundOpacity,
	akEditorTableCellMinWidth,
	akEditorTableCellOnStickyHeaderZIndex,
	akEditorTableHeaderCellBackground,
	akEditorTableHeaderCellBackgroundDark,
	akEditorTableLegacyCellMinWidth,
	akEditorTableNumberColumnWidth,
	akEditorTableToolbar,
	akEditorTableToolbarSize,
	akEditorUnitZIndex,
	akEditorCalculatedWideLayoutWidth,
	akEditorCalculatedWideLayoutWidthSmallViewport,
	akEditorWideLayoutWidth,
	akLayoutGutterOffset,
	akRichMediaResizeZIndex,
	avatarColors,
	participantColors,
	blockNodesVerticalMargin,
	scaledBlockNodesVerticalMargin,
	breakoutWideScaleRatio,
	editorFontSize,
	gridMediumMaxWidth,
	relativeSize,
	relativeFontSizeToBase16,
	DEFAULT_EMBED_CARD_HEIGHT,
	DEFAULT_EMBED_CARD_WIDTH,
	akEditorLineHeight,
	akEditorRuleBorderRadius,
	akEditorSelectedNodeClassName,
	akEditorToolbarKeylineHeight,
	MAX_BROWSER_SCROLLBAR_HEIGHT,
	VIEWPORT_SIZES,
	akEditorMobileMaxWidth,
	getTableCellBackgroundDarkModeColors,
	ATLASSIAN_NAVIGATION_HEIGHT,
	FULL_PAGE_EDITOR_TOOLBAR_HEIGHT,
	akEditorFullPageToolbarHeight,
	akEditorTableCellBlanketSelected,
	akEditorTableCellBlanketDeleted,
	akEditorWrappedNodeZIndex,
	layoutBreakpointWidth,
} from './consts';
export type { EditorTheme, ParticipantColor } from './consts';

export {
	SelectionStyle,
	getSelectionStyles,
	hideNativeBrowserTextSelectionStyles,
} from './selection';

export { overflowShadow } from './overflow-shadow/overflow-shadow';

export { getHashCode, getParticipantColor } from './utils';
