export const legacyColorMetaMap: Record<string, string[]> = {
	R50: ['danger'],
	R75: ['danger'],
	R100: ['danger'],
	R200: ['danger'],
	R300: ['danger', 'bold'],
	R400: ['danger', 'bold'],
	R500: ['danger', 'bold'],
	Y50: ['warning'],
	Y75: ['warning'],
	Y100: ['warning'],
	Y200: ['warning'],
	Y300: ['warning', 'bold'],
	Y400: ['warning', 'bold'],
	Y500: ['warning', 'bold'],
	G50: ['success'],
	G75: ['success'],
	G100: ['success'],
	G200: ['success'],
	G300: ['success'],
	G400: ['success'],
	G500: ['success'],
	B50: ['information'],
	B75: ['information'],
	B100: ['information'],
	B200: ['information'],
	B300: ['information', 'bold'],
	B400: ['information', 'bold'],
	B500: ['information', 'bold'],
	P50: ['discovery'],
	P75: ['discovery'],
	P100: ['discovery'],
	P200: ['discovery'],
	P300: ['discovery', 'bold'],
	P400: ['discovery', 'bold'],
	P500: ['discovery', 'bold'],
	T50: ['accent', 'teal'],
	T75: ['accent', 'teal'],
	T100: ['accent', 'teal'],
	T200: ['accent', 'teal'],
	T300: ['accent', 'teal'],
	T400: ['accent', 'teal'],
	T500: ['accent', 'teal'],
	N0: ['inverse'],
	N10: ['neutral'],
	N20: ['neutral'],
	N30: ['neutral'],
	N40: ['neutral'],
	N50: ['neutral'],
	N60: ['neutral'],
	N70: ['neutral'],
	N80: ['neutral'],
	N90: ['neutral'],
	N100: ['neutral'],
	N200: ['neutral'],
	N300: ['neutral'],
	N400: ['neutral'],
	N500: ['neutral'],
	N600: ['neutral'],
	N700: ['neutral'],
	N800: ['neutral'],
	N900: ['neutral'],
	background: ['background', 'default'],
	backgroundActive: ['background', 'pressed'],
	backgroundHover: ['background', 'hovered'],
	backgroundOnLayer: ['background', 'blanket'],
	text: ['text'],
	textHover: ['text', 'subtle'],
	textActive: ['text', 'link', 'pressed'],
	subtleText: ['text', 'subtlest'],
	placeholderText: ['text', 'subtlest'],
	heading: ['text'],
	subtleHeading: ['text', 'subtle'],
	link: ['link'],
	linkHover: ['link', 'hovered'],
	linkActive: ['link', 'pressed'],
	linkOutline: ['border', 'selected'],
	primary: ['brand'],
	blue: ['accent', 'blue'],
	teal: ['accent', 'teal'],
	purple: ['accent', 'purple'],
	red: ['accent', 'red'],
	yellow: ['accent', 'orange'],
	green: ['accent', 'green'],
	grey: ['background', 'neutral'],
	skeleton: ['skeleton'],
	white: ['inverse'],
};
