/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Finnish
export default {
  'fabric.media.accounts': 'Tilit',
  'fabric.media.actions': 'Toiminnot',
  'fabric.media.add_account': 'Lisää tili',
  'fabric.media.annotate': 'Tee merkintöjä',
  'fabric.media.annotate.confirmation.close.anyway': 'Sulje joka tapauksessa',
  'fabric.media.annotate.confirmation.content':
    'Sinulla on tallentamattomia muutoksia. Haluatko varmasti poistua?',
  'fabric.media.annotate.confirmation.heading': 'Tallentamattomat muutokset',
  'fabric.media.annotate.tool.arrow': 'Nuoli',
  'fabric.media.annotate.tool.blur': 'Sumennus',
  'fabric.media.annotate.tool.brush': 'Sivellin',
  'fabric.media.annotate.tool.color': 'Väri',
  'fabric.media.annotate.tool.line.thickness': 'Viivan paksuus',
  'fabric.media.annotate.tool.shape': 'Muoto',
  'fabric.media.annotate.tool.text': 'Teksti',
  'fabric.media.archive': 'arkistoi',
  'fabric.media.audio': 'ääni',
  'fabric.media.cancel': 'Peruuta',
  'fabric.media.cant_preview_file_type':
    'Tätä tiedostotyyppiä ei voi esikatsella.',
  'fabric.media.cant_retrieve_files':
    'Voi ei! Emme voineet noutaa yhtään tiedostoa',
  'fabric.media.cant_retrieve_gifs': 'Voi ei! Emme voineet noutaa yhtään GIFiä',
  'fabric.media.check_your_network': 'Tarkista verkkoyhteytesi',
  'fabric.media.click_to_join': 'Liity käyttämään tuotetta {context}',
  'fabric.media.click_to_join_description':
    'Sinut on hyväksytty, joten voit liittyä heti tuotteen {context} käyttäjäksi.',
  'fabric.media.close': 'Sulje',
  'fabric.media.close_and_reopen':
    'Kokeile sulkea tämä tiedosto ja avata se uudelleen.',
  'fabric.media.connect_account_description':
    'Avaamme uuden sivun, jotta voimme auttaa sinua yhdistämään {name} -tilisi',
  'fabric.media.connect_link_account': 'Yhdistä esikatseluun',
  'fabric.media.connect_link_account_card_view': 'Yhdistä',
  'fabric.media.connect_link_account_card_view_description':
    'Jotta voit esikatsella tätä linkkiä, yhdistä {context}-tilisi.',
  'fabric.media.connect_link_account_card_view_name':
    'Yhdistä {context}-tilisi',
  'fabric.media.connect_to': 'Yhdistä kohteeseen {name}',
  'fabric.media.could_not_load_editor': 'Voi ei! Muokkainta ei voitu ladata',
  'fabric.media.could_not_save_image': 'Voi ei! Kuvaa ei voitu tallentaa',
  'fabric.media.couldnt_generate_encrypted_entry_preview':
    'Salattuja tai salasanalla suojattuja tiedostoja ei voi esikatsella.',
  'fabric.media.couldnt_generate_preview':
    'Tälle tiedostolle ei voitu luoda esikatselua.',
  'fabric.media.couldnt_load_file': 'Tiedostoa ei voitu ladata.',
  'fabric.media.couldnt_load_link':
    'Tämän linkin lataaminen epäonnistui tuntemattomasta syystä.',
  'fabric.media.creating_preview': 'Luodaan esikatselua...',
  'fabric.media.default_avatars': 'Oletusavatarit',
  'fabric.media.disable_fullscreen': 'poista kokoruututila käytöstä',
  'fabric.media.document': 'asiakirja',
  'fabric.media.download': 'Lataa',
  'fabric.media.drag_and_drop_images_here': 'Vedä ja pudota kuvasi tänne',
  'fabric.media.drag_and_drop_your_files':
    'Vedä ja pudota tiedostosi minne tahansa tai',
  'fabric.media.drag_and_drop_your_files_and_folders':
    'Vedä ja pudota tiedostosi ja kansiosi minne tahansa tai',
  'fabric.media.drop_your_files': 'Pudota tiedostosi ladattavaksi',
  'fabric.media.drop_your_files_here': 'Pudota tiedostosi tänne',
  'fabric.media.email': 'Sähköposti',
  'fabric.media.enable_fullscreen': 'ota kokoruututila käyttöön',
  'fabric.media.error_429': 'Virhe 429',
  'fabric.media.error_generating_preview': 'Virhe esikatselun luomisessa',
  'fabric.media.error_hint_critical':
    'Jos ongelma toistuu jatkuvasti, ota yhteyttä tukeen.',
  'fabric.media.error_hint_retry':
    'Yritä uudelleen, ja mekin kokeilemme vielä kerran.',
  'fabric.media.error_loading_file': 'Virhe ladattaessa tiedostoa',
  'fabric.media.failed_to_load': 'Ei voitu ladata',
  'fabric.media.forbidden_description':
    'Sinulla ei ole tämän esikatselun käyttöoikeutta. Jos tarvitset käyttöoikeuden, ota yhteyttä sivuston ylläpitäjään.',
  'fabric.media.give_feedback': 'Anna palautetta',
  'fabric.media.image': 'kuva',
  'fabric.media.image_format_invalid_error':
    'Kuvaa ei voitu ladata, muoto on virheellinen.',
  'fabric.media.image_size_too_large_error':
    'Kuva on liian suuri, se ei voi olla suurempi kuin {MAX_SIZE_MB}Mt',
  'fabric.media.image_url_invalid_error':
    'Kuvaa ei voitu ladata, url-osoite on virheellinen.',
  'fabric.media.insert_files':
    '{0, plural, one {Lisää {0} tiedosto} other {Lisää {0} tiedostoa}}',
  'fabric.media.invalid_permissions': 'Rajoitettu linkki',
  'fabric.media.invalid_permissions_description':
    'Pyydä käyttöoikeus tai käytä toista tiliä, jos haluat nähdä tämän esikatselun.',
  'fabric.media.item_not_found_in_list':
    'Valittua kohdetta ei löytynyt luettelosta.',
  'fabric.media.learn_more': 'Lue lisää',
  'fabric.media.load_more_gifs': 'Lataa lisää GIFejä',
  'fabric.media.loading': 'Ladataan...',
  'fabric.media.loading_file': 'Ladataan tiedostoa...',
  'fabric.media.might_be_a_hiccup': 'Se saattaa olla vain tilapäinen ongelma.',
  'fabric.media.no_gifs_found': 'Hei? Minuako etsit?',
  'fabric.media.no_gifs_found_suggestion':
    'Emme löytäneet tuloksia kyselylle "{query}"',
  'fabric.media.no_pdf_artifacts':
    'PDF-artefaktoja ei löytynyt tälle tiedostolle.',
  'fabric.media.not_found_description':
    'Linkkiä ei löytynyt. Tarkista URL-osoite ja muokkaa tai liitä uudelleen.',
  'fabric.media.not_found_title': 'Oho. Emme löydä tätä linkkiä!',
  'fabric.media.or': 'tai',
  'fabric.media.pause': 'keskeytä',
  'fabric.media.play': 'toista',
  'fabric.media.playback_default_speed': 'Oletus',
  'fabric.media.playback_speed': 'Toistonopeus',
  'fabric.media.preview': 'Esikatselu',
  'fabric.media.preview_currently_unavailable':
    'Esikatselua ei tällä hetkellä saatavilla',
  'fabric.media.preview_rateLimited': 'Esikatselun luonnissa ilmeni vaikeuksia',
  'fabric.media.preview_unavailable': 'Esikatselua ei saatavilla',
  'fabric.media.recent_uploads': 'Viimeaikaiset lataukset',
  'fabric.media.remove_image': 'Poista kuva',
  'fabric.media.request_access': 'Pyydä pääsyä',
  'fabric.media.request_access_description':
    'Pyydä sovelluksen {context} käyttöoikeutta tämän esikatselun katsomista varten.',
  'fabric.media.request_access_pending': 'Käyttöoikeuksia odotetaan',
  'fabric.media.request_access_pending_description':
    'Käyttöoikeuspyyntösi on vireillä.',
  'fabric.media.request_denied_description':
    'Käyttöoikeuspyyntösi evättiin. Ota yhteyttä sivustosi ylläpitäjään, jos silti tarvitset käyttöoikeuden.',
  'fabric.media.retry': 'Yritä uudelleen',
  'fabric.media.save': 'Tallenna',
  'fabric.media.search': 'Hae',
  'fabric.media.search_all_gifs': 'Hae kaikista GIFeistä!',
  'fabric.media.share_files_instantly': 'Jaamme ne heti',
  'fabric.media.something_went_wrong': 'Jotain meni pieleen.',
  'fabric.media.srclink': 'Näytä kohteessa',
  'fabric.media.srclinkunknown': 'Näytä alkuperäinen',
  'fabric.media.text': 'Teksti',
  'fabric.media.try_again': 'Yritä uudelleen',
  'fabric.media.try_another_account': 'Kokeile toista tiliä',
  'fabric.media.try_downloading_file':
    'Kokeile ladata tiedosto, jotta voit tarkastella sitä.',
  'fabric.media.unable_to_annotate_image':
    'Et voi tehdä merkintöjä tähän kuvaan',
  'fabric.media.unknown': 'tuntematon',
  'fabric.media.unlink_account': 'Poista tilin linkitys',
  'fabric.media.upload': 'Lataa',
  'fabric.media.upload_an_avatar': 'Lataa avatar',
  'fabric.media.upload_file': 'Lataa tiedosto',
  'fabric.media.upload_file_from': 'Lataa tiedosto kohteesta {name}',
  'fabric.media.upload_image': 'Lataa kuva',
  'fabric.media.upload_photo': 'Lataa kuva',
  'fabric.media.video': 'video',
  'fabric.media.view': 'Näytä',
  'fabric.media.viewer_rateLimited': 'Tiedostosi lataamisessa on ongelma.',
  'fabric.media.webgl_warning_description':
    'Selaimesi ei tue WebGL:ää. Käytä WebGL:ää tukevaa selainta, jos haluat tehdä merkintöjä kuviin.',
  'fabric.media.zip_entry_load_failed':
    'Emme voineet ladata kyseistä zip-tiedoston kohdetta esikatselua varten',
  'fabric.media.zoom_in': 'lähennä',
  'fabric.media.zoom_out': 'loitonna',
};
