/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Russian
export default {
  'fabric.media.accounts': 'Аккаунты',
  'fabric.media.actions': 'Действия',
  'fabric.media.add_account': 'Добавить аккаунт',
  'fabric.media.annotate': 'Добавить примечание',
  'fabric.media.annotate.confirmation.close.anyway': 'Все равно закрыть',
  'fabric.media.annotate.confirmation.content':
    'Некоторые изменения не сохранены. Вы действительно хотите выйти?',
  'fabric.media.annotate.confirmation.heading': 'Несохраненные изменения',
  'fabric.media.annotate.tool.arrow': 'Стрелка',
  'fabric.media.annotate.tool.blur': 'Размытие',
  'fabric.media.annotate.tool.brush': 'Кисть',
  'fabric.media.annotate.tool.color': 'Цвет',
  'fabric.media.annotate.tool.line.thickness': 'Толщина линии',
  'fabric.media.annotate.tool.shape': 'Форма',
  'fabric.media.annotate.tool.text': 'Текст',
  'fabric.media.archive': 'архивировать',
  'fabric.media.audio': 'аудио',
  'fabric.media.cancel': 'Отменить',
  'fabric.media.cant_preview_file_type':
    'Предварительный просмотр файлов такого типа невозможен.',
  'fabric.media.cant_retrieve_files': 'К сожалению, не удалось получить файлы',
  'fabric.media.cant_retrieve_gifs': 'Не найдено ни одного файла GIF',
  'fabric.media.check_your_network': 'Проверьте подключение к сети',
  'fabric.media.click_to_join': 'Подключить {context}',
  'fabric.media.click_to_join_description':
    'Вы получили одобрение и можете присоединиться к продукту {context} прямо сейчас.',
  'fabric.media.close': 'Закрыть',
  'fabric.media.close_and_reopen':
    'Попробуйте закрыть этот файл и открыть его повторно.',
  'fabric.media.connect_account_description':
    'Откроется новая страница, где вы сможете подключить свой аккаунт {name}',
  'fabric.media.connect_link_account': 'Подключить для просмотра',
  'fabric.media.connect_link_account_card_view': 'Подключить',
  'fabric.media.connect_link_account_card_view_description':
    'Для предварительного просмотра этой ссылки подключите аккаунт {context}.',
  'fabric.media.connect_link_account_card_view_name':
    'Подключите свой аккаунт {context}',
  'fabric.media.connect_to': 'Подключить к {name}',
  'fabric.media.could_not_load_editor': 'Не удалось загрузить редактор',
  'fabric.media.could_not_save_image': 'Не удалось сохранить изображение',
  'fabric.media.couldnt_generate_encrypted_entry_preview':
    'Предварительный просмотр файлов, которые зашифрованы или защищены паролем, невозможен.',
  'fabric.media.couldnt_generate_preview':
    'Не удалось выполнить предварительный просмотр файла.',
  'fabric.media.couldnt_load_file': 'Не удалось загрузить файл.',
  'fabric.media.couldnt_load_link':
    'По неизвестной причине не удалось загрузить ссылку.',
  'fabric.media.creating_preview': 'Создание предварительного просмотра…',
  'fabric.media.default_avatars': 'Аватары по умолчанию',
  'fabric.media.disable_fullscreen': 'отключить полноэкранный режим',
  'fabric.media.document': 'документ',
  'fabric.media.download': 'Скачать',
  'fabric.media.drag_and_drop_images_here': 'Перетащите изображения сюда',
  'fabric.media.drag_and_drop_your_files': 'Перетащите файлы в любое место или',
  'fabric.media.drag_and_drop_your_files_and_folders':
    'Перетащите файлы и папки в любое место или',
  'fabric.media.drop_your_files': 'Перетащите файлы для загрузки',
  'fabric.media.drop_your_files_here': 'Перетащите файлы сюда',
  'fabric.media.email': 'Электронная почта',
  'fabric.media.enable_fullscreen': 'включить полноэкранный режим',
  'fabric.media.error_429': 'Ошибка 429',
  'fabric.media.error_generating_preview':
    'Не удалось создать предварительный просмотр для файла',
  'fabric.media.error_hint_critical':
    'Если проблема не исчезнет, обратитесь в службу поддержки.',
  'fabric.media.error_hint_retry': 'Повторите попытку.',
  'fabric.media.error_loading_file': 'При загрузке файла произошла ошибка',
  'fabric.media.failed_to_load': 'Не удалось загрузить файл.',
  'fabric.media.forbidden_description':
    'У вас нет доступа к предварительному просмотру. Если вам требуется доступ, обратитесь к администратору сайта.',
  'fabric.media.give_feedback': 'Оставить отзыв',
  'fabric.media.image': 'изображение',
  'fabric.media.image_format_invalid_error':
    'Не удалось загрузить изображение (недействительный формат).',
  'fabric.media.image_size_too_large_error':
    'Изображение превышает максимально допустимый размер ({MAX_SIZE_MB} МБ).',
  'fabric.media.image_url_invalid_error':
    'Не удалось загрузить изображение (недействительный URL).',
  'fabric.media.insert_files':
    '{0, plural, one {Вставить {0} файл} few {Вставить {0} файла} many {Вставить {0} файлов} other {Вставить {0} файла}}',
  'fabric.media.invalid_permissions': 'Ссылка с ограниченным доступом',
  'fabric.media.invalid_permissions_description':
    'Для предварительного просмотра этого элемента запросите право доступа или попробуйте воспользоваться другим аккаунтом.',
  'fabric.media.item_not_found_in_list': 'Выбранного объекта нет в списке.',
  'fabric.media.learn_more': 'Подробнее…',
  'fabric.media.load_more_gifs': 'Другие файлы GIF',
  'fabric.media.loading': 'Загрузка…',
  'fabric.media.loading_file': 'Загрузка файла…',
  'fabric.media.might_be_a_hiccup':
    'Скорее всего, это была небольшая техническая неполадка.',
  'fabric.media.no_gifs_found': 'Здравствуйте. Вы искали меня?',
  'fabric.media.no_gifs_found_suggestion':
    'По запросу «{query}» ничего не найдено',
  'fabric.media.no_pdf_artifacts': 'Нет PDF-артефактов для этого файла.',
  'fabric.media.not_found_description':
    'Не удалось найти ссылку. Проверьте URL-адрес и попробуйте изменить или вставить еще раз.',
  'fabric.media.not_found_title': 'К сожалению, не удалось найти эту ссылку.',
  'fabric.media.or': 'или',
  'fabric.media.pause': 'поставить на паузу',
  'fabric.media.play': 'воспроизвести',
  'fabric.media.playback_default_speed': 'По умолчанию',
  'fabric.media.playback_speed': 'Скорость воспроизведения',
  'fabric.media.preview': 'Предпросмотр',
  'fabric.media.preview_currently_unavailable':
    'Предварительный просмотр сейчас недоступен',
  'fabric.media.preview_rateLimited':
    'При создании предварительного просмотра возникли проблемы',
  'fabric.media.preview_unavailable': 'Предварительный просмотр недоступен',
  'fabric.media.recent_uploads': 'Недавно загруженные файлы',
  'fabric.media.remove_image': 'Удалить изображение',
  'fabric.media.request_access': 'Запросить доступ',
  'fabric.media.request_access_description':
    'Запросите доступ к продукту {context} для предварительного просмотра.',
  'fabric.media.request_access_pending': 'Ожидается предоставление доступа',
  'fabric.media.request_access_pending_description':
    'Ваш запрос на доступ ожидает рассмотрения.',
  'fabric.media.request_denied_description':
    'Ваш запрос на доступ отклонен. Если вам требуется доступ, обратитесь к администратору сайта.',
  'fabric.media.retry': 'Повторить',
  'fabric.media.save': 'Сохраните',
  'fabric.media.search': 'Поиск',
  'fabric.media.search_all_gifs': 'Поиск по всем файлам GIF',
  'fabric.media.share_files_instantly': 'Мы загрузим их автоматически',
  'fabric.media.something_went_wrong': 'Произошла ошибка.',
  'fabric.media.srclink': 'Просмотреть в',
  'fabric.media.srclinkunknown': 'Просмотреть оригинал',
  'fabric.media.text': 'Текст',
  'fabric.media.try_again': 'Повторить попытку',
  'fabric.media.try_another_account': 'Попробуйте использовать другой аккаунт',
  'fabric.media.try_downloading_file': 'Чтобы просмотреть файл, скачайте его.',
  'fabric.media.unable_to_annotate_image': 'Невозможно добавить примечание',
  'fabric.media.unknown': 'неизвестно',
  'fabric.media.unlink_account': 'Отменить связь с аккаунтом',
  'fabric.media.upload': 'Загрузить',
  'fabric.media.upload_an_avatar': 'Загрузите аватар',
  'fabric.media.upload_file': 'Загрузите файл',
  'fabric.media.upload_file_from': 'Загрузить файл из {name}',
  'fabric.media.upload_image': 'Загрузите изображение',
  'fabric.media.upload_photo': 'Загрузите фото',
  'fabric.media.video': 'видео',
  'fabric.media.view': 'Просмотреть',
  'fabric.media.viewer_rateLimited': 'Не удается загрузить файл.',
  'fabric.media.webgl_warning_description':
    'Эта функция недоступна. Чтобы добавлять примечания к изображениям, используйте браузер с поддержкой WebGL.',
  'fabric.media.zip_entry_load_failed':
    'Не удалось загрузить ZIP-файл для предварительного просмотра',
  'fabric.media.zoom_in': 'увеличить',
  'fabric.media.zoom_out': 'уменьшить',
};
