/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Vietnamese
export default {
  'fabric.media.accounts': 'Tài khoản',
  'fabric.media.actions': 'Hành động',
  'fabric.media.add_account': 'Thêm tài khoản',
  'fabric.media.annotate': 'Chú thích',
  'fabric.media.annotate.confirmation.close.anyway': 'Vẫn đóng',
  'fabric.media.annotate.confirmation.content':
    'Bạn chưa lưu một số thay đổi. Bạn có chắc chắn muốn thoát không?',
  'fabric.media.annotate.confirmation.heading': 'Các thay đổi chưa lưu',
  'fabric.media.annotate.tool.arrow': 'Mũi tên',
  'fabric.media.annotate.tool.blur': 'Làm mờ',
  'fabric.media.annotate.tool.brush': 'Cọ vẽ',
  'fabric.media.annotate.tool.color': 'Màu sắc',
  'fabric.media.annotate.tool.line.thickness': 'Độ dày đường nét',
  'fabric.media.annotate.tool.shape': 'Hình dạng',
  'fabric.media.annotate.tool.text': 'Văn bản',
  'fabric.media.archive': 'lưu trữ',
  'fabric.media.audio': 'âm thanh',
  'fabric.media.cancel': 'Hủy',
  'fabric.media.cant_preview_file_type':
    'Chúng tôi không thể xem trước loại tệp này.',
  'fabric.media.cant_retrieve_files':
    'Ôi! Chúng tôi không thể truy xuất bất kỳ tệp nào',
  'fabric.media.cant_retrieve_gifs':
    'Ôi! Chúng tôi không thể truy xuất bất kỳ tệp GIF nào',
  'fabric.media.check_your_network': 'Kiểm tra kết nối mạng của bạn',
  'fabric.media.click_to_join': 'Tham gia {context}',
  'fabric.media.click_to_join_description':
    'Bạn đã được phê duyệt nên bạn có thể tham gia {context} ngay.',
  'fabric.media.close': 'Đóng',
  'fabric.media.close_and_reopen': 'Hãy thử đóng tệp này và mở lại.',
  'fabric.media.connect_account_description':
    'Chúng tôi sẽ mở một trang mới để giúp bạn kết nối tài khoản {name} của bạn',
  'fabric.media.connect_link_account': 'Kết nối để xem trước',
  'fabric.media.connect_link_account_card_view': 'Kết nối',
  'fabric.media.connect_link_account_card_view_description':
    'Để hiển thị bản xem trước của đường liên kết này, hãy kết nối tài khoản {context} của bạn.',
  'fabric.media.connect_link_account_card_view_name':
    'Kết nối tài khoản {context} của bạn',
  'fabric.media.connect_to': 'Kết nối với {name}',
  'fabric.media.could_not_load_editor':
    'Ối! Chúng tôi không thể tải trình chỉnh sửa',
  'fabric.media.could_not_save_image': 'Ối! Chúng tôi không thể lưu hình ảnh',
  'fabric.media.couldnt_generate_encrypted_entry_preview':
    'Chúng tôi không thể xem trước các tệp được mã hóa hoặc được bảo vệ bằng mật khẩu.',
  'fabric.media.couldnt_generate_preview':
    'Chúng tôi không thể tạo bản xem trước cho tệp này.',
  'fabric.media.couldnt_load_file': 'Chúng tôi không thể tải tệp.',
  'fabric.media.couldnt_load_link':
    'Chúng tôi không thể tải đường liên kết này vì một lý do không xác định.',
  'fabric.media.creating_preview': 'Đang tạo bản xem trước...',
  'fabric.media.default_avatars': 'Ảnh đại diện mặc định',
  'fabric.media.disable_fullscreen': 'tắt chức năng toàn màn hình',
  'fabric.media.document': 'tài liệu',
  'fabric.media.download': 'Tải xuống',
  'fabric.media.drag_and_drop_images_here':
    'Kéo và thả hình ảnh của bạn tại đây',
  'fabric.media.drag_and_drop_your_files':
    'Kéo và thả các tệp của bạn bất kỳ nơi nào hoặc',
  'fabric.media.drag_and_drop_your_files_and_folders':
    'Kéo và thả tệp và thư mục bất cứ đâu hoặc',
  'fabric.media.drop_your_files': 'Thả các tệp của bạn để đăng tải',
  'fabric.media.drop_your_files_here': 'Thả các tệp của bạn tại đây',
  'fabric.media.email': 'email',
  'fabric.media.enable_fullscreen': 'bật chức năng toàn màn hình',
  'fabric.media.error_429': 'Lỗi 429',
  'fabric.media.error_generating_preview': 'Lỗi khi tạo bản xem trước',
  'fabric.media.error_hint_critical':
    'Nếu vẫn xảy ra sự cố, hãy liên hệ với bộ phận hỗ trợ.',
  'fabric.media.error_hint_retry': 'Hãy thử lại và chúng tôi sẽ chụp lại ảnh.',
  'fabric.media.error_loading_file': 'Lỗi khi tải tệp',
  'fabric.media.failed_to_load': 'Không thể tải',
  'fabric.media.forbidden_description':
    'Bạn không có quyền truy cập vào bản xem trước này. Hãy liên hệ với quản trị viên trang web nếu bạn cần quyền truy cập.',
  'fabric.media.give_feedback': 'Đưa ra phản hồi',
  'fabric.media.image': 'hình ảnh',
  'fabric.media.image_format_invalid_error':
    'Không thể tải hình ảnh, định dạng không hợp lệ.',
  'fabric.media.image_size_too_large_error':
    'Hình ảnh quá lớn, kích thước hình ảnh không được lớn hơn {MAX_SIZE_MB}Mb',
  'fabric.media.image_url_invalid_error':
    'Không thể tải hình ảnh, url không hợp lệ.',
  'fabric.media.insert_files': '{0, plural, other {Chèn {0} tệp}}',
  'fabric.media.invalid_permissions': 'Đường liên kết bị hạn chế',
  'fabric.media.invalid_permissions_description':
    'Bạn cần có quyền truy cập hoặc thử một tài khoản khác để xem bản xem trước này.',
  'fabric.media.item_not_found_in_list':
    'Không tìm thấy mục đã chọn trên danh sách.',
  'fabric.media.learn_more': 'Tìm hiểu thêm',
  'fabric.media.load_more_gifs': 'Tải thêm GIF',
  'fabric.media.loading': 'Đang tải...',
  'fabric.media.loading_file': 'Đang tải tệp...',
  'fabric.media.might_be_a_hiccup': 'Có thể do có chút sự cố.',
  'fabric.media.no_gifs_found': 'Xin chào? Bạn đang tìm tôi phải không nhỉ?',
  'fabric.media.no_gifs_found_suggestion':
    'Chúng tôi không thể tìm thấy bất kỳ thứ gì cho "{query}"',
  'fabric.media.no_pdf_artifacts': 'Không tìm thấy bản PDF cho tệp này.',
  'fabric.media.not_found_description':
    'Chúng tôi không thể tìm thấy đường liên kết này. Hãy kiểm tra url và thử chỉnh sửa hoặc dán lại.',
  'fabric.media.not_found_title':
    'Ôi! Chúng tôi không thể tìm thấy liên kết này!',
  'fabric.media.or': 'hoặc',
  'fabric.media.pause': 'tạm dừng',
  'fabric.media.play': 'phát',
  'fabric.media.playback_default_speed': 'Mặc định',
  'fabric.media.playback_speed': 'Tốc độ phát',
  'fabric.media.preview': 'Xem trước',
  'fabric.media.preview_currently_unavailable':
    'Bản xem trước hiện không khả dụng',
  'fabric.media.preview_rateLimited':
    'Chúng tôi gặp khó khăn khi tạo bản xem trước',
  'fabric.media.preview_unavailable': 'Bản xem trước không khả dụng',
  'fabric.media.recent_uploads': 'Các nội dung tải lên gần đây',
  'fabric.media.remove_image': 'Xóa hình ảnh',
  'fabric.media.request_access': 'Yêu cầu cấp quyền truy cập',
  'fabric.media.request_access_description':
    'Yêu cầu quyền truy cập để {context} xem bản xem trước này.',
  'fabric.media.request_access_pending': 'Đang chờ xử lý quyền truy cập',
  'fabric.media.request_access_pending_description':
    'Đang chờ xử lý yêu cầu quyền truy cập của bạn.',
  'fabric.media.request_denied_description':
    'Yêu cầu quyền truy cập của bạn đã bị từ chối. Hãy liên hệ với quản trị viên trang web nếu bạn vẫn cần quyền truy cập.',
  'fabric.media.retry': 'Thử lại',
  'fabric.media.save': 'Lưu',
  'fabric.media.search': 'tìm kiếm',
  'fabric.media.search_all_gifs': 'Hãy tìm kiếm tất cả các GIF!',
  'fabric.media.share_files_instantly': 'Chúng tôi sẽ chia sẻ tệp ngay',
  'fabric.media.something_went_wrong': 'Đã xảy ra lỗi.',
  'fabric.media.srclink': 'Xem trong',
  'fabric.media.srclinkunknown': 'Xem bản gốc',
  'fabric.media.text': 'văn bản',
  'fabric.media.try_again': 'Thử lại',
  'fabric.media.try_another_account': 'Thử một tài khoản khác',
  'fabric.media.try_downloading_file': 'Thử tải xuống tệp để xem.',
  'fabric.media.unable_to_annotate_image':
    'Bạn không thể ghi chú thích cho hình ảnh này',
  'fabric.media.unknown': 'Không xác định',
  'fabric.media.unlink_account': 'Hủy liên kết tài khoản',
  'fabric.media.upload': 'Tải lên',
  'fabric.media.upload_an_avatar': 'Tải lên ảnh đại diện',
  'fabric.media.upload_file': 'Tải lên tệp',
  'fabric.media.upload_file_from': 'Tải lên tệp từ {name}',
  'fabric.media.upload_image': 'Tải lên hình ảnh',
  'fabric.media.upload_photo': 'Tải ảnh lên',
  'fabric.media.video': 'video',
  'fabric.media.view': 'Xem',
  'fabric.media.viewer_rateLimited':
    'Chúng tôi đang gặp sự cố khi tải tệp của bạn.',
  'fabric.media.webgl_warning_description':
    'Trình duyệt của bạn không hỗ trợ WebGL. Sử dụng trình duyệt đã bật WebGL để chú thích hình ảnh.',
  'fabric.media.zip_entry_load_failed':
    'Chúng tôi không thể tải mục tệp zip đó để xem trước',
  'fabric.media.zoom_in': 'phóng to',
  'fabric.media.zoom_out': 'thu nhỏ',
};
