/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Croatian (Croatia) [hr-HR]
export default {
  'fabric.emoji.add.custom.emoji.label': 'Dodaj svoj emotikon',
  'fabric.emoji.add.label': 'Dodaj emotikon',
  'fabric.emoji.cancel.label': 'Odustani',
  'fabric.emoji.categories.label': 'Odaberi kategoriju emotikona',
  'fabric.emoji.categories.search.results': 'Rezultati pretraživanja',
  'fabric.emoji.category.activity': 'Aktivnost',
  'fabric.emoji.category.all.uploads': 'Svi prijenosi',
  'fabric.emoji.category.flags': 'Oznake',
  'fabric.emoji.category.foods': 'Hrana i piće',
  'fabric.emoji.category.frequent': 'Česti',
  'fabric.emoji.category.nature': 'Priroda',
  'fabric.emoji.category.objects': 'Objekti',
  'fabric.emoji.category.people': 'Osobe',
  'fabric.emoji.category.places': 'Putovanje i mjesta',
  'fabric.emoji.category.productivity': 'Atlassian i produktivnost',
  'fabric.emoji.category.symbols': 'Simboli',
  'fabric.emoji.category.user.uploads': 'Tvoji prijenosi',
  'fabric.emoji.choose.file.screenReaderDescription':
    'Odaberi datoteku za emotikon. JPG, PNG ili GIF. Maksimalna veličina 1 MB',
  'fabric.emoji.choose.file.title': 'Odaberi datoteku',
  'fabric.emoji.delete.description': 'Svi postojeći primjeri ovog emotikona bit će zamijenjeni {emojiShortName}',
  'fabric.emoji.delete.label': 'Ukloni',
  'fabric.emoji.delete.screenreader.tooltip': 'Za brisanje {shortName} emotikona, pritisni Backspace',
  'fabric.emoji.delete.title': 'Ukloni emotikon',
  'fabric.emoji.delete.tooltip': 'Izbriši',
  'fabric.emoji.emojipicker.emoi.roledescription': 'gumb emotikona',
  'fabric.emoji.emojipicker.error': 'Greška!',
  'fabric.emoji.error.delete.failed': 'Neuspjelo uklanjanje',
  'fabric.emoji.error.image.too.big': 'Odabrana slika je veća od 1 MB',
  'fabric.emoji.error.invalid.image': 'Odabrana slika je nevaljana',
  'fabric.emoji.error.upload.failed': 'Neuspjeli prijenos',
  'fabric.emoji.error.upload.timeout': 'Vrijeme prijenosa je isteklo',
  'fabric.emoji.image.requirements': 'JPG, PNG ili GIF. Maksimalna veličina 1 MB.',
  'fabric.emoji.name.ariaLabel': 'Unesi naziv za novi emotikon',
  'fabric.emoji.picker': 'Birač emotikona',
  'fabric.emoji.pickerlist.grid': '{showSearchResults, select, true {Rezultati pretraživanja} other {Emotikoni}}',
  'fabric.emoji.pickerlist.tabpanel': 'Radnje emotikona i ploča s popisom',
  'fabric.emoji.placeholder': 'npr. bok',
  'fabric.emoji.preview': 'Tvoj novi emotikon {emoji} izgleda sjajno',
  'fabric.emoji.preview.title': 'Pregled',
  'fabric.emoji.retry.label': 'Pokušaj ponovno',
  'fabric.emoji.search.label': 'Naziv emotikona',
  'fabric.emoji.search.placeholder': 'Pretraživanje',
  'fabric.emoji.search.status': 'Pregled svih emotikona',
  'fabric.emoji.select.skin.list.ariaLabel': 'Birač tona kože',
  'fabric.emoji.select.skin.tone.ariaLabel': 'Odaberi svoj ton kože, {selectedTone} odabran',
};
