/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Korean
export default {
  'fabric.emoji.add.custom.emoji.label': '나만의 이모지 추가',
  'fabric.emoji.add.label': '이모지 추가',
  'fabric.emoji.cancel.label': '취소',
  'fabric.emoji.categories.label': '이모지 범주 선택',
  'fabric.emoji.categories.search.results': '검색 결과',
  'fabric.emoji.category.activity': '활동',
  'fabric.emoji.category.all.uploads': '모든 업로드',
  'fabric.emoji.category.flags': '플래그',
  'fabric.emoji.category.foods': '음식 및 음료',
  'fabric.emoji.category.frequent': '자주 사용',
  'fabric.emoji.category.nature': '자연',
  'fabric.emoji.category.objects': '물건',
  'fabric.emoji.category.people': '사용자',
  'fabric.emoji.category.places': '여행 및 장소',
  'fabric.emoji.category.productivity': '생산성',
  'fabric.emoji.category.symbols': '기호',
  'fabric.emoji.category.user.uploads': '내 업로드',
  'fabric.emoji.choose.file.screenReaderDescription':
    '이모지를 위한 파일을 선택하세요. JPG, PNG 또는 GIF. 최대 크기 1MB',
  'fabric.emoji.choose.file.title': '파일 선택',
  'fabric.emoji.delete.description': '이 이모지의 모든 기존 인스턴스가 {emojiShortName}(으)로 교체됩니다',
  'fabric.emoji.delete.label': '제거',
  'fabric.emoji.delete.screenreader.tooltip': '{shortName} 이모지를 삭제하려면 백스페이스 키를 누르세요',
  'fabric.emoji.delete.title': '이모지 제거',
  'fabric.emoji.delete.tooltip': '삭제',
  'fabric.emoji.emojipicker.emoi.roledescription': '이모지 버튼',
  'fabric.emoji.emojipicker.error': '오류!',
  'fabric.emoji.error.delete.failed': '제거 실패',
  'fabric.emoji.error.image.too.big': '선택된 이미지가 1MB보다 큽니다',
  'fabric.emoji.error.invalid.image': '선택된 이미지가 유효하지 않습니다',
  'fabric.emoji.error.upload.failed': '업로드 실패',
  'fabric.emoji.image.requirements': 'JPG, PNG 또는 GIF. 최대 1 MB 크기.',
  'fabric.emoji.name.ariaLabel': '새 이모지의 이름을 입력하세요.',
  'fabric.emoji.picker': '이모지 선택기',
  'fabric.emoji.pickerlist.grid': '{showSearchResults, select, true {검색 결과} other {이모지}}',
  'fabric.emoji.pickerlist.tabpanel': '이모지 동작 및 목록 패널',
  'fabric.emoji.placeholder': '예: 안녕하세요',
  'fabric.emoji.preview': '새로운 이모지 {emoji}가 멋지네요.',
  'fabric.emoji.preview.title': '미리 보기',
  'fabric.emoji.retry.label': '다시 시도',
  'fabric.emoji.search.label': '이모지 이름',
  'fabric.emoji.search.placeholder': '검색',
  'fabric.emoji.search.status': '모든 이모지 표시 중',
  'fabric.emoji.select.skin.list.ariaLabel': '피부색 선택기',
  'fabric.emoji.select.skin.tone.ariaLabel': '피부색을 선택하세요. {selectedTone} 선택함',
};
