/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'fabric.emoji.add.custom.emoji.label': 'Dodaj swoją własną emoji',
  'fabric.emoji.add.label': 'Dodaj emoji',
  'fabric.emoji.cancel.label': 'Anuluj',
  'fabric.emoji.categories.search.results': 'Wyniki wyszukiwania',
  'fabric.emoji.category.activity': 'Aktywność',
  'fabric.emoji.category.all.uploads': 'Wszystkie przekazane',
  'fabric.emoji.category.flags': 'Flagi',
  'fabric.emoji.category.foods': 'Jedzenie i napoje',
  'fabric.emoji.category.frequent': 'Częste',
  'fabric.emoji.category.nature': 'Natura',
  'fabric.emoji.category.objects': 'Obiekty',
  'fabric.emoji.category.people': 'Ludzie',
  'fabric.emoji.category.places': 'Podróże i miejsca',
  'fabric.emoji.category.productivity': 'Produktywność',
  'fabric.emoji.category.symbols': 'Symbole',
  'fabric.emoji.category.user.uploads': 'Twoje przekazane pliki',
  'fabric.emoji.choose.file.screenReaderDescription':
    'Wybierz plik dla emoji. JPG, PNG lub GIF. Maks. rozmiar to 1 MB.',
  'fabric.emoji.choose.file.title': 'Wybierz plik',
  'fabric.emoji.delete.description':
    'Wszystkie istniejące wystąpienia tego emoji zostaną zastąpione {emojiShortName}',
  'fabric.emoji.delete.label': 'Usuń',
  'fabric.emoji.delete.title': 'Usuń emoji',
  'fabric.emoji.error.delete.failed': 'Usunięcie nie powiodło się',
  'fabric.emoji.error.image.too.big': 'Wybrany obraz jest większy niż 1 MB',
  'fabric.emoji.error.invalid.image': 'Wybrany obraz jest niepoprawny',
  'fabric.emoji.error.upload.failed': 'Przekazywanie nie powiodło się',
  'fabric.emoji.image.requirements':
    'Plik JPG, PNG lub GIF. Maksymalny rozmiar 1 MB.',
  'fabric.emoji.name.ariaLabel': 'Wpisz nazwę dla nowego emoji',
  'fabric.emoji.placeholder': 'Nazwa emoji',
  'fabric.emoji.preview': 'Twoja nowa emoji {emoji} wygląda świetnie',
  'fabric.emoji.preview.title': 'Podgląd',
  'fabric.emoji.retry.label': 'Spróbuj ponownie',
  'fabric.emoji.search.label': 'Wyszukaj emoji',
  'fabric.emoji.search.placeholder': 'Szukaj',
  'fabric.emoji.select.skin.tone.ariaLabel':
    'Wybierz odcień skóry, {selectedTone}',
};
