// THIS FILE IS GENERATED via packages/editor/editor-plugins/scripts/update-editor-plugins.ts. DO NOT MODIFY IT MANUALLY.
// Disable no-re-export rule for entry point files
/* eslint-disable @atlaskit/editor/no-re-export */
export {
	hoverColumns,
	hoverRows,
	hoverTable,
	hoverCell,
	hoverMergedCells,
	clearHoverSelection,
	showResizeHandleLine,
	hideResizeHandleLine,
	setTableHovered,
	insertColumn,
	insertRow,
	createTable,
	getNextLayout,
	toggleContextualMenu,
	toggleHeaderColumn,
	toggleHeaderRow,
	toggleNumberColumn,
	toggleTableLayout,
	clearMultipleCells,
	autoSizeTable,
	convertFirstRowToHeader,
	deleteTable,
	hideInsertColumnOrRowButton,
	moveCursorBackward,
	selectColumn,
	selectColumns,
	selectRow,
	selectRows,
	setCellAttr,
	setEditorFocus,
	setMultipleCellAttrs,
	setTableRef,
	showInsertColumnButton,
	showInsertRowButton,
	transformSliceToAddTableHeaders,
	triggerUnlessTableHeader,
	addBoldInEmptyHeaderCells,
	addResizeHandleDecorations,
	updateWidthToWidest,
	setFocusToCellMenu,
	sortByColumn,
	goToNextCell,
	removeDescendantNodes,
	setTableDisplayMode,
} from '@atlaskit/editor-plugin-table/commands';
