export type {
  Predicate,
  DomAtPos,
  ContentNodeWithPos,
  NodeWithPos,
  //CellTransform,
  //MovementOptions,
} from 'prosemirror-utils';

export {
  findParentNode,
  findParentNodeClosestToPos,
  findParentDomRef,
  hasParentNode,
  findParentNodeOfType,
  findParentNodeOfTypeClosestToPos,
  hasParentNodeOfType,
  findParentDomRefOfType,
  findSelectedNodeOfType,
  isNodeSelection,
  findPositionOfNodeBefore,
  findDomRefAtPos,
  flatten,
  findChildren,
  findTextNodes,
  findInlineNodes,
  findBlockNodes,
  findChildrenByAttr,
  findChildrenByType,
  findChildrenByMark,
  contains,
  removeParentNodeOfType,
  replaceParentNodeOfType,
  removeSelectedNode,
  replaceSelectedNode,
  canInsert,
  safeInsert,
  setParentNodeMarkup,
  selectParentNodeOfType,
  removeNodeBefore,
  setTextSelection,
} from 'prosemirror-utils';
