export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH6ATWUAA0Fkb2JlLUphcGFuMS0yLmJjbWFwAB3KwYpBUQDG8cPSZl7hlDWu2d2lZKFk4T6B4TQULufelJVIkjRJ0qRJkiRJmiRJkngPj+JPfb/N19/7SEXtck3nv3OuDJumEfg0DFNGsvaXklbNcVXRkfFSxtZlW6ddlQ36IoWCfPeO1MpRuvo6LaVkMJSIR2NJK+bxCHGvV/xCNOqsiRba6KCLHn7QxwBDjPCLMf4wwRQzzLHAEiusscEW/9hhjwOOOOGMC67i4yaez/yQfekAAAA=';
