export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH6ATWUAA0dCSzJLLVYuYmNtYXAAY34Q5JxfUFmUmZ5RomBoaWmga2RgYKngmJKflKoQXFlckppbrOCZl5xfVJBflFiSmqLH5ZiTowBWX6xQlFqcWlQGEgxOTVXQ0/fxdHb1C3Z9yO7u5G3kreuRyLNwEUOLPQNDix0bQ0sYA+MeCSA7nIW3xc2OYY9UsxJDixMbY4sLE0OLLSPDHmluxhYHR5bF+1uc5TWkORkZgOy9e2RkGRgZFBgcRZcsbFwXzsjEKMAoysgnySDPAmQzs7E2GnEAGTyMgoxcCMG2Qj4AQBsl+dsAAAA=';
