export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH+ATWUAA0hhbmtha3UuYmNtYXAAY3oQ5JxfUFmUmZ5RomBoaWmga2RgYKngmJKflKoQXFlckppbrOCZl5xfVJBflFiSmqLH5ZiTowBWX6xQlFqcWlQGEgxOTVXQ0/fxdHb1C3ZlYGRorE/gUrBvTGdgAGLZJg0mliZ3Bs4WFgaGpjAGvhY+RjsgX7ZFloGxmQUAaUZ7z4QAAAA=';
