export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH+ATWUAA0hpcmFnYW5hLmJjbWFwAGN6EOScX1BZlJmeUaJgaGlpoGtkYGCp4JiSn5SqEFxZXJKaW6zgmZecX1SQX5RYkpqix+WYk6MAVl+sUJRanFpUBhIMTk1V0NP38XR29Qt2ZWBkaKxP4FBgaGFmYGlyZ+BsYWFgaApj0GnhY2BsZmFgarFmlmixAwBKqkYZfAAAAA==';
