export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH+ATWUAA0hLc2NzLUI1LVYuYmNtYXAAY34Q5JxfUFmUmZ5RomBoaWmga2RgYKngmJKflKoQXFlckppbrOCZl5xfVJBflFiSmqLH5ZiTowBWX6xQlFqcWlQGEgxOTVXQ0/fxdHb1C3Z9yOXhXZxcrOtkquuRyLEwlrGRiYmxkQ2IuYCYD4iFgFgMiKWAWC6RZaE3wys/PobX+owMrw0b2Rhe+ScyHnvC+E4QAKwf9+WfAAAA';
