export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH+ATWUAA0tTQy1FVUMtVi5iY21hcABjfhDknF9QWZSZnlGiYGhpaaBrZGBgqeCYkp+UqhBcWVySmlus4JmXnF9UkF+UWJKaosflmJOjAFZfrFCUWpxaVAYSDE5NVdDT9/F0dvULdn3I6R3srOsa6qzrkSiwcBHjvgpGhn1VDAwHGZiY9lUD2XUs3PvqdRn2czebMuznYWPcz8vEsJ+fkWG/ADfrfkFphv3iQLYEEEtKM++XAgC8xXcVpAAAAA==';
