export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH+ATWUAA1VuaUNOUy1VVEYzMi1WLmJjbWFwAGN+EOScX1BZlJmeUaJgaGlpoGtkYGCp4JiSn5SqEFxZXJKaW6zgmZecX1SQX5RYkpqix+WYk6MAVl+sUJRanFpUBhIMTk1V0NP38XR29Qt2fcgXmpfp7BesGxriZmyk6+HMxsCgIFzBwCQg3bxHs/EqWxN345VwRoZkdgYGAw7GRjEGxkYhIJYCYjkg5mNibORqnlvE2MgEAMZC97qgAAAA';
