export const value: string =
  'H4sICH+ATWUAA1VuaUpJUy1VQ1MyLUhXLUguYmNtYXAAY3oQ5JxfUFmUmZ5RomBoaWmga2RgYKngmJKflKoQXFlckppbrOCZl5xfVJBflFiSmqLH5ZiTowBWX6xQlFqcWlQGEgxOTVXQ0/fxdHb1C3Z9yBual+nlGawb6hxspOuRyMKgYN2YzsBwhJ9BsUlFjaFJGQAgu5FfdwAAAA==';
