export const value: string =
  'H4sICH+ATWUAA1VuaUtTLVVURjgtVi5iY21hcABjfhDknF9QWZSZnlGiYGhpaaBrZGBgqeCYkp+UqhBcWVySmlus4JmXnF9UkF+UWJKaosflmJOjAFZfrFCUWpxaVAYSDE5NVdDT9/F0dvULdn3IE5qX6R2sGxriZqHr4cT9qGHavlo+9ub/uQobvucycLEwMujwMDIwMjTGmbew2CSxP2qYzLivuvl/DuO+ClbO/YxMjPvqN3wvYtzPK8C6X7Cxmmm/FAC92sxCqQAAAA==';
