export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH+ATWUAA1VuaUtTLVVDUzItVi5iY21hcABjfhDknF9QWZSZnlGiYGhpaaBrZGBgqeCYkp+UqhBcWVySmlus4JmXnF9UkF+UWJKaosflmJOjAFZfrFCUWpxaVAYSDE5NVdDT9/F0dvULdn3IE5qX6R2sG+ocbKTrkSikIMy4r5qRYV8tH8O+qvnRjPsqWDn3MzIy7OdmYNxX3zw3m2E/Dxvjfl4mhv38QFEBbtb9gtIM+8WBbAkglpRm2i/FwLCvrpGFYb8sAOZluMayAAAA';
