export const value: string =
  'data:application/x-gzip-compressed;base64,H4sICH+ATWUAA1YuYmNtYXAAY34Q5JxfUFmUmZ5RomBoaWmga2RgYKngmJKflKoQXFlckppbrOCZl5xfVJBflFiSmqLH5ZiTowBWX6xQlFqcWlQGEgxOTVXQ0/fxdHb1C3Z9yOiRyKqoxLjXn5dxbyAn095gJpa9YSyCe6MdRRUT9+a22jMwQqEkgzyYZmNoNMIimMioWsq4jwkAuak1ZaYAAAA=';
