/**
 * THIS FILE WAS CREATED VIA CODEGEN DO NOT MODIFY {@see http://go/af-codegen}
 *
 * Strict design token based typedef representing a subset of safe CSS properties.
 *
 * @codegen <<SignedSource::cc0f430b2dc9a266797e1ba536c0ff30>>
 * @codegenCommand yarn build tokens
 */
export type BackgroundColorHovered =
	| 'var(--ds-background-accent-lime-subtlest-hovered)'
	| 'var(--ds-background-accent-lime-subtler-hovered)'
	| 'var(--ds-background-accent-lime-subtle-hovered)'
	| 'var(--ds-background-accent-lime-bolder-hovered)'
	| 'var(--ds-background-accent-red-subtlest-hovered)'
	| 'var(--ds-background-accent-red-subtler-hovered)'
	| 'var(--ds-background-accent-red-subtle-hovered)'
	| 'var(--ds-background-accent-red-bolder-hovered)'
	| 'var(--ds-background-accent-orange-subtlest-hovered)'
	| 'var(--ds-background-accent-orange-subtler-hovered)'
	| 'var(--ds-background-accent-orange-subtle-hovered)'
	| 'var(--ds-background-accent-orange-bolder-hovered)'
	| 'var(--ds-background-accent-yellow-subtlest-hovered)'
	| 'var(--ds-background-accent-yellow-subtler-hovered)'
	| 'var(--ds-background-accent-yellow-subtle-hovered)'
	| 'var(--ds-background-accent-yellow-bolder-hovered)'
	| 'var(--ds-background-accent-green-subtlest-hovered)'
	| 'var(--ds-background-accent-green-subtler-hovered)'
	| 'var(--ds-background-accent-green-subtle-hovered)'
	| 'var(--ds-background-accent-green-bolder-hovered)'
	| 'var(--ds-background-accent-teal-subtlest-hovered)'
	| 'var(--ds-background-accent-teal-subtler-hovered)'
	| 'var(--ds-background-accent-teal-subtle-hovered)'
	| 'var(--ds-background-accent-teal-bolder-hovered)'
	| 'var(--ds-background-accent-blue-subtlest-hovered)'
	| 'var(--ds-background-accent-blue-subtler-hovered)'
	| 'var(--ds-background-accent-blue-subtle-hovered)'
	| 'var(--ds-background-accent-blue-bolder-hovered)'
	| 'var(--ds-background-accent-purple-subtlest-hovered)'
	| 'var(--ds-background-accent-purple-subtler-hovered)'
	| 'var(--ds-background-accent-purple-subtle-hovered)'
	| 'var(--ds-background-accent-purple-bolder-hovered)'
	| 'var(--ds-background-accent-magenta-subtlest-hovered)'
	| 'var(--ds-background-accent-magenta-subtler-hovered)'
	| 'var(--ds-background-accent-magenta-subtle-hovered)'
	| 'var(--ds-background-accent-magenta-bolder-hovered)'
	| 'var(--ds-background-accent-gray-subtlest-hovered)'
	| 'var(--ds-background-accent-gray-subtler-hovered)'
	| 'var(--ds-background-accent-gray-subtle-hovered)'
	| 'var(--ds-background-accent-gray-bolder-hovered)'
	| 'var(--ds-background-input-hovered)'
	| 'var(--ds-background-inverse-subtle-hovered)'
	| 'var(--ds-background-neutral-hovered)'
	| 'var(--ds-background-neutral-subtle-hovered)'
	| 'var(--ds-background-neutral-bold-hovered)'
	| 'var(--ds-background-selected-hovered)'
	| 'var(--ds-background-selected-bold-hovered)'
	| 'var(--ds-background-brand-subtlest-hovered)'
	| 'var(--ds-background-brand-bold-hovered)'
	| 'var(--ds-background-brand-boldest-hovered)'
	| 'var(--ds-background-danger-hovered)'
	| 'var(--ds-background-danger-bold-hovered)'
	| 'var(--ds-background-warning-hovered)'
	| 'var(--ds-background-warning-bold-hovered)'
	| 'var(--ds-background-success-hovered)'
	| 'var(--ds-background-success-bold-hovered)'
	| 'var(--ds-background-discovery-hovered)'
	| 'var(--ds-background-discovery-bold-hovered)'
	| 'var(--ds-background-information-hovered)'
	| 'var(--ds-background-information-bold-hovered)'
	| 'var(--ds-surface-hovered)'
	| 'var(--ds-surface-overlay-hovered)'
	| 'var(--ds-surface-raised-hovered)';
export type BackgroundColorPressed =
	| 'var(--ds-background-accent-lime-subtlest-pressed)'
	| 'var(--ds-background-accent-lime-subtler-pressed)'
	| 'var(--ds-background-accent-lime-subtle-pressed)'
	| 'var(--ds-background-accent-lime-bolder-pressed)'
	| 'var(--ds-background-accent-red-subtlest-pressed)'
	| 'var(--ds-background-accent-red-subtler-pressed)'
	| 'var(--ds-background-accent-red-subtle-pressed)'
	| 'var(--ds-background-accent-red-bolder-pressed)'
	| 'var(--ds-background-accent-orange-subtlest-pressed)'
	| 'var(--ds-background-accent-orange-subtler-pressed)'
	| 'var(--ds-background-accent-orange-subtle-pressed)'
	| 'var(--ds-background-accent-orange-bolder-pressed)'
	| 'var(--ds-background-accent-yellow-subtlest-pressed)'
	| 'var(--ds-background-accent-yellow-subtler-pressed)'
	| 'var(--ds-background-accent-yellow-subtle-pressed)'
	| 'var(--ds-background-accent-yellow-bolder-pressed)'
	| 'var(--ds-background-accent-green-subtlest-pressed)'
	| 'var(--ds-background-accent-green-subtler-pressed)'
	| 'var(--ds-background-accent-green-subtle-pressed)'
	| 'var(--ds-background-accent-green-bolder-pressed)'
	| 'var(--ds-background-accent-teal-subtlest-pressed)'
	| 'var(--ds-background-accent-teal-subtler-pressed)'
	| 'var(--ds-background-accent-teal-subtle-pressed)'
	| 'var(--ds-background-accent-teal-bolder-pressed)'
	| 'var(--ds-background-accent-blue-subtlest-pressed)'
	| 'var(--ds-background-accent-blue-subtler-pressed)'
	| 'var(--ds-background-accent-blue-subtle-pressed)'
	| 'var(--ds-background-accent-blue-bolder-pressed)'
	| 'var(--ds-background-accent-purple-subtlest-pressed)'
	| 'var(--ds-background-accent-purple-subtler-pressed)'
	| 'var(--ds-background-accent-purple-subtle-pressed)'
	| 'var(--ds-background-accent-purple-bolder-pressed)'
	| 'var(--ds-background-accent-magenta-subtlest-pressed)'
	| 'var(--ds-background-accent-magenta-subtler-pressed)'
	| 'var(--ds-background-accent-magenta-subtle-pressed)'
	| 'var(--ds-background-accent-magenta-bolder-pressed)'
	| 'var(--ds-background-accent-gray-subtlest-pressed)'
	| 'var(--ds-background-accent-gray-subtler-pressed)'
	| 'var(--ds-background-accent-gray-subtle-pressed)'
	| 'var(--ds-background-accent-gray-bolder-pressed)'
	| 'var(--ds-background-input-pressed)'
	| 'var(--ds-background-inverse-subtle-pressed)'
	| 'var(--ds-background-neutral-pressed)'
	| 'var(--ds-background-neutral-subtle-pressed)'
	| 'var(--ds-background-neutral-bold-pressed)'
	| 'var(--ds-background-selected-pressed)'
	| 'var(--ds-background-selected-bold-pressed)'
	| 'var(--ds-background-brand-subtlest-pressed)'
	| 'var(--ds-background-brand-bold-pressed)'
	| 'var(--ds-background-brand-boldest-pressed)'
	| 'var(--ds-background-danger-pressed)'
	| 'var(--ds-background-danger-bold-pressed)'
	| 'var(--ds-background-warning-pressed)'
	| 'var(--ds-background-warning-bold-pressed)'
	| 'var(--ds-background-success-pressed)'
	| 'var(--ds-background-success-bold-pressed)'
	| 'var(--ds-background-discovery-pressed)'
	| 'var(--ds-background-discovery-bold-pressed)'
	| 'var(--ds-background-information-pressed)'
	| 'var(--ds-background-information-bold-pressed)'
	| 'var(--ds-surface-pressed)'
	| 'var(--ds-surface-overlay-pressed)'
	| 'var(--ds-surface-raised-pressed)';
export type BackgroundColor =
	| 'transparent'
	| 'currentcolor'
	| BackgroundColorHovered
	| BackgroundColorPressed
	| 'var(--ds-background-accent-lime-subtlest)'
	| 'var(--ds-background-accent-lime-subtler)'
	| 'var(--ds-background-accent-lime-subtle)'
	| 'var(--ds-background-accent-lime-bolder)'
	| 'var(--ds-background-accent-red-subtlest)'
	| 'var(--ds-background-accent-red-subtler)'
	| 'var(--ds-background-accent-red-subtle)'
	| 'var(--ds-background-accent-red-bolder)'
	| 'var(--ds-background-accent-orange-subtlest)'
	| 'var(--ds-background-accent-orange-subtler)'
	| 'var(--ds-background-accent-orange-subtle)'
	| 'var(--ds-background-accent-orange-bolder)'
	| 'var(--ds-background-accent-yellow-subtlest)'
	| 'var(--ds-background-accent-yellow-subtler)'
	| 'var(--ds-background-accent-yellow-subtle)'
	| 'var(--ds-background-accent-yellow-bolder)'
	| 'var(--ds-background-accent-green-subtlest)'
	| 'var(--ds-background-accent-green-subtler)'
	| 'var(--ds-background-accent-green-subtle)'
	| 'var(--ds-background-accent-green-bolder)'
	| 'var(--ds-background-accent-teal-subtlest)'
	| 'var(--ds-background-accent-teal-subtler)'
	| 'var(--ds-background-accent-teal-subtle)'
	| 'var(--ds-background-accent-teal-bolder)'
	| 'var(--ds-background-accent-blue-subtlest)'
	| 'var(--ds-background-accent-blue-subtler)'
	| 'var(--ds-background-accent-blue-subtle)'
	| 'var(--ds-background-accent-blue-bolder)'
	| 'var(--ds-background-accent-purple-subtlest)'
	| 'var(--ds-background-accent-purple-subtler)'
	| 'var(--ds-background-accent-purple-subtle)'
	| 'var(--ds-background-accent-purple-bolder)'
	| 'var(--ds-background-accent-magenta-subtlest)'
	| 'var(--ds-background-accent-magenta-subtler)'
	| 'var(--ds-background-accent-magenta-subtle)'
	| 'var(--ds-background-accent-magenta-bolder)'
	| 'var(--ds-background-accent-gray-subtlest)'
	| 'var(--ds-background-accent-gray-subtler)'
	| 'var(--ds-background-accent-gray-subtle)'
	| 'var(--ds-background-accent-gray-bolder)'
	| 'var(--ds-background-disabled)'
	| 'var(--ds-background-input)'
	| 'var(--ds-background-inverse-subtle)'
	| 'var(--ds-background-neutral)'
	| 'var(--ds-background-neutral-subtle)'
	| 'var(--ds-background-neutral-bold)'
	| 'var(--ds-background-selected)'
	| 'var(--ds-background-selected-bold)'
	| 'var(--ds-background-brand-subtlest)'
	| 'var(--ds-background-brand-bold)'
	| 'var(--ds-background-brand-boldest)'
	| 'var(--ds-background-danger)'
	| 'var(--ds-background-danger-bold)'
	| 'var(--ds-background-warning)'
	| 'var(--ds-background-warning-bold)'
	| 'var(--ds-background-success)'
	| 'var(--ds-background-success-bold)'
	| 'var(--ds-background-discovery)'
	| 'var(--ds-background-discovery-bold)'
	| 'var(--ds-background-information)'
	| 'var(--ds-background-information-bold)'
	| 'var(--ds-skeleton)'
	| 'var(--ds-skeleton-subtle)'
	| 'var(--ds-surface)'
	| 'var(--ds-surface-overlay)'
	| 'var(--ds-surface-raised)'
	| 'var(--ds-surface-sunken)'
	| 'var(--ds-elevation-surface-current)';
export type FontShorthand =
	| 'var(--ds-font-heading-xxlarge)'
	| 'var(--ds-font-heading-xlarge)'
	| 'var(--ds-font-heading-large)'
	| 'var(--ds-font-heading-medium)'
	| 'var(--ds-font-heading-small)'
	| 'var(--ds-font-heading-xsmall)'
	| 'var(--ds-font-heading-xxsmall)'
	| 'var(--ds-font-body-large)'
	| 'var(--ds-font-body)'
	| 'var(--ds-font-body-small)'
	| 'var(--ds-font-body-UNSAFE_small)'
	| 'var(--ds-font-code)';
export type IconColorPressed = 'var(--ds-link-pressed)' | 'var(--ds-link-visited-pressed)';
export type IconColor =
	| IconColorPressed
	| 'var(--ds-link)'
	| 'var(--ds-link-visited)'
	| 'var(--ds-icon)'
	| 'var(--ds-icon-accent-lime)'
	| 'var(--ds-icon-accent-red)'
	| 'var(--ds-icon-accent-orange)'
	| 'var(--ds-icon-accent-yellow)'
	| 'var(--ds-icon-accent-green)'
	| 'var(--ds-icon-accent-teal)'
	| 'var(--ds-icon-accent-blue)'
	| 'var(--ds-icon-accent-purple)'
	| 'var(--ds-icon-accent-magenta)'
	| 'var(--ds-icon-accent-gray)'
	| 'var(--ds-icon-disabled)'
	| 'var(--ds-icon-inverse)'
	| 'var(--ds-icon-selected)'
	| 'var(--ds-icon-brand)'
	| 'var(--ds-icon-danger)'
	| 'var(--ds-icon-warning)'
	| 'var(--ds-icon-warning-inverse)'
	| 'var(--ds-icon-success)'
	| 'var(--ds-icon-discovery)'
	| 'var(--ds-icon-information)'
	| 'var(--ds-icon-subtlest)'
	| 'var(--ds-icon-subtle)';
export type BorderColor =
	| 'transparent'
	| 'var(--ds-border)'
	| 'var(--ds-border-accent-lime)'
	| 'var(--ds-border-accent-red)'
	| 'var(--ds-border-accent-orange)'
	| 'var(--ds-border-accent-yellow)'
	| 'var(--ds-border-accent-green)'
	| 'var(--ds-border-accent-teal)'
	| 'var(--ds-border-accent-blue)'
	| 'var(--ds-border-accent-purple)'
	| 'var(--ds-border-accent-magenta)'
	| 'var(--ds-border-accent-gray)'
	| 'var(--ds-border-disabled)'
	| 'var(--ds-border-focused)'
	| 'var(--ds-border-input)'
	| 'var(--ds-border-inverse)'
	| 'var(--ds-border-selected)'
	| 'var(--ds-border-brand)'
	| 'var(--ds-border-danger)'
	| 'var(--ds-border-warning)'
	| 'var(--ds-border-success)'
	| 'var(--ds-border-discovery)'
	| 'var(--ds-border-information)'
	| 'var(--ds-border-bold)';
export type BorderRadius =
	| 'var(--ds-border-radius-050)'
	| 'var(--ds-border-radius)'
	| 'var(--ds-border-radius-100)'
	| 'var(--ds-border-radius-200)'
	| 'var(--ds-border-radius-300)'
	| 'var(--ds-border-radius-400)'
	| 'var(--ds-border-radius-circle)'
	| 'inherit';
export type BorderWidth =
	| 'var(--ds-border-width)'
	| 'var(--ds-border-width-indicator)'
	| 'var(--ds-border-width-outline)'
	| 0
	| '0';
export type BorderShorthand = 'none' | `${BorderWidth} solid ${BorderColor}`;
type NumericSize = `${number}px` | `${number}rem` | `${number}vh` | `${number}vw` | `${number}%`;
export type SizeIntrinsic =
	| 'min-content'
	| 'max-content'
	| 'fit-content'
	| 'auto'
	| NumericSize
	| `min(${NumericSize}, ${NumericSize})`
	| `max(${NumericSize}, ${NumericSize})`;
export type Space =
	| 'var(--ds-space-0)'
	| 'var(--ds-space-025)'
	| 'var(--ds-space-050)'
	| 'var(--ds-space-075)'
	| 'var(--ds-space-100)'
	| 'var(--ds-space-150)'
	| 'var(--ds-space-200)'
	| 'var(--ds-space-250)'
	| 'var(--ds-space-300)'
	| 'var(--ds-space-400)'
	| 'var(--ds-space-500)'
	| 'var(--ds-space-600)'
	| 'var(--ds-space-800)'
	| 'var(--ds-space-1000)'
	| 'var(--ds-space-negative-025)'
	| 'var(--ds-space-negative-050)'
	| 'var(--ds-space-negative-075)'
	| 'var(--ds-space-negative-100)'
	| 'var(--ds-space-negative-150)'
	| 'var(--ds-space-negative-200)'
	| 'var(--ds-space-negative-250)'
	| 'var(--ds-space-negative-300)'
	| 'var(--ds-space-negative-400)';
export type SpaceMargin = Space | 'auto' | '0 auto' | '0' | 0;
export type Shadow =
	| 'var(--ds-shadow-overflow)'
	| 'var(--ds-shadow-overflow-perimeter)'
	| 'var(--ds-shadow-overflow-spread)'
	| 'var(--ds-shadow-overlay)'
	| 'var(--ds-shadow-raised)'
	| 'initial';
export type TextColorPressed = 'var(--ds-link-pressed)' | 'var(--ds-link-visited-pressed)';
export type TextColor =
	| 'transparent'
	| TextColorPressed
	| 'var(--ds-text)'
	| 'var(--ds-text-accent-lime)'
	| 'var(--ds-text-accent-lime-bolder)'
	| 'var(--ds-text-accent-red)'
	| 'var(--ds-text-accent-red-bolder)'
	| 'var(--ds-text-accent-orange)'
	| 'var(--ds-text-accent-orange-bolder)'
	| 'var(--ds-text-accent-yellow)'
	| 'var(--ds-text-accent-yellow-bolder)'
	| 'var(--ds-text-accent-green)'
	| 'var(--ds-text-accent-green-bolder)'
	| 'var(--ds-text-accent-teal)'
	| 'var(--ds-text-accent-teal-bolder)'
	| 'var(--ds-text-accent-blue)'
	| 'var(--ds-text-accent-blue-bolder)'
	| 'var(--ds-text-accent-purple)'
	| 'var(--ds-text-accent-purple-bolder)'
	| 'var(--ds-text-accent-magenta)'
	| 'var(--ds-text-accent-magenta-bolder)'
	| 'var(--ds-text-accent-gray)'
	| 'var(--ds-text-accent-gray-bolder)'
	| 'var(--ds-text-disabled)'
	| 'var(--ds-text-inverse)'
	| 'var(--ds-text-selected)'
	| 'var(--ds-text-brand)'
	| 'var(--ds-text-danger)'
	| 'var(--ds-text-warning)'
	| 'var(--ds-text-warning-inverse)'
	| 'var(--ds-text-success)'
	| 'var(--ds-text-discovery)'
	| 'var(--ds-text-information)'
	| 'var(--ds-text-subtlest)'
	| 'var(--ds-text-subtle)'
	| 'var(--ds-link)'
	| 'var(--ds-link-visited)';
export type Opacity =
	| 'var(--ds-opacity-disabled)'
	| 'var(--ds-opacity-loading)'
	| 0
	| 1
	| '0'
	| '1';
export type FontWeight =
	| 'var(--ds-font-weight-regular)'
	| 'var(--ds-font-weight-medium)'
	| 'var(--ds-font-weight-semibold)'
	| 'var(--ds-font-weight-bold)'
	| 'inherit'
	| 'initial'
	| 'unset';
export type FontFamily =
	| 'var(--ds-font-family-heading)'
	| 'var(--ds-font-family-body)'
	| 'var(--ds-font-family-code)'
	| 'var(--ds-font-family-brand-heading)'
	| 'var(--ds-font-family-brand-body)';

export interface CSSPropertiesHovered {
	backgroundColor: BackgroundColorHovered;
}

export interface CSSPropertiesActive {
	backgroundColor: BackgroundColorPressed;
	color: TextColorPressed;
}

export interface DesignTokenStyles {
	'&:active': CSSPropertiesActive;
	'&:hover': CSSPropertiesHovered;
	border: BorderShorthand;
	borderBlock: BorderShorthand;
	borderBlockEnd: BorderShorthand;
	borderBlockStart: BorderShorthand;
	borderBottom: BorderShorthand;
	borderInline: BorderShorthand;
	borderInlineEnd: BorderShorthand;
	borderInlineStart: BorderShorthand;
	borderLeft: BorderShorthand;
	borderRight: BorderShorthand;
	borderTop: BorderShorthand;
	appearance: 'none' | 'auto';
	background: never;
	backgroundColor: BackgroundColor;
	blockSize: SizeIntrinsic;
	borderBlockColor: BorderColor;
	borderBlockEndColor: BorderColor;
	borderBlockEndWidth: BorderWidth;
	borderBlockStartColor: BorderColor;
	borderBlockStartWidth: BorderWidth;
	borderBlockWidth: BorderWidth;
	borderBottomColor: BorderColor;
	borderBottomLeftRadius: BorderRadius;
	borderBottomRightRadius: BorderRadius;
	borderBottomWidth: BorderWidth;
	borderColor: BorderColor;
	borderEndEndRadius: BorderRadius;
	borderEndStartRadius: BorderRadius;
	borderInlineColor: BorderColor;
	borderInlineEndColor: BorderColor;
	borderInlineEndWidth: BorderWidth;
	borderInlineStartColor: BorderColor;
	borderInlineStartWidth: BorderWidth;
	borderInlineWidth: BorderWidth;
	borderLeftColor: BorderColor;
	borderLeftWidth: BorderWidth;
	borderRadius: BorderRadius;
	borderRightColor: BorderColor;
	borderRightWidth: BorderWidth;
	borderStartEndRadius: BorderRadius;
	borderStartStartRadius: BorderRadius;
	borderTopColor: BorderColor;
	borderTopLeftRadius: BorderRadius;
	borderTopRightRadius: BorderRadius;
	borderTopWidth: BorderWidth;
	borderWidth: BorderWidth;
	bottom: Space;
	boxShadow: Shadow;
	boxSizing: 'border-box';
	clear: never;
	clip: never;
	color: TextColor;
	columnGap: Space;
	container: never;
	containerName: never;
	containerType: never;
	float: never;
	font: FontShorthand;
	fontFamily: FontFamily;
	fontSize: never;
	fontSizeAdjust: never;
	fontStyle: 'normal' | 'italic';
	fontWeight: FontWeight;
	gap: Space;
	height: SizeIntrinsic;
	inlineSize: SizeIntrinsic;
	inset: Space;
	insetBlock: Space;
	insetBlockEnd: Space;
	insetBlockStart: Space;
	insetInline: Space;
	insetInlineEnd: Space;
	insetInlineStart: Space;
	left: Space;
	letterSpacing: never;
	lineHeight: never;
	lineHeightStep: never;
	margin: SpaceMargin;
	marginBlock: SpaceMargin;
	marginBlockEnd: SpaceMargin;
	marginBlockStart: SpaceMargin;
	marginBottom: SpaceMargin;
	marginInline: SpaceMargin;
	marginInlineEnd: SpaceMargin;
	marginInlineStart: SpaceMargin;
	marginLeft: SpaceMargin;
	marginRight: SpaceMargin;
	marginTop: SpaceMargin;
	maxBlockSize: SizeIntrinsic;
	maxHeight: SizeIntrinsic;
	maxInlineSize: SizeIntrinsic;
	maxWidth: SizeIntrinsic;
	minBlockSize: SizeIntrinsic;
	minHeight: SizeIntrinsic;
	minInlineSize: SizeIntrinsic;
	minWidth: SizeIntrinsic;
	opacity: Opacity;
	outlineColor: BorderColor;
	outlineOffset: Space;
	outlineWidth: BorderWidth;
	overflowWrap: 'normal' | 'break-word' | 'anywhere';
	overlay: never;
	padding: Space;
	paddingBlock: Space;
	paddingBlockEnd: Space;
	paddingBlockStart: Space;
	paddingBottom: Space;
	paddingInline: Space;
	paddingInlineEnd: Space;
	paddingInlineStart: Space;
	paddingLeft: Space;
	paddingRight: Space;
	paddingTop: Space;
	right: Space;
	rowGap: Space;
	textDecorationLine: 'line-through' | 'underline';
	top: Space;
	userModify: never;
	width: SizeIntrinsic;
	zIndex: -1 | 0 | 1 | 100 | 200 | 300 | 400 | 500 | 510 | 600 | 700 | 800;
}
