const properties = [
	'padding',
	'paddingBlock',
	'paddingInline',
	'paddingLeft',
	'paddingTop',
	'paddingRight',
	'paddingBottom',
	'paddingInline',
	'paddingInlineStart',
	'paddingInlineEnd',
	'paddingBlock',
	'paddingBlockStart',
	'paddingBlockEnd',
	'marginLeft',
	'marginTop',
	'marginRight',
	'marginBottom',
	'marginInline',
	'marginInlineStart',
	'marginInlineEnd',
	'marginBlock',
	'marginBlockStart',
	'marginBlockEnd',
	'margin',
	'gap',
	'rowGap',
	'gridRowGap',
	'columnGap',
	'gridColumnGap',
	'top',
	'left',
	'right',
	'bottom',
	'inlineStart',
	'inlineEnd',
	'blockStart',
	'blockEnd',
	'outline-offset',
];

export const isSpacingProperty = (propertyName: string): boolean => {
	return properties.includes(propertyName);
};
