/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//German (Germany)
export default {
  'fabric.linking.cannot_connect':
    'Verbindung nicht möglich, versuchen Sie es erneut',
  'fabric.linking.cannot_find_link': 'Link konnte nicht gefunden werden',
  'fabric.linking.click_to_join':
    '{context} beitreten, um diesen Vorgang anzuzeigen',
  'fabric.linking.connect_link_account': 'Verknüpfen und Vorschau ansehen',
  'fabric.linking.create_on': 'Erstellt am {context}',
  'fabric.linking.created_by': 'Erstellt von {context}',
  'fabric.linking.delete': 'Löschen',
  'fabric.linking.edit': 'Bearbeiten',
  'fabric.linking.forbidden_access': 'Sie sind nicht zugriffsberechtigt',
  'fabric.linking.invalid_permissions':
    'Eingeschränkter Link, bitte versuchen Sie es mit einem anderen Konto.',
  'fabric.linking.modified_on': 'Aktualisiert am {context}',
  'fabric.linking.pending_request': 'Ihre Zugriffsanfrage ist ausstehend.',
  'fabric.linking.priority_blocker': 'Blocker',
  'fabric.linking.priority_critical': 'Kritisch',
  'fabric.linking.priority_high': 'Hoch',
  'fabric.linking.priority_highest': 'Höchste',
  'fabric.linking.priority_low': 'Niedrig',
  'fabric.linking.priority_lowest': 'Niedrigste',
  'fabric.linking.priority_major': 'Sehr hoch',
  'fabric.linking.priority_medium': 'Mittel',
  'fabric.linking.priority_minor': 'Gering',
  'fabric.linking.priority_trivial': 'Unwesentlich',
  'fabric.linking.priority_undefined': 'Nicht definiert',
  'fabric.linking.request_access':
    'Zugriff auf {context} anfordern, um diesen Vorgang anzuzeigen',
  'fabric.linking.request_denied': 'Ihre Zugriffsanfrage wurde abgelehnt.',
  'fabric.linking.updated_by': 'Geändert von {context}',
};
