/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Japanese
export default {
  'fabric.linking.cannot_connect': '接続できません、もう一度お試しください。',
  'fabric.linking.cannot_find_link': 'リンクが見つかりません。',
  'fabric.linking.click_to_join': '{context}に参加してこの課題を見る',
  'fabric.linking.connect_link_account': '接続してプレビュー',
  'fabric.linking.create_on': '作成日: {context}',
  'fabric.linking.created_by': '作成元: {context}',
  'fabric.linking.delete': '削除',
  'fabric.linking.edit': '編集',
  'fabric.linking.forbidden_access': 'アクセスは禁止されています。',
  'fabric.linking.invalid_permissions':
    '制限されているリンクです、別のアカウントをお試しください。',
  'fabric.linking.modified_on': '更新日: {context}',
  'fabric.linking.pending_request': 'アクセス リクエストは保留中です。',
  'fabric.linking.priority_blocker': 'ブロッカー',
  'fabric.linking.priority_critical': '重要',
  'fabric.linking.priority_high': '高',
  'fabric.linking.priority_highest': '最高',
  'fabric.linking.priority_low': '低',
  'fabric.linking.priority_lowest': '最低',
  'fabric.linking.priority_major': '重大',
  'fabric.linking.priority_medium': '中',
  'fabric.linking.priority_minor': '軽度',
  'fabric.linking.priority_trivial': '軽微',
  'fabric.linking.priority_undefined': '未定義',
  'fabric.linking.request_access':
    'この課題を表示するには、{context}へのアクセスをリクエストします。',
  'fabric.linking.request_denied': 'アクセス リクエストが拒否されました。',
  'fabric.linking.updated_by': '変更元: {context}',
};
