/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Russian
export default {
  'fabric.linking.cannot_connect': 'Не удается подключиться, повторите попытку',
  'fabric.linking.cannot_find_link': 'Не удается найти ссылку',
  'fabric.linking.click_to_join':
    'Для просмотра этой задачи выполните подключение к {context}',
  'fabric.linking.connect_link_account': 'Подключить для просмотра',
  'fabric.linking.create_on': 'Создано: {context}',
  'fabric.linking.created_by': 'Создано: {context}',
  'fabric.linking.delete': 'Удалить',
  'fabric.linking.edit': 'Изменить',
  'fabric.linking.forbidden_access': 'Доступ запрещен',
  'fabric.linking.invalid_permissions':
    'Доступ к ссылке ограничен, попробуйте войти в другой аккаунт',
  'fabric.linking.modified_on': 'Обновлено: {context}',
  'fabric.linking.pending_request': 'Ваш запрос на доступ ожидает рассмотрения',
  'fabric.linking.priority_blocker': 'Блокер',
  'fabric.linking.priority_critical': 'Критический',
  'fabric.linking.priority_high': 'Высокий',
  'fabric.linking.priority_highest': 'Самый высокий',
  'fabric.linking.priority_low': 'Низкий',
  'fabric.linking.priority_lowest': 'Самый низкий',
  'fabric.linking.priority_major': 'Серьезный',
  'fabric.linking.priority_medium': 'Средний',
  'fabric.linking.priority_minor': 'Незначительный',
  'fabric.linking.priority_trivial': 'Тривиальный',
  'fabric.linking.priority_undefined': 'Не определен',
  'fabric.linking.request_access':
    'Для просмотра этой задачи запросите доступ к {context}',
  'fabric.linking.request_denied': 'Ваш запрос на доступ отклонен',
  'fabric.linking.updated_by': 'Изменено: {context}',
};
