/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Thai (Thailand)
export default {
  'fabric.linking.cannot_connect': 'ไม่สามารถเชื่อมต่อได้ โปรดลองอีกครั้ง',
  'fabric.linking.cannot_find_link': 'ไม่พบลิงก์',
  'fabric.linking.click_to_join': 'เข้าร่วม {context} เพื่อดูปัญหานี้',
  'fabric.linking.connect_link_account': 'เชื่อมต่อเพื่อดูตัวอย่าง',
  'fabric.linking.create_on': 'สร้าง {context} แล้ว',
  'fabric.linking.created_by': 'สร้างโดย {context}',
  'fabric.linking.delete': 'ลบ',
  'fabric.linking.edit': 'แก้ไข',
  'fabric.linking.forbidden_access': 'คุณไม่มีสิทธิ์เข้าถึง',
  'fabric.linking.invalid_permissions':
    'ลิงก์ถูกจำกัดการเข้าถึง โปรดลองใช้บัญชีอื่น',
  'fabric.linking.modified_on': 'อัปเดต {context} แล้ว',
  'fabric.linking.pending_request': 'คำขอการเข้าถึงของคุณกำลังรอดำเนินการ',
  'fabric.linking.priority_blocker': 'ตัวบล็อก',
  'fabric.linking.priority_critical': 'วิกฤต',
  'fabric.linking.priority_high': 'สูง',
  'fabric.linking.priority_highest': 'สูงที่สุด',
  'fabric.linking.priority_low': 'ต่ำ',
  'fabric.linking.priority_lowest': 'ต่ำที่สุด',
  'fabric.linking.priority_major': 'มาก',
  'fabric.linking.priority_medium': 'ปานกลาง',
  'fabric.linking.priority_minor': 'น้อย',
  'fabric.linking.priority_trivial': 'ไม่สำคัญ',
  'fabric.linking.priority_undefined': 'ไม่ได้ระบุ',
  'fabric.linking.request_access':
    'ส่งคำขอการเข้าถึงที่ {context} เพื่อดูปัญหานี้',
  'fabric.linking.request_denied': 'คำขอการเข้าถึงของคุณถูกปฏิเสธ',
  'fabric.linking.updated_by': 'แก้ไขแล้วโดย {context}',
};
