/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'fabric.atlassianSwitcher.administration': '管理',
  'fabric.atlassianSwitcher.browseApps': 'Marketplace アプリを参照',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence スペース',
  'fabric.atlassianSwitcher.discover': '発見',
  'fabric.atlassianSwitcher.discoverMore': 'もっと見る',
  'fabric.atlassianSwitcher.errorHeading': '問題が発生しました',
  'fabric.atlassianSwitcher.errorHeadingLoggedOut':
    'Atlassian アカウントからログアウトしました',
  'fabric.atlassianSwitcher.errorHeadingUnverified':
    'お使いのアカウントは認証されていません',
  'fabric.atlassianSwitcher.errorImageAltText':
    '鋭意問題の修正に当たっています。',
  'fabric.atlassianSwitcher.errorText':
    'エラーはすべて記録されていますが、リフレッシュしても問題が修正されない場合はお気軽にお問い合わせください。',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'アトラシアン スイッチャーを使用するには、再度ログインしてください。',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'このリストを読み込めませんでした。ページを読み込み直してもう一度お試しください。',
  'fabric.atlassianSwitcher.errorTextUnverified':
    '利用可能な製品の一覧を見るには、メールアドレスを確認してください。',
  'fabric.atlassianSwitcher.free.edition.product.description.confluence':
    '最大 10 ユーザーまで使用できる無料のドキュメント コラボレーション',
  'fabric.atlassianSwitcher.free.edition.product.description.jsd':
    '最大 3 エージェントまで使用できる無料の IT サービス デスクとカスタマー サービス デスク',
  'fabric.atlassianSwitcher.free.edition.product.description.jsm':
    '最大 3 エージェントまで無料でコラボレーション可能な IT サービス管理',
  'fabric.atlassianSwitcher.free.edition.product.description.jsw':
    '最大 10 ユーザーまで使用できる無料のプロジェクトと課題トラッキング',
  'fabric.atlassianSwitcher.gittools.description': 'Bitbucket、Github など',
  'fabric.atlassianSwitcher.gittools.label': 'Jira 向け Git 統合',
  'fabric.atlassianSwitcher.jiraProject': 'Jira プロジェクト',
  'fabric.atlassianSwitcher.join': '参加',
  'fabric.atlassianSwitcher.login': 'ログイン',
  'fabric.atlassianSwitcher.manageList': 'リストの管理',
  'fabric.atlassianSwitcher.more': 'その他',
  'fabric.atlassianSwitcher.product.description.confluence':
    'ドキュメント コラボレーション',
  'fabric.atlassianSwitcher.product.description.jsd':
    'IT サービス デスクとカスタマー サービス',
  'fabric.atlassianSwitcher.product.description.jsm':
    'コラボレーション可能な IT サービス管理',
  'fabric.atlassianSwitcher.product.description.jsw':
    'プロジェクトと課題トラッキング',
  'fabric.atlassianSwitcher.product.description.opsgenie':
    '最先端のインシデント管理',
  'fabric.atlassianSwitcher.recent': '最近',
  'fabric.atlassianSwitcher.show.more.sites': '他のサイトを表示',
  'fabric.atlassianSwitcher.sign.up.to.join.body':
    '{productLabel} に参加するには、メール アドレス {email} を使用して Atlassian アカウントを作成するか、すでにアカウントをお持ちの場合はログインしてください。',
  'fabric.atlassianSwitcher.sign.up.to.join.cta': 'メール アドレスで参加',
  'fabric.atlassianSwitcher.sign.up.to.join.header':
    '{productLabel} に参加する',
  'fabric.atlassianSwitcher.sign.up.to.join.image':
    '複数のホログラフィック画面を見ているチーム',
  'fabric.atlassianSwitcher.start': 'Atlassian を開始',
  'fabric.atlassianSwitcher.switchTo': '切り替え先',
  'fabric.atlassianSwitcher.switchToTooltip': '切り替え先...',
  'fabric.atlassianSwitcher.trello.has.new.freinds.body':
    'アトラシアンの他の製品を、Trello からすぐに見つけられるようになりました。お試しになる場合は、Atlassian アカウントを使用して設定のお手伝いをします。',
  'fabric.atlassianSwitcher.trello.has.new.freinds.dismiss': 'OK',
  'fabric.atlassianSwitcher.trello.has.new.freinds.heading':
    'Trello に新しい仲間ができました',
  'fabric.atlassianSwitcher.try': '試してみる',
};
