/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Turkish (Turkey)
export default {
  'fabric.linking.actions': 'Eylemler',
  'fabric.linking.add_account': 'Hesap ekle',
  'fabric.linking.cancel': 'İptal',
  'fabric.linking.cannot_connect': 'Bağlanılamıyor, tekrar deneyin',
  'fabric.linking.cannot_find_link': 'Bağlantı bulunamıyor',
  'fabric.linking.click_to_join': '{context} ürününe katılın',
  'fabric.linking.click_to_join_description':
    'Onay aldınız, {context} ürününe hemen katılabilirsiniz.',
  'fabric.linking.close': 'Kapat',
  'fabric.linking.connect_account_description':
    '{name} hesabınıza bağlanmanıza yardımcı olmak için yeni bir sayfa açacağız',
  'fabric.linking.connect_link_account': 'Önizlemeye bağlanın',
  'fabric.linking.connect_link_account_card_view': 'Bağla',
  'fabric.linking.connect_link_account_card_view_description':
    'Bu bağlantının bir önizlemesini görmek için {context} hesabınızı bağlayın.',
  'fabric.linking.connect_link_account_card_view_name':
    '{context} hesabınızı bağlayın',
  'fabric.linking.connect_to': '{name} hesabını bağlan',
  'fabric.linking.connect_unauthorised_account_action':
    '{context} hesabını bağlayın',
  'fabric.linking.connect_unauthorised_account_description':
    "Çalışmanız ve iş birliklerinizle ilgili daha fazla ayrıntıyı tek bir yerde bir arada görmek için hesabınızı Atlassian'a bağlayın.",
  'fabric.linking.couldnt_load_link':
    'Bilinmeyen bir nedenden dolayı bu bağlantıyı yükleyemedik.',
  'fabric.linking.create_on_absolute': '{context} tarihinde oluşturuldu',
  'fabric.linking.create_on_relative': '{context} oluşturuldu',
  'fabric.linking.created_by': '{context} tarafından oluşturuldu',
  'fabric.linking.delete': 'Sil',
  'fabric.linking.download': 'İndir',
  'fabric.linking.edit': 'Düzenle',
  'fabric.linking.forbidden_access': 'Erişiminiz yasak',
  'fabric.linking.forbidden_description':
    'Bu önizlemeye erişiminiz yok. Erişim gerekliyse site yöneticisiyle iletişime geçin.',
  'fabric.linking.invalid_permissions': 'Kısıtlanmış bağlantı',
  'fabric.linking.invalid_permissions_description':
    'Bu önizlemeyi görüntülemek için erişim izni talep etmeniz veya farklı bir hesap kullanmanız gerekir.',
  'fabric.linking.join_to_view':
    'Bu konuyu görüntülemek için {context} ürününe katılın',
  'fabric.linking.learn_more_about_smart_links':
    'Smart Links hakkında daha fazla bilgi edinin.',
  'fabric.linking.loading': 'Yükleniyor...',
  'fabric.linking.modified_on_absolute': '{context} tarihinde güncellendi',
  'fabric.linking.modified_on_relative': '{context} güncellendi',
  'fabric.linking.more_actions': 'Daha fazla işlem',
  'fabric.linking.not_found_description':
    "Bağlantıyı bulamadık. URL'yi kontrol edin ve düzenlemeyi veya yeniden yapıştırmayı deneyin.",
  'fabric.linking.not_found_title': 'Hay aksi! Bu bağlantıyı bulamadık!',
  'fabric.linking.open_link_in_a_new_tab': 'Bağlantıyı yeni sekmede aç',
  'fabric.linking.pending_request': 'Erişim talebiniz beklemede',
  'fabric.linking.preview': 'Tam ekran görünümü',
  'fabric.linking.preview_close': 'Önizlemeyi kapat',
  'fabric.linking.preview_max_size': 'Tam ekran görüntüle',
  'fabric.linking.preview_min_size': 'Tam ekranı kapat',
  'fabric.linking.priority_blocker': 'Engelleyici',
  'fabric.linking.priority_critical': 'Çok önemli',
  'fabric.linking.priority_high': 'Yüksek',
  'fabric.linking.priority_highest': 'En Yüksek',
  'fabric.linking.priority_low': 'Düşük',
  'fabric.linking.priority_lowest': 'En Düşük',
  'fabric.linking.priority_major': 'Önemli',
  'fabric.linking.priority_medium': 'Orta',
  'fabric.linking.priority_minor': 'Düşük',
  'fabric.linking.priority_trivial': 'Önemsiz',
  'fabric.linking.priority_undefined': 'Tanımlanmamış',
  'fabric.linking.request_access': 'Erişim talep edin',
  'fabric.linking.request_access_description':
    'Bu önizlemeyi görüntülemek için {context} ürününe erişim talep edin.',
  'fabric.linking.request_access_pending': 'Erişim bekleniyor',
  'fabric.linking.request_access_pending_description':
    'Erişim talebiniz beklemede.',
  'fabric.linking.request_access_to_view':
    'Bu konuyu görüntülemek için {context} ürününe erişim talep edin',
  'fabric.linking.request_denied': 'Erişim talebiniz reddedildi',
  'fabric.linking.request_denied_description':
    'Erişim talebiniz reddedildi. Hâlâ erişim gerekliyse site yöneticisiyle iletişime geçin.',
  'fabric.linking.restricted_link': 'Sınırlı bağlantı, başka bir hesap deneyin',
  'fabric.linking.retry': 'Yeniden Dene',
  'fabric.linking.save': 'Kaydet',
  'fabric.linking.srclink': 'Şurada görüntüleyin:',
  'fabric.linking.srclinkunknown': 'Orijinalini Görüntüleyin',
  'fabric.linking.try_again': 'Yeniden dene',
  'fabric.linking.try_another_account': 'Başka bir hesapla deneyin',
  'fabric.linking.unlink_account': 'Hesabın Bağlantısını Kaldır',
  'fabric.linking.updated_by': '{context} tarafından değiştirildi',
  'fabric.linking.view': 'Görüntüle',
};
