import {
	AtlassianAccessIcon,
	AtlassianAccessLogo,
	AtlassianAdminIcon,
	AtlassianAdministrationIcon,
	AtlassianAdministrationLogo,
	AtlassianAdminLogo,
	AtlassianAnalyticsIcon,
	AtlassianAnalyticsLogo,
	AtlassianIcon,
	AtlassianLogo,
	AtlassianMarketplaceIcon,
	AtlassianMarketplaceLogo,
	BitbucketIcon,
	BitbucketLogo,
	CompassIcon,
	CompassLogo,
	ConfluenceIcon,
	ConfluenceLogo,
	FocusIcon,
	FocusLogo,
	GuardIcon,
	GuardLogo,
	JiraAlignIcon,
	JiraAlignLogo,
	JiraIcon,
	JiraLogo,
	JiraProductDiscoveryIcon,
	JiraProductDiscoveryLogo,
	JiraServiceManagementIcon,
	JiraServiceManagementLogo,
	JiraSoftwareIcon,
	JiraSoftwareLogo,
	JiraWorkManagementIcon,
	JiraWorkManagementLogo,
	type LogoProps,
	LoomAttributionIcon,
	LoomAttributionLogo,
	LoomIcon,
	LoomLogo,
	OpsgenieIcon,
	OpsgenieLogo,
	RovoIcon,
	RovoLogo,
	StatuspageIcon,
	StatuspageLogo,
	TrelloIcon,
	TrelloLogo,
} from '@atlaskit/logo';

export const logos = [
	AtlassianAccessLogo,
	AtlassianAdministrationLogo,
	AtlassianAdminLogo,
	AtlassianAnalyticsLogo,
	AtlassianLogo,
	AtlassianMarketplaceLogo,
	BitbucketLogo,
	CompassLogo,
	ConfluenceLogo,
	FocusLogo,
	GuardLogo,
	JiraAlignLogo,
	JiraLogo,
	JiraProductDiscoveryLogo,
	JiraServiceManagementLogo,
	JiraSoftwareLogo,
	JiraWorkManagementLogo,
	LoomAttributionLogo,
	LoomLogo,
	OpsgenieLogo,
	RovoLogo,
	StatuspageLogo,
	TrelloLogo,
];

export const icons = [
	AtlassianAccessIcon,
	AtlassianAdminIcon,
	AtlassianAdministrationIcon,
	AtlassianAnalyticsIcon,
	AtlassianIcon,
	AtlassianMarketplaceIcon,
	BitbucketIcon,
	CompassIcon,
	ConfluenceIcon,
	FocusIcon,
	GuardIcon,
	JiraAlignIcon,
	JiraIcon,
	JiraProductDiscoveryIcon,
	JiraServiceManagementIcon,
	JiraSoftwareIcon,
	JiraWorkManagementIcon,
	LoomAttributionIcon,
	LoomIcon,
	OpsgenieIcon,
	RovoIcon,
	StatuspageIcon,
	TrelloIcon,
];

export const logosAndIcons = [
	{ name: 'Atlassian Access', logo: AtlassianAccessLogo, icon: AtlassianAccessIcon },
	{
		name: 'Atlassian Administration',
		logo: AtlassianAdministrationLogo,
		icon: AtlassianAdministrationIcon,
	},
	{ name: 'Atlassian Admin', logo: AtlassianAdminLogo, icon: AtlassianAdminIcon },
	{ name: 'Atlassian Analytics', logo: AtlassianAnalyticsLogo, icon: AtlassianAnalyticsIcon },
	{ name: 'Atlassian', logo: AtlassianLogo, icon: AtlassianIcon },
	{ name: 'Atlassian Marketplace', logo: AtlassianMarketplaceLogo, icon: AtlassianMarketplaceIcon },
	{ name: 'Bitbucket', logo: BitbucketLogo, icon: BitbucketIcon },
	{ name: 'Compass', logo: CompassLogo, icon: CompassIcon },
	{ name: 'Confluence', logo: ConfluenceLogo, icon: ConfluenceIcon },
	{ name: 'Focus', logo: FocusLogo, icon: FocusIcon },
	{ name: 'Guard', logo: GuardLogo, icon: GuardIcon },
	{ name: 'Jira Align', logo: JiraAlignLogo, icon: JiraAlignIcon },
	{ name: 'Jira', logo: JiraLogo, icon: JiraIcon },
	{
		name: 'Jira Product Discovery',
		logo: JiraProductDiscoveryLogo,
		icon: JiraProductDiscoveryIcon,
	},
	{
		name: 'Jira Service Management',
		logo: JiraServiceManagementLogo,
		icon: JiraServiceManagementIcon,
	},
	{ name: 'Jira Software', logo: JiraSoftwareLogo, icon: JiraSoftwareIcon },
	{ name: 'Jira Work Management', logo: JiraWorkManagementLogo, icon: JiraWorkManagementIcon },
	{ name: 'Loom Attribution', logo: LoomAttributionLogo, icon: LoomAttributionIcon },
	{ name: 'Loom', logo: LoomLogo, icon: LoomIcon },
	{ name: 'Opsgenie', logo: OpsgenieLogo, icon: OpsgenieIcon },
	{ name: 'Rovo', logo: RovoLogo, icon: RovoIcon },
	{ name: 'Statuspage', logo: StatuspageLogo, icon: StatuspageIcon },
	{ name: 'Trello', logo: TrelloLogo, icon: TrelloIcon },
];

export const appearances: LogoProps['appearance'][] = ['brand', 'neutral', 'inverse'];
