import { type UNSAFE_IconMetadata } from '@af/icon-build-process';
const metadata: UNSAFE_IconMetadata = {
	editions: {
		keywords: ['editions', 'gem', 'premium', 'diamond', 'precious stone'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage:
			'Single purpose - Reserved for representing premium features and functionality. Editions may replace the current premium sparkle icon.',
	},
	highlight: {
		keywords: ['highlight', 'highlighter', 'stabilo', 'pen'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Single purpose - Reserved for highlight text tool in Confluence Editor.',
	},
	'roadmaps-plan': {
		keywords: ['roadmaps', 'roadmap', 'plan'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Single purpose - Reserved for roadmaps plan.',
	},
	'roadmaps-service': {
		keywords: ['roadmaps', 'service', 'roadmap'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Single purpose - Reserved for roadmaps service.',
	},
	coins: {
		keywords: ['currency', 'money', 'loose change'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	'cross-octagon': {
		keywords: ['octagon', 'cross', 'stop', 'block'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	'field-text': {
		keywords: ['text field', 'form', 'input', 'label', 'cursor'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	'paint-brush': {
		keywords: ['paint', 'brush', 'appearance'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	'paint-roller': {
		keywords: ['paint', 'roller', 'background'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	speedometer: {
		keywords: ['dial', 'speed', 'performance'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	'takeout-container': {
		keywords: ['takeaway', 'takeout', 'food'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose - Known usages: Alternative option for food emoji category.',
	},
	ticket: {
		keywords: ['ticket', 'stub'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	'vehicle-train': {
		keywords: ['car', 'transportation', 'vehicle'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose - Known usages: Alternative option for transport emoji category.',
	},
	wallet: {
		keywords: ['wallet', 'money', 'sales', 'payment'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
	wrench: {
		keywords: ['tool', 'wrench', 'spanner'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		usage: 'Multi purpose',
	},
};

export default metadata;
