import { type IconMetadata } from '@af/icon-build-process';

const metadata: IconMetadata = {
	'ai-generative-chapters': {
		keywords: ['book', 'AI', 'automation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:38146',
		usage: 'Reserved for auto chapters functionality in Loom.',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'ai-generative-cleanup': {
		keywords: ['broom', 'tidy', 'clean up'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '43414:37403',
		usage: 'Reserved for automated cleanup and tidy functionality',
		slackChannel: '#icon-contributions',
	},
	'ai-generative-remove': {
		keywords: ['eraser', 'AI', 'automation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:50922',
		usage: 'Reserved for remove filler words functionality in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'ai-generative-remove-silence': {
		keywords: ['empty', 'AI', 'automation', 'pauses', 'silences'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:53828',
		usage: 'Reserved for silence removal functionality in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'ai-generative-text': {
		keywords: ['pencil', 'AI', 'automation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:40317',
		usage: 'Reserved for auto draft functionality in Loom.',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'ai-generative-text-title': {
		keywords: ['text', 'AI', 'automation', 'header'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:44083',
		usage: 'Reserved for auto titles functionality in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'align-content-bottom': {
		keywords: ['align', 'alignment', 'content', 'bottom', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:17080',
		usage: 'Used for aligning bottom edges of content in Whiteboards',
	},
	'align-content-center-horizontal': {
		keywords: ['align', 'alignment', 'content', 'center', 'middle', 'horizontal'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:14885',
		usage: 'Used for aligning horizontal centers of content in Whiteboards',
	},
	'align-content-center-vertical': {
		keywords: ['align', 'alignment', 'content', 'center', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:16237',
		usage: 'Used for aligning vertical centers of content in Whiteboards',
	},
	'align-content-left': {
		keywords: ['align', 'alignment', 'content', 'left', 'horizontal'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:14473',
		usage: 'Used for aligning left edges of content in Whiteboards',
	},
	'align-content-right': {
		keywords: ['align', 'alignment', 'content', 'right', 'horizontal'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:15297',
		usage: 'Used for aligning right edges of content in Whiteboards',
	},
	'align-content-top': {
		keywords: ['align', 'alignment', 'content', 'top', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:15767',
		usage: 'Used for aligning top edges of content in Whiteboards',
	},
	'align-position-bottom': {
		keywords: ['align', 'alignment', 'middle', 'text position', 'bottom', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '35810:31263',
		usage: 'Bottom-aligned text position within sticky notes in Whiteboards.',
	},
	'align-position-center-vertical': {
		keywords: ['align', 'alignment', 'middle', 'center', 'text position', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '35810:30793',
		usage: 'Center-aligned text position within sticky notes in Whiteboards.',
	},
	'align-position-top': {
		keywords: ['align', 'alignment', 'top edge', 'text position', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '35810:30323',
		usage: 'Top-aligned text position within sticky notes in Whiteboards.',
	},
	'arrows-diagonal-up-right-down-left': {
		keywords: ['Arrows', 'Switch', 'Space', 'Swap', 'crossflow'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Confluence Integrations',
		type: 'core',
		status: 'published',
		id: '36799:1489',
		usage: 'Used within Jira Pages to connect or switch to a Space or page.',
	},
	'assets-data-manager': {
		keywords: ['data manager', 'assets', 'CMDB', 'configuration management database'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Assets',
		type: 'core',
		status: 'published',
		id: '26733:8692',
		usage: 'Reserved for JSM Assets.',
	},
	'assets-graph': {
		keywords: ['assets', 'graph'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Assets',
		type: 'core',
		status: 'published',
		id: '40946:3077',
		usage: 'Reserved for representing Assets graph',
	},
	'assets-schema': {
		keywords: ['assets', 'CMDB', 'configuration management database'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Assets',
		type: 'core',
		status: 'published',
		id: '26723:6335',
		usage: 'Reserved for JSM Assets.',
	},
	atom: {
		keywords: ['atom', 'molecule', 'atomic design'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '43249:36176',
		slackChannel: '#icon-contributions',
	},
	'audio-waveform': {
		keywords: ['waveform', 'audio', 'soundwave', 'dialogue', 'speak'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:87925',
		usage: 'Known uses: show waveform editor in Loom.',
	},
	'beach-umbrella': {
		keywords: ['vacation', 'beach umbrella', 'sun shade', 'holiday'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		id: '38223:4224',
		usage: 'User-selectable icon choice for calendars',
	},
	bluetooth: {
		keywords: ['bluetooth', 'connectivity', 'bt'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '43249:36757',
		usage: 'Reserved for Bluetooth',
		slackChannel: '#icon-contributions',
	},
	blur: {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:10798',
		usage: 'Reserved for blurring an element in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'book-open': {
		keywords: ['book', 'knowledgebase article'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '22279:21587',
		usage: 'Known uses: None',
	},
	'browser-extension': {
		keywords: ['extension', 'puzzle piece', 'add on', 'jigsaw', 'chrome web store'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:13658',
		usage: 'Reserved for chrome extensions',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	calculate: {
		keywords: ['Calculate', 'databases', 'summation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Databases',
		type: 'core',
		status: 'published',
		id: '37846:2200',
		usage: 'Calculate for databases',
	},
	'cloud-offline': {
		keywords: ['cloud', 'offline', 'disconnected', 'strikethrough'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		id: '33429:14280',
		usage: "Reserved for showing when a connection can't be established to the cloud.",
	},
	'cloud-saved': {
		keywords: ['cloud', 'check mark', 'saved', 'success'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		id: '33429:16365',
		usage: 'Reserved for showing saved status after successful cloud synchronisation.',
	},
	coins: {
		keywords: ['money', 'loose change', 'currency'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14151:11114',
		usage: 'Multi purpose',
	},
	'colour-none': {
		keywords: ['Colour', 'Color', 'Remove', 'None', 'Colour picker'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40576:10655',
		usage: "Remove colours from Whiteboard's colour picker",
	},
	compare: {
		keywords: ['compare', 'git', 'bitbucket', 'diff'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Bitbucket',
		type: 'core',
		status: 'published',
		id: '45810:476',
		usage: 'Reserved for compare functionality in Bitbucket.',
	},
	'compass-hinged': {
		keywords: ['compass', 'calipers', 'divider'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '43245:34876',
		slackChannel: '#icon-contributions',
	},
	'continue-when': {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		id: '38222:2653',
		usage: 'Reserved for continue when delay in automation.',
		slackChannel: '#help-automation-design',
	},
	'cross-octagon': {
		keywords: ['cross', 'stop', 'block', 'octagon'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14062:9760',
		usage: 'Multi purpose',
	},
	cursor: {
		keywords: ['Whiteboards', 'Cursor'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34970:5306',
		usage: 'Selecting the cursor in Whiteboards',
	},
	'cursor-strikethrough': {
		keywords: ['Cursor', 'Cursors', 'Hide cursor', 'Whiteboard cursor', 'Cursor strikethrough'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34970:6687',
		usage: 'Hide collaborator cursors in the Whiteboard',
	},
	'database-storage': {
		keywords: ['database', 'db', 'storage', 'sql'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Ecosystem',
		type: 'core',
		status: 'published',
		id: '33278:7485',
		usage: 'Known uses: SQL database in Developer Console',
		slackChannel: '#forge-sql',
	},
	'database-storage-cache': {
		keywords: ['database', 'db', 'storage', 'sql', 'cache'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Ecosystem',
		type: 'core',
		status: 'published',
		id: '33278:8324',
		usage: 'Known uses: Storage cache in Developer Console.',
		slackChannel: '#forge-sql',
	},
	'diagram-symbol-action': {
		keywords: ['diagram', 'symbol', 'action'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:38468',
		usage: 'Reserved for action diagram symbol.',
	},
	'diagram-symbol-alternate-process': {
		keywords: ['diagram', 'symbol', 'alternate process'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:39454',
		usage: 'Reserved for alternate process diagram symbol.',
	},
	'diagram-symbol-collate': {
		keywords: ['diagram', 'symbol', 'collate'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:43273',
		usage: 'Reserved for collate diagram symbol.',
	},
	'diagram-symbol-comment-left': {
		keywords: ['comment', 'left', 'diagram', 'symbol'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:1636',
		usage: 'Reserved for comment left diagram symbol.',
	},
	'diagram-symbol-comment-right': {
		keywords: ['comment', 'right', 'diagram', 'symbol'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:6061',
		usage: 'Reserved for comment right diagram symbol.',
	},
	'diagram-symbol-connector-off-page': {
		keywords: ['off-page', 'diagram', 'symbol', 'connector'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:10391',
		usage: 'Reserved for off-page connector diagram symbol.',
	},
	'diagram-symbol-connector-on-page': {
		keywords: ['diagram', 'symbol', 'on-page', 'connector'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:46173',
		usage: 'Reserved for on-page connector diagram symbol.',
	},
	'diagram-symbol-database': {
		keywords: ['diagram', 'symbol', 'database'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:6469',
		usage: 'Reserved for database diagram symbol.',
	},
	'diagram-symbol-decision': {
		keywords: ['diagram', 'symbol', 'decision'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:40440',
		usage: 'Reserved for decision diagram symbol.',
	},
	'diagram-symbol-delay': {
		keywords: ['diagram', 'symbol', 'delay'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:6877',
		usage: 'Reserved for delay diagram symbol.',
	},
	'diagram-symbol-display': {
		keywords: ['diagram', 'symbol', 'display'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:7413',
		usage: 'Reserved for display diagram symbol.',
	},
	'diagram-symbol-document': {
		keywords: ['diagram', 'symbol', 'document'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:7882',
		usage: 'Reserved for single document diagram symbol.',
	},
	'diagram-symbol-documents': {
		keywords: ['diagram', 'symbol', 'multiple documents'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:9983',
		usage: 'Reserved for multiple documents diagram symbol',
	},
	'diagram-symbol-hard-disk': {
		keywords: ['diagram', 'symbol', 'hard disk', 'hard drive', 'storage'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:8290',
		usage: 'Reserved for hard disk diagram symbol.',
	},
	'diagram-symbol-input-output': {
		keywords: ['diagram', 'symbol', 'input', 'output'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:42418',
		usage: 'Reserved for input or output diagram symbols.',
	},
	'diagram-symbol-internal-storage': {
		keywords: ['diagram', 'symbol', 'internal storage'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:8759',
		usage: 'Reserved for internal storage diagram symbol.',
	},
	'diagram-symbol-loop-limit': {
		keywords: ['diagram', 'symbol', 'loop limit'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:45184',
		usage: 'Reserved for loop limit diagram symbol.',
	},
	'diagram-symbol-manual-input': {
		keywords: ['diagram', 'symbol', 'manual input'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:11804',
		usage: 'Reserved for manual input diagram symbol.',
	},
	'diagram-symbol-manual-operation': {
		keywords: ['diagram', 'symbol', 'manual operation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:9167',
		usage: 'Reserved for manual operation diagram symbol.',
	},
	'diagram-symbol-merge': {
		keywords: ['diagram', 'symbol', 'merge', 'triangle'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:44195',
		usage: 'Reserved for merge diagram symbol.',
	},
	'diagram-symbol-mind-map': {
		keywords: ['diagram', 'symbol', 'mind map'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:9575',
		usage: 'Reserved for mind map diagram symbol.',
	},
	'diagram-symbol-or': {
		keywords: ['diagram', 'symbol', 'or', 'logic'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:13698',
		usage: 'Reserved for or diagram symbol.',
	},
	'diagram-symbol-predefined-process': {
		keywords: ['diagram', 'symbol', 'predefined process'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:10799',
		usage: 'Reserved for predefined process diagram symbol.',
	},
	'diagram-symbol-preparation': {
		keywords: ['diagram', 'symbol', 'preparation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:11396',
		usage: 'Reserved for preparation diagram symbol.',
	},
	'diagram-symbol-sort': {
		keywords: ['diagram', 'symbol', 'sort'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:41429',
		usage: 'Reserved for sort diagram symbol.',
	},
	'diagram-symbol-stored-data': {
		keywords: ['diagram', 'symbol', 'stored data'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:12748',
		usage: 'Reserved for stored data diagram symbol.',
	},
	'diagram-symbol-summing-junction': {
		keywords: ['diagram', 'symbol', 'summing junction', 'cross'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:13217',
		usage: 'Reserved for summing junction diagram symbol.',
	},
	'diagram-symbol-terminator': {
		keywords: ['diagram', 'symbol', 'terminator', 'terminal', 'start point', 'end point'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '44846:12340',
		usage: 'Reserved for terminator (start or end point) diagram symbol.',
	},
	'distribute-spacing-horizontal': {
		keywords: ['Distribute', 'Horizontal spacing', 'Tidy up', 'Clean up'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40576:10120',
		usage:
			'Evenly distributing the horizontal space between multiple selected objects on Whiteboards',
	},
	'distribute-spacing-vertical': {
		keywords: ['Distribute', 'Vertical spacing', 'Clean up', 'Tidy'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40573:9585',
		usage:
			'Evenly distributing the vertical space between multiple selected objects on Whiteboards',
	},
	'divider-element': {
		keywords: ['divider', 'line break', 'horizontal rule'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'editor-design',
		type: 'core',
		status: 'published',
		id: '37481:23722',
		usage: 'Reserved for inserting divider elements in Confluence',
		slackChannel: '#editor-controls-project',
	},
	'dock-toolbar-top': {
		keywords: ['dock to top', 'fix to top', 'pin to top'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor-design',
		type: 'core',
		status: 'published',
		id: '40591:17031',
		usage: 'Reserved for docking a toolbar to the top of a page',
		slackChannel: '#Editor-design',
	},
	draw: {
		keywords: ['pencil', 'drawing', 'annotate'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '43245:5629',
		usage: 'For drawing and annotation',
		slackChannel: '#icon-contributions',
	},
	'drop-shadow': {
		keywords: ['Drop shadow'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34970:8105',
		usage: 'Toggle drop shadow on and off',
	},
	duplicate: {
		keywords: ['clone', 'duplicate', 'plus'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '34645:8165',
		usage: 'Reserved for cloning and duplicating objects.',
		slackChannel: '#icon-contributions',
	},
	editions: {
		keywords: ['gem', 'premium', 'diamond', 'precious stone', 'editions'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '13269:2278',
		usage:
			'Reserved for representing premium features and functionality. Editions may replace the current premium sparkle icon.',
	},
	'expand-element': {
		keywords: ['expand', 'editor object'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'editor-design',
		type: 'core',
		status: 'published',
		id: '37481:1524',
		usage: 'Reserved for inserting expand elements in Confluence',
		slackChannel: '#editor-controls-project',
	},
	eyedropper: {
		keywords: ['eyedropper', 'pipette', 'color picker', 'color sample'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '43249:35526',
		usage: 'Sampling a color with a color picker',
		slackChannel: '#icon-contributions',
	},
	'field-text': {
		keywords: ['form', 'input', 'label', 'cursor', 'text field'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '15048:9987',
		usage: 'Multi purpose',
	},
	'folder-shared': {
		keywords: ['Shared', 'User', 'Public'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:19713',
		usage: 'Reserved for shared folders',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'generative-date': {
		keywords: ['calendar', 'suggested date'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Align',
		type: 'core',
		status: 'published',
		id: '46125:5168',
		usage: 'Reserved for suggested dates.',
	},
	'generative-indicator': {
		keywords: ['AI', 'suggested', 'generative', 'suggestion'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Align',
		type: 'core',
		status: 'published',
		id: '46125:641',
		usage: 'Reserved for indicating generative and suggested content.',
	},
	gift: {
		keywords: ['gift', 'present'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		id: '38217:3180',
		usage: 'User-selectable icon choice for calendars',
	},
	'globe-strikethrough': {
		keywords: ['globe', 'strikethrough', 'private', 'not public'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:69001',
		usage: 'Known uses: Limited share permissions which are not public',
	},
	'group-selection': {
		keywords: ['group', 'selection', 'layers'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:31327',
		usage: 'Grouping selected objects in Whiteboards',
	},
	'group-ungroup-selection': {
		keywords: ['ungroup', 'selection', 'layers'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:31739',
		usage: 'Ungrouping selected objects in Whiteboards',
	},
	hand: {
		keywords: ['hand', 'grab', 'move', 'open palm'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:34788',
		usage: 'Used for move/hand tool in Whiteboards',
	},
	'hand-clenched': {
		keywords: ['whiteboards', 'grab'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '44846:17921',
		usage: 'Grabbing elements in whiteboards',
		replacement: {
			name: 'hand-closed',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'hand-closed': {
		keywords: ['hand tool', 'closed hand', 'grab', 'moving'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:10047',
		usage: 'Known uses: Hand tool in Whiteboards when actively moving objects.',
	},
	'hand-open': {
		keywords: ['hand tool', 'open hand', 'move tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:8905',
		usage: 'Known uses: Hand tool in Whiteboards for moving objects.',
	},
	'hand-raised': {
		keywords: ['hand', 'farewell', 'wave'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:34790',
		usage: 'Used for farewell feed in Atlassian Home.',
	},
	history: {
		keywords: ['version control', 'past', 'arrow', 'clock', 'time', 'history', 'recent'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:14213',
		usage: 'Reserved for history and recent',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	hourglass: {
		keywords: [],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Trello',
		type: 'core',
		status: 'published',
		id: '44510:5003',
		usage: 'Aging or expiring items',
		slackChannel: 'joel unger',
	},
	'if-else': {
		keywords: ['condition', 'statement', 'branch'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		id: '37740:3430',
		usage: 'Reserved for If Else conditions',
		slackChannel: '#help-automation-design',
	},
	'image-alt-text': {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor',
		type: 'core',
		status: 'published',
		id: '39011:1640',
		usage: 'Reserved for creating alt text for an image',
		slackChannel: '#editor-design',
	},
	'image-crop': {
		keywords: ['crop', 'crop tool', 'trim'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '39049:1523',
		usage: 'Reserved for cropping images',
	},
	'image-strikethrough': {
		keywords: ['image', 'strikethrough', 'hide images'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom Core Product - Workflows',
		type: 'core',
		status: 'published',
		id: '46133:1790',
		usage: 'Known uses: Represents "hide images" action in Loom Workflows.',
		slackChannel: '#pod-workflows',
	},
	incognito: {
		keywords: ['Whiteboards', 'Private', 'Incognito'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34970:7547',
		usage: 'Toggle Whiteboards private mode on and off.',
	},
	initiative: {
		keywords: ['crystal ball', 'system object', 'work collection', 'work type'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Enterprise',
		type: 'core',
		status: 'published',
		id: '25239:6752',
		usage: 'Reserved for initiative work type.',
	},
	jira: {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34970:9609',
		usage: 'Representing JIRA',
	},
	'jira-add': {
		keywords: ['Jira', 'Work items', 'Create'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40922:9669',
		usage: 'Reserved for adding Jira work items',
	},
	'jira-upload': {
		keywords: ['Jira', 'Work items', 'Import', 'Arrow up'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40922:10304',
		usage: 'Reserved for importing Jira work items',
	},
	kanban: {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Trello',
		type: 'core',
		status: 'published',
		id: '44028:34212',
		usage: 'Kanban board',
		slackChannel: '@joel unger',
	},
	'layout-five-columns': {
		keywords: ['layout', 'columns', '5 col', '5 cols'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Confluence Editor',
		type: 'core',
		status: 'published',
		id: '41494:11358',
		usage: 'Reserved for 5 column layout option in Confluence Editor.',
	},
	'layout-four-columns': {
		keywords: ['layout', 'columns', '4 col', '4 cols'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Confluence Editor',
		type: 'core',
		status: 'published',
		id: '41494:10898',
		usage: 'Reserved for 4 columns layout option in Confluence Editor.',
	},
	'layout-three-columns-sidebars-left': {
		keywords: ['layout', 'columns', '3 col', '3 cols', 'sidebars', 'asides'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor',
		type: 'core',
		status: 'published',
		id: '43213:8591',
		usage: 'Reserved for 3 column layout with 2 sidebars on left option in Confluence Editor.',
	},
	'layout-three-columns-sidebars-right': {
		keywords: ['layout', 'columns', '3 col', '3 cols', 'sidebars', 'asides'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor',
		type: 'core',
		status: 'published',
		id: '43213:12486',
		usage: 'Reserved for 3 column layout with 2 sidebars on right option in Confluence Editor.',
	},
	'link-restricted-access': {
		keywords: ['link', 'strikethrough', 'limited'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:69321',
		usage: 'Reserved for when there is limited link permissions',
	},
	lozenge: {
		keywords: ['insert', 'status', 'badge'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor',
		type: 'core',
		status: 'published',
		id: '19872:15541',
		usage: 'Reserved for inserting status lozenges in Editor.',
	},
	'microphone-strikethrough': {
		keywords: ['mic', 'no audio', 'off'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:69641',
		usage: 'Reserved for no microphone input',
	},
	'milestone-complete': {
		keywords: ['milestone', 'completed', 'check mark', 'roadmaps', 'calendar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Align',
		type: 'core',
		status: 'published',
		id: '46125:6451',
		usage: 'Reserved for representing a completed milestone.',
	},
	'milestone-incomplete': {
		keywords: ['milestone', 'incompleted', 'roadmaps', 'calendar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Align',
		type: 'core',
		status: 'published',
		id: '46125:6899',
		usage: 'Reserved for representing an incomplete milestone.',
	},
	'milestone-multiple': {
		keywords: ['milestone', 'milestones', 'multiple milestones', 'roadmaps', 'calendar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Align',
		type: 'core',
		status: 'published',
		id: '46125:5616',
		usage: 'Reserved for use when multiple milestones occur on a single date or point in time.',
	},
	'milestone-overdue': {
		keywords: ['overdue', 'past due', 'milestone', 'roadmaps', 'calendar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Align',
		type: 'core',
		status: 'published',
		id: '46125:6064',
		usage: 'Reserved for representing an overdue milestone.',
	},
	'node-parallel-bottom-left': {
		keywords: ['Node', 'Parallel', 'Bottom', 'Left'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:19825',
		usage: 'Reserved for whiteboard’s node parallel-bottom-left',
	},
	'node-parallel-bottom-right': {
		keywords: ['Node', 'parallel', 'bottom', 'right'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:21557',
		usage: 'Reserved for whiteboard’s node parallel-bottom-right',
	},
	'node-parallel-top-left': {
		keywords: ['Node', 'Parallel', 'Top', 'Left'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:20487',
		usage: 'Reserved for whiteboard’s node parallel-top-left',
	},
	'node-parallel-top-right': {
		keywords: ['Node', 'parallel', 'top', 'right'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:22039',
		usage: 'Reserved for whiteboard’s node parallel-top-right',
	},
	'node-single-left': {
		keywords: ['Node', 'Single', 'Left'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:19295',
		usage: 'Reserved for whiteboard’s node single-left alignment',
	},
	'node-single-right': {
		keywords: ['Node', 'single', 'right'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:21027',
		usage: 'Reserved for whiteboard’s node single-right',
	},
	notepad: {
		keywords: ['Card', 'Note', 'Notepad', 'Memo'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Confluence Whiteboards',
		type: 'core',
		status: 'published',
		id: '40949:7714',
		usage: "Whiteboard component 'card'",
	},
	'page-live-doc': {
		keywords: ['page', 'live edit', 'lightning bolt', 'multiplayer', 'document', 'live doc'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		id: '34342:7619',
		usage: 'Reserved for Live Document content type.',
	},
	'paint-brush': {
		keywords: ['brush', 'appearance', 'paint'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14012:6657',
		usage: 'Multi purpose',
	},
	'paint-roller': {
		keywords: ['roller', 'background', 'paint'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14012:6658',
		usage: 'Multi purpose',
	},
	panel: {
		keywords: ['panel', 'card'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '37184:3289',
		usage: 'Panel category in Confluence',
	},
	'party-popper': {
		keywords: ['party', 'celebrate', 'celebration', 'confetti'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		id: '38217:3528',
		usage: 'User-selectable icon choice for calendars',
	},
	pencil: {
		keywords: ['compose', 'write', 'pen'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:12317',
		usage: 'Known uses: compose video title in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'person-voiceover': {
		keywords: ['voice', 'speak', 'speech', 'human', 'user'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:64640',
		usage: 'Known uses: voiceover within Loom Variables',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'pin-strikethrough': {
		keywords: ['push pin', 'thumbtack', 'tack', 'unpin'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira',
		type: 'core',
		status: 'published',
		id: '42715:8474',
		usage: 'Known uses: Unpinning comments in Jira',
	},
	'plus-circle': {
		keywords: ['add'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:31518',
		usage: 'Known uses: add task in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	power: {
		keywords: ['energy', 'turn on', 'turn off', 'power off'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:32465',
		usage: 'Known uses: Turn off Loom companion in Chrome extension',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'qr-code': {
		keywords: ['QR code', 'barcode'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Assets',
		type: 'core',
		status: 'published',
		id: '26733:10661',
		usage: 'Reserved for QR code experiences.',
	},
	'queue-pop-in': {
		keywords: ['Queues', 'pop-in', 'pop in', 'move back to sidebar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'JSM core capabilities',
		type: 'core',
		status: 'published',
		id: '36839:5653',
		usage: 'Reserved for JSM queue navigation to move back to sidebar',
	},
	'queue-pop-out': {
		keywords: ['pop-out', 'pop out', 'Queues', 'Move out from sidebar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'JSM core capabilities',
		type: 'core',
		status: 'published',
		id: '36849:2586',
		usage: 'Reserved for JSM queue navigation to pop out from sidebar',
	},
	randomize: {
		keywords: ['randomize', 'randomise', 'shuffle'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '46664:37049',
		usage: 'Reserved for randomizing or shuffling functionality.',
	},
	recur: {
		keywords: ['recur', 'recurring', 'repeat', 'repeating'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Pandora',
		type: 'core',
		status: 'deprecated',
		id: '42266:50489',
		usage: 'Reserved for setting objects to recur (eg Work items, Forms)',
		slackChannel: '#horizon-pandora-eng',
		replacement: {
			name: 'repeat',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	repeat: {
		keywords: ['recur', 'recurring', 'repeat', 'repeating'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Pandora',
		type: 'core',
		status: 'published',
		id: '39662:2817',
		usage: 'Reserved for setting objects to recur (eg Work items, Forms)',
		slackChannel: '#horizon-pandora-eng',
	},
	'reply-left': {
		keywords: ['arrow', 'reply', 'respond', 'message'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:69961',
		usage: 'Known uses: replying to a message thread',
	},
	'reply-right': {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:70281',
		usage: 'Known uses: replying to a message thread',
	},
	return: {
		keywords: ['submit', 'return', 'enter', 'confirm'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Data Experiences (AVP)',
		type: 'core',
		status: 'published',
		id: '42181:10648',
		usage: 'Reserved for submitting text fields without dedicated button, mainly AI prompts',
		slackChannel: '#avp-design',
	},
	'roadmaps-plan': {
		keywords: ['roadmaps', 'roadmap', 'plan'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '9267:17512',
		usage: 'Reserved for roadmaps plan.',
	},
	'roadmaps-service': {
		keywords: ['roadmaps', 'service', 'roadmap'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '9267:17513',
		usage: 'Reserved for roadmaps service.',
	},
	save: {
		keywords: ['floppy disk', 'save', 'floppy drive', 'storage', 'diskette'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '43245:6194',
		usage: 'Reserved for saving',
		slackChannel: '#icon-contributions',
	},
	'screen-record': {
		keywords: ['screen recorder', 'camera', 'cam bubble'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:74674',
		usage: 'Known uses: screen recorder with the cam bubble for Loom',
	},
	section: {
		keywords: ['section', 'related content'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:35851',
		usage: 'Used for section tool in Whiteboards',
	},
	'shape-comment-left': {
		keywords: ['comment', 'left', 'diagram', 'symbol'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:11605',
		usage: 'Reserved for comment left diagram symbol.',
		replacement: {
			name: 'diagram-symbol-comment-left',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-comment-right': {
		keywords: ['comment', 'right', 'diagram', 'symbol'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:12589',
		usage: 'Reserved for comment right diagram symbol.',
		replacement: {
			name: 'diagram-symbol-comment-right',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-database': {
		keywords: ['diagram', 'symbol', 'database'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:13573',
		usage: 'Reserved for database diagram symbol.',
		replacement: {
			name: 'diagram-symbol-database',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-delay': {
		keywords: ['diagram', 'symbol', 'delay'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:14496',
		usage: 'Reserved for delay diagram symbol.',
		replacement: {
			name: 'diagram-symbol-delay',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-diamond': {
		keywords: ['diamond', 'shape tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:50849',
		usage: 'Diamond shape tool in Whiteboards',
	},
	'shape-display': {
		keywords: ['diagram', 'symbol', 'display'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:15419',
		usage: 'Reserved for display diagram symbol.',
		replacement: {
			name: 'diagram-symbol-display',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-document-symbol': {
		keywords: ['diagram', 'symbol', 'document'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:16403',
		usage: 'Reserved for single document diagram symbol.',
		replacement: {
			name: 'diagram-symbol-document',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-ellipse': {
		keywords: ['ellipse', 'circle', 'shape tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:50437',
		usage: 'Ellipse shape tool in Whiteboards',
	},
	'shape-hard-disk': {
		keywords: ['diagram', 'symbol', 'hard disk', 'hard drive', 'storage'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:17387',
		usage: 'Reserved for hard disk diagram symbol.',
		replacement: {
			name: 'diagram-symbol-hard-disk',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-internal-storage': {
		keywords: ['diagram', 'symbol', 'internal storage'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:18213',
		usage: 'Reserved for internal storage diagram symbol.',
		replacement: {
			name: 'diagram-symbol-internal-storage',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-manual-input': {
		keywords: ['diagram', 'symbol', 'manual input'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:18978',
		usage: 'Reserved for manual input diagram symbol.',
		replacement: {
			name: 'diagram-symbol-manual-input',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-manual-operation-symbol': {
		keywords: ['diagram', 'symbol', 'manual operation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:19743',
		usage: 'Reserved for manual operation diagram symbol.',
		replacement: {
			name: 'diagram-symbol-manual-operation',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-mindmap': {
		keywords: ['diagram', 'symbol', 'mind map'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:21201',
		usage: 'Reserved for mind map diagram symbol.',
		replacement: {
			name: 'diagram-symbol-mind-map',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-multiple-documents': {
		keywords: ['diagram', 'symbol', 'multiple documents'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:22185',
		usage: 'Reserved for multiple documents diagram symbol',
		replacement: {
			name: 'diagram-symbol-documents',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-off-page': {
		keywords: ['off-page', 'diagram', 'symbol', 'connector'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:30137',
		usage: 'Reserved for off-page connector diagram symbol.',
		replacement: {
			name: 'diagram-symbol-connector-off-page',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-parallelogram-skew-left': {
		keywords: ['parallelogram', 'skewed', 'left', 'shape tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:49594',
		usage: 'Left parallelogram shape tool in Whiteboards',
	},
	'shape-parallelogram-skew-right': {
		keywords: ['parallelogram', 'skewed', 'shape tool', 'right'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:49182',
		usage: 'Right parallelogram shape tool in Whiteboards',
	},
	'shape-predefined-process': {
		keywords: ['diagram', 'symbol', 'predefined process'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:31431',
		usage: 'Reserved for predefined process diagram symbol.',
		replacement: {
			name: 'diagram-symbol-predefined-process',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-preparation-symbol': {
		keywords: ['diagram', 'symbol', 'preparation'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:32320',
		usage: 'Reserved for preparation diagram symbol.',
		replacement: {
			name: 'diagram-symbol-preparation',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-rectangle': {
		keywords: ['shape tool', 'rectangle', 'square'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34972:46759',
		usage: 'Rectangle shape tool in Whiteboards',
	},
	'shape-rectangle-rounded': {
		keywords: ['shape tool', 'rectangle', 'rounded', 'square'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34972:47171',
		usage: 'Rounded rectangle shape tool in Whiteboards',
	},
	'shape-start-end': {
		keywords: ['diagram', 'symbol', 'terminator', 'terminal', 'start point', 'end point'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:33279',
		usage: 'Reserved for terminator (start or end point) diagram symbol.',
		replacement: {
			name: 'diagram-symbol-terminator',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-stored-data': {
		keywords: ['diagram', 'symbol', 'stored data'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:34238',
		usage: 'Reserved for stored data diagram symbol.',
		replacement: {
			name: 'diagram-symbol-stored-data',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-summing-junction-cross': {
		keywords: ['diagram', 'symbol', 'summing junction', 'cross'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:35264',
		usage: 'Reserved for summing junction diagram symbol.',
		replacement: {
			name: 'diagram-symbol-summing-junction',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-summing-junction-plus': {
		keywords: ['diagram', 'symbol', 'or', 'logic'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'deprecated',
		id: '46664:36053',
		usage: 'Reserved for or diagram symbol.',
		replacement: {
			name: 'diagram-symbol-or',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'shape-triangle': {
		keywords: ['triangle', 'shape tool', 'equilateral'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:48712',
		usage: 'Triangle shape tool in Whiteboards',
	},
	'shape-triangle-inverted': {
		keywords: ['triangle', 'shape tool', 'equilateral'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:51261',
		usage: 'Upside down triangle shape tool in Whiteboards',
	},
	signature: {
		keywords: ['signature', 'scribble', 'author', 'authour', 'sticky note', 'post-it'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34857:1500',
		usage: 'Toggle author visibility on sticky notes in Whiteboards.',
	},
	'sort-options': {
		keywords: ['sorting', 'ordering', 'alphabetization', 'alphabetisation', 'reordering'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Databases',
		type: 'core',
		status: 'published',
		id: '39345:3314',
		usage: 'Reserved for accessing sorting options.',
	},
	space: {
		keywords: ['space', 'spaces', 'projects'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira',
		type: 'core',
		status: 'deprecated',
		id: '45538:34528',
		usage:
			'Reserved for use for Jira Projects for now. This will replace the Jira rocket. \n\nMore context: Later, it will eventually replace the Confluence Spaces icon later when Jira Projects -> Jira Spaces. This is a planned phased rollout.',
		slackChannel: '#jira-design-system-figma-libraries',
		replacement: {
			name: 'spaces',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	spaces: {
		keywords: ['space', 'spaces', 'projects'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira',
		type: 'core',
		status: 'published',
		id: '40759:3075',
		usage:
			'Reserved for use for Jira Projects for now. This will replace the Jira rocket. \n\nMore context: Later, it will eventually replace the Confluence Spaces icon later when Jira Projects -> Jira Spaces. This is a planned phased rollout.',
		slackChannel: '#jira-design-system-figma-libraries',
	},
	speedometer: {
		keywords: ['speed', 'performance', 'dial', 'fast'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'deprecated',
		id: '42266:53267',
		usage: 'Known uses: video is set to a faster playback speed',
		replacement: {
			name: 'speedometer-right',
			type: 'core',
			location: '@atlaskit/icon-lab',
		},
	},
	'speedometer-left': {
		keywords: ['speed', 'performance', 'dial', 'slow'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:70985',
		usage: 'Known uses: video is set to a slower playback speed',
	},
	'speedometer-right': {
		keywords: ['speed', 'performance', 'dial', 'fast'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '14531:7329',
		usage: 'Known uses: video is set to a faster playback speed',
	},
	'speedometer-up': {
		keywords: ['speed', 'performance', 'dial'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:70665',
		usage: 'Known uses: video is set a normal playback speed',
	},
	'split-parallel': {
		keywords: ['router', 'branches'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		id: '38222:3275',
		usage: 'Reserved for split parallel branches in Automation',
		slackChannel: '#help-automation-design',
	},
	stamp: {
		keywords: ['stamp', 'rubber stamp', 'handstamp'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:33830',
		usage: 'Used for stamp tool in Whiteboards',
	},
	sticker: {
		keywords: ['sticker', 'peel-off'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:33198',
		usage: 'Used for sticker tool in Whiteboards',
	},
	'stroke-curvature-curved': {
		keywords: ['line tool', 'shape property', 'stroke style', 'border', 'smooth'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:53538',
		usage: 'Reserved for curved line type setting for line tool in Whiteboards.',
	},
	'stroke-curvature-dynamic': {
		keywords: ['line tool', 'shape property', 'stroke style', 'border'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:53072',
		usage: 'Reserved for dynamic line type setting for line tool in Whiteboards',
	},
	'stroke-curvature-straight': {
		keywords: ['line tool', 'shape property', 'stroke style', 'sharp corners', 'border'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:54004',
		usage: 'Reserved for straight line type setting for line tool in Whiteboards',
	},
	'stroke-properties': {
		keywords: ['stroke properties', 'border options'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34982:54840',
		usage: 'Reserved for stroke properties in Whiteboards',
	},
	'stroke-style-dashed': {
		keywords: ['border', 'stroke', 'border style', 'dashed', 'outline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34972:44125',
		usage: 'Reserved for representing dashed stroke and border styles.',
	},
	'stroke-style-dotted': {
		keywords: ['border', 'stroke', 'border style', 'dotted', 'outline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34972:42884',
		usage: 'Reserved for representing dotted stroke and border styles.',
	},
	'stroke-style-solid': {
		keywords: ['border', 'stroke', 'border style', 'solid', 'outline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34959:42208',
		usage: 'Reserved for representing solid stroke and border styles.',
	},
	studio: {
		keywords: ['studio', 'atlassian studio'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design Systems Team',
		type: 'core',
		status: 'published',
		id: '42768:12786',
		usage: 'Reserved for functional representation of Atlassian Studio',
	},
	'suggested-edit': {
		keywords: ['AI', 'suggestion', 'suggested edit', 'suggest', 'generative'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '37184:4281',
		usage: 'Reserved for suggestions powered by Atlassian Intelligence',
	},
	sunset: {
		keywords: ['sun', 'horizon', 'farewell', 'goodbye', 'sky', 'farewell feed'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'confluence insights',
		type: 'core',
		status: 'published',
		id: '33454:1935',
		usage: 'Farewell feed in hello.',
	},
	swap: {
		keywords: ['Swap', 'Jira status', 'Whiteboards', 'Smart section'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34961:2665',
		usage: 'Swapping between Jira tickets in Whiteboard smart section',
	},
	'switch-case': {
		keywords: ['conditions', 'if', 'else', 'else if'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automations',
		type: 'core',
		status: 'published',
		id: '38222:4582',
		usage: 'Reserved for switch case conditions in automation',
		slackChannel: '#help-automation-design',
	},
	sync: {
		keywords: ['sync', 'synch', 'synchronise', 'synchronize', 'saving', 'arrows'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		id: '33429:18763',
		usage: 'Reserved for syncing changes and save operations.',
	},
	tab: {
		keywords: ['key', 'tab'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '42430:37472',
		usage: 'Reserved for representing tab key.',
		slackChannel: '#icon-contributions',
	},
	'takeout-container': {
		keywords: ['takeout', 'food', 'takeaway'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14151:10764',
		usage: 'Known usages: Alternative option for food emoji category.',
	},
	talent: {
		keywords: ['talent', 'person', 'star'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Talent',
		type: 'core',
		status: 'published',
		id: '41418:13168',
		usage: 'Reserved for functional representation of Talent app',
	},
	telescope: {
		keywords: ['telescope', 'scope', 'discover', 'discovery'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Atlassian Home',
		type: 'core',
		status: 'published',
		id: '43218:2261',
		usage: 'Known uses: Discover feature in Atlassian Home',
	},
	template: {
		keywords: ['template', 'templates'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34895:30637',
		usage: 'Used for templates in Whiteboards',
	},
	'text-adjust-length': {
		keywords: ['text length', 'change text length', 'adjust text length'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '46226:5732',
		usage: 'Reserved for accessing text length generative AI actions.',
	},
	'text-audio-transcript': {
		keywords: ['microphone', 'script', 'paragraph'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:57122',
		usage: 'Reserved for viewing transcript in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'text-bold-italic': {
		keywords: ['Text', 'Type', 'Font', 'Bold', 'Italic'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:14547',
		usage: 'Reserved for bold text with italic',
	},
	'text-bold-italic-strikethrough': {
		keywords: ['Text', 'Type', 'strikethrough', 'Bold', 'Italic'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40581:13117',
		usage: 'Reserved for italic bold text with a strikethrough',
	},
	'text-bold-italic-underline': {
		keywords: ['Text', 'Type', 'Font', 'Bold', 'Italic', 'Underline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40581:14223',
		usage: 'Reserved for bold italic text with underline',
	},
	'text-bold-italic-underline-strikethrough': {
		keywords: ['text formatting', 'bold', 'underline', 'strikethrough', 'italic'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40743:11377',
		usage: 'Reserved for bold italic text with underline and strikethrough',
	},
	'text-bold-strikethrough': {
		keywords: ['Text', 'Type', 'Bold', 'strikethrough'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40581:12385',
		usage: 'Reserved for bold strikethrough text',
	},
	'text-bold-underline': {
		keywords: ['bold', 'underline', 'text formatting'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40743:10409',
		usage: 'Reserved for bold text with underline',
	},
	'text-bold-underline-strikethrough': {
		keywords: ['text formatting', 'bold', 'strikethrough', 'underline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40743:12351',
		usage: 'Reserved for bold text with underline and strikethrough',
	},
	'text-conclusion-add': {
		keywords: ['text', 'conclusion', 'AI', 'generative'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '37184:2645',
		usage: 'Confluence Editor AI action for generating a conclusion',
	},
	'text-heading-five': {
		keywords: ['heading 5', 'H5', 'text style'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor design',
		type: 'core',
		status: 'published',
		id: '42216:18751',
		usage: 'Reserved for H5 / Heading 5 text style',
		slackChannel: '#editor-design',
	},
	'text-heading-four': {
		keywords: ['heading 4', 'H4', 'text style'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor design',
		type: 'core',
		status: 'published',
		id: '42216:17878',
		usage: 'Reserved for H4 / Heading 4 text style',
		slackChannel: '#editor-design',
	},
	'text-heading-one': {
		keywords: ['Heading 1', 'H1', 'text style'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor design',
		type: 'core',
		status: 'published',
		id: '42015:7585',
		usage: 'Reserved for H1 / Heading 1 text style',
		slackChannel: '#Editor-design',
	},
	'text-heading-six': {
		keywords: ['heading 6', 'H6', 'text style'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor design',
		type: 'core',
		status: 'published',
		id: '42216:19624',
		usage: 'Reserved for H6 / Heading 6 text style',
		slackChannel: '#editor-design',
	},
	'text-heading-three': {
		keywords: ['heading 3', 'H3', 'text style'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor design',
		type: 'core',
		status: 'published',
		id: '42106:77338',
		usage: 'Reserved for H3 / Heading 3 text style',
		slackChannel: '#editor-design',
	},
	'text-heading-two': {
		keywords: ['Heading 2', 'H2', 'text style'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor design',
		type: 'core',
		status: 'published',
		id: '42106:35610',
		usage: 'Reserved for H2 / Heading 2 text style',
		slackChannel: '#editor-design',
	},
	'text-introduction-add': {
		keywords: ['text', 'introduction', 'AI', 'generative'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '37184:2993',
		usage: 'Confluence Editor AI action for generating an introduction',
	},
	'text-italic-strikethrough': {
		keywords: ['Text', 'Type', 'Font', 'Italic', 'Strikethrough'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:16873',
		usage: 'Reserved for italic text with strikethrough',
	},
	'text-italic-underline': {
		keywords: ['Text', 'Type', 'Font', 'Underline', 'Italic'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:17539',
		usage: 'Reserved for italic text with underline',
	},
	'text-italic-underline-strikethrough': {
		keywords: ['text formatting', 'italic', 'underline', 'strikethrough'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40743:13080',
		usage: 'Reserved for italic text with underline and strikethrough',
	},
	'text-lengthen': {
		keywords: ['text', 'lengthen', 'expand', 'AI', 'generative'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '37184:3933',
		usage: 'Lengthening text content with Atlassian Intelligence',
	},
	'text-letter-case': {
		keywords: [
			'text case',
			'letter case',
			'uppercase',
			'lowercase',
			'sentence case',
			'title case',
			'Aa',
		],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '44118:41694',
		usage: 'Reserved for letter casing and text-transform',
		slackChannel: '#icon-contributions',
	},
	'text-paragraph': {
		keywords: ['text', 'paragraph break', 'AI', 'generative', 'reformat'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '37184:4629',
		usage:
			'Confluence Editor AI action for reformatting paragraphs into multiple shorter paragraphs',
	},
	'text-rephrase': {
		keywords: ['text', 'rephrase', 'AI', 'generative'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor AI',
		type: 'core',
		status: 'published',
		id: '37184:3585',
		usage: 'Confluence Editor AI action for rephrasing text',
	},
	'text-subscript': {
		keywords: ['subscript', 'text formatting'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor',
		type: 'core',
		status: 'published',
		id: '44549:637',
		usage: 'Reserved for subscript text formatting.',
		slackChannel: '#editor-design',
	},
	'text-superscript': {
		keywords: ['superscript', 'text formatting'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor',
		type: 'core',
		status: 'published',
		id: '44556:4256',
		usage: 'Reserved for superscript text formatting.',
		slackChannel: '#Editor-design',
	},
	'text-underline-strikethrough': {
		keywords: ['text', 'type', 'font', 'strikethrough', 'underline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '40584:18624',
		usage: 'Reserved for underline text with a strikethrough',
	},
	ticket: {
		keywords: ['stub', 'ticket'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14196:13220',
		usage: 'Multi purpose',
	},
	tidy: {
		keywords: ['Tidy', 'Clean up', 'Tidy up', 'Grid'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		id: '34970:11670',
		usage: 'Tidy up objects on Whiteboards',
	},
	variable: {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:36042',
		usage: 'Reserved for Variables functionality in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'vehicle-airplane': {
		keywords: ['plane', 'airplane', 'aeroplane', 'travel', 'vehicle'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		id: '38223:3876',
		usage: 'User-selectable icon choice for calendars',
	},
	'vehicle-train': {
		keywords: ['transportation', 'vehicle', 'car'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '13786:9073',
		usage: 'Known usages: Alternative option for transport emoji category.',
	},
	'video-captions-stylized': {
		keywords: ['CC', 'subtitles'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:48503',
		usage: 'Reserved for stylized captions functionality in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'video-clip': {
		keywords: ['film', 'film strip', 'video', 'media', 'file'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:11695',
		usage: 'Known uses: add clip in Loom video editor',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'video-closed-captions': {
		keywords: ['CC', 'closed captions', 'subtitles'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:68297',
		usage: 'Reserved for enabling closed captions for videos.',
	},
	'video-closed-captions-filled': {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:68617',
		usage: 'Reserved to show that closed captions are enabled for videos.',
	},
	'video-hd': {
		keywords: ['high definition', 'hi def'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Atlassian Design System',
		type: 'core',
		status: 'published',
		id: '40278:3615',
		usage: 'Single purpose - Reserved for enabling high definition videos',
	},
	'video-hd-filled': {
		keywords: ['high definition', 'hi def'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Atlassian Design System',
		type: 'core',
		status: 'published',
		id: '40650:21827',
		usage: 'Single purpose - Reserved to show that high definition is enabled for videos',
	},
	'video-miniplayer': {
		keywords: ['picture in picture', 'PIP'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:24003',
		usage: 'Reserved for picture-in-picture functionality for videos.',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'video-overlay-tools': {
		keywords: ['overlays', 'video', 'add text', 'add arrow', 'add box'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:78317',
		usage: 'Reserved for overlays over a video.',
	},
	'video-play-circle': {
		keywords: ['video', 'start'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42075:26112',
		usage: 'Known uses: play video in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'video-record': {
		keywords: ['live', 'circle', 'ellipse', 'recording'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42087:34452',
		usage: 'Reserved for when a video is recording',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'video-rewind-overlay': {
		keywords: ['rewind back'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:72772',
		usage: 'Reserved for rewinding videos.',
	},
	'video-skip-backward-five': {
		keywords: ['video', 'media', 'skip', 'forward', '5', 'seconds'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:67913',
		usage: 'Reserved for skipping video content backward by 5 seconds.',
	},
	'video-skip-forward-five': {
		keywords: ['video', 'media', 'skip', 'forward', '5', 'seconds'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:72132',
		usage: 'Reserved for skipping video content forward by 5 seconds.',
	},
	'video-strikethrough': {
		keywords: ['video', 'no video', 'camera off', 'off'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:72452',
		usage: 'Reserved for no video input',
	},
	'video-theater-mode': {
		keywords: ['theater mode', 'view', 'viewport', 'video', 'wide'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:77623',
		usage: 'Reserved for theater mode functionality within video player.',
	},
	'video-timeline-clip-split': {
		keywords: ['split', 'clip', 'edit', 'enhance', 'video', 'timeline', 'trim'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:75687',
		usage: 'Reserved for split clip functionality in Loom.',
	},
	'video-timeline-editor': {
		keywords: ['track', 'edit', 'video'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42087:34943',
		usage: 'Reserved for timeline editor functionality in Loom',
		slackChannel: '#feedback-loom-vizrefresh',
	},
	'video-watch-later-remove': {
		keywords: ['bookmark', 'x', 'remove', 'cross'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:83109',
		usage: 'Reserved for watch later functionality in Loom',
	},
	'video-watch-later-saved': {
		keywords: ['bookmark', 'check', 'saved'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Loom',
		type: 'core',
		status: 'published',
		id: '42096:80171',
		usage: 'Reserved for watch later functionality in Loom',
	},
	'view-type-board-home': {
		keywords: ['board view', 'databases', 'home', 'default view'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Databases',
		type: 'core',
		status: 'published',
		id: '37878:2088',
		usage: 'Home view for database board layout',
	},
	'view-type-card-home': {
		keywords: ['card view', 'databases', 'home', 'default view'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Databases',
		type: 'core',
		status: 'published',
		id: '37849:3085',
		usage: 'Home view for database card layout',
	},
	'view-type-table-home': {
		keywords: ['table view', 'databases', 'home', 'default view'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Databases',
		type: 'core',
		status: 'published',
		id: '37849:2650',
		usage: 'Home view for database table layout',
	},
	vulnerability: {
		keywords: ['vulnerability', 'security', 'alert', 'warning'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		id: '22279:20982',
		usage: 'Reserved for security vulnerabilities.',
	},
	wallet: {
		keywords: ['money', 'sales', 'payment', 'wallet'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14151:10946',
		usage: 'Multi purpose',
	},
	'warning-outline': {
		keywords: ['warning', 'exclamation', 'overdue', 'past due', 'late'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Atlassian Home',
		type: 'core',
		status: 'published',
		id: '36692:9337',
		usage: 'Low-impact warnings. Overdue dates in Atlassian Home.',
	},
	webhook: {
		keywords: ['api', 'callback', 'payload'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		id: '37740:2659',
		usage: 'Reserved for using a webhook to send data between applications via HTTP',
		slackChannel: '#help-automation-design',
	},
	'welcome-feed': {
		keywords: ['welcome', 'hello', 'blog', 'smile', 'intro'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Insights',
		type: 'core',
		status: 'published',
		id: '32051:1614',
		usage: 'Known uses: Intro blog feed picker on Hello',
		slackChannel: '#cc-insights-and-reporting',
	},
	'work-item-add': {
		keywords: ['work item', 'work type', 'add', 'plus', 'create'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira',
		type: 'core',
		status: 'published',
		id: '39421:3488',
		usage: 'Reserved for adding or creating a new work item.',
	},
	'workflow-controls': {
		keywords: ['orchestration'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		id: '38222:5661',
		usage: 'Reserved for workflow controls in automation',
		slackChannel: '#help-automation-design',
	},
	wrench: {
		keywords: ['wrench', 'spanner', 'tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		id: '14520:13419',
		usage: 'Multi purpose',
	},
};

export default metadata;
