import { type IconMetadata } from '@af/icon-build-process';
const metadata: IconMetadata = {
	'assets-data-manager': {
		keywords: ['data manager', 'assets', 'CMDB', 'configuration management database'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Assets',
		type: 'core',
		status: 'published',
		usage: 'Reserved for JSM Assets.',
	},
	'assets-schema': {
		keywords: ['assets', 'CMDB', 'configuration management database'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Assets',
		type: 'core',
		status: 'published',
		usage: 'Reserved for JSM Assets.',
	},
	'cloud-offline': {
		keywords: ['cloud', 'offline', 'disconnected', 'strikethrough'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		usage: "Reserved for showing when a connection can't be established to the cloud.",
	},
	'cloud-saved': {
		keywords: ['cloud', 'check mark', 'saved', 'success'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		usage: 'Reserved for showing saved status after successful cloud synchronisation.',
	},
	'continue-when': {
		keywords: [],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		usage: 'Reserved for continue when delay in automation.',
		slackChannel: '#help-automation-design',
	},
	'drop-shadow': {
		keywords: ['Drop shadow'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Toggle drop shadow on and off',
	},
	duplicate: {
		keywords: ['clone', 'duplicate', 'plus'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Reserved for cloning and duplicating objects.',
		slackChannel: '#icon-contributions',
	},
	editions: {
		keywords: ['gem', 'premium', 'diamond', 'precious stone', 'editions'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage:
			'Reserved for representing premium features and functionality. Editions may replace the current premium sparkle icon.',
	},
	'if-else': {
		keywords: ['condition', 'statement', 'branch'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		usage: 'Reserved for If Else conditions',
		slackChannel: '#help-automation-design',
	},
	incognito: {
		keywords: ['Whiteboards', 'Private', 'Incognito'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Toggle Whiteboards private mode on and off.',
	},
	initiative: {
		keywords: [
			'fortune teller',
			'crystal ball',
			'future',
			'issue type',
			'system object',
			'work collection',
		],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Jira Enterprise',
		type: 'core',
		status: 'published',
		usage: 'Representing Jira Initiatives',
	},
	lozenge: {
		keywords: ['insert', 'status', 'badge'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Editor',
		type: 'core',
		status: 'published',
		usage: 'Reserved for inserting status lozenges in Editor.',
	},
	'page-live-doc': {
		keywords: ['page', 'live edit', 'lightning bolt', 'multiplayer', 'document', 'live doc'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		usage: 'Reserved for Live Document content type.',
	},
	'qr-code': {
		keywords: ['QR code', 'barcode'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Assets',
		type: 'core',
		status: 'published',
		usage: 'Reserved for QR code experiences.',
	},
	'queue-pop-in': {
		keywords: ['Queues', 'pop-in', 'pop in', 'move back to sidebar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'JSM core capabilities',
		type: 'core',
		status: 'published',
		usage: 'Reserved for JSM queue navigation to move back to sidebar',
	},
	'queue-pop-out': {
		keywords: ['pop-out', 'pop out', 'Queues', 'Move out from sidebar'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'JSM core capabilities',
		type: 'core',
		status: 'published',
		usage: 'Reserved for JSM queue navigation to pop out from sidebar',
	},
	'roadmaps-plan': {
		keywords: ['roadmaps', 'roadmap', 'plan'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Reserved for roadmaps plan.',
	},
	'roadmaps-service': {
		keywords: ['roadmaps', 'service', 'roadmap'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Reserved for roadmaps service.',
	},
	'split-parallel': {
		keywords: ['router', 'branches'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		usage: 'Reserved for split parallel branches in Automation',
		slackChannel: '#help-automation-design',
	},
	'stroke-curvature-curved': {
		keywords: ['line tool', 'shape property', 'stroke style', 'border', 'smooth'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Reserved for curved line type setting for line tool in Whiteboards.',
	},
	'stroke-curvature-dynamic': {
		keywords: ['line tool', 'shape property', 'stroke style', 'border'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Reserved for dynamic line type setting for line tool in Whiteboards',
	},
	'stroke-curvature-straight': {
		keywords: ['line tool', 'shape property', 'stroke style', 'sharp corners', 'border'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Reserved for straight line type setting for line tool in Whiteboards',
	},
	'stroke-properties': {
		keywords: ['stroke properties', 'border options'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Reserved for stroke properties in Whiteboards',
	},
	'stroke-style-dashed': {
		keywords: ['border', 'stroke', 'border style', 'dashed', 'outline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Reserved for representing dashed stroke and border styles.',
	},
	'stroke-style-dotted': {
		keywords: ['border', 'stroke', 'border style', 'dotted', 'outline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Reserved for representing dotted stroke and border styles.',
	},
	'stroke-style-solid': {
		keywords: ['border', 'stroke', 'border style', 'solid', 'outline'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Reserved for representing solid stroke and border styles.',
	},
	swap: {
		keywords: ['Swap', 'Jira status', 'Whiteboards', 'Smart section'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Swapping between Jira tickets in Whiteboard smart section',
	},
	'switch-case': {
		keywords: ['conditions', 'if', 'else', 'else if'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automations',
		type: 'core',
		status: 'published',
		usage: 'Reserved for switch case conditions in automation',
		slackChannel: '#help-automation-design',
	},
	sync: {
		keywords: ['sync', 'synch', 'synchronise', 'synchronize', 'saving', 'arrows'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Content Types',
		type: 'core',
		status: 'published',
		usage: 'Reserved for syncing changes and save operations.',
	},
	tidy: {
		keywords: ['Tidy', 'Clean up', 'Tidy up', 'Grid'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Tidy up objects on Whiteboards',
	},
	vulnerability: {
		keywords: ['vulnerability', 'security', 'alert', 'warning'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		usage: 'Reserved for security vulnerabilities.',
	},
	webhook: {
		keywords: ['api', 'callback', 'payload'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		usage: 'Reserved for using a webhook to send data between applications via HTTP',
		slackChannel: '#help-automation-design',
	},
	'workflow-controls': {
		keywords: ['orchestration'],
		categorization: 'single-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Automation',
		type: 'core',
		status: 'published',
		usage: 'Reserved for workflow controls in automation',
		slackChannel: '#help-automation-design',
	},
	'align-content-bottom': {
		keywords: ['align', 'alignment', 'content', 'bottom', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for aligning bottom edges of content in Whiteboards',
	},
	'align-content-center-horizontal': {
		keywords: ['align', 'alignment', 'content', 'center', 'middle', 'horizontal'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for aligning horizontal centers of content in Whiteboards',
	},
	'align-content-center-vertical': {
		keywords: ['align', 'alignment', 'content', 'center', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for aligning vertical centers of content in Whiteboards',
	},
	'align-content-left': {
		keywords: ['align', 'alignment', 'content', 'left', 'horizontal'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for aligning left edges of content in Whiteboards',
	},
	'align-content-right': {
		keywords: ['align', 'alignment', 'content', 'right', 'horizontal'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for aligning right edges of content in Whiteboards',
	},
	'align-content-top': {
		keywords: ['align', 'alignment', 'content', 'top', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for aligning top edges of content in Whiteboards',
	},
	'align-position-bottom': {
		keywords: ['align', 'alignment', 'middle', 'text position', 'bottom', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Bottom-aligned text position within sticky notes in Whiteboards.',
	},
	'align-position-center-vertical': {
		keywords: ['align', 'alignment', 'middle', 'center', 'text position', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Center-aligned text position within sticky notes in Whiteboards.',
	},
	'align-position-top': {
		keywords: ['align', 'alignment', 'top edge', 'text position', 'vertical'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Top-aligned text position within sticky notes in Whiteboards.',
	},
	'beach-umbrella': {
		keywords: ['vacation', 'beach umbrella', 'sun shade', 'holiday'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		usage: 'User-selectable icon choice for calendars',
	},
	'book-open': {
		keywords: ['book', 'knowledgebase article'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Known uses: None',
	},
	coins: {
		keywords: ['money', 'loose change', 'currency'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	'cross-octagon': {
		keywords: ['cross', 'stop', 'block', 'octagon'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	cursor: {
		keywords: ['Whiteboards', 'Cursor'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Selecting the cursor in Whiteboards',
	},
	'cursor-strikethrough': {
		keywords: ['Cursor', 'Cursors', 'Hide cursor', 'Whiteboard cursor', 'Cursor strikethrough'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Hide collaborator cursors in the Whiteboard',
	},
	'database-storage': {
		keywords: ['database', 'db', 'storage', 'sql'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Ecosystem',
		type: 'core',
		status: 'published',
		usage: 'Known uses: SQL database in Developer Console',
		slackChannel: '#forge-sql',
	},
	'database-storage-cache': {
		keywords: ['database', 'db', 'storage', 'sql', 'cache'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Ecosystem',
		type: 'core',
		status: 'published',
		usage: 'Known uses: Storage cache in Developer Console.',
		slackChannel: '#forge-sql',
	},
	'divider-element': {
		keywords: [],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'editor-design',
		type: 'core',
		status: 'published',
		usage: 'Known uses: Insert divider element in Confluence',
		slackChannel: '#editor-controls-project',
	},
	'expand-element': {
		keywords: [],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'editor-design',
		type: 'core',
		status: 'published',
		usage: 'Known usage: Insert expand element in Confluence',
		slackChannel: '#editor-controls-project',
	},
	'field-text': {
		keywords: ['form', 'input', 'label', 'cursor', 'text field'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	gift: {
		keywords: ['gift', 'present'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		usage: 'User-selectable icon choice for calendars',
	},
	'group-selection': {
		keywords: ['group', 'selection', 'layers'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Grouping selected objects in Whiteboards',
	},
	'group-ungroup-selection': {
		keywords: ['ungroup', 'selection', 'layers'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Ungrouping selected objects in Whiteboards',
	},
	hand: {
		keywords: ['hand', 'grab', 'move', 'open palm'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for move/hand tool in Whiteboards',
	},
	jira: {
		keywords: [],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Representing JIRA',
	},
	'paint-brush': {
		keywords: ['brush', 'appearance', 'paint'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	'paint-roller': {
		keywords: ['roller', 'background', 'paint'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	'party-popper': {
		keywords: ['party', 'celebrate', 'celebration', 'confetti'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		usage: 'User-selectable icon choice for calendars',
	},
	section: {
		keywords: ['section', 'related content'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for section tool in Whiteboards',
	},
	'shape-diamond': {
		keywords: ['diamond', 'shape tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Diamond shape tool in Whiteboards',
	},
	'shape-ellipse': {
		keywords: ['ellipse', 'circle', 'shape tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Ellipse shape tool in Whiteboards',
	},
	'shape-parallelogram-skew-left': {
		keywords: ['parallelogram', 'skewed', 'left', 'shape tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Left parallelogram shape tool in Whiteboards',
	},
	'shape-parallelogram-skew-right': {
		keywords: ['parallelogram', 'skewed', 'shape tool', 'right'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Right parallelogram shape tool in Whiteboards',
	},
	'shape-rectangle': {
		keywords: ['shape tool', 'rectangle', 'square'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Rectangle shape tool in Whiteboards',
	},
	'shape-rectangle-rounded': {
		keywords: ['shape tool', 'rectangle', 'rounded', 'square'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Rounded rectangle shape tool in Whiteboards',
	},
	'shape-triangle': {
		keywords: ['triangle', 'shape tool', 'equilateral'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Triangle shape tool in Whiteboards',
	},
	'shape-triangle-inverted': {
		keywords: ['triangle', 'shape tool', 'equilateral'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Upside down triangle shape tool in Whiteboards',
	},
	signature: {
		keywords: ['signature', 'scribble', 'author', 'authour', 'sticky note', 'post-it'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Toggle author visibility on sticky notes in Whiteboards.',
	},
	speedometer: {
		keywords: ['speed', 'performance', 'dial'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	stamp: {
		keywords: ['stamp', 'rubber stamp', 'handstamp'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for stamp tool in Whiteboards',
	},
	sticker: {
		keywords: ['sticker', 'peel-off'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for sticker tool in Whiteboards',
	},
	sunset: {
		keywords: ['sun', 'horizon', 'farewell', 'goodbye', 'sky', 'farewell feed'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'confluence insights',
		type: 'core',
		status: 'published',
		usage: 'Farewell feed in hello.',
	},
	'takeout-container': {
		keywords: ['takeout', 'food', 'takeaway'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Known usages: Alternative option for food emoji category.',
	},
	template: {
		keywords: ['template', 'templates'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Whiteboards',
		type: 'core',
		status: 'published',
		usage: 'Used for templates in Whiteboards',
	},
	ticket: {
		keywords: ['stub', 'ticket'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	'vehicle-airplane': {
		keywords: ['plane', 'airplane', 'aeroplane', 'travel', 'vehicle'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Growth Buy',
		type: 'core',
		status: 'published',
		usage: 'User-selectable icon choice for calendars',
	},
	'vehicle-train': {
		keywords: ['transportation', 'vehicle', 'car'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Known usages: Alternative option for transport emoji category.',
	},
	wallet: {
		keywords: ['money', 'sales', 'payment', 'wallet'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
	'welcome-feed': {
		keywords: ['welcome', 'hello', 'blog', 'smile', 'intro'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Insights',
		type: 'core',
		status: 'published',
		usage: 'Known uses: Intro blog feed picker on Hello',
		slackChannel: '#cc-insights-and-reporting',
	},
	wrench: {
		keywords: ['wrench', 'spanner', 'tool'],
		categorization: 'multi-purpose',
		location: '@atlaskit/icon-lab',
		team: 'Design System Team',
		type: 'core',
		status: 'published',
		usage: 'Multi purpose',
	},
};

export default metadata;
