/* eslint-disable @atlaskit/editor/no-re-export */
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export {
	PanelType,
	blockCard,
	blockCardWithLocalId,
	blockquote,
	extendedBlockquote,
	extendedBlockquoteWithLocalId,
	bodiedExtension,
	bodiedExtensionRootOnlyStage0,
	bulletList,
	bulletListSelector,
	bulletListWithLocalId,
	caption,
	captionWithLocalId,
	codeBlock,
	codeBlockWithLocalId,
	codeBlockToJSON,
	confluenceJiraIssue,
	confluenceUnsupportedBlock,
	confluenceUnsupportedInline,
	copyPrivateMediaAttributes,
	date,
	dateWithLocalId,
	decisionItem,
	decisionList,
	decisionListSelector,
	doc,
	embedCard,
	embedCardWithLocalId,
	emoji,
	emojiWithLocalId,
	expandWithNestedExpand,
	expandWithNestedExpandLocalId,
	expandToJSON,
	extension,
	extensionRootOnlyStage0,
	hardBreak,
	heading,
	image,
	inlineCard,
	inlineCardWithLocalId,
	inlineExtension,
	layoutColumn,
	layoutColumnStage0,
	layoutColumnWithLocalId,
	layoutSection,
	layoutSectionWithLocalId,
	layoutSectionWithSingleColumn,
	layoutSectionWithSingleColumnLocalId,
	listItem,
	listItemWithLocalId,
	media,
	mediaGroup,
	mediaSingle,
	mediaSingleSpec,
	mediaInline,
	mediaSingleWithCaption,
	mediaSingleWithWidthType,
	mediaSingleFull,
	mediaSingleFullWithLocalId,
	mediaSingleToJSON,
	mediaToJSON,
	mention,
	mentionToJSON,
	nestedExpand,
	nestedExpandWithLocalId,
	orderedList,
	orderedListSelector,
	orderedListWithLocalId,
	orderedListWithOrder,
	orderedListWithOrderAndLocalId,
	extendedPanel,
	extendedPanelC1,
	extendedPanelC1WithLocalId,
	extendedPanelRootOnlyStage0,
	extendedPanelC1RootOnlyStage0,
	extendedPanelWithLocalId,
	paragraph,
	placeholder,
	placeholderWithLocalId,
	rule,
	ruleWithLocalId,
	getCellAttrs,
	getCellDomAttrs,
	status,
	table,
	tableStage0,
	tableWithCustomWidth,
	tableBackgroundBorderColor,
	tableBackgroundColorNames,
	tableBackgroundColorPalette,
	tableBackgroundColorPaletteNew,
	tableCell,
	tableCellContentDomSelector,
	tableCellContentWrapperSelector,
	tableCellSelector,
	tableHeader,
	tableHeaderSelector,
	tablePrefixSelector,
	tableRow,
	tableToJSON,
	taskItem,
	blockTaskItem,
	taskList,
	taskListSelector,
	text,
	toJSONTableCell,
	toJSONTableHeader,
	unknownBlock,
	unsupportedBlock,
	unsupportedInline,
	extensionFrame,
	multiBodiedExtension,
	multiBodiedExtensionRootOnlyStage0,
	syncBlock,
	bodiedSyncBlock,
	tableWithNestedTable,
	tableRowWithNestedTable,
	tableCellWithNestedTable,
	tableHeaderWithNestedTable,
	tableCellStage0,
	tableHeaderStage0,
	tableCellWithNestedTableStage0,
	tableHeaderWithNestedTableStage0,
	tableRowWithLocalId,
	tableCellWithLocalId,
	tableHeaderWithLocalId,
	tableRowWithNestedTableWithLocalId,
	tableCellWithNestedTableWithLocalId,
	tableHeaderWithNestedTableWithLocalId,
} from './nodes';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export type {
	BlockCardDefinition,
	BlockContent,
	BlockQuoteDefinition,
	BodiedExtensionDefinition,
	BodiedExtensionRootOnlyDefinition,
	BulletListDefinition,
	CaptionDefinition,
	CardAttributes,
	CellAttributes,
	CodeBlockAttrs,
	CodeBlockBaseDefinition,
	CodeBlockDefinition,
	CodeBlockWithMarksDefinition,
	DatasourceAttributes,
	DatasourceAttributeProperties,
	DataType,
	DateDefinition,
	DecisionItemDefinition,
	DecisionListDefinition,
	DocNode,
	EmbedCardDefinition,
	EmbedCardAttributes,
	EmojiAttributes,
	EmojiDefinition,
	ExpandDefinition,
	ExtensionDefinition,
	ExtensionRootOnlyDefinition,
	ExtensionLayout,
	ExternalMediaAttributes,
	HardBreakDefinition,
	HeadingBaseDefinition,
	HeadingDefinition,
	HeadingWithAlignmentDefinition,
	HeadingWithIndentationDefinition,
	HeadingWithMarksDefinition,
	Inline,
	InlineCardDefinition,
	InlineCode,
	InlineExtensionDefinition,
	InlineFormattedText,
	InlineLinkText,
	LayoutColumnDefinition,
	LayoutSectionDefinition,
	LayoutSectionBaseDefinition,
	LayoutSectionFullDefinition,
	LayoutSectionWithSingleColumnDefinition,
	ListItemArray,
	ListItemDefinition,
	MarksObject,
	MediaADFAttrs,
	MediaAttributes,
	MediaInlineAttributes,
	MediaInlineDefinition,
	MediaBaseAttributes,
	MediaDefinition,
	MediaDisplayType,
	MediaGroupDefinition,
	MediaSingleDefinition,
	MediaType,
	MentionAttributes,
	MentionDefinition,
	MentionUserType,
	NestedExpandContent,
	NestedExpandDefinition,
	NoMark,
	NonNestableBlockContent,
	OrderedListDefinition,
	PanelAttributes,
	PanelDefinition,
	ParagraphBaseDefinition,
	ParagraphDefinition,
	ParagraphWithAlignmentDefinition,
	ParagraphWithIndentationDefinition,
	ParagraphWithMarksDefinition,
	PlaceholderDefinition,
	RuleDefinition,
	StatusDefinition,
	TableAttributes,
	TableCellDefinition,
	TableDefinition,
	TableWithNestedTableDefinition,
	TableRowWithNestedTableDefinition,
	TableCellWithNestedTableDefinition,
	TableHeaderWithNestedTableDefinition,
	TableDisplayMode,
	TableHeaderDefinition,
	TableLayout,
	TableRowDefinition,
	TaskItemDefinition,
	BlockTaskItemDefinition,
	TaskListContent,
	TaskListDefinition,
	TextDefinition,
	UrlType,
	RichMediaAttributes,
	ExtendedMediaAttributes,
	RichMediaLayout,
	CellDomAttrs,
	ExtensionFrameDefinition,
	MultiBodiedExtensionDefinition,
	MultiBodiedExtensionRootOnlyDefinition,
	SyncBlockDefinition,
	BodiedSyncBlockDefinition,
} from './nodes';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export {
	AnnotationTypes,
	alignment,
	alignmentPositionMap,
	annotation,
	fontSize,
	breakout,
	code,
	colorPalette,
	colorPaletteNew,
	// eslint-disable-next-line @repo/internal/deprecations/deprecation-ticket-required
	/** @deprecated [ED-15849] The extended palette is now rolled into the main one. Use `colorPalette` instead. */
	colorPaletteExtended,
	confluenceInlineComment,
	dataConsumer,
	dataConsumerToJSON,
	em,
	fragment,
	fragmentToJSON,
	indentation,
	link,
	linkToJSON,
	strike,
	strong,
	subsup,
	textColor,
	typeAheadQuery,
	underline,
	buildAnnotationMarkDataAttributes,
	AnnotationMarkStates,
	unsupportedMark,
	unsupportedNodeAttribute,
	border,
	borderColorPalette,
	backgroundColor,
	backgroundColorPalette,
	backgroundColorPaletteNew,
} from './marks';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export type {
	AlignmentAttributes,
	AlignmentMarkDefinition,
	AnnotationMarkAttributes,
	AnnotationMarkDefinition,
	BreakoutMarkAttrs,
	BreakoutMarkDefinition,
	CodeDefinition,
	EmDefinition,
	FontSizeMarkAttrs,
	FontSizeMarkDefinition,
	FragmentAttributes,
	FragmentDefinition,
	IndentationMarkAttributes,
	IndentationMarkDefinition,
	LinkAttributes,
	LinkDefinition,
	StrikeDefinition,
	StrongDefinition,
	SubSupAttributes,
	SubSupDefinition,
	TextColorAttributes,
	TextColorDefinition,
	UnderlineDefinition,
	AnnotationId,
	AnnotationDataAttributes,
	DataConsumerAttributes,
	DataConsumerDefinition,
	BorderMarkAttributes,
	BorderMarkDefinition,
	BackgroundColorDefinition,
} from './marks';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export { unsupportedNodeTypesForMediaCards } from './unsupported';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export { inlineNodes } from './inline-nodes';

// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export { createSchema } from './create-schema';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export { sanitizeNodes } from './sanitizeNodes';

// ADF createPMSpecFactory
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export type { NodeSpecOptions, MarkSpecOptions } from './createPMSpecFactory';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export { createPMMarkSpecFactory } from './create-pm-mark-spec-factory';
// eslint-disable-next-line @atlaskit/volt-strict-mode/no-re-exports -- Public compatibility re-export.
export { createPMNodeSpecFactory } from './create-pm-node-spec-factory';
