export enum IdentifierEnum {
	ActivationId = 'activationId',
	AlignUserId = 'alignUserId',
	AnalyticsAnonymousId = 'analyticsAnonymousId',
	AtlassianAccountId = 'atlassianAccountId',
	AtlassianOrgId = 'atlassianOrgId',
	BitbucketConnectAppId = 'bitbucketConnectAppId',
	BitbucketRepositoryId = 'bitbucketRepositoryId',
	BitbucketWorkspaceId = 'bitbucketWorkspaceId',
	GsacIssueId = 'gsacIssueId',
	IntercomConversationId = 'intercomConversationId',
	MarketplaceAnonymousId = 'marketplaceAnonymousId',
	MsTeamsTenantId = 'msTeamsTenantId',
	MarketplacePartnerId = 'marketplacePartnerId',
	LoomAnonymousId = 'loomAnonymousId',
	LoomUserId = 'loomUserId',
	LoomWorkspaceId = 'loomWorkspaceId',
	ProductIntegrationsVendorId = 'productIntegrationsVendorId',
	RandomizationId = 'randomizationId',
	TenantId = 'tenantId',
	TransactionAccountId = 'transactionAccountId',
	TrelloUserId = 'trelloUserId',
	TrelloWorkspaceId = 'trelloWorkspaceId',
	/** Statsig's stableID */
	StableId = 'stableID',
	MiscellaneousId = 'miscellaneousId',
}
