/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.editor.codeBlockCopyButton.copiedToClipboard': 'Zkopírováno!',
  'fabric.editor.codeBlockCopyButton.copyToClipboard': 'Kopírovat',
  'fabric.editor.headingLink.copied': 'Zkopírováno!',
  'fabric.editor.headingLink.copyAnchorLink': 'Kopírovat odkaz na nadpis',
  'fabric.editor.headingLink.failedToCopy': 'Kopírování se nezdařilo',
};
