/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'fabric.editor.codeBlockCopyButton.copiedToClipboard': 'Kopieret!',
  'fabric.editor.codeBlockCopyButton.copyToClipboard': 'Kopiér',
  'fabric.editor.headingLink.copied': 'Kopieret!',
  'fabric.editor.headingLink.copyAnchorLink': 'Kopiér link til overskrift',
  'fabric.editor.headingLink.failedToCopy': 'Kopiering mislykkedes',
};
