/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//French (France)
export default {
  'fabric.editor.codeBlockCopyButton.copiedToClipboard': 'Copié !',
  'fabric.editor.codeBlockCopyButton.copyToClipboard': 'Copier',
  'fabric.editor.headingLink.ascOrderLabel': 'Trier la colonne de Z à A',
  'fabric.editor.headingLink.ascSortingLabel': 'ordre croissant',
  'fabric.editor.headingLink.copied': 'Copié !',
  'fabric.editor.headingLink.copyAnchorLink': "Copier le lien vers l'en-tête",
  'fabric.editor.headingLink.copyAriaLabel': 'Copier',
  'fabric.editor.headingLink.descOrderLabel':
    '⚠️ Impossible de trier un tableau comportant des cellules fusionnées',
  'fabric.editor.headingLink.failedToCopy': 'Copie impossible',
  'fabric.editor.headingLink.noOrderLabel': 'Trier la colonne de A à Z',
  'fabric.editor.headingLink.noneSortingLabel': 'ordre décroissant',
};
