/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Italian (Italy)
export default {
  'fabric.editor.headingLink.ascSortingLabel': 'crescente',
  'fabric.editor.headingLink.copied': 'Copiato.',
  'fabric.editor.headingLink.copyAnchorLink': "Copia link nell'intestazione",
  'fabric.editor.headingLink.copyAriaLabel': 'Copia',
  'fabric.editor.headingLink.descSortingLabel': 'decrescente',
  'fabric.editor.headingLink.failedToCopy': 'Copia non riuscita',
  'fabric.editor.headingLink.noneSortingLabel': 'nessuno',
  'fabric.editor.inlineComment.marker.end': 'fine del commento in linea',
  'fabric.editor.inlineComment.marker.start': 'inizio del commento in linea',
  'fabric.editor.status.accessibilityLabel': 'stato:',
};
