/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Japanese
export default {
  'fabric.editor.codeBlockCopyButton.copiedToClipboard': 'コピーしました',
  'fabric.editor.codeBlockCopyButton.copyToClipboard': 'コピー',
  'fabric.editor.headingLink.ascOrderLabel': '列の並べ替え: Z から A',
  'fabric.editor.headingLink.ascSortingLabel': '昇順',
  'fabric.editor.headingLink.copied': 'コピーしました',
  'fabric.editor.headingLink.copyAnchorLink': '見出しへのリンクをコピー',
  'fabric.editor.headingLink.copyAriaLabel': 'コピー',
  'fabric.editor.headingLink.descOrderLabel':
    '⚠️ 結合セルを含む表は並べ替えられません。',
  'fabric.editor.headingLink.failedToCopy': 'コピーできませんでした。',
  'fabric.editor.headingLink.noOrderLabel': '列の並べ替え: A から Z',
  'fabric.editor.headingLink.noneSortingLabel': '降順',
};
