/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Norwegian (Bokmål)
export default {
  'fabric.editor.codeBlockCopyButton.copiedToClipboard': 'Kopiert!',
  'fabric.editor.codeBlockCopyButton.copyToClipboard': 'Kopier',
  'fabric.editor.headingLink.ascOrderLabel': 'Sorter kolonne Å til A',
  'fabric.editor.headingLink.ascSortingLabel': 'stigende',
  'fabric.editor.headingLink.copied': 'Kopiert!',
  'fabric.editor.headingLink.copyAnchorLink': 'Kopier kobling til overskrift',
  'fabric.editor.headingLink.copyAriaLabel': 'Kopier',
  'fabric.editor.headingLink.descOrderLabel':
    '⚠️ Du kan ikke sortere en tabell med en sammenslått celle',
  'fabric.editor.headingLink.failedToCopy': 'Kopiering mislyktes',
  'fabric.editor.headingLink.noOrderLabel': 'Sorter kolonne A til Å',
  'fabric.editor.headingLink.noneSortingLabel': 'synkende',
};
