/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Turkish (Turkey)
export default {
  'fabric.editor.headingLink.ascSortingLabel': 'artan',
  'fabric.editor.headingLink.copied': 'Kopyalandı!',
  'fabric.editor.headingLink.copyAnchorLink': 'Başlık bağlantısını kopyala',
  'fabric.editor.headingLink.copyAriaLabel': 'Kopyala',
  'fabric.editor.headingLink.descSortingLabel': 'azalan',
  'fabric.editor.headingLink.failedToCopy': 'Kopyalama işlemi başarısız oldu',
  'fabric.editor.headingLink.noneSortingLabel': 'yok',
};
