/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Chinese (Simplified)
export default {
  'fabric.editor.headingLink.ascOrderLabel': '按照 Z 到 A 进行列排序',
  'fabric.editor.headingLink.ascSortingLabel': '升序',
  'fabric.editor.headingLink.copied': '已复制！',
  'fabric.editor.headingLink.copyAnchorLink': '复制标题链接',
  'fabric.editor.headingLink.copyAriaLabel': '复制',
  'fabric.editor.headingLink.descOrderLabel': '清除排序',
  'fabric.editor.headingLink.descSortingLabel': '降序',
  'fabric.editor.headingLink.failedToCopy': '复制失败',
  'fabric.editor.headingLink.invalidLabel': '⚠️ 无法对包含合并单元格的表格进行排序',
  'fabric.editor.headingLink.noOrderLabel': '按照 A 到 Z 进行列排序',
  'fabric.editor.headingLink.noneSortingLabel': '无',
  'fabric.editor.tableHeader.sorting.asc': '已应用升序排序',
  'fabric.editor.tableHeader.sorting.default': '对列进行排序',
  'fabric.editor.tableHeader.sorting.desc': '已应用降序排序',
  'fabric.editor.tableHeader.sorting.invalid': '无法对包含合并单元格的表格进行排序',
  'fabric.editor.tableHeader.sorting.no': '未对该列应用任何排序',
};
