import { wb, type WorkbenchExample } from '@atlassian/workbench';

import NestedSideNavigationVrExample from './00-nested-side-navigation.vr.ap';
import SidebarWithRbdExample from './01-sidebar-with-rbd';
import CustomisedComponentsExample from './02-customised-components';
import SimpleSidebarExample from './03-simple-sidebar';
import AsyncNestedSideNavigationExample from './04-async-nested-side-navigation';
import ControlledExample from './05-controlled';
import ControlledAsyncExample from './06-controlled-async';
import LoadingSectionExample from './07-loading-section';
import SuspenseLoadingSectionExample from './08-suspense-loading-section';
import LoadingAtScaleExample from './09-loading-at-scale';
import WithSpotlightExample from './10-with-spotlight';
import InvalidNestingExample from './11-invalid-nesting';
import NestedSideNavigationScrollIndicatorVrExample from './12-nested-side-navigation-scroll-indicator.vr.ap';
import ContentVrExample from './13-content.vr.ap';
import SidebarWithDragImagesExample from './14-sidebar-with-drag-images';
import ButtonItemExample from './button-item';
import CustomItemExample from './custom-item';
import CustomNestedChildrenExample from './custom-nested-children';
import GoBackItemVrExample from './go-back-item.vr.ap';
import HeadingItemExample from './heading-item';
import LinkItemExample from './link-item';
import LoadingSkeletonsExample from './loading-skeletons';
import LoadingSkeletonsNestedExample from './loading-skeletons-nested';
import NavigationContentExample from './navigation-content';
import NavigationFooterExample from './navigation-footer';
import NavigationHeaderExample from './navigation-header';
import NestingItemVrExample from './nesting-item.vr.ap';
import SectionExample from './section';
import SideNavigationExample from './side-navigation';
import SkeletonHeadingItemExample from './skeleton-heading-item';
import SkeletonItemExample from './skeleton-item';

// Explicit named export Used to generate integration-test URLs.
export const NestedSideNavigation: WorkbenchExample = wb(NestedSideNavigationVrExample);
// Default export required by accessibility tooling.
export default NestedSideNavigation;
export const SidebarWithRbd: WorkbenchExample = wb(SidebarWithRbdExample);
export const CustomisedComponents: WorkbenchExample = wb(CustomisedComponentsExample);
export const SimpleSidebar: WorkbenchExample = wb(SimpleSidebarExample);
export const AsyncNestedSideNavigation: WorkbenchExample = wb(AsyncNestedSideNavigationExample);
export const Controlled: WorkbenchExample = wb(ControlledExample);
export const ControlledAsync: WorkbenchExample = wb(ControlledAsyncExample);
export const LoadingSection: WorkbenchExample = wb(LoadingSectionExample);
export const SuspenseLoadingSection: WorkbenchExample = wb(SuspenseLoadingSectionExample);
export const LoadingAtScale: WorkbenchExample = wb(LoadingAtScaleExample);
export const WithSpotlight: WorkbenchExample = wb(WithSpotlightExample);
export const InvalidNesting: WorkbenchExample = wb(InvalidNestingExample);
export const NestedSideNavigationScrollIndicatorVr: WorkbenchExample = wb(
	NestedSideNavigationScrollIndicatorVrExample,
);
export const ContentVr: WorkbenchExample = wb(ContentVrExample);
export const SidebarWithDragImages: WorkbenchExample = wb(SidebarWithDragImagesExample);
export const ButtonItem: WorkbenchExample = wb(ButtonItemExample);
export const CustomItem: WorkbenchExample = wb(CustomItemExample);
export const CustomNestedChildren: WorkbenchExample = wb(CustomNestedChildrenExample);
export const GoBackItemVr: WorkbenchExample = wb(GoBackItemVrExample);
export const HeadingItem: WorkbenchExample = wb(HeadingItemExample);
export const LinkItem: WorkbenchExample = wb(LinkItemExample);
export const LoadingSkeletons: WorkbenchExample = wb(LoadingSkeletonsExample);
export const LoadingSkeletonsNested: WorkbenchExample = wb(LoadingSkeletonsNestedExample);
export const NavigationContent: WorkbenchExample = wb(NavigationContentExample);
export const NavigationFooter: WorkbenchExample = wb(NavigationFooterExample);
export const NavigationHeader: WorkbenchExample = wb(NavigationHeaderExample);
export const NestingItemVr: WorkbenchExample = wb(NestingItemVrExample);
export const Section: WorkbenchExample = wb(SectionExample);
export const SideNavigation: WorkbenchExample = wb(SideNavigationExample);
export const SkeletonHeadingItem: WorkbenchExample = wb(SkeletonHeadingItemExample);
export const SkeletonItem: WorkbenchExample = wb(SkeletonItemExample);
