export const selectOptions = [
	{ label: 'Brand', value: 'brand' },
	{ label: 'Neutral', value: 'neutral' },
	{ label: 'Inverse', value: 'inverse' },
	{ label: 'Legacy', value: 'legacy' },
] as const;

export const appOrder: string[] = [
	'More Atlassian Apps',
	'Jira',
	'Confluence',
	'Loom',
	'Loom Internal',
	'Rovo',
	'Rovo Hex',
	'Focus',
	'Align',
	'Talent',
	'Bitbucket',
	'Compass',
	'Dx',
	'Rovo Dev',
	'Rovo Dev Agent',
	'Statuspage',
	'Jira Service Management',
	'Assets',
	'Opsgenie',
	'Customer Service Management',
	'Jira Product Discovery',
	'Trello',
	'Guard',
	'Guard Detect',
	'Home',
	'Company Hub',
	'Projects',
	'Goals',
	'Teams',
	'Chat',
	'Search',
	'Studio',
	'Analytics',
	'Admin',
	'Jira Data Center',
	'Jira Service Management Data Center',
	'Confluence Data Center',
	'Bitbucket Data Center',
	'Bamboo',
	'Crowd',
	'Custom Link',
];
