import { wb, type WorkbenchExample } from '@atlassian/workbench';

import ActionLinksVrExample from './action-links.vr.ap';
import AllPlacementsVrExample from './all-placements.vr.ap';
import CardVrExample from './card.vr.ap';
import CtaAppearanceExample from './cta-appearance';
import CustomisationsExample from './customisations';
import DisableClickOutsideExample from './disable-click-outside';
import FullWidthTargetVrExample from './full-width-target.vr.ap';
import GlobalVsLocalActionsExample from './global-vs-local-actions';
import ImageMediaExample from './image-media';
import MotionExample from './motion';
import NewCustomMotionExample from './new-custom-motion';
import NewDisableMotionExample from './new-disable-motion';
import OffsetVrExample from './offset.vr.ap';
import OnModalVrExample from './on-modal.vr.ap';
import OverlayingGridExample from './overlaying-grid';
import OverlayingUiVrExample from './overlaying-ui.vr.ap';
import PlacementsExample from './placements';
import ReflowVrExample from './reflow.vr.ap';
import ResizableTargetExample from './resizable-target';
import SingleStepExample from './single-step';
import StepVariantsVrExample from './step-variants.vr.ap';
import TestingInitialFocusMatrixExample from './testing-initial-focus-matrix';
import TourExample from './tour';
import VideoMediaExample from './video-media';
import WithShowMoreExample from './with-show-more';
import WithoutImageVrExample from './without-image.vr.ap';

const ActionLinksVr: WorkbenchExample = wb(ActionLinksVrExample);

export default ActionLinksVr;
export const AllPlacementsVr: WorkbenchExample = wb(AllPlacementsVrExample);
// Named "Card" to match the Workbench URL used by existing integration tests.
export const Card: WorkbenchExample = wb(CardVrExample);
export const CtaAppearance: WorkbenchExample = wb(CtaAppearanceExample);
export const Customisations: WorkbenchExample = wb(CustomisationsExample);
export const DisableClickOutside: WorkbenchExample = wb(DisableClickOutsideExample);
export const FullWidthTargetVr: WorkbenchExample = wb(FullWidthTargetVrExample);
export const GlobalVsLocalActions: WorkbenchExample = wb(GlobalVsLocalActionsExample);
export const ImageMedia: WorkbenchExample = wb(ImageMediaExample);
export const Motion: WorkbenchExample = wb(MotionExample);
export const NewCustomMotion: WorkbenchExample = wb(NewCustomMotionExample);
export const NewDisableMotion: WorkbenchExample = wb(NewDisableMotionExample);
export const OffsetVr: WorkbenchExample = wb(OffsetVrExample);
export const OnModalVr: WorkbenchExample = wb(OnModalVrExample);
export const OverlayingGrid: WorkbenchExample = wb(OverlayingGridExample);
export const OverlayingUiVr: WorkbenchExample = wb(OverlayingUiVrExample);
export const Placements: WorkbenchExample = wb(PlacementsExample);
export const ReflowVr: WorkbenchExample = wb(ReflowVrExample);
export const ResizableTarget: WorkbenchExample = wb(ResizableTargetExample);
export const SingleStep: WorkbenchExample = wb(SingleStepExample);
export const StepVariantsVr: WorkbenchExample = wb(StepVariantsVrExample);
export const TestingInitialFocusMatrix: WorkbenchExample = wb(TestingInitialFocusMatrixExample);
export const Tour: WorkbenchExample = wb(TourExample);
export const VideoMedia: WorkbenchExample = wb(VideoMediaExample);
export const WithShowMore: WorkbenchExample = wb(WithShowMoreExample);
export const WithoutImageVr: WorkbenchExample = wb(WithoutImageVrExample);
