export type {
	CustomGlyphProps,
	GlyphProps,
	IconProps,
	IconSize,
	IconSpacing,
	IconTileAppearance,
	IconTileProps,
	IconTileSize,
	LEGACY_Metadata,
	LegacyIconTileSize,
	NewCoreIconProps,
	NewGlyphColorProps,
	NewIconProps,
	NewIconTileSize,
	SVGProps,
	Size,
	SkeletonProps,
	UNSAFE_NewCoreGlyphProps,
	UNSAFE_NewGlyphProps,
} from '../types';
