export type {
	CustomGlyphProps,
	GlyphProps,
	IconProps,
	Size,
	SkeletonProps,
	SVGProps,
	NewIconProps,
	NewGlyphColorProps,
	NewUtilityIconProps,
	NewCoreIconProps,
	IconMigrationMap,
	IconSpacing,
	IconTileProps,
} from '../types';
