/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Spanish (International)
export default {
  'jql-editor.common.validation.unknown-error': 'No se ha podido analizar la consulta.',
  'jql-editor.plugins.autocomplete.autocomplete-option.deprecated-tooltip.default':
    'Este campo ha quedado obsoleto y es posible que deje de funcionar en el futuro.',
  'jql-editor.plugins.autocomplete.autocomplete-option.deprecated-tooltip.epic-link':
    "<b>''{received}'</b> se sustituirá pronto por <b>''{parentReplacement}'</b>. En su lugar, usa el campo <b>''{parentReplacement}'</b>.",
  'jql-editor.plugins.autocomplete.options-found': 'Elige una opción de la lista que se sugiere a continuación.',
  'jql-editor.plugins.jql-ast.error-messages.expectingCFButReceived':
    "Se esperaba un nombre de campo, pero se ha recibido '['. ¿Querías decir 'cf['?",
  'jql-editor.plugins.jql-ast.error-messages.expectingCustomFieldId':
    "Se esperaba un ID de campo personalizado entre '[ ]' después de 'cf'. Ejemplo: 'cf[10021]'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldBeforeEOF':
    'Se esperaba un nombre de campo antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldButReceived':
    "Se esperaba un nombre de campo, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como nombre de campo.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldPropertyIdBeforeEOF':
    'Se esperaba un ID de propiedad antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldPropertyIdButReceived':
    "Se esperaba un ID de propiedad, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionArgBeforeEOF':
    'Se esperaba un argumento de función antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionArgButReceived':
    "Se esperaba un argumento de función, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionBeforeEOF':
    'Se esperaba una función antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionButReceived':
    "Se esperaba una función, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.expectingListBeforeEOF':
    'Se esperaba una lista antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingListButReceived':
    "Se esperaba una lista, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.expectingListOrFunctionBeforeEOF':
    'Se esperaba una lista o función antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingListOrFunctionButReceived':
    "Se esperaba una lista o función, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.expectingMultipleTokensBeforeEOF':
    "Se esperaba {firstExpectedTokens} o ''{lastExpectedToken}' antes del final de la consulta.",
  'jql-editor.plugins.jql-ast.error-messages.expectingMultipleTokensButReceived':
    "Se esperaba {firstExpectedTokens} o ''{lastExpectedToken}', pero se obtuvo ''{received}'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingOperandBeforeEOF':
    'Se esperaba un valor, una lista o una función antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingOperandButReceived':
    "Se esperaba un valor, una lista o una función, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.expectingOperatorBeforeEOF':
    "Se esperaba un operador antes del final de la consulta. Los operadores válidos son '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' e 'IS NOT'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingOperatorButReceived':
    "Se esperaba un operador, pero se obtuvo ''{received}'. Los operadores válidos son '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' e 'IS NOT'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingTokenBeforeEOF':
    "Se esperaba ''{expectedToken}' antes del final de la consulta.",
  'jql-editor.plugins.jql-ast.error-messages.expectingTokenButReceived':
    "Se esperaba ''{expectedToken}', pero se obtuvo ''{received}'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingValueBeforeEOF':
    'Se esperaba un valor antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingValueButReceived':
    "Se esperaba un valor, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.expectingValueOrFunctionBeforeEOF':
    'Se esperaba un valor o función antes del final de la consulta.',
  'jql-editor.plugins.jql-ast.error-messages.expectingValueOrFunctionButReceived':
    "Se esperaba un valor o función, pero se obtuvo ''{received}'. Debes poner ''{received}' entre comillas para usarlo como valor.",
  'jql-editor.plugins.jql-ast.error-messages.illegalChar':
    "El carácter ''{char}' debe ser de escape. Utiliza en su lugar el carácter de escape ''{escapedChar}'.",
  'jql-editor.plugins.jql-ast.error-messages.illegalEscape':
    "''{received}' es una secuencia de escape de JQL no válida. Las secuencias de escape válidas son \\', \\\", \\t, \\n, \\r, \\\\, '\\ ' y \\uXXXX.",
  'jql-editor.plugins.jql-ast.error-messages.illegalEscapeBlank':
    "La secuencia de escape no se ha completado. Las secuencias de escape válidas son \\', \\\", \\t, \\n, \\r, \\\\, '\\ ' y \\uXXXX.",
  'jql-editor.plugins.jql-ast.error-messages.reservedChar':
    "El carácter ''{char}' es un carácter reservado de JQL. Debes envolverlo en una cadena o escaparlo con ''{escapedChar}'.",
  'jql-editor.plugins.jql-ast.error-messages.reservedWord':
    "''{word}' es una palabra reservada de JQL. Debes ponerla entre comillas para usarla en una consulta.",
  'jql-editor.plugins.jql-ast.error-messages.unfinishedString': "La cadena citada ''{received}' no se ha completado.",
  'jql-editor.plugins.jql-ast.error-messages.unfinishedStringBlank': 'La cadena citada no se ha completado.',
  'jql-editor.plugins.jql-ast.error-messages.unknownErrorAtToken':
    "No se ha podido analizar la consulta en ''{received}'.",
  'jql-editor.ui.input-label': 'Consulta en JQL',
  'jql-editor.ui.jql-editor-controls-content.expand-toggle.button-label': 'Editor',
  'jql-editor.ui.jql-editor-controls-content.expand-toggle.collapse-tooltip': 'Contraer editor',
  'jql-editor.ui.jql-editor-controls-content.expand-toggle.expand-tooltip': 'Ampliar editor',
  'jql-editor.ui.jql-editor-controls-content.search.label': 'Buscar',
  'jql-editor.ui.jql-editor-footer-content.jql-editor-help.syntax-help.description':
    'Abre la Ayuda de Sintaxis JQL en una nueva pestaña.',
  'jql-editor.ui.jql-editor-footer-content.jql-editor-help.syntax-help.tooltip': 'Ayuda de Sintaxis',
  'jql-editor.ui.jql-editor-help.field-new-line-command': '<b>Intro</b> para añadir una nueva línea',
  'jql-editor.ui.jql-editor-help.new-line-command': '<b>Mayús+Intro</b> para añadir una línea nueva',
  'jql-editor.ui.jql-editor-help.search-command': '<b>Intro</b> para buscar',
  'jql-editor.ui.jql-validation-message.jql-error-position': '(línea {lineNumber}, carácter {charPosition})',
  'jql-editor.ui.jql-warning-message.default':
    '{deprecatedField} ha quedado obsoleto y es posible que deje de funcionar en el futuro.',
  'jql-editor.ui.jql-warning-message.deprecated-both-epic-link-parent-link-field':
    '{receivedFirst} y {receivedSecond} se sustituirán pronto por {parentReplacement}. <link>Actualiza a {parentReplacement}</link> para prepararte de cara a estos cambios.',
  'jql-editor.ui.jql-warning-message.deprecated-epic-link-or-parent-link-field':
    '{deprecatedField} se sustituirá pronto por {parentReplacement}. <link>Actualiza a {parentReplacement}</link> para prepararte de cara a estos cambios.',
};
