/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Italian (Italy)
export default {
  'jql-editor.common.validation.unknown-error': 'Impossibile analizzare la query.',
  'jql-editor.plugins.autocomplete.autocomplete-option.deprecated-tooltip.default':
    'Questo campo è obsoleto e potrebbe smettere di funzionare in futuro.',
  'jql-editor.plugins.autocomplete.autocomplete-option.deprecated-tooltip.epic-link':
    '<b>&quot;{received}&quot;</b> sarà presto sostituito da <b>&quot;{parentReplacement}&quot;</b>. Al suo posto, utilizza il campo <b>&quot;{parentReplacement}&quot;</b>.',
  'jql-editor.plugins.autocomplete.options-found': "Scegli dall'elenco di opzioni suggerite di seguito.",
  'jql-editor.plugins.jql-ast.error-messages.expectingCFButReceived':
    "Era atteso un nome di campo, ma è stato ricevuto '['. Intendevi 'cf['",
  'jql-editor.plugins.jql-ast.error-messages.expectingCustomFieldId':
    "Era atteso un ID campo personalizzato racchiuso tra '[ ]' dopo 'cf'. Esempio: 'cf[10021]'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldBeforeEOF':
    'Era atteso un nome di campo prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldButReceived':
    "Era atteso un nome di campo ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come nome di campo.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldPropertyIdBeforeEOF':
    'Era atteso un ID proprietà prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFieldPropertyIdButReceived':
    "Era atteso un ID proprietà, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionArgBeforeEOF':
    'Era atteso un argomento di funzione prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionArgButReceived':
    "Era atteso un argomento di funzione, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionBeforeEOF':
    'Era attesa una funzione prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingFunctionButReceived':
    "Era attesa una funzione, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.expectingListBeforeEOF':
    'Era atteso un elenco prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingListButReceived':
    "Era atteso un elenco, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.expectingListOrFunctionBeforeEOF':
    'Era atteso un elenco o una funzione prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingListOrFunctionButReceived':
    "Era atteso un elenco o una funzione, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.expectingMultipleTokensBeforeEOF':
    "Era atteso {firstExpectedTokens} o ''{lastExpectedToken}' prima della fine della query.",
  'jql-editor.plugins.jql-ast.error-messages.expectingMultipleTokensButReceived':
    "Era atteso {firstExpectedTokens} o ''{lastExpectedToken}', ma è stato ricevuto \"{received}\".",
  'jql-editor.plugins.jql-ast.error-messages.expectingOperandBeforeEOF':
    'Era atteso un valore, un elenco o una funzione prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingOperandButReceived':
    "Era atteso un valore, un elenco o una funzione, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.expectingOperatorBeforeEOF':
    "Era atteso un operatore prima della fine della query. Gli operatori validi sono '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' e 'IS NOT'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingOperatorButReceived':
    "Era atteso un operatore, ma è stato ricevuto ''{received}'. Gli operatori validi sono '=', '!=', '<', '>', '<=', '>=', '~', '!~', 'IN', 'NOT IN', 'IS' e 'IS NOT'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingTokenBeforeEOF':
    "Era atteso ''{expectedToken}' prima della fine della query.",
  'jql-editor.plugins.jql-ast.error-messages.expectingTokenButReceived':
    "Era atteso ''{expectedToken}', ma è stato ricevuto ''{received}'.",
  'jql-editor.plugins.jql-ast.error-messages.expectingValueBeforeEOF':
    'Era atteso un valore prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingValueButReceived':
    "Era atteso un valore, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.expectingValueOrFunctionBeforeEOF':
    'Era atteso un valore o una funzione prima della fine della query.',
  'jql-editor.plugins.jql-ast.error-messages.expectingValueOrFunctionButReceived':
    "Era atteso un valore o una funzione, ma è stato ricevuto ''{received}'. È necessario racchiudere ''{received}' tra virgolette per utilizzarlo come valore.",
  'jql-editor.plugins.jql-ast.error-messages.illegalChar':
    "È necessario eseguire l'escape del carattere ''{char}'. Utilizzare il carattere di escape ''{escapedChar}'.",
  'jql-editor.plugins.jql-ast.error-messages.illegalEscape':
    "''{received}' è una sequenza di escape JQL non valida. Le sequenze di escape valide sono \\', \\\", \\t, \\n, \\r, \\\\, '\\ ' e \\uXXXX.",
  'jql-editor.plugins.jql-ast.error-messages.illegalEscapeBlank':
    "La sequenza di escape non è stata completata. Le sequenze di escape valide sono \\', \\\", \\t, \\n, \\r, \\\\, '\\ ' e \\uXXXX.",
  'jql-editor.plugins.jql-ast.error-messages.reservedChar':
    "Il carattere ''{char}' è un carattere JQL riservato. È necessario racchiuderlo in una stringa o utilizzare il carattere di escape ''{escapedChar}'.",
  'jql-editor.plugins.jql-ast.error-messages.reservedWord':
    "''{word}' è una parola JQL riservata. È necessario racchiuderla tra virgolette per utilizzarla in una query.",
  'jql-editor.plugins.jql-ast.error-messages.unfinishedString':
    "La stringa ''{received}' tra virgolette non è stata completata.",
  'jql-editor.plugins.jql-ast.error-messages.unfinishedStringBlank':
    'La stringa tra virgolette non è stata completata.',
  'jql-editor.plugins.jql-ast.error-messages.unknownErrorAtToken': "Impossibile analizzare la query in ''{received}'.",
  'jql-editor.ui.input-label': 'Query JQL',
  'jql-editor.ui.jql-editor-controls-content.expand-toggle.button-label': 'Editor',
  'jql-editor.ui.jql-editor-controls-content.expand-toggle.collapse-tooltip': 'Comprimi editor',
  'jql-editor.ui.jql-editor-controls-content.expand-toggle.expand-tooltip': 'Espandi editor',
  'jql-editor.ui.jql-editor-controls-content.search.label': 'Ricerca',
  'jql-editor.ui.jql-editor-footer-content.jql-editor-help.syntax-help.description':
    'Apri la guida alla sintassi JQL in una nuova scheda.',
  'jql-editor.ui.jql-editor-footer-content.jql-editor-help.syntax-help.tooltip': 'Guida alla sintassi',
  'jql-editor.ui.jql-editor-help.field-new-line-command': '<b>Invio</b> per aggiungere una nuova riga',
  'jql-editor.ui.jql-editor-help.new-line-command': '<b>Maiusc+Invio</b> per aggiungere una nuova riga',
  'jql-editor.ui.jql-editor-help.search-command': '<b>Invio</b> per eseguire la ricerca',
  'jql-editor.ui.jql-validation-message.jql-error-position': '(riga {lineNumber}, carattere {charPosition})',
  'jql-editor.ui.jql-warning-message.default':
    'Il campo {deprecatedField} è obsoleto e potrebbe smettere di funzionare in futuro.',
  'jql-editor.ui.jql-warning-message.deprecated-both-epic-link-parent-link-field':
    "{receivedFirst} e {receivedSecond} verranno presto sostituiti da {parentReplacement}. <link>Effettua l'aggiornamento a {parentReplacement}</link> per prepararti a questi cambiamenti.",
  'jql-editor.ui.jql-warning-message.deprecated-epic-link-or-parent-link-field':
    "{deprecatedField} verrà presto sostituito da {parentReplacement}. <link>Effettua l'aggiornamento a {parentReplacement}</link> per prepararti a questi cambiamenti.",
};
