// Available icon names (kebab-case) - icons supported in icon-object
export const AVAILABLE_ICON_NAMES: string[] = [
	'blog',
	'branch',
	'bug',
	'calendar',
	'changes',
	'code',
	'commit',
	'epic',
	'improvement',
	'incident',
	'issue',
	'new-feature',
	'page',
	'page-live-doc',
	'problem',
	'pull-request',
	'question',
	'story',
	'subtask',
	'task',
	'whiteboard',
];
