/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//French (France)
export default {
  "smart-experiences.smart-hooks.external.sourced.from": "Trouvé dans :",
  "smart-experiences.smart-hooks.github.provider": "GitHub",
  "smart-experiences.smart-hooks.google.provider": "Google",
  "smart-experiences.smart-hooks.guest.lozenge.text": "INVITÉ",
  "smart-experiences.smart-hooks.guest.lozenge.tooltip.group": "Les groupes d'invités peuvent uniquement accéder à certains espaces et ont un accès limité aux informations utilisateur.",
  "smart-experiences.smart-hooks.guest.lozenge.tooltip.user": "Les invités peuvent uniquement accéder à certains espaces et ont un accès limité aux informations utilisateur.",
  "smart-experiences.smart-hooks.member.lozenge.text": "MEMBRE",
  "smart-experiences.smart-hooks.microsoft.provider": "Microsoft",
  "smart-experiences.smart-hooks.slack.provider": "Slack"
};
