/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Thai
export default {
  'smart-experiences.smart-hooks.external.sourced.from': 'พบใน:',
  'smart-experiences.smart-hooks.github.provider': 'GitHub',
  'smart-experiences.smart-hooks.google.provider': 'Google',
  'smart-experiences.smart-hooks.guest.lozenge.text': 'ผู้ใช้ทั่วไป',
  'smart-experiences.smart-hooks.guest.lozenge.tooltip.group':
    'กลุ่มผู้ใช้ทั่วไปสามารถเข้าถึงได้เฉพาะบางพื้นที่เท่านั้นและมีสิทธิ์ในการเข้าถึงข้อมูลผู้ใช้ที่จำกัด',
  'smart-experiences.smart-hooks.guest.lozenge.tooltip.user':
    'ผู้ใช้ทั่วไปสามารถเข้าถึงได้เฉพาะบางพื้นที่เท่านั้นและมีสิทธิ์ในการเข้าถึงข้อมูลผู้ใช้ที่จำกัด',
  'smart-experiences.smart-hooks.member.lozenge.text': 'สมาชิก',
  'smart-experiences.smart-hooks.microsoft.provider': 'Microsoft',
  'smart-experiences.smart-hooks.slack.provider': 'Slack',
};
