/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Vietnamese
export default {
  'smart-experiences.smart-hooks.external.sourced.from': 'Tìm thấy trong:',
  'smart-experiences.smart-hooks.github.provider': 'GitHub',
  'smart-experiences.smart-hooks.google.provider': 'Google',
  'smart-experiences.smart-hooks.guest.lozenge.text': 'KHÁCH',
  'smart-experiences.smart-hooks.guest.lozenge.tooltip.group':
    'Các nhóm khách chỉ có thể vào một số không gian nhất định và có quyền truy cập hạn chế vào thông tin người dùng.',
  'smart-experiences.smart-hooks.guest.lozenge.tooltip.user':
    'Khách chỉ có thể vào một số không gian nhất định và có quyền truy cập hạn chế vào thông tin người dùng.',
  'smart-experiences.smart-hooks.member.lozenge.text': 'Thành viên',
  'smart-experiences.smart-hooks.microsoft.provider': 'Microsoft',
  'smart-experiences.smart-hooks.slack.provider': 'Slack',
};
