/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Croatian (Croatia) [hr-HR]
export default {
  'fabric.elements.mentions.team.member.50plus': 'Tim • 50+ članova',
  'fabric.elements.mentions.team.member.50plus.including.you': 'Tim • 50+ članova, uključujući tebe',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one {Tim • 1 član} few {Tim • {0} člana} many {Tim • {0} članova} other {Tim • {0} članova}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one {Tim • 1 član, uključujući tebe} few {Tim • {0} člana, uključujući tebe} many {Tim • {0} članova, uključujući tebe} other {Tim • {0} članova, uključujući tebe}}',
  'fabric.elements.mentions.xproduct.mention.description': 'Potreban je pristup Confluenceu',
  'fabric.mention.error.defaultAction': 'Pokušaj ponovno za nekoliko sekundi',
  'fabric.mention.error.defaultHeadline': 'Nešto nije u redu',
  'fabric.mention.error.differentText': 'Pokušaj unijeti drugi tekst',
  'fabric.mention.error.loginAgain': 'Pokušaj se odjaviti, a zatim se ponovno prijaviti',
  'fabric.mention.noAccess.label': 'Nema pristupa',
  'fabric.mention.noAccess.warning': '{name} neće biti obaviješten jer nema pristup',
  'fabric.mention.unknow.user.error': 'Nepoznati korisnik {userId}',
};
