/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Turkish
export default {
  'fabric.elements.mentions.team.meantion.highlight.close.button.tooltip':
    'Kapat',
  'fabric.elements.mentions.team.member.50plus': "Takım • 50'den fazla üye",
  'fabric.elements.mentions.team.member.50plus.including.you':
    "Takım • Siz de dahil olmak üzere 50'den fazla üye",
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one {Takım • 1 üye} other {Takım • {0} üye}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one {Takım • Siz de dahil olmak üzere 1 üye} other {Takım • Siz de dahil olmak üzere {0} üye}}',
  'fabric.elements.mentions.team.mention.highlight.description':
    'Tek tıklamayla bu sayfadaki herkesi ekleyin. Takımınız yok mu?',
  'fabric.elements.mentions.team.mention.highlight.description.link':
    'Bir takım oluşturun.',
  'fabric.elements.mentions.team.mention.highlight.title':
    'Takımınızdan bahsedin',
  'fabric.mention.error.defaultAction': 'Birkaç saniye sonra yeniden deneyin',
  'fabric.mention.error.defaultHeadline': 'Bir hata oluştu',
  'fabric.mention.error.differentText': 'Farklı bir metin girmeyi deneyin',
  'fabric.mention.error.loginAgain': 'Oturumu kapatıp yeniden açmayı deneyin',
  'fabric.mention.noAccess.label': 'Erişim izni yok',
  'fabric.mention.noAccess.warning':
    'Erişimi olmadığı için {name} adlı kullanıcıya bildirim gönderilmeyecek',
  'fabric.mention.unknow.user.error': 'Bilinmeyen kullanıcı {userId}',
};
