import { wb, type WorkbenchExample } from '@atlassian/workbench';

import SignupFormExample from './00-signup-form';
import TextFieldsExample from './01-text-fields';
import CheckboxFieldsExample from './02-checkbox-fields';
import SelectFieldsExample from './03-select-fields';
import DatetimeFieldsExample from './04-datetime-fields';
import FieldValidationExample from './05-field-validation';
import CreateRepositoryExample from './06-create-repository.vr.ap';
import CustomFieldExample from './07-custom-field';
import ModalSupportExample from './08-modal-support';
import SubmitFormExample from './09-submit-form';
import SubmissionValidationExample from './10-submission-validation';
import ComplexValidationExample from './11-complex-validation';
import FormFooterLeftAlignmentExample from './12-form-footer-left-alignment';
import ResetFormExample from './13-reset-form';
import FieldModifiersExample from './14-field-modifiers';
import ObjectsArraysExample from './15-objects-arrays';
import AsyncValidationExample from './18-async-validation';
import RangeFieldsExample from './19-range-fields';
import SelectFieldsCustomExample from './20-select-fields-custom';
import MessagesExample from './21-messages.vr.ap';
import FieldLevelValidationExample from './22-field-level-validation';
import SignupFormSimpleExample from './23-signup-form-simple';
import LabelExample from './99-label';

const SignupForm: WorkbenchExample = wb(SignupFormExample);

export default SignupForm;
export const TextFields: WorkbenchExample = wb(TextFieldsExample);
export const CheckboxFields: WorkbenchExample = wb(CheckboxFieldsExample);
export const SelectFields: WorkbenchExample = wb(SelectFieldsExample);
export const DatetimeFields: WorkbenchExample = wb(DatetimeFieldsExample);
export const FieldValidation: WorkbenchExample = wb(FieldValidationExample);
export const CreateRepository: WorkbenchExample = wb(CreateRepositoryExample);
export const CustomField: WorkbenchExample = wb(CustomFieldExample);
export const ModalSupport: WorkbenchExample = wb(ModalSupportExample);
export const SubmitForm: WorkbenchExample = wb(SubmitFormExample);
export const SubmissionValidation: WorkbenchExample = wb(SubmissionValidationExample);
export const ComplexValidation: WorkbenchExample = wb(ComplexValidationExample);
export const FormFooterLeftAlignment: WorkbenchExample = wb(FormFooterLeftAlignmentExample);
export const ResetForm: WorkbenchExample = wb(ResetFormExample);
export const FieldModifiers: WorkbenchExample = wb(FieldModifiersExample);
export const ObjectsArrays: WorkbenchExample = wb(ObjectsArraysExample);
export const AsyncValidation: WorkbenchExample = wb(AsyncValidationExample);
export const RangeFields: WorkbenchExample = wb(RangeFieldsExample);
export const SelectFieldsCustom: WorkbenchExample = wb(SelectFieldsCustomExample);
export const Messages: WorkbenchExample = wb(MessagesExample);
export const FieldLevelValidation: WorkbenchExample = wb(FieldLevelValidationExample);
export const SignupFormSimple: WorkbenchExample = wb(SignupFormSimpleExample);
export const Label: WorkbenchExample = wb(LabelExample);
