/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.elements.user-picker.external.sourced.from': 'Nalezen v:',
  'fabric.elements.user-picker.github.provider': 'GitHub',
  'fabric.elements.user-picker.google.provider': 'Google',
  'fabric.elements.user-picker.guest.lozenge.text': 'HOST',
  'fabric.elements.user-picker.guest.lozenge.tooltip.group':
    'Skupiny hostů mají přístup pouze k určitým prostorům a mají omezený přístup k uživatelským údajům.',
  'fabric.elements.user-picker.guest.lozenge.tooltip.user':
    'Hosté mají přístup pouze k určitým prostorům a mají omezený přístup k uživatelským údajům.',
  'fabric.elements.user-picker.member.lozenge.text': 'ČLEN',
  'fabric.elements.user-picker.microsoft.provider': 'Microsoft',
  'fabric.elements.user-picker.slack.provider': 'Slack',
};
