/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//German (Germany)
export default {
  'fabric.editor.canNotSortTable': '⚠️ Tabellen mit zusammengeführten Zellen können nicht sortiert werden.',
  'fabric.editor.cellBackground': 'Zellenhintergrund',
  'fabric.editor.cellOptions': 'Zelloptionen',
  'fabric.editor.clearCells': '{0, plural, one {Zelleninhalt löschen} other {Zelleninhalte löschen}}',
  'fabric.editor.collapseTable': 'Tabelle reduzieren',
  'fabric.editor.cornerControl': 'Tabelle hervorheben',
  'fabric.editor.distributeColumns': 'Spalten verteilen',
  'fabric.editor.extension.deleteElementTitle': 'Element löschen',
  'fabric.editor.floatingToolbar.confirmModalCheckboxLabel': 'Verbundene Elemente ebenfalls löschen',
  'fabric.editor.headerColumn': 'Kopfzeilen-Spalte',
  'fabric.editor.headerRow': 'Kopfzeile',
  'fabric.editor.insertColumn': 'Spalte rechts einfügen',
  'fabric.editor.insertRow': 'Zeile unten einfügen',
  'fabric.editor.mergeCells': 'Zellen zusammenführen',
  'fabric.editor.numberedColumn': 'Nummerierte Spalte',
  'fabric.editor.removeColumns': '{0, plural, one {Spalte löschen} other {Spalten löschen}}',
  'fabric.editor.removeRows': '{0, plural, one {Zeile löschen} other {Zeilen löschen}}',
  'fabric.editor.rowControl': 'Zeile hervorheben',
  'fabric.editor.sortColumnASC': 'Spalte sortieren: A → Z',
  'fabric.editor.sortColumnDESC': 'Spalte sortieren: Z → A',
  'fabric.editor.splitCell': 'Zelle teilen',
  'fabric.editor.tableOptions': 'Tabellenoptionen',
  'fabric.editor.tables.confirmDeleteLinkedModalMessage':
    'Durch das Löschen von {nodeName} werden alle damit verbundenen Elemente unbrauchbar.',
  'fabric.editor.tables.confirmDeleteLinkedModalOKButton': 'Löschen',
};
