/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Italian (Italy)
export default {
  'fabric.editor.canNotSortTable': '⚠️ Non puoi ordinare una tabella con celle unite',
  'fabric.editor.cellBackground': 'Sfondo cella',
  'fabric.editor.cellOptions': 'Opzioni cella',
  'fabric.editor.clearCells': '{0, plural, one {Cancella cella} other {Cancella celle}}',
  'fabric.editor.collapseTable': 'Comprimi tabella',
  'fabric.editor.cornerControl': 'Evidenzia tabella',
  'fabric.editor.distributeColumns': 'Distribuisci colonne',
  'fabric.editor.extension.confirmDeleteLinkedModalMessagePrefix': "L'eliminazione di",
  'fabric.editor.extension.deleteElementTitle': "Elimina l'elemento",
  'fabric.editor.extension.sourceNoTitledName': 'questo elemento',
  'fabric.editor.floatingToolbar.confirmModalCheckboxLabel': 'Elimina anche gli elementi collegati',
  'fabric.editor.headerColumn': 'Colonna di intestazione',
  'fabric.editor.headerRow': 'Riga di intestazione',
  'fabric.editor.insertColumn': 'Inserisci colonna a destra',
  'fabric.editor.insertRow': 'Inserisci riga sotto',
  'fabric.editor.mergeCells': 'Unisci celle',
  'fabric.editor.numberedColumn': 'Colonna numerata',
  'fabric.editor.removeColumns': '{0, plural, one {Elimina colonna} other {Elimina colonne}}',
  'fabric.editor.removeRows': '{0, plural, one {Elimina riga} other {Elimina righe}}',
  'fabric.editor.rowControl': 'Evidenzia riga',
  'fabric.editor.sortColumnASC': 'Ordina colonna A → Z',
  'fabric.editor.sortColumnDESC': 'Ordina colonna Z → A',
  'fabric.editor.splitCell': 'Dividi celle',
  'fabric.editor.tableOptions': 'Opzioni tabella',
  'fabric.editor.tables.adjustColumn': 'Regola colonna',
  'fabric.editor.tables.confirmDeleteLinkedModalMessage':
    "L'eliminazione di {nodeName} comporterà l'interruzione di tutti i relativi collegamenti.",
  'fabric.editor.tables.confirmDeleteLinkedModalOKButton': 'Elimina',
  'fabric.editor.tables.resizeTable': 'Ridimensiona tabella',
};
