/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'fabric.editor.captionPlaceholder': 'Añadir un subtítulo',
  'fabric.editor.collapseNode': 'contraer contenido',
  'fabric.editor.expandDefaultTitle': 'Haz clic aquí para ampliar...',
  'fabric.editor.expandNode': 'Ampliar contenido',
  'fabric.editor.expandPlaceholder': 'Indica un nombre para esta expansión...',
  'fabric.editor.openLink': 'Abrir el enlace en otra pestaña',
  'fabric.editor.unsupportedBlockContent':
    'Este editor no permite mostrar este contenido.',
  'fabric.editor.unsupportedContentTooltip':
    'El contenido no está disponible en este editor, se conservará cuando edites y guardes.',
  'fabric.editor.unsupportedInlineContent': 'Contenido no admitido',
};
