/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'fabric.editor.collapseNode': 'Réduire le contenu',
  'fabric.editor.expandDefaultTitle': 'Cliquez ici pour développer...',
  'fabric.editor.expandNode': 'Développer le contenu',
  'fabric.editor.expandPlaceholder': 'Donnez un titre à cette zone plus large…',
  'fabric.editor.openLink': 'Ouvrir le lien dans un nouvel onglet',
};
