/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Japanese
export default {
  'fabric.editor.captionPlaceholder': 'キャプションを追加',
  'fabric.editor.codeBidiWarningLabel':
    '双方向文字はテキストのレンダリング順序を変更します。このため、悪意のあるコードを隠すために使用される場合があります。',
  'fabric.editor.collapseNode': 'コンテンツを折りたたむ',
  'fabric.editor.expandDefaultTitle': 'こちらをクリックして展開…',
  'fabric.editor.expandNode': 'コンテンツを展開',
  'fabric.editor.expandPlaceholder': 'この展開にタイトルを付ける…',
  'fabric.editor.openLink': 'リンクを新しいタブで開く',
  'fabric.editor.unsupportedBlockContent':
    'このエディターはこのコンテンツの表示をサポートしていません',
  'fabric.editor.unsupportedContentTooltip':
    'このエディターではコンテンツが利用できないため、編集および保存の際にはコンテンツが保持されます',
  'fabric.editor.unsupportedInlineContent': 'サポートされていないコンテンツ',
};
