/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'fabric.editor.collapseNode': '콘텐츠 접기',
  'fabric.editor.expandDefaultTitle': '여기를 클릭하여 펼치기...',
  'fabric.editor.expandNode': '콘텐츠 펼치기',
  'fabric.editor.expandPlaceholder': '이 펼치기에 제목 지정...',
  'fabric.editor.openLink': '새 탭에서 링크 열기',
};
