/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Chinese (Traditional)
export default {
  'fabric.editor.captionPlaceholder': '新增標題',
  'fabric.editor.codeBidiWarningLabel':
    '雙向字元會變更文字呈現的順序。這可用來將惡意程式碼模糊化。',
  'fabric.editor.collapseNode': '摺疊內容',
  'fabric.editor.expandDefaultTitle': '按一下此處以展開...',
  'fabric.editor.expandNode': '展開內容',
  'fabric.editor.expandPlaceholder': '為此展開設定標題...',
  'fabric.editor.openLink': '在新的索引標籤中開啟連結',
  'fabric.editor.unsupportedBlockContent': '此編輯器不支援顯示此內容',
  'fabric.editor.unsupportedContentTooltip':
    '內容不適用於此編輯器，這會在您編輯和儲存時進行保留',
  'fabric.editor.unsupportedInlineContent': '不支援的內容',
};
