/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Danish (Denmark)
export default {
  'fabric.elements.share.copied.to.clipboard.message': 'Link er kopieret til udklipsholder',
  'fabric.elements.share.copylink.button.text': 'Kopier link',
  'fabric.elements.share.copypubliclink.button.text': 'Kopiér offentligt link',
  'fabric.elements.share.failure.icon.label': 'Fejlikon',
  'fabric.elements.share.failure.message': 'Kan ikke deles',
  'fabric.elements.share.form.comment.placeholder': 'TIlføj en meddelelse',
  'fabric.elements.share.form.info.message.no.invite.confluence': 'Modtagere vil se navnet på siden og din besked',
  'fabric.elements.share.form.info.message.no.invite.jira': 'Modtagere vil se navnet på sagen og din meddelelse',
  'fabric.elements.share.form.no-permissions': 'Du kan ikke dele.',
  'fabric.elements.share.form.public.send': 'Send offentligt link',
  'fabric.elements.share.form.public.share': 'Del offentligt link',
  'fabric.elements.share.form.retry': 'Prøv igen',
  'fabric.elements.share.form.send': 'Send',
  'fabric.elements.share.form.share': 'Del',
  'fabric.elements.share.form.title': 'Del',
  'fabric.elements.share.form.user-picker.add-more': 'Indtast mere',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Vi kunne ikke finde nogen resultater for "{inputValue}".',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Vi kunne ikke finde nogen resultater for "{inputValue}". Invitér personer via e-mailadresser.',
  'fabric.elements.share.form.user-picker.placeholder.jira': 'Indtast navn, team eller e-mailadresse',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vælg mindst én bruger, én gruppe, ét team eller én e-mail.',
  'fabric.elements.share.in.integration.button': 'Del i {integrationName}',
  'fabric.elements.share.main.tab.text.confluence': 'Del side',
  'fabric.elements.share.main.tab.text.jira': 'Del sag',
  'fabric.elements.share.to.integration.button': 'Del med {integrationName}',
  'fabric.elements.share.trigger.button.icon.label': 'Del ikon',
  'fabric.elements.share.trigger.button.invite.text': 'Invitér',
  'fabric.elements.share.trigger.button.text': 'Del',
  'fabric.elements.share.trigger.button.tooltip.text': 'Del',
};
