/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Italian (Italy)
export default {
  'fabric.elements.share.copied.to.clipboard.message':
    'Link copiato negli appunti',
  'fabric.elements.share.copylink.button.text': 'Copia link',
  'fabric.elements.share.copypubliclink.button.text': 'Copia link pubblico',
  'fabric.elements.share.failure.icon.label': 'Icona Errore',
  'fabric.elements.share.failure.message':
    'Impossibile effettuare la condivisione',
  'fabric.elements.share.form.comment.placeholder': 'Aggiungi un messaggio',
  'fabric.elements.share.form.info.message.no.invite.confluence':
    'I destinatari vedranno il nome della pagina e il tuo messaggio',
  'fabric.elements.share.form.info.message.no.invite.jira':
    'I destinatari vedranno il nome del ticket e il tuo messaggio',
  'fabric.elements.share.form.public.send': 'Invia link pubblico',
  'fabric.elements.share.form.public.share': 'Condividi link pubblico',
  'fabric.elements.share.form.retry': 'Riprova',
  'fabric.elements.share.form.send': 'Invia',
  'fabric.elements.share.form.share': 'Condividi',
  'fabric.elements.share.form.title': 'Condividi',
  'fabric.elements.share.form.user-picker.add-more': 'Inerisci altri elementi',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Nessun risultato trovato per “{inputValue}”.',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Nessun risultato trovato per “{inputValue}”. Invita le persone inserendo il loro indirizzo e-mail.',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Inserisci nome o team',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Inserisci nome, gruppo, team o e-mail',
  'fabric.elements.share.form.user-picker.placeholder.jira':
    'Inserisci nome, team o indirizzo e-mail',
  'fabric.elements.share.form.user-picker.placholder.generic.existingUserOnly':
    'Inserisci il nome, il gruppo o il team',
  'fabric.elements.share.form.user-picker.validation.required':
    "Seleziona almeno un utente, un gruppo, un team o un'e-mail.",
  'fabric.elements.share.form.user-picker.validation.required.existingUserOnly':
    'Seleziona almeno un utente, un gruppo o un team.',
  'fabric.elements.share.form.user-picker.validation.required.jira':
    'Seleziona almeno un utente, un team o un indirizzo e-mail.',
  'fabric.elements.share.form.user-picker.validation.required.jira.existingUserOnly':
    'Seleziona almeno un utente o un team.',
  'fabric.elements.share.in.integration.button':
    'Condividi in {integrationName}',
  'fabric.elements.share.main.tab.text.confluence': 'Condividi pagina',
  'fabric.elements.share.main.tab.text.jira': 'Condividi ticket',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Post del blog condiviso} board {Board condivisa} calendar {Calendario condiviso} draft {Bozza condivisa} filter {Filtro condiviso} issue {Ticket condiviso} media {File multimediale condiviso} page {Pagina condivisa} project {Progetto condiviso} pullrequest {Richiesta di pull condivisa} question {Domanda condivisa} report {Report condiviso} repository {Repository condiviso} request {Richiesta condivisa} roadmap {Roadmap condivisa} site {Sito condiviso} space {Spazio condiviso} other {Collegamento condiviso}}',
  'fabric.elements.share.to.integration.button':
    'Condividi in {integrationName}',
  'fabric.elements.share.trigger.button.icon.label': 'Icona Condividi',
  'fabric.elements.share.trigger.button.invite.text': 'Invita',
  'fabric.elements.share.trigger.button.text': 'Condividi',
  'fabric.elements.share.trigger.button.tooltip.text': 'Condividi',
};
