/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'fabric.elements.share.admin.notified.message':
    'Administratoren din har blitt varslet',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Kopiert kobling-ikon',
  'fabric.elements.share.copied.to.clipboard.message':
    'Kobling er kopiert til utklippstavlen',
  'fabric.elements.share.copylink.button.icon.label': 'Kopier kobling-ikon',
  'fabric.elements.share.copylink.button.text': 'Kopier kobling',
  'fabric.elements.share.copypubliclink.button.text':
    'Kopier offentlig tilgjengelig kobling',
  'fabric.elements.share.failure.icon.label': 'Feil-ikon',
  'fabric.elements.share.failure.message': 'Kan ikke deles',
  'fabric.elements.share.form.comment.placeholder': 'Legg til en melding',
  'fabric.elements.share.form.info.message.direct.invite':
    'De som ikke har tilgang vil motta en invitasjon til å bli med',
  'fabric.elements.share.form.info.message.no.invite.confluence':
    'Mottakerne vil se navnet på siden og meldingen',
  'fabric.elements.share.form.info.message.no.invite.jira':
    'Mottakerne vil se navnet på saken og meldingen',
  'fabric.elements.share.form.info.message.pending.invite':
    'Invitasjonen vil bli sendt til en administrator for godkjenning',
  'fabric.elements.share.form.public.send':
    'Send offentlig tilgjengelig kobling',
  'fabric.elements.share.form.retry': 'Prøv igjen',
  'fabric.elements.share.form.send': 'Send',
  'fabric.elements.share.form.title': 'Del',
  'fabric.elements.share.form.user-picker.add-more': 'Legg til mer',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Du kan bare invitere folk med e-postadresser som tilhører {domains}. Ta kontakt med sideadministratoren for å invitere andre.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Vi kunne ikke finne noen resultater for "{inputValue}".',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Vi kunne ikke finne noen resultater for "{inputValue}". Inviter personer ved å bruke en e-postadresse.',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Skriv inn navn eller team',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Skriv inn navn, gruppe, team eller e-post',
  'fabric.elements.share.form.user-picker.placeholder.jira':
    'Skriv inn navn, team eller e-postadresse',
  'fabric.elements.share.form.user-picker.validation.required':
    'Velg minst én bruker, gruppe eller e-post eller minst ett team.',
  'fabric.elements.share.form.user-picker.validation.required.jira':
    'Velg minst én bruker, arbeidsgruppe eller e-postadresse.',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blogginnlegg delt} board {Tavle delt} calendar {Kalender delt} draft {Utkast delt} filter {Filter delt} issue {Sak delt} media {Media delt} page {Side delt} project {Prosjekt delt} pullrequest {Pull-forespørsel delt} question {Spørsmål delt} report {Rapport delt} repository {Repositorium delt} request {Forespørsel delt} roadmap {Veikart delt} site {Side delt} space {Område delt} other {Kobling delt}}',
  'fabric.elements.share.to.integration.button': 'Del til {integrationName}',
  'fabric.elements.share.trigger.button.icon.label': 'Dele-ikon',
  'fabric.elements.share.trigger.button.invite.text': 'Inviter',
  'fabric.elements.share.trigger.button.text': 'Del',
  'fabric.elements.share.trigger.button.tooltip.text': 'Del',
};
