/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Portuguese (Brazil)
export default {
  'fabric.elements.share.copied.to.clipboard.message': 'Link copiado para a área de transferência',
  'fabric.elements.share.copylink.button.text': 'Copiar link',
  'fabric.elements.share.copypubliclink.button.text': 'Copiar link público',
  'fabric.elements.share.failure.icon.label': 'Ícone de erro',
  'fabric.elements.share.failure.message': 'Não foi possível compartilhar',
  'fabric.elements.share.form.comment.placeholder': 'Adicione uma mensagem',
  'fabric.elements.share.form.info.message.no.invite.confluence':
    'Os destinatários vão ver o nome da página e sua mensagem',
  'fabric.elements.share.form.info.message.no.invite.jira': 'Os destinatários vão ver o nome do item e sua mensagem',
  'fabric.elements.share.form.no-permissions': 'Você não está apto a compartilhar.',
  'fabric.elements.share.form.public.send': 'Enviar link público',
  'fabric.elements.share.form.public.share': 'Compartilhar link público',
  'fabric.elements.share.form.retry': 'Tentar novamente',
  'fabric.elements.share.form.send': 'Enviar',
  'fabric.elements.share.form.share': 'Compartilhar',
  'fabric.elements.share.form.title': 'Compartilhar',
  'fabric.elements.share.form.user-picker.add-more': 'Insira mais itens',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Não encontramos nenhum resultado para "{inputValue}".',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Não encontramos nenhum resultado para "{inputValue}". Convide pessoas usando um endereço de e-mail.',
  'fabric.elements.share.form.user-picker.placeholder.jira': 'Insira o nome, a equipe ou o e-mail',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selecione ao menos um usuário, grupo, equipe ou e-mail.',
  'fabric.elements.share.in.integration.button': 'Compartilhar em {integrationName}',
  'fabric.elements.share.main.tab.text.confluence': 'Compartilhar página',
  'fabric.elements.share.main.tab.text.jira': 'Compartilhar item',
  'fabric.elements.share.to.integration.button': 'Compartilhar em {integrationName}',
  'fabric.elements.share.trigger.button.icon.label': 'Ícone de compartilhamento',
  'fabric.elements.share.trigger.button.invite.text': 'Convidar',
  'fabric.elements.share.trigger.button.text': 'Compartilhar',
  'fabric.elements.share.trigger.button.tooltip.text': 'Compartilhar',
};
