/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// undefined
export default {
  'fabric.elements.share.copied.to.clipboard.icon.label': '複製連結成功圖示',
  'fabric.elements.share.copied.to.clipboard.message': '已將連結複製到剪貼簿',
  'fabric.elements.share.copylink.button.icon.label': '複製連結圖示',
  'fabric.elements.share.copylink.button.text': '複製連結',
  'fabric.elements.share.copypubliclink.button.text': '複製公開連結',
  'fabric.elements.share.failure.icon.label': '錯誤圖示',
  'fabric.elements.share.failure.message': '無法分享',
  'fabric.elements.share.form.comment.placeholder': '新增訊息',
  'fabric.elements.share.form.info.message.no.invite.confluence':
    '收件者將看到頁面的名稱和您的訊息',
  'fabric.elements.share.form.info.message.no.invite.jira':
    '收件者將看到議題的名稱和您的訊息',
  'fabric.elements.share.form.public.send': '傳送公開連結',
  'fabric.elements.share.form.retry': '重試',
  'fabric.elements.share.form.send': '傳送',
  'fabric.elements.share.form.title': '分享',
  'fabric.elements.share.form.user-picker.add-more': '輸入更多項目',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    '我們找不到「{inputValue}」的任何結果。',
  'fabric.elements.share.form.user-picker.no-options.generic':
    '我們找不到「{inputValue}」的任何結果。請透過電子郵件地址邀請使用者。',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    '輸入名稱或團隊',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    '輸入名稱、群組、團隊或電子郵件',
  'fabric.elements.share.form.user-picker.placeholder.jira':
    '輸入名稱、團隊或電子郵件',
  'fabric.elements.share.form.user-picker.placholder.generic.existingUserOnly':
    '輸入名稱、群組或團隊',
  'fabric.elements.share.form.user-picker.validation.required':
    '請至少選取一個使用者、群組、團隊或電子郵件。',
  'fabric.elements.share.form.user-picker.validation.required.existingUserOnly':
    '至少選取一個使用者、群組或團隊。',
  'fabric.elements.share.form.user-picker.validation.required.jira':
    '請選取至少一個使用者、團隊或電子郵件。',
  'fabric.elements.share.form.user-picker.validation.required.jira.existingUserOnly':
    '至少選取一個使用者或團隊。',
  'fabric.elements.share.in.integration.button': '在 {integrationName} 中分享',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {已分享部落格貼文} board {已分享看板} calendar {已分享日曆} draft {已分享草稿} filter {已分享篩選條件} issue {已分享問題} media {已分享媒體} page {已分享頁面} project {已分享專案} pullrequest {已分享提取請求} question {已分享問題} report {已分享報告} repository {已分享存放庫} request {已分享請求} roadmap {已分享藍圖} site {已分享網站} space {已分享空間} other {已分享連結}}',
  'fabric.elements.share.to.integration.button': '與 {integrationName} 分享',
  'fabric.elements.share.trigger.button.icon.label': '分享圖示',
  'fabric.elements.share.trigger.button.invite.text': '邀請',
  'fabric.elements.share.trigger.button.text': '分享',
  'fabric.elements.share.trigger.button.tooltip.text': '分享',
};
