/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Czech
export default {
  "bitbucket.panel-collapse.message": "sbalit",
  "bitbucket.panel-expand.message": "rozbalit"
};
