/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Japanese
export default {
  'bitbucket.panel-collapse.message': '折りたたむ',
  'bitbucket.panel-expand.message': '展開',
};
