/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Norwegian (Bokmål)
export default {
  'bitbucket.panel-collapse.message': 'skjul',
  'bitbucket.panel-expand.message': 'utvid',
};
