/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Danish (Denmark)
export default {
  'fabric.editor.blockquote.description': 'Indsæt citat',
  'fabric.editor.blockquote2': 'Citat',
  'fabric.editor.codeblock': 'Kodestump',
  'fabric.editor.codeblock.description': 'Vis kode med syntaksfremhævning',
  'fabric.editor.customPanel': 'Brugerdefineret panel',
  'fabric.editor.customPanel.description': 'Tilføj en note med en emoji og farvet baggrund',
  'fabric.editor.errorPanel': 'Fejlpanel',
  'fabric.editor.errorPanel.description': 'Vis fejl i et farvel panel',
  'fabric.editor.heading1': 'Overskrift 1',
  'fabric.editor.heading1Description': 'Brug denne til overskrift på øverste niveau',
  'fabric.editor.heading2': 'Overskrift 2',
  'fabric.editor.heading2Description': 'Brug denne til hovedafsnit',
  'fabric.editor.heading3': 'Overskrift 3',
  'fabric.editor.heading3Description': 'Brug denne til underafsnit og mindre overskrifter',
  'fabric.editor.heading4': 'Overskrift 4',
  'fabric.editor.heading4Description': 'Brug denne til dybe overskrifter',
  'fabric.editor.heading5': 'Overskrift 5',
  'fabric.editor.heading5Description': 'Brug denne til at gruppere listeelementer',
  'fabric.editor.heading6': 'Overskrift 6',
  'fabric.editor.heading6Description': 'Brug denne til overskrift på lavt niveau',
  'fabric.editor.infoPanel': 'Informationspanel',
  'fabric.editor.infoPanel.description': 'Fremhæv information i et farvet panel',
  'fabric.editor.normal': 'Normal tekst',
  'fabric.editor.notePanel': 'Bemærkningspanel',
  'fabric.editor.notePanel.description': 'Tilføj en note i et farvet panel',
  'fabric.editor.other': 'Andre ...',
  'fabric.editor.successPanel': 'Succespanel',
  'fabric.editor.successPanel.description': 'Tilføj tip i et farvet panel',
  'fabric.editor.textStyles': 'Tekstformatering',
  'fabric.editor.warningPanel': 'Advarselspanel',
  'fabric.editor.warningPanel.description': 'Tilføj en advarselsnote i et farvet panel',
};
