/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Italian (Italy)
export default {
  'fabric.editor.blockquote.description': 'Inserisci citazione',
  'fabric.editor.blockquote2': 'Citazione',
  'fabric.editor.codeblock': 'Frammento di codice',
  'fabric.editor.codeblock.description': 'Mostra codice con colorazione della sintassi',
  'fabric.editor.customPanel': 'Pannello personalizzato',
  'fabric.editor.customPanel.description': 'Aggiungi una nota con un emoji e uno sfondo colorato',
  'fabric.editor.errorPanel': 'Pannello errori',
  'fabric.editor.errorPanel.description': 'Segnala gli errori in un pannello colorato',
  'fabric.editor.heading1': 'Titolo 1',
  'fabric.editor.heading1Description': 'Per un titolo di primo livello',
  'fabric.editor.heading2': 'Titolo 2',
  'fabric.editor.heading2Description': 'Per le sezioni principali',
  'fabric.editor.heading3': 'Titolo 3',
  'fabric.editor.heading3Description': 'Per i titoli delle sottosezioni e dei gruppi',
  'fabric.editor.heading4': 'Titolo 4',
  'fabric.editor.heading4Description': 'Per i titoli interni',
  'fabric.editor.heading5': 'Titolo 5',
  'fabric.editor.heading5Description': 'Per le voci degli elenchi',
  'fabric.editor.heading6': 'Titolo 6',
  'fabric.editor.heading6Description': 'Per i titoli di livello inferiore',
  'fabric.editor.infoPanel': 'Pannello informazioni',
  'fabric.editor.infoPanel.description': 'Metti in evidenza l’informazione in un pannello colorato',
  'fabric.editor.normal': 'Testo normale',
  'fabric.editor.notePanel': 'Pannello note',
  'fabric.editor.notePanel.description': 'Aggiungi una nota in un pannello colorato',
  'fabric.editor.other': 'Altri...',
  'fabric.editor.successPanel': 'Pannello operazioni completate',
  'fabric.editor.successPanel.description': 'Aggiungi consigli in un pannello colorato',
  'fabric.editor.textStyles': 'Stili del testo',
  'fabric.editor.warningPanel': 'Pannello avvisi',
  'fabric.editor.warningPanel.description': 'Aggiungi un avviso in un pannello colorato',
};
