/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Ukrainian (Ukraine)
export default {
  'fabric.editor.blockquote.description': 'Вставити цитату чи посилання',
  'fabric.editor.blockquote2': 'Цитата',
  'fabric.editor.codeblock': 'Фрагмент коду',
  'fabric.editor.codeblock.description': 'Показати код із розміткою синтаксису',
  'fabric.editor.customPanel': 'Користувацька панель',
  'fabric.editor.customPanel.description': 'Додайте примітку з емодзі та кольоровим фоном',
  'fabric.editor.errorPanel': 'Панель помилок',
  'fabric.editor.errorPanel.description': 'Відобразити помилки на панелі з кольорами',
  'fabric.editor.heading1': 'Заголовок 1',
  'fabric.editor.heading1Description': 'Для заголовка верхнього рівня',
  'fabric.editor.heading2': 'Заголовок 2',
  'fabric.editor.heading2Description': 'Для ключових розділів',
  'fabric.editor.heading3': 'Заголовок 3',
  'fabric.editor.heading3Description': 'Для заголовків підрозділів і груп',
  'fabric.editor.heading4': 'Заголовок 4',
  'fabric.editor.heading4Description': 'Для вкладених заголовків',
  'fabric.editor.heading5': 'Заголовок 5',
  'fabric.editor.heading5Description': 'Для елементів списку',
  'fabric.editor.heading6': 'Заголовок 6',
  'fabric.editor.heading6Description': 'Для заголовків нижнього рівня',
  'fabric.editor.infoPanel': 'Панель з інформацією',
  'fabric.editor.infoPanel.description': 'Панель із виділеною кольорами інформацією',
  'fabric.editor.normal': 'Звичайний текст',
  'fabric.editor.notePanel': 'Панель приміток',
  'fabric.editor.notePanel.description': 'Додати примітку на панель із кольорами',
  'fabric.editor.other': 'Інше...',
  'fabric.editor.successPanel': 'Панель успіху',
  'fabric.editor.successPanel.description': 'Додати поради на панель із кольорами',
  'fabric.editor.textStyles': 'Стилі тексту',
  'fabric.editor.warningPanel': 'Панель із попередженнями',
  'fabric.editor.warningPanel.description': 'Додати застереження на панель із кольорами',
};
