/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Spanish (International)
export default {
  'platform.teams.containers.empty-web-link-description': 'Añade cualquier enlace web',
  'platform.teams.containers.web-link-title-description': 'Enlace web',
  'ptc-directory.team-containers.disconnect-button.tooltip': 'Desconectar',
  'ptc-directory.team-containers.edit-link': 'Editar enlace',
  'ptc-directory.team-containers.remove-link': 'Eliminar',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-description': 'Confluence',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-title': 'Añadir espacio',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-description': 'Jira',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-title': 'Añadir proyecto',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-description': 'Loom',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-title': 'Añadir espacio',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.cancel-button': 'Cancelar',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.remove-button': 'Eliminar',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.title': 'Desconectar sitio',
  'ptc-directory.team-profile-page.team-containers.show-less': 'Mostrar menos',
  'ptc-directory.team-profile-page.team-containers.show-more': 'Mostrar más',
  'ptc.team-profile-page.team-containers.empty-state.description':
    'Tu equipo puede vincular sus proyectos de Jira y espacios de Confluence aquí para mostrar dónde trabaja',
  'ptc.team-profile-page.team-containers.empty-state.title': 'Añade los espacios donde tu equipo trabaja',
};
