/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Korean
export default {
  'platform.teams.containers.empty-web-link-description': '웹 링크 추가',
  'platform.teams.containers.web-link-title-description': '웹 연결',
  'ptc-directory.team-containers.disconnect-button.tooltip': '연결 해제',
  'ptc-directory.team-containers.edit-link': '링크 편집',
  'ptc-directory.team-containers.remove-link': '제거',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-description': 'Confluence',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-title': '스페이스 추가',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-description': 'Jira',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-title': '프로젝트 추가',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-description': 'Loom',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-title': '스페이스 추가',
  'ptc-directory.team-profile-page.team-containers.create.add-confluence-space-description': '지식 은행을 만듭니다',
  'ptc-directory.team-profile-page.team-containers.create.add-confluence-space-title': 'Confluence 스페이스',
  'ptc-directory.team-profile-page.team-containers.create.add-jira-project-description': '프로젝트 작업을 계획합니다',
  'ptc-directory.team-profile-page.team-containers.create.add-jira-project-title': 'Jira 프로젝트',
  'ptc-directory.team-profile-page.team-containers.create.add-loom-space-description': '비동기 업데이트를 공유합니다',
  'ptc-directory.team-profile-page.team-containers.create.add-loom-space-title': 'Loom 스페이스',
  'ptc-directory.team-profile-page.team-containers.create.add-web-link-title': '웹 링크 추가',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.cancel-button': '취소',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.description':
    '{containerType, select, JiraProject {이 팀은 더 이상 {containerName} Jira 프로젝트에 연결되지 않습니다.} ConfluenceSpace {이 팀은 더 이상 {containerName} Confluence 스페이스에 연결되지 않습니다.} LoomSpace {이 팀은 더 이상 {containerName} Loom 스페이스에 연결되지 않습니다.} other {이 팀은 더 이상 {containerName} 링크에 연결되지 않습니다.}}',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.disclaimer':
    '{containerType, select, JiraProject {{containerType, select, JiraProject {프로젝트에서 팀을 연결 해제해도 프로젝트 내의 팀과 연결된 업무에 영향을 주지 않습니다.} ConfluenceSpace {스페이스에서 팀을 연결 해제해도 프로젝트 내의 팀과 연결된 업무에 영향을 주지 않습니다.} LoomSpace {스페이스에서 팀을 연결 해제해도 프로젝트 내의 팀과 연결된 업무에 영향을 주지 않습니다.} other {링크에서 팀을 연결 해제해도 프로젝트 내의 팀과 연결된 업무에 영향을 주지 않습니다.}}} ConfluenceSpace {{containerType, select, JiraProject {프로젝트에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.} ConfluenceSpace {스페이스에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.} LoomSpace {스페이스에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.} other {링크에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.}}} LoomSpace {{containerType, select, JiraProject {프로젝트에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.} ConfluenceSpace {스페이스에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.} LoomSpace {스페이스에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.} other {링크에서 팀을 연결 해제해도 스페이스 내의 팀과 연결된 업무에 영향을 주지 않습니다.}}} other {{containerType, select, JiraProject {프로젝트에서 팀을 연결 해제해도 링크 내의 팀과 연결된 업무에 영향을 주지 않습니다.} ConfluenceSpace {스페이스에서 팀을 연결 해제해도 링크 내의 팀과 연결된 업무에 영향을 주지 않습니다.} LoomSpace {스페이스에서 팀을 연결 해제해도 링크 내의 팀과 연결된 업무에 영향을 주지 않습니다.} other {링크에서 팀을 연결 해제해도 링크 내의 팀과 연결된 업무에 영향을 주지 않습니다.}}}}',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.disclaimer-fallback':
    '링크에서 팀을 연결 해제해도 팀에 연결된 작업에 영향을 주지 않습니다.',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.remove-button': '제거',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.title': '작업 영역 연결 해제',
  'ptc-directory.team-profile-page.team-containers.show-less': '간단히 보기',
  'ptc-directory.team-profile-page.team-containers.show-more': '더 보기',
  'ptc.team-profile-page.team-containers.empty-state.description':
    '팀은 Jira 프로젝트, Confluence 스페이스를 여기에 연결하여 작업 영역을 보여줄 수 있습니다',
  'ptc.team-profile-page.team-containers.empty-state.title': '팀의 작업 영역 추가',
  'teams-public.team-containers.timeout-action': '다시 시도',
  'teams-public.team-containers.timeout-description': '문제가 발생했습니다. 연결을 확인하고 다시 시도하세요.',
  'teams-public.team-containers.timeout-no-connection-action': '지원 팀에 문의',
  'teams-public.team-containers.timeout-no-connection-description': '스페이스를 수동으로 직접 만들어 보세요.',
  'teams-public.team-containers.timeout-no-connection-title': '연결 실패',
  'teams-public.team-containers.timeout-title': '스페이스를 연결할 수 없습니다',
};
