/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Serbian (Serbia) [sr-RS]
export default {
  'platform.teams.containers.empty-web-link-description': 'Dodaj bilo koji veb-link',
  'platform.teams.containers.web-link-title-description': 'Veb-link',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-description': 'Confluence',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-title': 'Dodaj prostor',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-description': 'Jira',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-title': 'Dodaj projekat',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-description': 'Loom',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-title': 'Dodaj prostor',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.cancel-button': 'Otkaži',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.disclaimer-fallback':
    'Isključivanje tima sa linka neće uticati ni na koji rad povezan sa timom.',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.title': 'Isključi mesto',
  'ptc-directory.team-profile-page.team-containers.show-less': 'Prikaži manje',
  'ptc-directory.team-profile-page.team-containers.show-more': 'Prikaži više',
  'ptc.team-profile-page.team-containers.empty-state.description':
    'Vaš tim ovde može da povezuje svoje Jira projekte, Confluence prostore da bi prikazali gde rade',
  'ptc.team-profile-page.team-containers.empty-state.title': 'Dodajte mesta radova vašeg tima',
};
