/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Swedish
export default {
  'platform.teams.containers.empty-web-link-description': 'Lägg till en webblänk',
  'platform.teams.containers.web-link-title-description': 'Webblänk',
  'ptc-directory.team-containers.disconnect-button.tooltip': 'Koppla från',
  'ptc-directory.team-containers.edit-link': 'Redigera länk',
  'ptc-directory.team-containers.remove-link': 'Ta bort',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-description': 'Confluence',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-title': 'Lägg till utrymme',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-description': 'Jira',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-title': 'Lägg till projekt',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-description': 'Loom',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-title': 'Lägg till utrymme',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.cancel-button': 'Avbryt',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.disclaimer-fallback':
    'Att koppla bort teamet från länken påverkar inte något arbete som är kopplat till teamet.',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.remove-button': 'Ta bort',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.title': 'Koppla bort platsen',
  'ptc-directory.team-profile-page.team-containers.show-less': 'Visa mindre',
  'ptc-directory.team-profile-page.team-containers.show-more': 'Visa mer',
  'ptc.team-profile-page.team-containers.empty-state.description':
    'Ditt team kan länka sina Jira-projekt och Confluence-utrymmen här för att visa var de arbetar',
  'ptc.team-profile-page.team-containers.empty-state.title': 'Lägg till platser där ditt team arbetar',
};
