/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Vietnamese (Vietnam)
export default {
  'platform.teams.containers.empty-web-link-description': 'Thêm liên kết web bất kỳ',
  'platform.teams.containers.web-link-title-description': 'Liên kết web',
  'ptc-directory.team-containers.disconnect-button.tooltip': 'Ngắt kết nối',
  'ptc-directory.team-containers.edit-link': 'Sửa liên kết',
  'ptc-directory.team-containers.remove-link': 'Xóa',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-description': 'Confluence',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-title': 'Thêm không gian',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-description': 'Jira',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-title': 'Thêm dự án',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-description': 'Loom',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-title': 'Thêm không gian',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.cancel-button': 'Hủy',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.disclaimer-fallback':
    'Việc ngắt kết nối đội ngũ khỏi liên kết sẽ không ảnh hưởng đến bất kỳ công việc nào được kết nối với đội ngũ.',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.remove-button': 'Xóa',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.title': 'Ngắt kết nối địa điểm',
  'ptc-directory.team-profile-page.team-containers.show-less': 'Hiển thị ít hơn',
  'ptc-directory.team-profile-page.team-containers.show-more': 'Hiển thị thêm',
  'ptc.team-profile-page.team-containers.empty-state.description':
    'Đội ngũ của bạn có thể liên kết các dự án Jira, không gian Confluence ở đây để hiển thị nơi họ làm việc',
  'ptc.team-profile-page.team-containers.empty-state.title': 'Thêm các địa điểm mà đội ngũ của bạn làm việc',
};
