/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Chinese (Simplified)
export default {
  'platform.teams.containers.empty-web-link-description': '添加任意网络链接',
  'platform.teams.containers.web-link-title-description': '网络链接',
  'ptc-directory.team-containers.disconnect-button.tooltip': '断开连接',
  'ptc-directory.team-containers.edit-link': '编辑链接',
  'ptc-directory.team-containers.remove-link': '移除',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-description': 'Confluence',
  'ptc-directory.team-profile-page.team-containers.add-confluence-space-title': '添加空间',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-description': 'Jira',
  'ptc-directory.team-profile-page.team-containers.add-jira-project-title': '添加项目',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-description': 'Loom',
  'ptc-directory.team-profile-page.team-containers.add-loom-space-title': '添加空间',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.cancel-button': '取消',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.remove-button': '移除',
  'ptc-directory.team-profile-page.team-containers.disconnect-dialog.title': '断开连接地点',
  'ptc-directory.team-profile-page.team-containers.show-less': '显示更少',
  'ptc-directory.team-profile-page.team-containers.show-more': '显示更多',
  'ptc.team-profile-page.team-containers.empty-state.description':
    '您的团队成员可以将 Jira 项目、Confluence 空间链接到此处，以显示他们的工作地点',
  'ptc.team-profile-page.team-containers.empty-state.title': '添加您团队的工作地点',
};
