import { wb, type WorkbenchExample } from '@atlassian/workbench';

import FileCardFlowExample from './00-file-card-flow';
import InlineVideoCardExample from './01-inline-video-card';
import MediaViewerIntegrationExample from './02-media-viewer-integration';
import MediaInlineCardExample from './03-media-inline-card';
import CardResponsiveExample from './04-card-responsive';
import CardFilesExample from './05-card-files';
import CardFilestatesExample from './06-card-filestates';
import CardLazyLoadExample from './07-card-lazy-load';
import CardLightExample from './08-card-light';
import CardMediaTypeMatrixExample from './09-card-media-type-matrix';
import CardResizingModesExample from './10-card-resizing-modes';
import CardViewEditableCardExample from './11-card-view-editableCard';
import CardViewIconsExample from './12-card-view-icons';
import CardViewMatrixExample from './13-card-view-matrix';
import OrientationExampleSource from './14-orientation-example';
import I18NExample from './15-i18n';
import InlineCardFilestatesExample from './16-inline-card-filestates';
import CardV2Example from './17-card-v2';
import CardV2HydrationExample from './18-card-v2-SSR-hydration';
import CardV2CasesExample from './19-card-v2-SSR-cases';
import CardLoadingMotionExample from './20-card-loading-motion';
import SvgLoadExample from './20-svg-load';
import SvgResponsiveExample from './21-svg-responsive';
import VisuallyCompleteExampleSource from './22-visually-complete-example';
import AndAbuseExample from './23-DSP-and-abuse';
import VideoCaptionsExample from './24-video-captions';
import PlayerBreakpointsExample from './25-player-breakpoints';
import ResponsivePlayerExample from './25-responsive-player';
import UnhandledErrorCardExample from './unhandled-error-card';

export const FileCardFlow: WorkbenchExample = wb(FileCardFlowExample);
export const InlineVideoCard: WorkbenchExample = wb(InlineVideoCardExample);
export const MediaViewerIntegration: WorkbenchExample = wb(MediaViewerIntegrationExample);
export const MediaInlineCard: WorkbenchExample = wb(MediaInlineCardExample);
export const CardResponsive: WorkbenchExample = wb(CardResponsiveExample);
export const CardFiles: WorkbenchExample = wb(CardFilesExample);
export const CardFilestates: WorkbenchExample = wb(CardFilestatesExample);
export const CardLazyLoad: WorkbenchExample = wb(CardLazyLoadExample);
export const CardLight: WorkbenchExample = wb(CardLightExample);
export const CardMediaTypeMatrix: WorkbenchExample = wb(CardMediaTypeMatrixExample);
export const CardResizingModes: WorkbenchExample = wb(CardResizingModesExample);
export const CardViewEditableCard: WorkbenchExample = wb(CardViewEditableCardExample);
export const CardViewIcons: WorkbenchExample = wb(CardViewIconsExample);
export const CardViewMatrix: WorkbenchExample = wb(CardViewMatrixExample);
export const OrientationExample: WorkbenchExample = wb(OrientationExampleSource);
export const I18N: WorkbenchExample = wb(I18NExample);
export const InlineCardFilestates: WorkbenchExample = wb(InlineCardFilestatesExample);
export const CardV2: WorkbenchExample = wb(CardV2Example);
export const CardV2Hydration: WorkbenchExample = wb(CardV2HydrationExample);
export const CardV2Cases: WorkbenchExample = wb(CardV2CasesExample);
export const CardLoadingMotion: WorkbenchExample = wb(CardLoadingMotionExample);
export const SvgLoad: WorkbenchExample = wb(SvgLoadExample);
export const SvgResponsive: WorkbenchExample = wb(SvgResponsiveExample);
export const VisuallyCompleteExample: WorkbenchExample = wb(VisuallyCompleteExampleSource);
export const AndAbuse: WorkbenchExample = wb(AndAbuseExample);
export const VideoCaptions: WorkbenchExample = wb(VideoCaptionsExample);
export const PlayerBreakpoints: WorkbenchExample = wb(PlayerBreakpointsExample);
export const ResponsivePlayer: WorkbenchExample = wb(ResponsivePlayerExample);
export const UnhandledErrorCard: WorkbenchExample = wb(UnhandledErrorCardExample);
