export type {
  Icon,
  RenderOptionsProps,
  AlignType,
  ConfirmDialogOptions,
  FloatingToolbarButton,
  FloatingToolbarInput,
  FloatingToolbarCustom,
  FloatingToolbarListPicker,
  FloatingToolbarColorPicker,
  FloatingToolbarEmojiPicker,
  FloatingToolbarDatePicker,
  FloatingToolbarSelect,
  FloatingToolbarSeparator,
  FloatingToolbarDropdown,
  FloatingToolbarFallbackItem,
  FloatingToolbarItem,
  FloatingToolbarConfig,
  FloatingToolbarHandler,
} from '@atlaskit/editor-common/types';
