/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Icelandic
export default {
  'global_search.confluence.no_results_in_space':
    'Engar niðurstöður í ‚{spaceTitle}‘',
  'global_search.confluence.remove_space_filter': 'Fjarlægja svæðissíu',
  'global_search.confluence.space_filter': 'Sía niðurstöður eftir svæði',
  'global_search.confluence.more_filters': 'Fleiri síuvalkostir',
  'global_search.confluence.recent_pages_heading': 'Nýlegar síður og blogg',
  'global_search.confluence.recent_spaces_heading': 'Nýleg svæði',
  'global_search.confluence.search_placeholder': 'Leita í Confluence',
  'global_search.confluence.spaces_heading': 'Svæði',
  'global_search.confluence.confluence_objects_heading':
    'Síður, blogg og viðhengi',
  'global_search.confluence.advanced_search': 'Ítarleg leit',
  'global_search.confluence.advanced_search_filters': 'Ítarleg leit með síum',
  'global_search.confluence.advanced_search_for': 'Ítarleg leit að "{query}"',
  'global_search.no_recent_activity_title': 'Leitaðu þess sem þú þarft',
  'global_search.no_recent_activity_body':
    'Eða notaðu<a href={url}>ítarleg leit</a> (`shift + enter`) til að þrengja niðurstöðurnar.',
  'global_search.no_results_title':
    'Okkur tókst ekki að finna neitt sem samræmdust leit þinni',
  'global_search.no_results_body':
    'Reyndu aftur með öðru leitarorði, eða fínstillt niðurstöðurnar þínar með ítarlegu leitinni okkar.',
  'global_search.people.recent_people_heading': 'Nýlega unnið með',
  'global_search.people.people_heading': 'Fólk',
  'global_search.people.advanced_search': 'Leita að fólki',
  'global_search.search_error_title': 'Við eigum í vandræðum með að leita.',
  'global_search.search_error_body':
    'Þetta gæti bara verið smá hnökri. Best er að {link}.',
  'global_search.search_error_body.link': 'reyna aftur',
  'global_search.jira.search_placeholder': 'Leita í Jira',
  'global_search.jira.recent_issues_heading': 'Nýleg málefni',
  'global_search.jira.recent_people_heading': 'Nýlega unnið með',
  'global_search.jira.recent_containers': 'Nýlegar töflur, verkefni og síur',
  'global_search.jira.recent_core_containers': 'Nýlegar verkefni og síur',
  'global_search.jira.search_result_issues_heading': 'Málefni',
  'global_search.jira.search_result_containers_heading':
    'Töflur, verkefni og síur',
  'global_search.jira.search_result_core_containers_heading':
    'Verkefni og síur',
  'global_search.jira.search_result_people_heading': 'Fólk',
  'global_search.jira.advanced_search': 'Skoða allt:',
  'global_search.jira.advanced_search_issues': 'Vandamál',
  'global_search.jira.advanced_search_projects': 'Verkefni',
  'global_search.jira.advanced_search_boards': 'Borð',
  'global_search.jira.advanced_search_filters': 'Síur',
  'global_search.jira.advanced_search_people': 'Fólk',
  'global_search.jira.advanced_issue_search': 'Ítarleg leit fyrir málefni',
  'global_search.jira.view_all_issues': 'Skoða öll vandamál',
  'global_search.jira.no_results_title':
    'Okkur tókst ekki að finna neitt sem samræmdust leit þinni',
  'global_search.jira.no_results_body': 'Reyna aftur með öðru orðasambandi.',
  'global_search.jira.no_recent_activity_body':
    'Eða fínstillt niðurstöðurnar þínar með ítarlegu leitinni okkar.',
  'global_search.jira.project_type.business_project': 'Viðskiptaverkefni',
  'global_search.jira.project_type.software_project': 'Verkefni hugbúnaðar',
  'global_search.jira.project_type.service_desk_project':
    'Verkefni þjónustuborðs',
  'global_search.jira.project_type.ops_project': 'Aðgerðaverkefni',
  'global_search.jira.result_type.board': 'Tafla',
  'global_search.jira.result_type.filter': 'Sía',
  'global_search.give_feedback': 'Senda athugasemdir',
  'global_search.show_more_button_text':
    'Sýna {itemsPerPage} fleiri niðurstöður',
  'global_search.show_more_button_advanced_search':
    'Fínstillt niðurstöðurnar með ítarlegu leitinni',
  'global_search.confluence.subtext_with_modified_date':
    '{containerName}.  Uppfært {friendlyLastModified}',
};
