/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'global_search.confluence.advanced_search': 'Zaawansowane wyszukiwanie',
  'global_search.confluence.advanced_search_filters':
    'Zaawansowane wyszukiwanie z filtrami',
  'global_search.confluence.advanced_search_for':
    'Zaawansowane wyszukiwanie zapytań dla „{query}”',
  'global_search.confluence.confluence_objects_heading':
    'Strony, blogi i załączniki',
  'global_search.confluence.more_filters': 'Więcej opcji filtrowania',
  'global_search.confluence.no_results_in_space':
    "Brak wyników w '{'spaceTitle'}'",
  'global_search.confluence.recent_pages_heading':
    'Ostatnio odwiedzane strony i blogi',
  'global_search.confluence.recent_spaces_heading':
    'Ostatnio odwiedzane przestrzenie',
  'global_search.confluence.remove_space_filter': 'Usuń filtr przestrzeni',
  'global_search.confluence.search_placeholder': 'Szukaj w Confluence',
  'global_search.confluence.space_filter': 'Filtruj wyniki według przestrzeni',
  'global_search.confluence.spaces_heading': 'Przestrzenie',
  'global_search.confluence.subtext_with_modified_date':
    '{containerName}  ·  Zaktualizowano {friendlyLastModified}',
  'global_search.give_feedback': 'Przekaż opinię',
  'global_search.jira.advanced_issue_search':
    'Zaawansowane wyszukiwanie zgłoszeń',
  'global_search.jira.advanced_search': 'Wyświetl wszystko:',
  'global_search.jira.advanced_search_boards': 'Tablice',
  'global_search.jira.advanced_search_filters': 'Filtry',
  'global_search.jira.advanced_search_issues': 'Zgłoszenia',
  'global_search.jira.advanced_search_people': 'Użytkownicy',
  'global_search.jira.advanced_search_projects': 'Projekty',
  'global_search.jira.no_recent_activity_body':
    'Lub doprecyzuj swoje wyniki dzięki zaawansowanemu wyszukiwaniu.',
  'global_search.jira.no_results_body':
    'Spróbuj ponownie, wybierając inny termin.',
  'global_search.jira.no_results_title':
    'Nie znaleziono żadnych filtrów pasujących do kryteriów wyszukiwania',
  'global_search.jira.project_type.business_project': 'Projekt biznesowy',
  'global_search.jira.project_type.ops_project': 'Projekt Ops',
  'global_search.jira.project_type.service_desk_project':
    'Projekt Service Desk',
  'global_search.jira.project_type.software_project': 'Projekt oprogramowania',
  'global_search.jira.recent_containers': 'Ostatnie tablice, projekty i filtry',
  'global_search.jira.recent_core_containers': 'Ostatnie projekty i filtry',
  'global_search.jira.recent_issues_heading': 'Ostatnie zgłoszenia',
  'global_search.jira.recent_people_heading': 'Pracowano ostatnio z',
  'global_search.jira.result_type.board': 'Tablica',
  'global_search.jira.result_type.filter': 'Filtr',
  'global_search.jira.search_placeholder': 'Wyszukiwanie Jira',
  'global_search.jira.search_result_containers_heading':
    'Tablice, projekty i filtry',
  'global_search.jira.search_result_core_containers_heading':
    'Projekty i filtry',
  'global_search.jira.search_result_issues_heading': 'Zgłoszenia',
  'global_search.jira.search_result_people_heading': 'Użytkownicy',
  'global_search.jira.view_all_issues': 'Wyświetl wszystkie zgłoszenia',
  'global_search.no_recent_activity_body':
    'Lub skorzystaj z funkcji <a href={url}>wyszukiwania zaawansowanego</a> („shit+enter”), aby zawęzić wyniki.',
  'global_search.no_recent_activity_title': 'Wyszukaj to, czego potrzebujesz',
  'global_search.no_results_body':
    'Spróbuj wyszukać inny termin lub doprecyzuj swoje wyniki dzięki zaawansowanemu wyszukiwaniu.',
  'global_search.no_results_title':
    'Nie znaleziono żadnych filtrów pasujących do kryteriów wyszukiwania',
  'global_search.people.advanced_search': 'Wyszukaj użytkowników',
  'global_search.people.people_heading': 'Użytkownicy',
  'global_search.people.recent_people_heading': 'Pracowano ostatnio z',
  'global_search.search_error_body':
    'To może być tylko chwilowy problem. Najlepiej {link}.',
  'global_search.search_error_body.link': 'spróbować ponownie',
  'global_search.search_error_title':
    'Wystąpiły problemy podczas wyszukiwania.',
  'global_search.show_more_button_advanced_search_v2':
    'Wyświetl wszystkie wyniki',
  'global_search.show_more_button_text':
    'Pokaż więcej wyników ({itemsPerPage})',
};
