/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Czech
export default {
  'ai-mate.agent-avatar-label': 'Avatar agenta',
  'ai-mate.agent-profile-info.created-by': 'Agent Rovo od {creatorNameWithLink}',
  'ai-mate.agent-profile-info.creator': 'Autor',
  'ai-mate.agent-profile-info.deactivated': '(deaktivováno)',
  'ai-mate.agent-profile-info.hidden-icon': 'Skryté',
  'ai-mate.agent-profile-info.hidden-tooltip': 'Agent se nezobrazí ve výsledcích vyhledávání.',
  'ai-mate.agent-profile-info.star-agent-tooltip': 'Přidat agenta do oblíbených',
  'ai-mate.agent-profile-info.starred-count':
    '{starCount, plural, one {1 uživatel} few {{starCount} uživatelé} many {{starCount} uživatele} other {{starCount} uživatelů}}',
  'ai-mate.chat-history.empty-state.agent-suggestion1': 'Povězte mi o sobě',
  'ai-mate.chat-history.empty-state.agent-suggestion2': 'S čím mi můžete pomoci?',
  'ai-mate.chat-history.empty-state.agent-suggestion3': 'Shrnout, na co se dívám',
  'ai-mate.chat-history.empty-state.suggestion1': 'Jsou některé z mých ticketů po termínu?',
  'ai-mate.chat-history.empty-state.suggestion2': 'Na čem mám pracovat dále?',
  'ai-mate.chat-history.empty-state.suggestion3': 'Napsat aktualizaci o mém týdnu',
  'ai-mate.rovo-agent-components.browse-agents-pill.label': 'Procházet agenty',
  'rovo-chat.browse-agents.click-to-favourite-label': 'Není v oblíbených, kliknutím přidáte.',
  'rovo-chat.browse-agents.copy-agent-label': 'Kopírovat odkaz na agenta',
  'rovo-chat.browse-agents.remove-from-favourites-label': 'Odebrat z oblíbených',
  'rovo-chat.view-agent.chat-to-agent-button': 'Chatovat s agentem',
  'rovo-chat.view-agent.copy-link-to-profile': 'Kopírovat odkaz',
  'rovo-chat.view-agent.delete-agent': 'Odstranit agenta',
  'rovo-chat.view-agent.duplicate-agent': 'Duplikovat agenta',
  'rovo-chat.view-agent.edit-agent': 'Upravit agenta',
  'rovo-chat.view-agent.link-copied-to-profile': 'Zkopírovaná adresa URL',
  'rovo-chat.view-agent.more-actions-for-label': 'Další akce položky {agentName}',
  'rovo-chat.view-agent.more-actions-label': 'Další akce',
  'rovo-chat.view-agents.use-template-button': 'Použít šablonu',
  'rovo-chat.view-agents.view-agent': 'Zobrazit agenta',
  'rovo-chat.view-agents.view-agent-full-profile': 'Zobrazit úplný profil',
};
