/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Serbian (Cyrillic) [sr-YR]
export default {
  'rovo-chat.view-agent.more-actions-for-label': 'Више радњи за {agentName}',
};
