/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Russian
export default {
  'fabric.editor.fieldsetLabel': 'Список задач',
  'platform.taskDecision.markTaskAsCompleted': 'Отметить задачу как выполненную',
  'platform.taskDecision.markTaskAsNotCompleted': 'Отметить задачу как невыполненную',
};
