/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Ukrainian (Ukraine)
export default {
  'fabric.editor.fieldsetLabel': 'Список пунктів завдань',
  'platform.taskDecision.markTaskAsCompleted': 'Позначити задачу як завершену',
  'platform.taskDecision.markTaskAsNotCompleted': 'Позначити задачу як незавершену',
};
