/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Chinese (Traditional)
export default {
  'fabric.editor.fieldsetLabel': '交辦事項列表',
  'platform.taskDecision.markTaskAsCompleted': '將任務標示為已完成',
  'platform.taskDecision.markTaskAsNotCompleted': '將任務標示為未完成',
};
