/**
 * THIS FILE WAS CREATED VIA CODEGEN DO NOT MODIFY {@see http://go/af-codegen}
 *
 * To change the format of this file, modify `UNSAFE_createIconDocsNew` in icon-build-process/src/create-icon-docs.tsx.
 *
 * @codegen <<SignedSource::f616f5d0a9783832de09265d7ac5d646>>
 * @codegenCommand yarn build:icon-glyphs
 */
interface metadata {
	/**
	 * Default component name for the icon
	 */
	componentName: string;

	/**
	 * Package path to the icon component
	 */
	package: string;

	/**
	 * The category of the icon:
	 * - 'single-purpose' icons should only be used for the purposes listed in the 'usage' field
	 * - 'multi-purpose' icons are designed for various use cases and don't have the same usage restrictions
	 * - 'utility' icons are used for utility purposes
	 */
	categorization: 'single-purpose' | 'multi-purpose' | 'utility';

	/**
	 * The type of the icon - either a 16px 'core' icon, or a 12px 'utility' icon
	 */
	type: 'core' | 'utility';

	/**
	 * Usage guidelines for the icon. For single-purpose icons,
	 */
	usage?: string;

	/**
	 * Additional keywords used to assist in search/lookup of an icon
	 */
	keywords: string[];

	/**
	 * The name of the team owning the icon
	 */
	team: string;

	/**
	 * Contact slack channel for the team owning the icon
	 */
	slackChannel?: string;

	/**
	 * A list of keys for old icons that have been replaced by this icon
	 */
	oldName?: string[];
}

const metadata: Record<string, metadata> = {
	add: {
		keywords: ['add', 'plus', 'create', 'new', 'icon', 'core', 'create', 'plus'],
		componentName: 'AddIcon',
		package: '@atlaskit/icon/core/add',
		oldName: ['add-circle', 'add', 'editor/add', 'emoji/custom'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for creating and adding an object.',
		team: 'ADS',
	},
	'ai-agent': {
		keywords: ['ai-agent', 'aiagent', 'icon', 'core', 'Rovo', 'AI', 'chat agent'],
		componentName: 'AiAgentIcon',
		package: '@atlaskit/icon/core/ai-agent',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for Rovo Agent.',
		team: 'Rovo',
	},
	'ai-chat': {
		keywords: ['ai-chat', 'aichat', 'icon', 'core', 'Rovo', 'AI', 'chat agent'],
		componentName: 'AiChatIcon',
		package: '@atlaskit/icon/core/ai-chat',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for Rovo Chat.',
		team: 'Rovo',
	},
	alert: {
		keywords: ['alert', 'icon', 'core', 'alert', 'event', 'operations'],
		componentName: 'AlertIcon',
		package: '@atlaskit/icon/core/alert',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for alerts in JSM and Compass.',
		team: 'Jira',
	},
	'align-center': {
		keywords: ['align-center', 'aligncenter', 'icon', 'core', 'alignment', 'text', 'content'],
		componentName: 'AlignCenterIcon',
		package: '@atlaskit/icon/core/align-center',
		oldName: ['editor/align-center'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: align text center, align center.',
		team: 'Editor',
	},
	'align-left': {
		keywords: [
			'align-left',
			'alignleft',
			'icon',
			'core',
			'alignment',
			'text',
			'content',
			'summary',
		],
		componentName: 'AlignLeftIcon',
		package: '@atlaskit/icon/core/align-left',
		oldName: ['editor/align-left', 'overview'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: align text left, align content left, summary.',
		team: 'Editor',
	},
	'align-right': {
		keywords: ['align-right', 'alignright', 'icon', 'core', 'alignment', 'text', 'content'],
		componentName: 'AlignRightIcon',
		package: '@atlaskit/icon/core/align-right',
		oldName: ['editor/align-right'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: align text right, align content right.',
		team: 'Editor',
	},
	'angle-brackets': {
		keywords: ['angle-brackets', 'anglebrackets', 'icon', 'core', 'code', '<>', '</>', 'syntax'],
		componentName: 'AngleBracketsIcon',
		package: '@atlaskit/icon/core/angle-brackets',
		oldName: ['bitbucket/repos', 'bitbucket/source', 'code', 'editor/code', 'media-services/code'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: code or source code in Bitbucket and Jira.',
		team: 'Jira',
	},
	app: {
		keywords: [
			'app',
			'icon',
			'core',
			'add-on',
			'add on',
			'plugin',
			'external app',
			'third-party app',
		],
		componentName: 'AppIcon',
		package: '@atlaskit/icon/core/app',
		oldName: ['addon'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for marketplace apps and integrations across products.',
		team: 'ADS',
	},
	'app-switcher': {
		keywords: [
			'app-switcher',
			'appswitcher',
			'icon',
			'core',
			'application switcher',
			'change product',
			'switch product',
			'product switcher',
			'top navigation',
		],
		componentName: 'AppSwitcherIcon',
		package: '@atlaskit/icon/core/app-switcher',
		oldName: ['app-switcher', 'switcher'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for app switcher in global product navigation.',
		team: 'ADS',
	},
	'app-switcher-legacy': {
		keywords: [
			'app-switcher-legacy',
			'appswitcherlegacy',
			'icon',
			'core',
			'application switcher',
			'change product',
			'switch product',
			'product switcher',
			'top navigation',
		],
		componentName: 'AppSwitcherLegacyIcon',
		package: '@atlaskit/icon/core/app-switcher-legacy',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for the legacy app switcher in global product navigation.',
		team: 'ADS',
	},
	apps: {
		keywords: ['apps', 'icon', 'core', 'third-party', 'applications'],
		componentName: 'AppsIcon',
		package: '@atlaskit/icon/core/apps',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for adding or viewing apps.',
		team: 'ADS',
	},
	'archive-box': {
		keywords: ['archive-box', 'archivebox', 'icon', 'core', 'file box'],
		componentName: 'ArchiveBoxIcon',
		package: '@atlaskit/icon/core/archive-box',
		oldName: ['archive'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: archiving pages, storage.',
		team: 'ADS',
	},
	'arrow-down': {
		keywords: ['arrow-down', 'arrowdown', 'icon', 'core', 'down', 'bottom', 'sorting'],
		componentName: 'ArrowDownIcon',
		package: '@atlaskit/icon/core/arrow-down',
		oldName: ['arrow-down-circle', 'arrow-down'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Know uses: sorting table headers or Bitbucket code difference.',
		team: 'ADS',
	},
	'arrow-left': {
		keywords: ['arrow-left', 'arrowleft', 'back', 'previous', 'icon', 'core', 'back', 'previous'],
		componentName: 'ArrowLeftIcon',
		package: '@atlaskit/icon/core/arrow-left',
		oldName: ['arrow-left-circle', 'arrow-left'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: back to previous screen, previous slide.',
		team: 'ADS',
	},
	'arrow-right': {
		keywords: [
			'arrow-right',
			'arrowright',
			'forward',
			'next',
			'icon',
			'core',
			'forward',
			'next',
			'link',
		],
		componentName: 'ArrowRightIcon',
		package: '@atlaskit/icon/core/arrow-right',
		oldName: ['arrow-right-circle', 'arrow-right'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: link to nested menu item, a linked menu item, next slide.',
		team: 'ADS',
	},
	'arrow-up': {
		keywords: ['arrow-up', 'arrowup', 'icon', 'core', 'improvement'],
		componentName: 'ArrowUpIcon',
		package: '@atlaskit/icon/core/arrow-up',
		oldName: ['arrow-up-circle', 'arrow-up'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: back to top.',
		team: 'ADS',
	},
	'arrow-up-right': {
		keywords: [
			'arrow-up-right',
			'arrowupright',
			'icon',
			'core',
			'expand',
			'open',
			'diagonal arrow',
		],
		componentName: 'ArrowUpRightIcon',
		package: '@atlaskit/icon/core/arrow-up-right',
		oldName: ['editor/open', 'open'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: open a link in a new page (but not a new tab).',
		team: 'ADS',
	},
	'atlassian-intelligence': {
		keywords: ['atlassian-intelligence', 'atlassianintelligence', 'icon', 'core', 'AI'],
		componentName: 'AtlassianIntelligenceIcon',
		package: '@atlaskit/icon/core/atlassian-intelligence',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for Atlassian Intelligence products or experiences.',
		team: 'ADS',
	},
	attachment: {
		keywords: ['attachment', 'paperclip', 'icon', 'core', 'paperclip', 'attach'],
		componentName: 'AttachmentIcon',
		package: '@atlaskit/icon/core/attachment',
		oldName: ['attachment', 'editor/attachment'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for attaching files to issues or other objects.',
		team: 'ADS',
	},
	audio: {
		keywords: ['audio', 'music', 'note', 'sound', 'icon', 'core', 'music', 'musical note'],
		componentName: 'AudioIcon',
		package: '@atlaskit/icon/core/audio',
		oldName: ['audio-circle', 'audio', 'media-services/audio'],
		type: 'core',
		categorization: 'single-purpose',
		team: 'Media',
	},
	automation: {
		keywords: ['automation', 'icon', 'core', 'lightning bolt', 'automation rule'],
		componentName: 'AutomationIcon',
		package: '@atlaskit/icon/core/automation',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved to represent an Automation.',
		team: 'Automation',
	},
	backlog: {
		keywords: ['backlog', 'icon', 'core', 'rows'],
		componentName: 'BacklogIcon',
		package: '@atlaskit/icon/core/backlog',
		oldName: ['backlog'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for backlogs in Jira.',
		team: 'ADS',
	},
	board: {
		keywords: ['board', 'icon', 'core', 'columns', 'active sprint'],
		componentName: 'BoardIcon',
		package: '@atlaskit/icon/core/board',
		oldName: ['board'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for boards in Jira.',
		team: 'ADS',
	},
	boards: {
		keywords: ['boards', 'icon', 'core'],
		componentName: 'BoardsIcon',
		package: '@atlaskit/icon/core/boards',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved as the icon to represent multiple boards.',
		team: 'ADS',
	},
	'book-with-bookmark': {
		keywords: [
			'book-with-bookmark',
			'bookwithbookmark',
			'icon',
			'core',
			'knowledge base',
			'article',
		],
		componentName: 'BookWithBookmarkIcon',
		package: '@atlaskit/icon/core/book-with-bookmark',
		oldName: ['book'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: knowledge bases, articles, and other representations of books or info.',
		team: 'ADS',
	},
	branch: {
		keywords: ['branch', 'icon', 'core', 'git branch', 'bitbucket branch', 'branches'],
		componentName: 'BranchIcon',
		package: '@atlaskit/icon/core/branch',
		oldName: ['bitbucket/branches'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for branches in Bitbucket and Jira',
		team: 'Jira',
	},
	briefcase: {
		keywords: ['briefcase', 'icon', 'core', 'suitcase', 'toolbox', 'operations', 'business'],
		componentName: 'BriefcaseIcon',
		package: '@atlaskit/icon/core/briefcase',
		oldName: ['suitcase'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: Job title in Atlas, Operations in JSM.',
		team: 'Atlas',
	},
	bug: {
		keywords: ['bug', 'icon', 'core', 'bug report', 'test'],
		componentName: 'BugIcon',
		package: '@atlaskit/icon/core/bug',
		oldName: ['jira/test-session'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: Request types in JSM, bugs in Jira.',
		team: 'Jira',
	},
	'bulleted-list': {
		keywords: ['bulleted-list', 'bulletedlist', 'icon', 'core', 'bullets', 'unordered list'],
		componentName: 'BulletedListIcon',
		package: '@atlaskit/icon/core/bulleted-list',
		oldName: ['bullet-list', 'editor/bullet-list'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: bulleted lists, view all.',
		team: 'Editor',
	},
	calendar: {
		keywords: ['calendar', 'date', 'icon', 'core', 'date', 'month', 'day', 'year'],
		componentName: 'CalendarIcon',
		package: '@atlaskit/icon/core/calendar',
		oldName: ['calendar-filled', 'calendar', 'editor/date'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: date metadata, date input field, calendar view.',
		team: 'ADS',
	},
	camera: {
		keywords: ['camera', 'photo', 'icon', 'core'],
		componentName: 'CameraIcon',
		package: '@atlaskit/icon/core/camera',
		oldName: ['camera-filled', 'camera', 'editor/photo'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: upload photo in Trello, photos.',
		team: 'Media',
	},
	capture: {
		keywords: ['capture', 'icon', 'core'],
		componentName: 'CaptureIcon',
		package: '@atlaskit/icon/core/capture',
		oldName: ['jira/capture'],
		type: 'core',
		categorization: 'multi-purpose',
		team: 'Media',
	},
	changes: {
		keywords: ['changes', 'icon', 'core', 'horizontal arrows'],
		componentName: 'ChangesIcon',
		package: '@atlaskit/icon/core/changes',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for changes in Jira.',
		team: 'Jira',
	},
	'chart-bar': {
		keywords: ['chart-bar', 'chartbar', 'icon', 'core', 'graph', 'bar', 'analytics', 'report'],
		componentName: 'ChartBarIcon',
		package: '@atlaskit/icon/core/chart-bar',
		oldName: ['graph-bar', 'media-services/presentation'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: Reports in JSM, Space Analytics in Confluence, and other graph charts.',
		team: 'Analytics',
	},
	'chart-matrix': {
		keywords: ['chart-matrix', 'chartmatrix', 'icon', 'core', 'dot chart', 'graph', 'matrix'],
		componentName: 'ChartMatrixIcon',
		package: '@atlaskit/icon/core/chart-matrix',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: Matrix view in in JPD, and other matrix charts.',
		team: 'Analytics',
	},
	'chart-pie': {
		keywords: ['chart-pie', 'chartpie', 'icon', 'core', 'segment', 'chart', 'graph', 'pie'],
		componentName: 'ChartPieIcon',
		package: '@atlaskit/icon/core/chart-pie',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: pie charts.',
		team: 'Analytics',
	},
	'chart-trend': {
		keywords: ['chart-trend', 'charttrend', 'icon', 'core', 'reports', 'graph', 'impact effort'],
		componentName: 'ChartTrendIcon',
		package: '@atlaskit/icon/core/chart-trend',
		oldName: ['graph-line'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: charts, reports in Jira, and sprint insights.',
		team: 'Analytics',
	},
	'check-circle': {
		keywords: [
			'check-circle',
			'checkcircle',
			'tick',
			'icon',
			'core',
			'tick',
			'yes',
			'success',
			'filled',
		],
		componentName: 'CheckCircleIcon',
		package: '@atlaskit/icon/core/check-circle',
		oldName: ['check-circle', 'editor/success'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: success section messages or a list of done items.',
		team: 'ADS',
	},
	'check-mark': {
		keywords: ['check-mark', 'checkmark', 'icon', 'core', 'tick'],
		componentName: 'CheckMarkIcon',
		package: '@atlaskit/icon/core/check-mark',
		oldName: ['check', 'editor/done'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: table cells, checkboxes.',
		team: 'ADS',
	},
	'checkbox-checked': {
		keywords: [
			'checkbox-checked',
			'checkboxchecked',
			'icon',
			'core',
			'filled',
			'checked',
			'select all',
		],
		componentName: 'CheckboxCheckedIcon',
		package: '@atlaskit/icon/core/checkbox-checked',
		oldName: ['checkbox', 'editor/task'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Reserved for interactive checkbox experiences. Consider using the checkbox component.',
		team: 'ADS',
	},
	'checkbox-indeterminate': {
		keywords: [
			'checkbox-indeterminate',
			'checkboxindeterminate',
			'icon',
			'core',
			'filled',
			'mixed',
		],
		componentName: 'CheckboxIndeterminateIcon',
		package: '@atlaskit/icon/core/checkbox-indeterminate',
		oldName: ['checkbox-indeterminate'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Reserved for interactive checkbox experiences. Consider using the checkbox component.',
		team: 'ADS',
	},
	'checkbox-unchecked': {
		keywords: ['checkbox-unchecked', 'checkboxunchecked', 'icon', 'core', 'unchecked'],
		componentName: 'CheckboxUncheckedIcon',
		package: '@atlaskit/icon/core/checkbox-unchecked',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Reserved for interactive checkbox experiences. Consider using the checkbox component.',
		team: 'ADS',
	},
	'child-issues': {
		keywords: ['child-issues', 'childissues', 'icon', 'core'],
		componentName: 'ChildIssuesIcon',
		package: '@atlaskit/icon/core/child-issues',
		oldName: ['child-issues'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for child issues in Jira.',
		team: 'Jira',
	},
	clock: {
		keywords: ['clock', 'icon', 'core', 'time', 'recent', 'history'],
		componentName: 'ClockIcon',
		package: '@atlaskit/icon/core/clock',
		oldName: ['editor/recent', 'emoji/frequent', 'recent'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: recent, time input, sprint time remaining.',
		team: 'ADS',
	},
	close: {
		keywords: ['close', 'icon', 'core', 'cross', 'x'],
		componentName: 'CloseIcon',
		package: '@atlaskit/icon/core/close',
		oldName: ['cross', 'editor/close'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for closing an element.',
		team: 'ADS',
	},
	'cloud-arrow-up': {
		keywords: ['cloud-arrow-up', 'cloudarrowup', 'icon', 'core', 'deployments', 'up arrow'],
		componentName: 'CloudArrowUpIcon',
		package: '@atlaskit/icon/core/cloud-arrow-up',
		oldName: ['upload'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: deployments in Jira.',
		team: 'ADS',
	},
	collapse: {
		keywords: ['collapse', 'icon', 'core', 'contract', 'width', 'horizontal arrows'],
		componentName: 'CollapseIcon',
		package: '@atlaskit/icon/core/collapse',
		oldName: ['editor/collapse'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for contracting or reducing the width of an element.',
		team: 'Editor',
	},
	comment: {
		keywords: ['comment', 'chat', 'speech', 'icon', 'core', 'speech bubble'],
		componentName: 'CommentIcon',
		package: '@atlaskit/icon/core/comment',
		oldName: ['comment', 'questions'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for comments on objects.',
		team: 'ADS',
	},
	'comment-add': {
		keywords: ['comment-add', 'commentadd', 'icon', 'core', 'speech bubble', 'plus'],
		componentName: 'CommentAddIcon',
		package: '@atlaskit/icon/core/comment-add',
		oldName: ['media-services/add-comment'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for adding a comment to an object.',
		team: 'ADS',
	},
	commit: {
		keywords: ['commit', 'icon', 'core', 'git commit', 'bitbucket commit'],
		componentName: 'CommitIcon',
		package: '@atlaskit/icon/core/commit',
		oldName: ['bitbucket/commits'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for commits in Jira or Bitbucket.',
		team: 'Jira',
	},
	compass: {
		keywords: ['compass', 'icon', 'core', 'template'],
		componentName: 'CompassIcon',
		package: '@atlaskit/icon/core/compass',
		oldName: ['discover-filled', 'discover'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: templates.',
		team: 'ADS',
	},
	component: {
		keywords: ['component', 'block', 'lego', 'icon', 'core', 'lego', 'brick', 'block'],
		componentName: 'ComponentIcon',
		package: '@atlaskit/icon/core/component',
		oldName: ['component'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for components in Jira and Compass.',
		team: 'ADS',
	},
	copy: {
		keywords: ['copy', 'duplicate', 'icon', 'core', 'copy', 'object'],
		componentName: 'CopyIcon',
		package: '@atlaskit/icon/core/copy',
		oldName: ['copy'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for copying data such as text, code or other objects.',
		team: 'ADS',
	},
	'credit-card': {
		keywords: ['credit-card', 'creditcard', 'icon', 'core', 'payment', 'invoice'],
		componentName: 'CreditCardIcon',
		package: '@atlaskit/icon/core/credit-card',
		oldName: ['creditcard-filled', 'creditcard'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: billing in Admin, invoices in PPC, payments.',
		team: 'ADS',
	},
	'cross-circle': {
		keywords: [
			'cross-circle',
			'crosscircle',
			'close',
			'x',
			'cancel',
			'icon',
			'core',
			'x',
			'exit',
			'clear',
			'no',
			'filled',
		],
		componentName: 'CrossCircleIcon',
		package: '@atlaskit/icon/core/cross-circle',
		oldName: ['cross-circle', 'editor/error', 'select-clear'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: clear text field, error status icon.',
		team: 'ADS',
	},
	customize: {
		keywords: [
			'customize',
			'icon',
			'core',
			'customise',
			'configure',
			'modify',
			'preferences',
			'settings',
			'sliders',
		],
		componentName: 'CustomizeIcon',
		package: '@atlaskit/icon/core/customize',
		oldName: ['preferences'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: modify a sidebar order, change view, settings.',
		team: 'ADS',
	},
	dashboard: {
		keywords: ['dashboard', 'window', 'grid', 'icon', 'core', 'activity', 'view'],
		componentName: 'DashboardIcon',
		package: '@atlaskit/icon/core/dashboard',
		oldName: ['activity', 'dashboard'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for dashboards in Jira.',
		team: 'ADS',
	},
	database: {
		keywords: ['database', 'icon', 'core', 'spreadsheet', 'table', 'data', 'cells'],
		componentName: 'DatabaseIcon',
		package: '@atlaskit/icon/core/database',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for databases in Confluence.',
		team: 'ADS',
	},
	decision: {
		keywords: ['decision', 'icon', 'core', 'fork', 'diagonal arrow'],
		componentName: 'DecisionIcon',
		package: '@atlaskit/icon/core/decision',
		oldName: ['decision', 'editor/decision'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for decisions.',
		team: 'ADS',
	},
	delete: {
		keywords: ['delete', 'icon', 'core', 'trash', 'bin', 'remove'],
		componentName: 'DeleteIcon',
		package: '@atlaskit/icon/core/delete',
		oldName: ['editor/remove', 'trash'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for removing or deleting an object.',
		team: 'ADS',
	},
	department: {
		keywords: [
			'department',
			'icon',
			'core',
			'organization',
			'organisation',
			'org chart',
			'hierarchy',
		],
		componentName: 'DepartmentIcon',
		package: '@atlaskit/icon/core/department',
		oldName: ['department'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for departments, reporting lines, or other tree chart representations.',
		team: 'Atlas',
	},
	'device-mobile': {
		keywords: [
			'device-mobile',
			'devicemobile',
			'icon',
			'core',
			'iphone',
			'mobile phone',
			'cell phone',
		],
		componentName: 'DeviceMobileIcon',
		package: '@atlaskit/icon/core/device-mobile',
		oldName: ['mobile'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: call, contact us.',
		team: 'ADS',
	},
	download: {
		keywords: ['download', 'cloud', 'icon', 'core', 'down arrow', 'file download'],
		componentName: 'DownloadIcon',
		package: '@atlaskit/icon/core/download',
		oldName: ['download'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for file downloads.',
		team: 'ADS',
	},
	'drag-handle': {
		keywords: [
			'drag-handle',
			'draghandle',
			'icon',
			'core',
			'drag handler',
			'drag dots',
			'reorder',
			'move',
		],
		componentName: 'DragHandleIcon',
		package: '@atlaskit/icon/core/drag-handle',
		oldName: ['drag-handler'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for draggable elements.',
		team: 'ADS',
	},
	edit: {
		keywords: ['edit', 'pencil', 'write', 'icon', 'core', 'pencil', 'pencil on page'],
		componentName: 'EditIcon',
		package: '@atlaskit/icon/core/edit',
		oldName: ['edit-filled', 'edit', 'editor/edit'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for editing objects.',
		team: 'ADS',
	},
	email: {
		keywords: ['email', 'icon', 'core', 'envelope', 'message'],
		componentName: 'EmailIcon',
		package: '@atlaskit/icon/core/email',
		oldName: ['email'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for when an email-related things.',
		team: 'ADS',
	},
	emoji: {
		keywords: ['emoji', 'emoticon', 'smiley', 'icon', 'core', 'smiley face', 'emoticon'],
		componentName: 'EmojiIcon',
		package: '@atlaskit/icon/core/emoji',
		oldName: ['editor/emoji', 'emoji/emoji', 'emoji', 'emoji/people'],
		type: 'core',
		categorization: 'single-purpose',
		usage: "Reserved for Editor as a category for Emoji's.",
		team: 'Editor',
	},
	'emoji-add': {
		keywords: ['emoji-add', 'emojiadd', 'icon', 'core', 'smiley face', 'emoticon', 'plus'],
		componentName: 'EmojiAddIcon',
		package: '@atlaskit/icon/core/emoji-add',
		oldName: ['emoji-add'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for adding an emoji reaction.',
		team: 'Editor',
	},
	epic: {
		keywords: ['epic', 'icon', 'core', 'lightning bolt', 'filled'],
		componentName: 'EpicIcon',
		package: '@atlaskit/icon/core/epic',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for epics in Jira.',
		team: 'Jira',
	},
	error: {
		keywords: ['error', 'warning', 'alert', 'icon', 'core', 'filled', 'status'],
		componentName: 'ErrorIcon',
		package: '@atlaskit/icon/core/error',
		oldName: ['error'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for when there is an error.',
		team: 'ADS',
	},
	expand: {
		keywords: ['expand', 'icon', 'core', 'diagonal', 'resize'],
		componentName: 'ExpandIcon',
		package: '@atlaskit/icon/core/expand',
		oldName: ['editor/expand', 'editor/image-resize', 'image-resize'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for expanding a object or panel.',
		team: 'ADS',
	},
	'eye-open': {
		keywords: [
			'eye-open',
			'eyeopen',
			'icon',
			'core',
			'watch',
			'visible',
			'visbility',
			'permissions',
		],
		componentName: 'EyeOpenIcon',
		package: '@atlaskit/icon/core/eye-open',
		oldName: ['watch'],
		type: 'core',
		categorization: 'multi-purpose',
		usage:
			'Known uses: watch page in Confluence, show password in text field, and following in Atlas.',
		team: 'ADS',
	},
	'eye-open-filled': {
		keywords: [
			'eye-open-filled',
			'eyeopenfilled',
			'icon',
			'core',
			'watching',
			'visible',
			'visbility',
			'permissions',
			'filled',
		],
		componentName: 'EyeOpenFilledIcon',
		package: '@atlaskit/icon/core/eye-open-filled',
		oldName: ['hipchat/audio-only', 'watch-filled'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: watched pages in Confluence.',
		team: 'ADS',
	},
	feed: {
		keywords: ['feed', 'icon', 'core', 'feed', 'updates', 'release notes', "what's new"],
		componentName: 'FeedIcon',
		package: '@atlaskit/icon/core/feed',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for update feeds in Atlassian Home.',
		team: 'Atlas',
	},
	feedback: {
		keywords: [
			'feedback',
			'announce',
			'speaker',
			'megaphone',
			'icon',
			'core',
			'diagonal arrow',
			'chat bubble',
		],
		componentName: 'FeedbackIcon',
		package: '@atlaskit/icon/core/feedback',
		oldName: ['editor/feedback', 'feedback'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: customer feedback.',
		team: 'ADS',
	},
	filter: {
		keywords: ['filter', 'icon', 'core', 'funnel', 'refine'],
		componentName: 'FilterIcon',
		package: '@atlaskit/icon/core/filter',
		oldName: ['filter', 'media-services/filter'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for filterting data or objects.',
		team: 'ADS',
	},
	flag: {
		keywords: ['flag', 'icon', 'core', 'important', 'emoji category'],
		componentName: 'FlagIcon',
		package: '@atlaskit/icon/core/flag',
		oldName: ['emoji/flags'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: flags in Editor, feature flags.',
		team: 'Editor',
	},
	flask: {
		keywords: ['flask', 'icon', 'core', 'labs', 'test', 'erlenmeyer flask', 'beaker'],
		componentName: 'FlaskIcon',
		package: '@atlaskit/icon/core/flask',
		oldName: ['jira/labs'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: labs in Jira.',
		team: 'Jira',
	},
	'folder-closed': {
		keywords: ['folder-closed', 'folderclosed', 'icon', 'core', 'directory'],
		componentName: 'FolderClosedIcon',
		package: '@atlaskit/icon/core/folder-closed',
		oldName: ['folder'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for folders in Confluence.',
		team: 'ADS',
	},
	'folder-open': {
		keywords: ['folder-open', 'folderopen', 'icon', 'core', 'directory'],
		componentName: 'FolderOpenIcon',
		package: '@atlaskit/icon/core/folder-open',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for open folders in Confluence.',
		team: 'ADS',
	},
	'fullscreen-enter': {
		keywords: ['fullscreen-enter', 'fullscreenenter', 'icon', 'core', 'full screen'],
		componentName: 'FullscreenEnterIcon',
		package: '@atlaskit/icon/core/fullscreen-enter',
		oldName: ['vid-full-screen-on'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for full screen videos or objects.',
		team: 'Media',
	},
	'fullscreen-exit': {
		keywords: [
			'fullscreen-exit',
			'fullscreenexit',
			'icon',
			'core',
			'un-full screen',
			'un-fullscreen',
		],
		componentName: 'FullscreenExitIcon',
		package: '@atlaskit/icon/core/fullscreen-exit',
		oldName: ['media-services/full-screen', 'vid-full-screen-off'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for return screen videos or objects.',
		team: 'Media',
	},
	globe: {
		keywords: ['globe', 'icon', 'core', 'world'],
		componentName: 'GlobeIcon',
		package: '@atlaskit/icon/core/globe',
		oldName: ['world', 'world-small'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: public link in Confluence share dialog, global rules in Automation.',
		team: 'ADS',
	},
	goal: {
		keywords: ['goal', 'icon', 'core', 'target'],
		componentName: 'GoalIcon',
		package: '@atlaskit/icon/core/goal',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for goals in Atlas.',
		team: 'Atlas',
	},
	grid: {
		keywords: ['grid', 'icon', 'core', 'view all content', 'tile view', 'layout', 'grid', 'tiles'],
		componentName: 'GridIcon',
		package: '@atlaskit/icon/core/grid',
		oldName: ['editor/table', 'media-services/grid', 'table'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: spaces in Confluence, and grid view, all content in Confluence.',
		team: 'ADS',
	},
	hashtag: {
		keywords: ['hashtag', 'icon', 'core', 'tag', 'topic', 'pound'],
		componentName: 'HashtagIcon',
		package: '@atlaskit/icon/core/hashtag',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: topics in Atlas, tags.',
		team: 'ADS',
	},
	heart: {
		keywords: ['heart', 'icon', 'core', 'like', 'love', 'emoji category'],
		componentName: 'HeartIcon',
		package: '@atlaskit/icon/core/heart',
		oldName: ['emoji/symbols'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: emoji symbols in Editor.',
		team: 'Editor',
	},
	home: {
		keywords: ['home', 'icon', 'core', 'house', 'building'],
		componentName: 'HomeIcon',
		package: '@atlaskit/icon/core/home',
		oldName: ['home-circle', 'home'],
		type: 'core',
		categorization: 'single-purpose',
		usage:
			'Reserved for home in navigation. When a user clicks on this, they should return to the homepage.',
		team: 'ADS',
	},
	image: {
		keywords: ['image', 'picture', 'photo', 'icon', 'core', 'picture', 'asset'],
		componentName: 'ImageIcon',
		package: '@atlaskit/icon/core/image',
		oldName: [
			'editor/image',
			'image',
			'media-services/image',
			'media-services/scale-large',
			'media-services/scale-small',
		],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: images, image upload.',
		team: 'ADS',
	},
	inbox: {
		keywords: ['inbox', 'icon', 'core', 'document tray', 'work', 'letter', 'post'],
		componentName: 'InboxIcon',
		package: '@atlaskit/icon/core/inbox',
		oldName: ['tray'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: "Known uses: 'Your work' in Confluence, inbox, mail.",
		team: 'Unknown',
	},
	incident: {
		keywords: ['incident', 'icon', 'core', 'witches hat', 'traffic cone'],
		componentName: 'IncidentIcon',
		package: '@atlaskit/icon/core/incident',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for incidents in Jira.',
		team: 'Jira',
	},
	information: {
		keywords: ['information', 'icon', 'core', 'info', 'filled', 'helper', 'tip'],
		componentName: 'InformationIcon',
		package: '@atlaskit/icon/core/information',
		oldName: ['editor/info', 'editor/panel', 'info'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Known uses: helper message under textfield, information state insection messages.',
		team: 'ADS',
	},
	issue: {
		keywords: ['issue', 'tick', 'check', 'confirm', 'task', 'icon', 'core'],
		componentName: 'IssueIcon',
		package: '@atlaskit/icon/core/issue',
		oldName: ['issue'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for issues in Jira.',
		team: 'Jira',
	},
	issues: {
		keywords: ['issues', 'tick', 'check', 'confirm', 'task', 'icon', 'core', 'multiple issues'],
		componentName: 'IssuesIcon',
		package: '@atlaskit/icon/core/issues',
		oldName: ['issues'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for multiple issues in Jira.',
		team: 'Jira',
	},
	lightbulb: {
		keywords: [
			'lightbulb',
			'idea',
			'hint',
			'icon',
			'core',
			'idea',
			'initiative',
			'tip',
			'learnings',
		],
		componentName: 'LightbulbIcon',
		package: '@atlaskit/icon/core/lightbulb',
		oldName: ['editor/hint', 'emoji/objects', 'lightbulb-filled', 'lightbulb'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: learnings in Atlas, initiatives in Jira.',
		team: 'ADS',
	},
	link: {
		keywords: ['link', 'icon', 'core', 'url', 'hyperlink', 'website', 'www', 'http'],
		componentName: 'LinkIcon',
		package: '@atlaskit/icon/core/link',
		oldName: ['editor/link', 'link-filled', 'link'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for links, urls, or copy link.',
		team: 'ADS',
	},
	'link-broken': {
		keywords: [
			'link-broken',
			'linkbroken',
			'icon',
			'core',
			'unlink',
			'remove link',
			'break link',
			'url',
			'hyperlink',
			'website',
			'www',
			'https',
		],
		componentName: 'LinkBrokenIcon',
		package: '@atlaskit/icon/core/link-broken',
		oldName: ['editor/unlink', 'unlink'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for removing a link.',
		team: 'ADS',
	},
	'link-external': {
		keywords: [
			'link-external',
			'linkexternal',
			'icon',
			'core',
			'new tab',
			'new window',
			'open in',
			'url',
			'hyperlink',
			'www',
			'http',
			'https',
			'website',
			'external',
			'shortcut',
			'diagonal arrow',
		],
		componentName: 'LinkExternalIcon',
		package: '@atlaskit/icon/core/link-external',
		oldName: ['shortcut'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for links that open up a new tab.',
		team: 'ADS',
	},
	'lobby-bell': {
		keywords: ['lobby-bell', 'lobbybell', 'icon', 'core', 'ding', 'risks'],
		componentName: 'LobbyBellIcon',
		package: '@atlaskit/icon/core/lobby-bell',
		oldName: ['hipchat/lobby'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: risks in Atlas.',
		team: 'Editor',
	},
	location: {
		keywords: ['location', 'pin', 'gps', 'map', 'icon', 'core', 'map', 'pin', 'address'],
		componentName: 'LocationIcon',
		package: '@atlaskit/icon/core/location',
		oldName: ['location'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: location in Atlas.',
		team: 'ADS',
	},
	'lock-locked': {
		keywords: [
			'lock-locked',
			'locklocked',
			'icon',
			'core',
			'permissions',
			'no access',
			'restricted',
			'security',
			'secure',
			'forbidden',
			'authentication',
		],
		componentName: 'LockLockedIcon',
		package: '@atlaskit/icon/core/lock-locked',
		oldName: ['lock-circle', 'lock-filled', 'lock', 'unlock-circle'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: secure password in textfields, locked page in Confluence.',
		team: 'ADS',
	},
	'lock-unlocked': {
		keywords: [
			'lock-unlocked',
			'lockunlocked',
			'icon',
			'core',
			'open permissions',
			'unrestricted access',
			'security',
			'insecure',
			'authentication',
		],
		componentName: 'LockUnlockedIcon',
		package: '@atlaskit/icon/core/lock-unlocked',
		oldName: ['unlock-filled', 'unlock'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: unlocked page in Confluence.',
		team: 'ADS',
	},
	'log-in': {
		keywords: ['log-in', 'login', 'icon', 'core', 'sign in', 'enter', 'account'],
		componentName: 'LogInIcon',
		package: '@atlaskit/icon/core/log-in',
		oldName: ['sign-in'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for login.',
		team: 'ADS',
	},
	'log-out': {
		keywords: ['log-out', 'logout', 'icon', 'core', 'sign out', 'exit', 'account'],
		componentName: 'LogOutIcon',
		package: '@atlaskit/icon/core/log-out',
		oldName: ['sign-out'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for logout.',
		team: 'ADS',
	},
	marketplace: {
		keywords: [
			'marketplace',
			'store',
			'shop',
			'icon',
			'core',
			'app store',
			'storefront',
			'stand',
			'third-party developer',
		],
		componentName: 'MarketplaceIcon',
		package: '@atlaskit/icon/core/marketplace',
		oldName: ['marketplace'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for Atlassian Marketplace.',
		team: 'ADS',
	},
	maximize: {
		keywords: ['maximize', 'icon', 'core', 'resize', 'diagonal arrows', 'bigger'],
		componentName: 'MaximizeIcon',
		package: '@atlaskit/icon/core/maximize',
		oldName: ['media-services/actual-size'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for maximizing screens, panels, or objects.',
		team: 'Media',
	},
	megaphone: {
		keywords: ['megaphone', 'icon', 'core', 'announcement', 'bullhorn', 'feedback', 'news'],
		componentName: 'MegaphoneIcon',
		package: '@atlaskit/icon/core/megaphone',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: feedback in products.',
		team: 'ADS',
	},
	mention: {
		keywords: [
			'mention',
			'user',
			'person',
			'@',
			'icon',
			'core',
			'at symbol',
			'@',
			'tag',
			'username',
		],
		componentName: 'MentionIcon',
		package: '@atlaskit/icon/core/mention',
		oldName: ['editor/mention'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for user mentions.',
		team: 'Editor',
	},
	menu: {
		keywords: [
			'menu',
			'hamburger',
			'navigation',
			'switcher',
			'app switcher',
			'icon',
			'core',
			'menu',
			'top navigation',
			'3 lines',
			'hamburger',
		],
		componentName: 'MenuIcon',
		package: '@atlaskit/icon/core/menu',
		oldName: ['menu-expand', 'menu'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for accessing the menu in global product navigation.',
		team: 'ADS',
	},
	microphone: {
		keywords: ['microphone', 'icon', 'core', 'mic', 'mic on', 'voice', 'speak'],
		componentName: 'MicrophoneIcon',
		package: '@atlaskit/icon/core/microphone',
		oldName: ['vid-audio-on'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: record sounds in Trello.',
		team: 'Media',
	},
	minimize: {
		keywords: ['minimize', 'icon', 'core', 'minimise', 'resize', 'diagonal arrows'],
		componentName: 'MinimizeIcon',
		package: '@atlaskit/icon/core/minimize',
		oldName: ['media-services/fit-to-page', 'vid-full-screen-off'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Known uses: minimize modal window, minimize panel, minimize video screen.',
		team: 'ADS',
	},
	node: {
		keywords: ['node', 'icon', 'core', 'page', 'dot', 'page tree', 'navigation'],
		componentName: 'NodeIcon',
		package: '@atlaskit/icon/core/node',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for a non-expandable item in a page tree.',
		team: 'Confluence',
	},
	notification: {
		keywords: ['notification', 'bell', 'alarm', 'icon', 'core', 'bell', 'alert', 'top navigation'],
		componentName: 'NotificationIcon',
		package: '@atlaskit/icon/core/notification',
		oldName: ['notification-direct', 'notification'],
		type: 'core',
		categorization: 'single-purpose',
		usage:
			'Reserved for notifications within global product navigation and within product screens.',
		team: 'ADS',
	},
	'office-building': {
		keywords: [
			'office-building',
			'officebuilding',
			'icon',
			'core',
			'organization',
			'organisation',
			'business',
		],
		componentName: 'OfficeBuildingIcon',
		package: '@atlaskit/icon/core/office-building',
		oldName: ['office-building-filled', 'office-building'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: office in Atlas, company.',
		team: 'ADS',
	},
	page: {
		keywords: ['page', 'file', 'document', 'icon', 'core', 'feed', 'document'],
		componentName: 'PageIcon',
		package: '@atlaskit/icon/core/page',
		oldName: [
			'document-filled',
			'document',
			'editor/note',
			'media-services/document',
			'page-filled',
			'page',
		],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for pages in Confluence.',
		team: 'ADS',
	},
	pages: {
		keywords: ['pages', 'icon', 'core', 'feeds', 'documents'],
		componentName: 'PagesIcon',
		package: '@atlaskit/icon/core/pages',
		oldName: ['documents', 'queues'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for multipe pages in Confluence.',
		team: 'ADS',
	},
	person: {
		keywords: ['person', 'person', 'user', 'avatar', 'icon', 'core', 'user', 'customer'],
		componentName: 'PersonIcon',
		package: '@atlaskit/icon/core/person',
		oldName: ['person'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Known uses: representing a person or user, owner, contributor.',
		team: 'ADS',
	},
	'person-add': {
		keywords: ['person-add', 'personadd', 'icon', 'core', 'user', 'customer', 'plus'],
		componentName: 'PersonAddIcon',
		package: '@atlaskit/icon/core/person-add',
		oldName: ['invite-team'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for adding a user to an object.',
		team: 'ADS',
	},
	'person-added': {
		keywords: ['person-added', 'personadded', 'icon', 'core', 'user', 'customer', 'check', 'tick'],
		componentName: 'PersonAddedIcon',
		package: '@atlaskit/icon/core/person-added',
		oldName: ['app-access', 'person-with-tick'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for a user added to an object.',
		team: 'ADS',
	},
	'person-avatar': {
		keywords: ['person-avatar', 'personavatar', 'icon', 'core', 'user', 'customer'],
		componentName: 'PersonAvatarIcon',
		package: '@atlaskit/icon/core/person-avatar',
		oldName: ['person-circle', 'user-avatar-circle'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for user avatar.',
		team: 'ADS',
	},
	'person-offboard': {
		keywords: [
			'person-offboard',
			'personoffboard',
			'icon',
			'core',
			'user',
			'customer',
			'right arrow',
		],
		componentName: 'PersonOffboardIcon',
		package: '@atlaskit/icon/core/person-offboard',
		oldName: ['followers'],
		type: 'core',
		categorization: 'single-purpose',
		team: 'ADS',
	},
	phone: {
		keywords: ['phone', 'icon', 'core', 'call', 'dial out'],
		componentName: 'PhoneIcon',
		package: '@atlaskit/icon/core/phone',
		oldName: ['hipchat/dial-out'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: call us, phone number input.',
		team: 'Media',
	},
	pin: {
		keywords: ['pin', 'icon', 'core', 'push pin', 'thumbtack', 'tack'],
		componentName: 'PinIcon',
		package: '@atlaskit/icon/core/pin',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: pinning Jira issue fields.',
		team: 'ADS',
	},
	'pin-filled': {
		keywords: [
			'pin-filled',
			'pinfilled',
			'icon',
			'core',
			'push pin',
			'thumbtack',
			'tack',
			'filled',
		],
		componentName: 'PinFilledIcon',
		package: '@atlaskit/icon/core/pin-filled',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: pinned Jira issue fields.',
		team: 'ADS',
	},
	'power-plug': {
		keywords: ['power-plug', 'powerplug', 'icon', 'core', 'plug-in', 'add-on', 'socket'],
		componentName: 'PowerPlugIcon',
		package: '@atlaskit/icon/core/power-plug',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: plugins, add ons.',
		team: 'Unknown',
	},
	premium: {
		keywords: ['premium', 'icon', 'core', 'AI', 'sparkles', 'stars', 'new', 'feature'],
		componentName: 'PremiumIcon',
		package: '@atlaskit/icon/core/premium',
		oldName: ['premium'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for premium features.',
		team: 'Growth',
	},
	'presenter-mode': {
		keywords: [
			'presenter-mode',
			'presentermode',
			'icon',
			'core',
			'pointer',
			'cursor',
			'presentation',
			'present',
		],
		componentName: 'PresenterModeIcon',
		package: '@atlaskit/icon/core/presenter-mode',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for presenter mode in Confluence.',
		team: 'Confluence',
	},
	printer: {
		keywords: ['printer', 'icon', 'core', 'print'],
		componentName: 'PrinterIcon',
		package: '@atlaskit/icon/core/printer',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: print page, print-friendly view.',
		team: 'ADS',
	},
	'priority-blocker': {
		keywords: ['priority-blocker', 'priorityblocker', 'icon', 'core', 'blocked', 'showstopper'],
		componentName: 'PriorityBlockerIcon',
		package: '@atlaskit/icon/core/priority-blocker',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for blocker issue priority.',
		team: 'Jira',
	},
	'priority-critical': {
		keywords: ['priority-critical', 'prioritycritical', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityCriticalIcon',
		package: '@atlaskit/icon/core/priority-critical',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for critial issue priority.',
		team: 'Jira',
	},
	'priority-high': {
		keywords: ['priority-high', 'priorityhigh', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityHighIcon',
		package: '@atlaskit/icon/core/priority-high',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for high issue priority.',
		team: 'Jira',
	},
	'priority-highest': {
		keywords: ['priority-highest', 'priorityhighest', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityHighestIcon',
		package: '@atlaskit/icon/core/priority-highest',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for highest issue priority.',
		team: 'Jira',
	},
	'priority-low': {
		keywords: ['priority-low', 'prioritylow', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityLowIcon',
		package: '@atlaskit/icon/core/priority-low',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for low issue priority.',
		team: 'Jira',
	},
	'priority-lowest': {
		keywords: ['priority-lowest', 'prioritylowest', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityLowestIcon',
		package: '@atlaskit/icon/core/priority-lowest',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for lowest issue priority.',
		team: 'Jira',
	},
	'priority-major': {
		keywords: ['priority-major', 'prioritymajor', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityMajorIcon',
		package: '@atlaskit/icon/core/priority-major',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for major issue priority.',
		team: 'Jira',
	},
	'priority-medium': {
		keywords: ['priority-medium', 'prioritymedium', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityMediumIcon',
		package: '@atlaskit/icon/core/priority-medium',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for medium issue priority.',
		team: 'Jira',
	},
	'priority-minor': {
		keywords: ['priority-minor', 'priorityminor', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityMinorIcon',
		package: '@atlaskit/icon/core/priority-minor',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for minor issue priority.',
		team: 'Jira',
	},
	'priority-trivial': {
		keywords: ['priority-trivial', 'prioritytrivial', 'icon', 'core', 'issue', 'priority'],
		componentName: 'PriorityTrivialIcon',
		package: '@atlaskit/icon/core/priority-trivial',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for trivial issue priority.',
		team: 'Jira',
	},
	problem: {
		keywords: ['problem', 'icon', 'core', 'stop', 'issue', 'priority'],
		componentName: 'ProblemIcon',
		package: '@atlaskit/icon/core/problem',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for problem issue priority.',
		team: 'Jira',
	},
	project: {
		keywords: ['project', 'icon', 'core', 'rocket', 'rocketship', 'spaceship'],
		componentName: 'ProjectIcon',
		package: '@atlaskit/icon/core/project',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for projects in Jira.',
		team: 'Atlas',
	},
	'pull-request': {
		keywords: [
			'pull-request',
			'pullrequest',
			'icon',
			'core',
			'git pull request',
			'bitbucket pull request',
		],
		componentName: 'PullRequestIcon',
		package: '@atlaskit/icon/core/pull-request',
		oldName: ['bitbucket/pullrequests'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for pull requests in Jira or Bitbucket.',
		team: 'Jira',
	},
	'question-circle': {
		keywords: [
			'question-circle',
			'questioncircle',
			'help',
			'icon',
			'core',
			'help',
			'answers',
			'faq',
		],
		componentName: 'QuestionCircleIcon',
		package: '@atlaskit/icon/core/question-circle',
		oldName: ['editor/help', 'question-circle', 'question'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: help, tip.',
		team: 'Jira',
	},
	'quotation-mark': {
		keywords: [
			'quotation-mark',
			'quotationmark',
			'icon',
			'core',
			'quote',
			'testimonial',
			'blockquote',
		],
		componentName: 'QuotationMarkIcon',
		package: '@atlaskit/icon/core/quotation-mark',
		oldName: ['editor/quote', 'quote'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: blockquote, comment, testimonial, blogs in Confluence.',
		team: 'Jira',
	},
	redo: {
		keywords: ['redo', 'icon', 'core', 'editor', 'redo', 'backwards'],
		componentName: 'RedoIcon',
		package: '@atlaskit/icon/core/redo',
		oldName: ['editor/redo', 'redo'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for redo in Editor.',
		team: 'Media',
	},
	release: {
		keywords: ['release', 'icon', 'core', 'ship', 'boat'],
		componentName: 'ReleaseIcon',
		package: '@atlaskit/icon/core/release',
		oldName: ['ship'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for releases in Jira.',
		team: 'Jira',
	},
	retry: {
		keywords: ['retry', 'icon', 'core', 'try again'],
		componentName: 'RetryIcon',
		package: '@atlaskit/icon/core/retry',
		oldName: ['retry'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for retry.',
		team: 'ADS',
	},
	roadmap: {
		keywords: ['roadmap', 'icon', 'core'],
		componentName: 'RoadmapIcon',
		package: '@atlaskit/icon/core/roadmap',
		oldName: ['roadmap'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for roadmaps in Jira or Trello.',
		team: 'ADS',
	},
	scorecard: {
		keywords: ['scorecard', 'icon', 'core', 'tick', 'check', 'circle', 'unfinished'],
		componentName: 'ScorecardIcon',
		package: '@atlaskit/icon/core/scorecard',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for Scorecard in Analytics.',
		team: 'Analytics',
	},
	screen: {
		keywords: [
			'screen',
			'desktop',
			'computer',
			'monitor',
			'icon',
			'core',
			'display',
			'monitor',
			'desktop',
		],
		componentName: 'ScreenIcon',
		package: '@atlaskit/icon/core/screen',
		oldName: ['screen'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: assets in Jira.',
		team: 'ADS',
	},
	search: {
		keywords: ['search', 'find', 'magnify', 'icon', 'core', 'magnifying glass'],
		componentName: 'SearchIcon',
		package: '@atlaskit/icon/core/search',
		oldName: ['editor/search', 'search'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for searching objects.',
		team: 'ADS',
	},
	send: {
		keywords: ['send', 'mail', 'icon', 'core', 'submit', 'paper airplane', 'paper aeroplane'],
		componentName: 'SendIcon',
		package: '@atlaskit/icon/core/send',
		oldName: ['send'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for sending messages in Rovo Chat.',
		team: 'ADS',
	},
	settings: {
		keywords: [
			'settings',
			'cog',
			'options',
			'configuration',
			'icon',
			'core',
			'system preferences',
			'gear',
			'cog',
		],
		componentName: 'SettingsIcon',
		package: '@atlaskit/icon/core/settings',
		oldName: ['editor/settings', 'settings'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for any object or user settings.',
		team: 'ADS',
	},
	shapes: {
		keywords: ['shapes', 'icon', 'core', 'objects', 'whiteboard', 'asset', 'graphic'],
		componentName: 'ShapesIcon',
		package: '@atlaskit/icon/core/shapes',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for shapes in Whiteboards.',
		team: 'Whiteboards',
	},
	share: {
		keywords: ['share', 'icon', 'core', 'share', 'access'],
		componentName: 'ShareIcon',
		package: '@atlaskit/icon/core/share',
		oldName: ['share'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for sharing an object.',
		team: 'ADS',
	},
	shield: {
		keywords: [
			'shield',
			'icon',
			'core',
			'security',
			'secure',
			'safety',
			'defence',
			'protection',
			'guard',
		],
		componentName: 'ShieldIcon',
		package: '@atlaskit/icon/core/shield',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Reserved for classifications in Enterprise Trust.',
		team: 'Admin',
	},
	shortcut: {
		keywords: ['shortcut', 'export', 'icon', 'core', 'add shortcut', 'square', 'plus'],
		componentName: 'ShortcutIcon',
		package: '@atlaskit/icon/core/shortcut',
		oldName: ['add-item'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for shortcuts in Jira.',
		team: 'ADS',
	},
	'show-more-horizontal': {
		keywords: [
			'show-more-horizontal',
			'showmorehorizontal',
			'icon',
			'core',
			'ellipses',
			'three dots',
			'more actions',
		],
		componentName: 'ShowMoreHorizontalIcon',
		package: '@atlaskit/icon/core/show-more-horizontal',
		oldName: ['editor/more', 'more'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for more action menus.',
		team: 'ADS',
	},
	'show-more-vertical': {
		keywords: [
			'show-more-vertical',
			'showmorevertical',
			'icon',
			'core',
			'three dots',
			'more actions',
		],
		componentName: 'ShowMoreVerticalIcon',
		package: '@atlaskit/icon/core/show-more-vertical',
		oldName: ['more-vertical'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for more action menus, traditionally on mobile.',
		team: 'ADS',
	},
	'sidebar-collapse': {
		keywords: [
			'sidebar-collapse',
			'sidebarcollapse',
			'icon',
			'core',
			'navigation',
			'close sidebar',
		],
		componentName: 'SidebarCollapseIcon',
		package: '@atlaskit/icon/core/sidebar-collapse',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for collapsing the navigation sidebar.',
		team: 'ADS',
	},
	'sidebar-expand': {
		keywords: ['sidebar-expand', 'sidebarexpand', 'icon', 'core', 'navigation', 'open sidebar'],
		componentName: 'SidebarExpandIcon',
		package: '@atlaskit/icon/core/sidebar-expand',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for expanding the navigation sidebar.',
		team: 'ADS',
	},
	snippet: {
		keywords: ['snippet', 'icon', 'core', 'scissors', 'cut'],
		componentName: 'SnippetIcon',
		package: '@atlaskit/icon/core/snippet',
		oldName: ['bitbucket/snippets'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for snippets in Bitbucket.',
		team: 'BitBucket',
	},
	spreadsheet: {
		keywords: ['spreadsheet', 'icon', 'core', 'table', 'cells', 'data'],
		componentName: 'SpreadsheetIcon',
		package: '@atlaskit/icon/core/spreadsheet',
		oldName: ['media-services/spreadsheet'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for spreadsheets.',
		team: 'ADS',
	},
	sprint: {
		keywords: ['sprint', 'icon', 'core', 'loop', 'iterate'],
		componentName: 'SprintIcon',
		package: '@atlaskit/icon/core/sprint',
		oldName: ['sprint'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for sprints in Jira.',
		team: 'ADS',
	},
	'star-starred': {
		keywords: [
			'star-starred',
			'starstarred',
			'icon',
			'core',
			'favourite',
			'star',
			'starred',
			'filled',
		],
		componentName: 'StarStarredIcon',
		package: '@atlaskit/icon/core/star-starred',
		oldName: ['star-filled'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for starred or favourited objects.',
		team: 'ADS',
	},
	'star-unstarred': {
		keywords: ['star-unstarred', 'starunstarred', 'icon', 'core', 'favourite', 'star'],
		componentName: 'StarUnstarredIcon',
		package: '@atlaskit/icon/core/star-unstarred',
		oldName: ['star', 'star-large'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for starring or favoriting objects.',
		team: 'ADS',
	},
	stopwatch: {
		keywords: ['stopwatch', 'icon', 'core', 'timer'],
		componentName: 'StopwatchIcon',
		package: '@atlaskit/icon/core/stopwatch',
		oldName: ['stopwatch'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: timer in Confluence Whiteboards',
		team: 'ADS',
	},
	story: {
		keywords: ['story', 'icon', 'core', 'bookmark', 'issue'],
		componentName: 'StoryIcon',
		package: '@atlaskit/icon/core/story',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for stories in Jira.',
		team: 'Jira',
	},
	subtasks: {
		keywords: ['subtasks', 'icon', 'core', 'issue', 'todo', 'checklist'],
		componentName: 'SubtasksIcon',
		package: '@atlaskit/icon/core/subtasks',
		oldName: ['subtask'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for subtasks in Jira.',
		team: 'Jira',
	},
	tag: {
		keywords: ['tag', 'icon', 'core', 'label', 'topic'],
		componentName: 'TagIcon',
		package: '@atlaskit/icon/core/tag',
		oldName: ['label'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for tags in Atlas.',
		team: 'ADS',
	},
	task: {
		keywords: ['task', 'check', 'tick', 'icon', 'core', 'todo', 'list'],
		componentName: 'TaskIcon',
		package: '@atlaskit/icon/core/task',
		oldName: ['task'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for tasks in Jira.',
		team: 'Jira',
	},
	tasks: {
		keywords: ['tasks', 'icon', 'core', 'todo', 'list'],
		componentName: 'TasksIcon',
		package: '@atlaskit/icon/core/tasks',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for multiple tasks in Jira.',
		team: 'Jira',
	},
	teams: {
		keywords: ['teams', 'icon', 'core', 'infinite love', 'people', 'persons', 'customers', 'users'],
		componentName: 'TeamsIcon',
		package: '@atlaskit/icon/core/teams',
		oldName: ['teams'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for teams in Atlassian.',
		team: 'Atlas',
	},
	'text-style': {
		keywords: [
			'text-style',
			'textstyle',
			'icon',
			'core',
			'characters',
			'font',
			'letters',
			'type',
			'typography',
		],
		componentName: 'TextStyleIcon',
		package: '@atlaskit/icon/core/text-style',
		oldName: ['editor/text-style', 'emoji/keyboard'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for text styles in Editor.',
		team: 'Editor',
	},
	'thumbs-down': {
		keywords: [
			'thumbs-down',
			'thumbsdown',
			'icon',
			'core',
			'vote',
			'downvote',
			'dislike',
			'feedback',
			'hand',
		],
		componentName: 'ThumbsDownIcon',
		package: '@atlaskit/icon/core/thumbs-down',
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: voting, feedback in AI.',
		team: 'ADS',
	},
	'thumbs-up': {
		keywords: [
			'thumbs-up',
			'thumbsup',
			'icon',
			'core',
			'vote',
			'upvote',
			'like',
			'feedback',
			'hand',
		],
		componentName: 'ThumbsUpIcon',
		package: '@atlaskit/icon/core/thumbs-up',
		oldName: ['like'],
		type: 'core',
		categorization: 'multi-purpose',
		usage: 'Known uses: voting options in Jira, like',
		team: 'ADS',
	},
	timeline: {
		keywords: ['timeline', 'icon', 'core', 'gantt', 'calendar'],
		componentName: 'TimelineIcon',
		package: '@atlaskit/icon/core/timeline',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for timelines in Jira or Trello.',
		team: 'Jira',
	},
	transition: {
		keywords: ['transition', 'icon', 'core', 'connector', 'movement'],
		componentName: 'TransitionIcon',
		package: '@atlaskit/icon/core/transition',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for transitions in Analytics.',
		team: 'Automation',
	},
	undo: {
		keywords: ['undo', 'icon', 'core', 'backward', 'mistake', 'correct'],
		componentName: 'UndoIcon',
		package: '@atlaskit/icon/core/undo',
		oldName: ['editor/undo', 'undo'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for undo in Editor.',
		team: 'Editor',
	},
	upload: {
		keywords: ['upload', 'cloud', 'icon', 'core', 'stream', 'file'],
		componentName: 'UploadIcon',
		package: '@atlaskit/icon/core/upload',
		oldName: ['export'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for upload in Editor.',
		team: 'ADS',
	},
	video: {
		keywords: ['video', 'icon', 'core', 'media', 'movie'],
		componentName: 'VideoIcon',
		package: '@atlaskit/icon/core/video',
		oldName: [
			'media-services/video',
			'hipchat/sd-video',
			'vid-camera-on',
			'video-circle',
			'video-filled',
		],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for video in Media.',
		team: 'Media',
	},
	'video-next': {
		keywords: ['video-next', 'videonext', 'icon', 'core', 'skip', 'next', 'media', 'forward'],
		componentName: 'VideoNextIcon',
		package: '@atlaskit/icon/core/video-next',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for next video in Media.',
		team: 'Media',
	},
	'video-pause': {
		keywords: ['video-pause', 'videopause', 'icon', 'core', 'media', 'video'],
		componentName: 'VideoPauseIcon',
		package: '@atlaskit/icon/core/video-pause',
		oldName: ['vid-pause'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for pause video in Media.',
		team: 'Media',
	},
	'video-play': {
		keywords: ['video-play', 'videoplay', 'icon', 'core', 'media', 'video'],
		componentName: 'VideoPlayIcon',
		package: '@atlaskit/icon/core/video-play',
		oldName: ['vid-play'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for play video in Media.',
		team: 'Media',
	},
	'video-previous': {
		keywords: [
			'video-previous',
			'videoprevious',
			'icon',
			'core',
			'media',
			'video',
			'back',
			'previous',
		],
		componentName: 'VideoPreviousIcon',
		package: '@atlaskit/icon/core/video-previous',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for previous video in Media.',
		team: 'Media',
	},
	'volume-high': {
		keywords: ['volume-high', 'volumehigh', 'icon', 'core', 'louder', 'volume up'],
		componentName: 'VolumeHighIcon',
		package: '@atlaskit/icon/core/volume-high',
		oldName: ['hipchat/outgoing-sound', 'vid-volume-full'],
		type: 'core',
		categorization: 'multi-purpose',
		team: 'Media',
	},
	'volume-low': {
		keywords: ['volume-low', 'volumelow', 'icon', 'core', 'quiter', 'volume down'],
		componentName: 'VolumeLowIcon',
		package: '@atlaskit/icon/core/volume-low',
		oldName: ['vid-volume-half'],
		type: 'core',
		categorization: 'multi-purpose',
		team: 'Media',
	},
	'volume-muted': {
		keywords: ['volume-muted', 'volumemuted', 'icon', 'core', 'volume off', 'no volume'],
		componentName: 'VolumeMutedIcon',
		package: '@atlaskit/icon/core/volume-muted',
		oldName: ['vid-volume-muted'],
		type: 'core',
		categorization: 'multi-purpose',
		team: 'Media',
	},
	warning: {
		keywords: [
			'warning',
			'error',
			'alert',
			'icon',
			'core',
			'alert',
			'danger',
			'triangle',
			'filled',
		],
		componentName: 'WarningIcon',
		package: '@atlaskit/icon/core/warning',
		oldName: ['editor/warning', 'warning'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for warning system status.',
		team: 'ADS',
	},
	whiteboard: {
		keywords: ['whiteboard', 'icon', 'core', 'shapes', 'canvas'],
		componentName: 'WhiteboardIcon',
		package: '@atlaskit/icon/core/whiteboard',
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for whiteboards in Confluence.',
		team: 'Whiteboards',
	},
	'zoom-in': {
		keywords: ['zoom-in', 'zoomin', 'icon', 'core', 'magnify', 'magnifying glass'],
		componentName: 'ZoomInIcon',
		package: '@atlaskit/icon/core/zoom-in',
		oldName: ['media-services/zoom-in'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for zooming in of an object or view.',
		team: 'Media',
	},
	'zoom-out': {
		keywords: ['zoom-out', 'zoomout', 'icon', 'core', 'minify', 'magnifying glass'],
		componentName: 'ZoomOutIcon',
		package: '@atlaskit/icon/core/zoom-out',
		oldName: ['media-services/zoom-out'],
		type: 'core',
		categorization: 'single-purpose',
		usage: 'Reserved for zooming out of an object or view.',
		team: 'Media',
	},
};

export default metadata;
