/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//
export default {
  'fabric.reactions.error.unexpected':
    '⁣⁢Something went wrong⁯⁮⁭‍‌⁯؜؜⁮‌‌⁠⁫‍⁯⁪⁭⁮⁣⁤',
  'fabric.reactions.loading': '⁣⁢Loading...⁭⁫⁡⁬⁮⁭؜⁬⁫⁬⁪⁫⁯⁯؜؜⁪‌⁣⁤',
  'fabric.reactions.more.emoji': '⁣⁢More emoji‍⁯⁠⁭⁠⁡؜‌⁫⁫⁠⁫⁪⁭⁫⁯⁯⁮⁡⁫⁯⁬⁫⁮⁠⁣⁤',
  'fabric.reactions.other.reacted.users':
    '{count, plural, one {⁣⁢and one other⁫⁯‍⁠؜⁯⁠⁭⁬⁪⁡⁬‌⁫⁠⁫⁠⁠⁪⁫⁣⁤} other {⁣⁢and {count} others⁫⁯‍⁠؜⁯⁠⁭⁬⁪⁡⁬‌⁫⁠⁫⁠⁠⁪⁫⁣⁤}}',
};
