/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Estonian
export default {
  'fabric.reactions.error.unexpected': 'Midagi läks nässu',
  'fabric.reactions.loading': 'Laadimine...',
  'fabric.reactions.more.emoji': 'Veel emojisid',
};
