/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Russian
export default {
  'fabric.reactions.add': 'Добавить реакцию',
  'fabric.reactions.error.unexpected': 'Реакции временно недоступны',
  'fabric.reactions.loading': 'Загрузка…',
  'fabric.reactions.more.emojis': 'Другие эмодзи',
  'fabric.reactions.more.info': 'Подробнее',
  'fabric.reactions.other.reacted.users':
    '{count, plural, one {и еще один} few {и еще {count}} many {и еще {count}} other {и еще {count}}}',
  'fabric.reactions.reactwithemoji': 'Отреагировать с помощью эмодзи {emoji}',
  'reactions.dialog.close': 'Закрыть',
  'reactions.dialog.left.navigate': 'Навигация влево',
  'reactions.dialog.reactions.count':
    '{count, plural, one {{count,number} реакция} few {{count,number} реакции} many {{count,number} реакций} other {{count,number} реакции}}',
  'reactions.dialog.right.navigate': 'Навигация вправо',
  'reactions.dialog.viewall': 'Посмотреть, кто отреагировал',
  'reactions.dialog.viewall.tooltip': 'Посмотреть все реакции пользователей',
};
