/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Chinese (Simplified)
export default {
  'fabric.reactions.error.unexpected': '出错了',
  'fabric.reactions.loading': '正在加载...',
  'fabric.reactions.more.emoji': '更多表情符号',
  'fabric.reactions.other.reacted.users':
    '{count, plural, other {以及其他 {count} 个人}}',
};
