// THIS FILE IS GENERATED. DO NOT MODIFY IT MANUALLY.
export {
  RESIZE_HANDLE_AREA_DECORATION_GAP,
  TableDecorations,
  TableCssClassName,
  ShadowEvent,
} from '@atlaskit/editor-plugin-table/types';
export type {
  RowInsertPosition,
  PermittedLayoutsDescriptor,
  Cell,
  CellTransform,
  InsertRowOptions,
  PluginInjectionAPI,
  PluginInjectionAPIWithA11y,
  TableSharedStateInternal,
  TableSharedState,
  InsertRowMethods,
  PluginConfig,
  ColumnResizingPluginState,
  CellColumnPositioning,
  CellHoverMeta,
  WidthToWidest,
  TablePluginState,
  TablePluginAction,
  ColumnResizingPluginAction,
  ToolbarMenuConfig,
  ToolbarMenuState,
  ToolbarMenuContext,
  ReportInvalidNodeAttrs,
  InvalidNodeAttr,
  TableDirection,
  DraggableType,
  DraggableBehaviour,
  DraggableSourceData,
  DraggableTargetData,
  DraggableData,
  HandleTypes,
  MessageDescriptor,
} from '@atlaskit/editor-plugin-table/types';
