/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Dutch (Netherlands)
export default {
  "fabric.editor.confluence.legacyMobileMacros.chartPlaceholderText": "Hier zou een grafiek moeten staan, maar deze kan niet worden weergegeven. Open deze pagina in een browser om de grafiek te bekijken."
};
