/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Thai (Thailand)
export default {
  'fabric.editor.confluence.legacyMobileMacros.chartPlaceholderText':
    'แผนภูมิควรจะอยู่ที่นี่ แต่ไม่สามารถแสดงได้ เปิดหน้าข้อมูลนี้ในเบราว์เซอร์เพื่อดูแผนภูมิ',
};
