export const knownNamedColors: Record<string, string[]> = {
	aliceblue: ['blue'],
	antiquewhite: [],
	aqua: ['teal'],
	aquamarine: ['teal'],
	azure: ['teal', 'subtlest'],
	beige: [],
	bisque: [],
	black: [],
	blanchedalmond: [],
	blue: ['blue'],
	blueviolet: ['blue'],
	brown: [],
	burlywood: [],
	cadetblue: ['blue'],
	chartreuse: [],
	chocolate: [],
	coral: [],
	cornflowerblue: ['blue'],
	cornsilk: [],
	crimson: ['red'],
	cyan: ['accent', 'teal', 'subtle'],
	darkblue: ['accent', 'blue', 'bold'],
	darkcyan: ['accent', 'teal', 'bold'],
	darkgoldenrod: [],
	darkgray: [],
	darkgrey: [],
	darkgreen: ['green'],
	darkkhaki: [],
	darkmagenta: ['magenta', 'bold'],
	darkolivegreen: ['green'],
	darkorange: [],
	darkorchid: [],
	darkred: ['accent', 'red', 'bold'],
	darksalmon: [],
	darkseagreen: ['green'],
	darkslateblue: [],
	darkslategray: [],
	darkslategrey: [],
	darkturquoise: ['teal', 'bold'],
	darkviolet: ['purple', 'bold'],
	deeppink: ['magenta'],
	deepskyblue: ['blue'],
	dimgray: [],
	dimgrey: [],
	dodgerblue: [],
	firebrick: ['red', 'bold'],
	floralwhite: [],
	forestgreen: ['green'],
	fuchsia: ['magenta', 'subtle'],
	gainsboro: [],
	ghostwhite: [],
	gold: ['yellow'],
	goldenrod: [],
	gray: [],
	grey: [],
	green: ['green'],
	greenyellow: [],
	honeydew: [],
	hotpink: ['magenta'],
	indianred: [],
	indigo: ['purple'],
	ivory: [],
	khaki: [],
	lavender: ['purple'],
	lavenderblush: ['purple'],
	lawngreen: ['green'],
	lemonchiffon: [],
	lightblue: [],
	lightcoral: [],
	lightcyan: [],
	lightgoldenrodyellow: [],
	lightgray: [],
	lightgrey: [],
	lightgreen: ['green', 'accent'],
	lightpink: ['magenta'],
	lightsalmon: ['pink', 'subtler'],
	lightseagreen: ['green'],
	lightskyblue: ['blue', 'accent'],
	lightslategray: [],
	lightslategrey: [],
	lightsteelblue: ['blue'],
	lightyellow: [],
	lime: ['green', 'subtler'],
	limegreen: ['green'],
	linen: [],
	magenta: ['magenta'],
	maroon: [],
	mediumaquamarine: [],
	mediumblue: [],
	mediumorchid: [],
	mediumpurple: [],
	mediumseagreen: ['green'],
	mediumslateblue: [],
	mediumspringgreen: ['green'],
	mediumturquoise: [],
	mediumvioletred: [],
	midnightblue: [],
	mintcream: [],
	mistyrose: [],
	moccasin: [],
	navajowhite: [],
	navy: ['blue', 'bold'],
	oldlace: [],
	olive: [],
	olivedrab: [],
	orange: [],
	orangered: [],
	orchid: ['purple'],
	palegoldenrod: [],
	palegreen: ['green'],
	paleturquoise: [],
	palevioletred: [],
	papayawhip: [],
	peachpuff: [],
	peru: [],
	pink: ['magenta'],
	plum: [],
	powderblue: ['blue', 'subtle'],
	purple: ['purple'],
	rebeccapurple: ['purple', 'accent'],
	red: ['red', 'accent'],
	rosybrown: [],
	royalblue: [],
	saddlebrown: [],
	salmon: [],
	sandybrown: [],
	seagreen: ['green'],
	seashell: [],
	sienna: [],
	silver: [],
	skyblue: ['blue', 'subtlest'],
	slateblue: [],
	slategray: [],
	slategrey: [],
	snow: [],
	springgreen: ['green'],
	steelblue: ['blue'],
	tan: [],
	teal: ['accent', 'teal'],
	thistle: [],
	tomato: ['red'],
	turquoise: [],
	violet: ['purple'],
	wheat: [],
	white: ['elevation', 'surface'],
	whitesmoke: [],
	yellow: ['yellow'],
	yellowgreen: ['yellow'],
};
