export default {
  type: 'array',
  items: [
    [
      'blockCard',
      'paragraph_with_no_marks',
      'paragraph_with_alignment',
      'mediaSingle_caption',
      'mediaSingle_full',
      'codeBlock_with_no_marks',
      'bulletList',
      'orderedList',
      'heading_with_no_marks',
      'heading_with_alignment',
      'heading_with_indentation',
      'panel',
      'blockquote',
      'rule',
      'mediaGroup',
      'decisionList',
      'taskList',
      'extension_with_marks',
      'embedCard',
      'nestedExpand_with_no_marks',
    ],
  ],
  minItems: 1,
  allowUnsupportedBlock: true,
};
