import type { EntryPointConfigOverrides } from './types';

/**
 * Manual mappings merged on top of codegen output.
 * Use for ambiguous cases where heuristics cannot pick a single entry-point,
 * or to keep a symbol on the barrel (`voltCompliant: false`).
 */
export const overrides: EntryPointConfigOverrides = {
	'@atlaskit/button': {
		'': {
			Appearance: {
				'entry-point': '/old-button/types',
				isDefaultExport: false,
				name: 'Appearance',
				type: 'type',
				voltCompliant: true,
			},
			Spacing: {
				'entry-point': '/old-button/types',
				isDefaultExport: false,
				name: 'Spacing',
				type: 'type',
				voltCompliant: true,
			},
			BaseOwnProps: {
				'entry-point': '/old-button/types',
				isDefaultExport: false,
				name: 'BaseOwnProps',
				type: 'type',
				voltCompliant: true,
			},
			BaseProps: {
				'entry-point': '/old-button/types',
				isDefaultExport: false,
				name: 'BaseProps',
				type: 'type',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/button',
				isDefaultExport: true,
				name: 'Button',
				type: 'component',
				voltCompliant: true,
			},
			ButtonProps: {
				'entry-point': '/button',
				name: 'ButtonProps',
				type: 'type',
				voltCompliant: true,
			},
			LoadingButton: {
				'entry-point': '/loading-button',
				name: 'LoadingButton',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			LoadingButtonProps: {
				'entry-point': '/loading-button',
				name: 'LoadingButtonProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			LoadingButtonOwnProps: {
				'entry-point': '/loading-button',
				name: 'LoadingButtonOwnProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			CustomThemeButton: {
				'entry-point': '/custom-theme-button/custom-theme-button',
				name: 'CustomThemeButton',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			Theme: {
				'entry-point': '/theme',
				name: 'Theme',
				isDefaultExport: true,
				type: 'value',
				voltCompliant: true,
			},
			ThemeTokens: {
				'entry-point': '/custom-theme-button-types',
				name: 'ThemeTokens',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			ThemeProps: {
				'entry-point': '/custom-theme-button-types',
				name: 'ThemeProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			InteractionState: {
				'entry-point': '/custom-theme-button-types',
				name: 'InteractionState',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			CustomThemeButtonProps: {
				'entry-point': '/custom-theme-button-types',
				name: 'CustomThemeButtonProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			CustomThemeButtonOwnProps: {
				'entry-point': '/custom-theme-button-types',
				name: 'CustomThemeButtonOwnProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			ButtonGroup: {
				'entry-point': '/button-group',
				name: 'ButtonGroup',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			ButtonGroupProps: {
				'entry-point': '/button-group',
				name: 'ButtonGroupProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
		},
		'/custom-theme-button': {
			default: {
				'entry-point': '/custom-theme-button/custom-theme-button',
				name: 'CustomThemeButton',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			Theme: {
				'entry-point': '/theme',
				name: 'Theme',
				isDefaultExport: true,
				type: 'value',
				voltCompliant: true,
			},
			ThemeTokens: {
				'entry-point': '/custom-theme-button-types',
				name: 'ThemeTokens',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			ThemeProps: {
				'entry-point': '/custom-theme-button-types',
				name: 'ThemeProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			InteractionState: {
				'entry-point': '/custom-theme-button-types',
				name: 'InteractionState',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			CustomThemeButtonProps: {
				'entry-point': '/custom-theme-button-types',
				name: 'CustomThemeButtonProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			CustomThemeButtonOwnProps: {
				'entry-point': '/custom-theme-button-types',
				name: 'CustomThemeButtonOwnProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
		},
		'/split-button': {
			SplitButton: {
				'entry-point': '/split-button/split-button',
				name: 'SplitButton',
				isDefaultExport: false,
				type: 'component',
				voltCompliant: true,
			},
			Divider: {
				'entry-point': '/divider',
				name: 'Divider',
				isDefaultExport: false,
				type: 'component',
				voltCompliant: true,
			},
			SplitButtonContainer: {
				'entry-point': '/split-button-container',
				name: 'SplitButtonContainer',
				isDefaultExport: false,
				type: 'component',
				voltCompliant: true,
			},
			SplitButtonWithSlots: {
				'entry-point': '/split-button-with-slots',
				name: 'SplitButtonWithSlots',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
		},
		'/new': {
			default: {
				'entry-point': '/default/button',
				name: 'Button',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			ButtonProps: {
				'entry-point': '/default/button',
				name: 'ButtonProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			LinkButton: {
				'entry-point': '/link',
				name: 'LinkButton',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			LinkButtonProps: {
				'entry-point': '/link',
				name: 'LinkButtonProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			IconButton: {
				'entry-point': '/icon/button',
				name: 'IconButton',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			IconButtonProps: {
				'entry-point': '/icon/button',
				name: 'IconButtonProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			LinkIconButton: {
				'entry-point': '/icon/link',
				name: 'LinkIconButton',
				isDefaultExport: true,
				type: 'component',
				voltCompliant: true,
			},
			LinkIconButtonProps: {
				'entry-point': '/icon/link',
				name: 'LinkIconButtonProps',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			SplitButton: {
				'entry-point': '/split-button/split-button',
				name: 'SplitButton',
				isDefaultExport: false,
				type: 'component',
				voltCompliant: true,
			},
			Appearance: {
				'entry-point': '/variants/types',
				name: 'Appearance',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			Spacing: {
				'entry-point': '/variants/types',
				name: 'Spacing',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			IconProp: {
				'entry-point': '/variants/types',
				name: 'IconProp',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			IconButtonSpacing: {
				'entry-point': '/variants/types',
				name: 'IconButtonSpacing',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
			IconButtonAppearance: {
				'entry-point': '/variants/types',
				name: 'IconButtonAppearance',
				isDefaultExport: false,
				type: 'type',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/tokens': {
		'': {
			token: {
				'entry-point': '',
				name: 'token',
				type: 'value',
				voltCompliant: true,
			},
			ThemeColorModes: {
				'entry-point': '/theme-color-modes',
				isDefaultExport: false,
				name: 'ThemeColorModes',
				voltCompliant: true,
			},
			ThemeIds: {
				'entry-point': '/theme-ids',
				isDefaultExport: false,
				name: 'ThemeIds',
				voltCompliant: true,
			},
			UNSAFE_loadCustomThemeStyles: {
				'entry-point': '/unsafe-load-custom-theme-styles',
				isDefaultExport: false,
				name: 'UNSAFE_loadCustomThemeStyles',
				voltCompliant: true,
			},
			getCSSCustomProperty: {
				'entry-point': '/utils/get-css-custom-property',
				isDefaultExport: false,
				name: 'getCSSCustomProperty',
				voltCompliant: true,
			},
			getFullyQualifiedTokenId: {
				'entry-point': '/utils/get-fully-qualified-token-id',
				isDefaultExport: false,
				name: 'getFullyQualifiedTokenId',
				voltCompliant: true,
			},
			getTokenId: {
				'entry-point': '/utils/get-token-id',
				isDefaultExport: false,
				name: 'getTokenId',
				voltCompliant: true,
			},
			themeColorModes: {
				'entry-point': '/theme-color-modes',
				isDefaultExport: false,
				name: 'themeColorModes',
				voltCompliant: true,
			},
			themeIds: {
				'entry-point': '/theme-ids',
				isDefaultExport: false,
				name: 'themeIds',
				voltCompliant: true,
			},
			themeStateDefaults: {
				'entry-point': '/theme-state-defaults',
				isDefaultExport: false,
				name: 'themeStateDefaults',
				voltCompliant: true,
			},
		},
		'/tokens-raw': {
			light: {
				'entry-point': '/atlassian-light',
				isDefaultExport: true,
				name: 'light',
				type: 'value',
				voltCompliant: true,
			},
			dark: {
				'entry-point': '/atlassian-dark',
				isDefaultExport: true,
				name: 'dark',
				type: 'value',
				voltCompliant: true,
			},
			spacing: {
				'entry-point': '/atlassian-spacing',
				isDefaultExport: true,
				name: 'spacing',
				type: 'value',
				voltCompliant: true,
			},
			typography: {
				'entry-point': '/atlassian-typography',
				isDefaultExport: true,
				name: 'typography',
				type: 'value',
				voltCompliant: true,
			},
			shape: {
				'entry-point': '/atlassian-shape',
				isDefaultExport: true,
				name: 'shape',
				type: 'value',
				voltCompliant: true,
			},
			motion: {
				'entry-point': '/atlassian-motion',
				isDefaultExport: true,
				name: 'motion',
				type: 'value',
				voltCompliant: true,
			},
		},
		'/palettes-raw': {
			default: {
				'entry-point': '/palette',
				isDefaultExport: true,
				name: 'tokens',
				type: 'value',
				voltCompliant: true,
			},
			typographyPalette: {
				'entry-point': '/typography-palette',
				isDefaultExport: true,
				name: 'typographyPalette',
				type: 'value',
				voltCompliant: true,
			},
		},
		'/theme-state-transformer': {
			themeStringToObject: {
				'entry-point': '/theme-string-to-object',
				name: 'themeStringToObject',
				type: 'value',
				voltCompliant: true,
			},
			themeObjectToString: {
				'entry-point': '/theme-object-to-string',
				name: 'themeObjectToString',
				type: 'value',
				voltCompliant: true,
			},
		},
		'/theme-config': {
			themeColorModes: {
				'entry-point': '/theme-color-modes',
				name: 'themeColorModes',
				type: 'value',
				voltCompliant: true,
			},
			ThemeColorModes: {
				'entry-point': '/theme-color-modes',
				name: 'ThemeColorModes',
				type: 'type',
				voltCompliant: true,
			},
			themeIds: {
				'entry-point': '/theme-ids',
				name: 'themeIds',
				type: 'value',
				voltCompliant: true,
			},
			ThemeIds: {
				'entry-point': '/theme-ids',
				name: 'ThemeIds',
				type: 'type',
				voltCompliant: true,
			},
			themeStateDefaults: {
				'entry-point': '/theme-state-defaults',
				name: 'themeStateDefaults',
				type: 'value',
				voltCompliant: true,
			},
		},
		'/custom-themes': {
			UNSAFE_loadCustomThemeStyles: {
				'entry-point': '/unsafe-load-custom-theme-styles',
				name: 'UNSAFE_loadCustomThemeStyles',
				type: 'value',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/app-provider': {
		'': {
			default: {
				'entry-point': '/app-provider',
				isDefaultExport: false,
				name: 'AppProvider',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/avatar': {
		'/constants': {
			ACTIVE_SCALE_FACTOR: {
				'entry-point': '/constants/default',
				isDefaultExport: false,
				name: 'ACTIVE_SCALE_FACTOR',
				voltCompliant: true,
			},
			AVATAR_RADIUS: {
				'entry-point': '/avatar-radius',
				isDefaultExport: false,
				name: 'AVATAR_RADIUS',
				voltCompliant: true,
			},
			AVATAR_SIZES: {
				'entry-point': '/avatar-sizes',
				isDefaultExport: false,
				name: 'AVATAR_SIZES',
				voltCompliant: true,
			},
			BORDER_WIDTH: {
				'entry-point': '/constants/default',
				isDefaultExport: false,
				name: 'BORDER_WIDTH',
				voltCompliant: true,
			},
		},
		'/presence-old': {
			PresenceProps: {
				'entry-point': '/presence',
				isDefaultExport: false,
				name: 'PresenceProps',
				voltCompliant: true,
			},
			PresenceType: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'PresenceType',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/presence',
				isDefaultExport: true,
				name: 'AvatarPresence',
				voltCompliant: true,
			},
		},
		'/status-old': {
			StatusProps: {
				'entry-point': '/status',
				isDefaultExport: false,
				name: 'StatusProps',
				voltCompliant: true,
			},
			StatusType: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'StatusType',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/status',
				isDefaultExport: true,
				name: 'AvatarStatus',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/badge': {
		'/new': {
			BadgeNewProps: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'BadgeProps',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/badge-new',
				isDefaultExport: true,
				name: 'Badge',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/code': {
		'': {
			bidiCharacterRegex: {
				'entry-point': '/bidi-character-regex',
				isDefaultExport: false,
				name: 'bidiCharacterRegex',
				voltCompliant: true,
			},
			CODE_BLOCK_SELECTOR: {
				'entry-point': '/constants',
				isDefaultExport: false,
				name: 'CODE_BLOCK_SELECTOR',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/bidi-warning',
				isDefaultExport: true,
				name: 'BidiWarning',
				voltCompliant: true,
			},
		},
		'/bidi-warning-decorator': {
			bidiCharacterRegex: {
				'entry-point': '/bidi-character-regex',
				isDefaultExport: false,
				name: 'bidiCharacterRegex',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/bidi-warning/bidi-warning-decorator',
				isDefaultExport: true,
				name: 'codeBidiWarningDecorator',
				voltCompliant: true,
			},
		},
		'/block': {
			CodeBlockProps: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'CodeBlockProps',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/code-block',
				isDefaultExport: true,
				name: 'CodeBlock',
				voltCompliant: true,
			},
		},
		'/inline': {
			CodeBlockProps: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'CodeBlockProps',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/code',
				isDefaultExport: true,
				name: 'Code',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/flag': {
		'': {
			FlagContext: {
				'entry-point': '/flag-context',
				isDefaultExport: false,
				name: 'FlagContext',
				voltCompliant: true,
			},
			FlagGroupContext: {
				'entry-point': '/flag-group-context',
				isDefaultExport: false,
				name: 'FlagGroupContext',
				voltCompliant: true,
			},
			FlagsProvider: {
				'entry-point': '/flags-provider',
				isDefaultExport: false,
				name: 'FlagsProvider',
				voltCompliant: true,
			},
			actionTextColor: {
				'entry-point': '/action-text-color',
				isDefaultExport: false,
				name: 'actionTextColor',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/flag-group',
				isDefaultExport: false,
				name: 'FlagGroup',
				voltCompliant: true,
			},
			flagBackgroundColor: {
				'entry-point': '/flag-background-color',
				isDefaultExport: false,
				name: 'flagBackgroundColor',
				voltCompliant: true,
			},
			flagIconColor: {
				'entry-point': '/flag-icon-color',
				isDefaultExport: false,
				name: 'flagIconColor',
				voltCompliant: true,
			},
			flagIconGlyph: {
				'entry-point': '/flag-icon-glyph',
				isDefaultExport: false,
				name: 'flagIconGlyph',
				voltCompliant: true,
			},
			flagTextColor: {
				'entry-point': '/flag-text-color',
				isDefaultExport: false,
				name: 'flagTextColor',
				voltCompliant: true,
			},
			flagTextColorToken: {
				'entry-point': '/flag-text-color-token',
				isDefaultExport: false,
				name: 'flagTextColorToken',
				voltCompliant: true,
			},
			flagWidth: {
				'entry-point': '/constants',
				isDefaultExport: false,
				name: 'flagWidth',
				voltCompliant: true,
			},
			useFlagGroup: {
				'entry-point': '/use-flag-group',
				isDefaultExport: false,
				name: 'useFlagGroup',
				voltCompliant: true,
			},
			useFlags: {
				'entry-point': '/use-flags',
				isDefaultExport: false,
				name: 'useFlags',
				voltCompliant: true,
			},
			withFlagsProvider: {
				'entry-point': '/with-flags-provider',
				isDefaultExport: false,
				name: 'withFlagsProvider',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/form': {
		'/label': {
			Label: {
				'entry-point': '/label/default',
				isDefaultExport: false,
				name: 'Label',
				voltCompliant: true,
			},
			LabelProps: {
				'entry-point': '/label/default',
				isDefaultExport: false,
				name: 'LabelProps',
				voltCompliant: true,
			},
			Legend: {
				'entry-point': '/legend',
				isDefaultExport: false,
				name: 'Legend',
				voltCompliant: true,
			},
			LegendProps: {
				'entry-point': '/legend',
				isDefaultExport: false,
				name: 'LegendProps',
				voltCompliant: true,
			},
		},
		'/messages': {
			ErrorMessage: {
				'entry-point': '/error-message',
				isDefaultExport: false,
				name: 'ErrorMessage',
				voltCompliant: true,
			},
			HelperMessage: {
				'entry-point': '/helper-message',
				isDefaultExport: false,
				name: 'HelperMessage',
				voltCompliant: true,
			},
			MessageWrapper: {
				'entry-point': '/message-wrapper',
				isDefaultExport: false,
				name: 'MessageWrapper',
				voltCompliant: true,
			},
			ValidMessage: {
				'entry-point': '/valid-message',
				isDefaultExport: false,
				name: 'ValidMessage',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/popper': {
		'/popper': {
			CustomPopperProps: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'CustomPopperProps',
				voltCompliant: true,
			},
			ManagerProps: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'ManagerProps',
				voltCompliant: true,
			},
			Modifier: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'Modifier',
				voltCompliant: true,
			},
			Placement: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'Placement',
				voltCompliant: true,
			},
			Popper: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'Popper',
				voltCompliant: true,
			},
			PopperArrowProps: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'PopperArrowProps',
				voltCompliant: true,
			},
			PopperChildrenProps: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'PopperChildrenProps',
				voltCompliant: true,
			},
			PopperProps: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'PopperProps',
				voltCompliant: true,
			},
			ReferenceProps: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'ReferenceProps',
				voltCompliant: true,
			},
			State: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'State',
				voltCompliant: true,
			},
			StrictModifier: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'StrictModifier',
				voltCompliant: true,
			},
			VirtualElement: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'VirtualElement',
				voltCompliant: true,
			},
			placements: {
				'entry-point': '/main',
				isDefaultExport: false,
				name: 'placements',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/popup': {
		'/experimental/compositional': {
			Popup: {
				'entry-point': '/compositional/popup',
				isDefaultExport: false,
				name: 'Popup',
				voltCompliant: true,
			},
			PopupContent: {
				'entry-point': '/compositional/popup-content',
				isDefaultExport: false,
				name: 'PopupContent',
				voltCompliant: true,
			},
			PopupContentProps: {
				'entry-point': '/compositional/popup-content',
				isDefaultExport: false,
				name: 'PopupContentProps',
				voltCompliant: true,
			},
			PopupProps: {
				'entry-point': '/compositional/popup',
				isDefaultExport: false,
				name: 'PopupProps',
				voltCompliant: true,
			},
			PopupTrigger: {
				'entry-point': '/compositional/popup-trigger',
				isDefaultExport: false,
				name: 'PopupTrigger',
				voltCompliant: true,
			},
			PopupTriggerProps: {
				'entry-point': '/compositional/popup-trigger',
				isDefaultExport: false,
				name: 'PopupTriggerProps',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/section-message': {
		'/section-message': {
			SectionMessageProps: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'SectionMessageProps',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/message',
				isDefaultExport: true,
				name: 'SectionMessage',
				voltCompliant: true,
			},
		},
		'/section-message-action': {
			SectionMessageActionProps: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'SectionMessageActionProps',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/message-action',
				isDefaultExport: true,
				name: 'SectionMessageAction',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/theme': {
		'': {
			GlobalThemeTokens: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'GlobalThemeTokens',
				voltCompliant: true,
			},
			ThemeProp: {
				'entry-point': '/create-theme',
				isDefaultExport: false,
				name: 'ThemeProp',
				voltCompliant: true,
			},
			createTheme: {
				'entry-point': '/create-theme',
				isDefaultExport: false,
				name: 'createTheme',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/theme',
				isDefaultExport: true,
				name: 'Theme',
				voltCompliant: true,
			},
			getTheme: {
				'entry-point': '/get-theme',
				isDefaultExport: false,
				name: 'getTheme',
				voltCompliant: true,
			},
		},
	},
	'@atlaskit/tile': {
		'/skeleton': {
			TileSkeletonProps: {
				'entry-point': '/types',
				isDefaultExport: false,
				name: 'TileSkeletonProps',
				voltCompliant: true,
			},
			default: {
				'entry-point': '/tile-skeleton',
				isDefaultExport: true,
				name: 'TileSkeleton',
				voltCompliant: true,
			},
		},
	},
};
