/**
 * THIS FILE WAS CREATED VIA CODEGEN DO NOT MODIFY {@see http://go/af-codegen}
 *
 * Volt Stage 1 / Stage 2 readiness map derived from volt-preset-packages.json.
 *
 * @codegen <<SignedSource::31c1967acda15a26c7a06a251dca4ddc>>
 * @codegenCommand yarn workspace @atlaskit/volt-components-entry-point-config codegen
 */
/**
 * Package → Volt Stage 1 / Stage 2 readiness from
 * `platform/volt-preset-packages.json`.
 * `voltCompliant: true` means confident mappings may set per-symbol
 * `voltCompliant: true` (lint report + suggestion).
 * `consumersMigrated: true` is Stage 2 (reserved for future warn→error).
 *
 * Do not edit by hand — regenerate via:
 * `yarn workspace @atlaskit/volt-components-entry-point-config codegen`
 */
export const PACKAGE_NAMES = {
	'@atlaskit/adf-schema': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/adf-utils': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/analytics-cross-product': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/analytics-listeners': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/analytics-namespaced-context': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/analytics-next': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/app-provider': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/atlassian-context': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/avatar': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/avatar-group': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/badge': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/blanket': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/button': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/calendar': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/checkbox': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/chunkinator': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/code': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/css': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/datetime-picker': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/drawer': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/dropdown-menu': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/editor-json-transformer': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/editor-prosemirror': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/editor-shared-styles': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/editor-tables': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/embedded-confluence': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/emoji': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/empty-state': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/feature-gate-js-client': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/flag': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/focus-ring': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/form': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/frontend-utilities': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/give-kudos': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/heading': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/icon': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/image': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/inline-dialog': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/inline-edit': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/intl-messages-provider': { voltCompliant: true, consumersMigrated: true },
	'@atlaskit/jql-ast': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/jql-autocomplete': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/jql-editor': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/jql-editor-autocomplete-rest': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/jql-editor-common': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/jql-parser': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/json-ld-types': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/layering': { voltCompliant: true, consumersMigrated: true },
	'@atlaskit/link': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/link-analytics': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/link-client-extension': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/link-datasource': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/link-extractors': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/link-picker': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/link-provider': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/linking-common': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/linking-types': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/locale': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/logo': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/lozenge': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-card': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-client': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/media-client-react': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-common': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/media-core': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-document-viewer': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/media-file-preview': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-picker': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-state': { voltCompliant: true, consumersMigrated: true },
	'@atlaskit/media-svg': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-ui': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/media-viewer': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/mention': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/menu': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/modal-dialog': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/motion': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/object': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/outbound-auth-flow-client': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/people-teams-ui-public': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/platform-feature-flags': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/platform-feature-flags-react': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/popper': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/popup': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/portal': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/pragmatic-drag-and-drop': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/pragmatic-drag-and-drop-hitbox': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/pragmatic-drag-and-drop-react-beautiful-dnd-autoscroll': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/pragmatic-drag-and-drop-react-drop-indicator': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/primitives': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/profilecard': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/prosemirror-history': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/radio': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/range': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/react-select': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/react-ufo': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/rovo-agent-components': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/rovo-triggers': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/section-message': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/select': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/side-navigation': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/smart-card': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/smart-user-picker': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/spinner': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/spotlight': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/tabs': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/tag': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/teams-app-config': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/teams-app-internal-analytics': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/teams-app-internal-navigation': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/teams-app-internal-product-permissions': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/teams-avatar': { voltCompliant: true, consumersMigrated: true },
	'@atlaskit/teams-client': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/teams-public': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/textarea': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/textfield': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/theme': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/tile': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/tmp-editor-statsig': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/tokens': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/tooltip': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/top-layer': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/townsquare-emoji-provider': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/ufo': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/user-picker': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/util-service-support': { voltCompliant: false, consumersMigrated: false },
	'@atlaskit/visually-hidden': { voltCompliant: true, consumersMigrated: false },
	'@atlaskit/width-detector': { voltCompliant: true, consumersMigrated: false },
	'@atlassian/atl-context': { voltCompliant: true, consumersMigrated: false },
	'@atlassian/browser-metrics': { voltCompliant: true, consumersMigrated: false },
	'@atlassian/browser-storage-controls': { voltCompliant: false, consumersMigrated: false },
	'@atlassian/embedded-confluence-common': { voltCompliant: true, consumersMigrated: false },
	'@atlassian/experience-tracker': { voltCompliant: true, consumersMigrated: false },
	'@atlassian/relay-fetch': { voltCompliant: true, consumersMigrated: false },
	'@atlassian/trace-context': { voltCompliant: true, consumersMigrated: true },
	'@atlassian/ufo': { voltCompliant: true, consumersMigrated: false },
	'@atlassian/ufo-experimental': { voltCompliant: true, consumersMigrated: false },
	'@atlassiansox/analytics-cross-product-interaction-client': { voltCompliant: true, consumersMigrated: false },
	'@atlassiansox/analytics-web-client': { voltCompliant: false, consumersMigrated: false },
} as const;
