import type { CSSProperties } from 'react';

import type { StrictXCSSProp, XCSSAllProperties, XCSSAllPseudos } from '@atlaskit/css';

export type BasePrimitiveProps = {
	/**
	 * A unique string that appears as data attribute `data-testid` in the rendered code, serving as a hook for automated tests.
	 */
	testId?: string;

	/**
	 * `data-testid` is strictly controlled through the `testId` prop.
	 * This lets consumers know that this data attribute will not be applied.
	 */
	'data-testid'?: never;

	/**
	 * Apply a subset of permitted styles powered by Atlassian Design System design tokens.
	 */
	xcss?: StrictXCSSProp<XCSSAllProperties, XCSSAllPseudos>;

	/**
	 * Accessible role.
	 */
	role?: string;
};

export type StyleProp = {
	// TODO: Can we have some bounded styles here, like only `width, height` or at least our same Design System token interface?
	style?: CSSProperties;
};

// NOTE: May be some cross-over in here to reduce.
export type AlignBlock = 'start' | 'center' | 'end' | 'baseline' | 'stretch';
export type AlignContent =
	| 'center'
	| 'start'
	| 'space-around'
	| 'space-between'
	| 'space-evenly'
	| 'stretch'
	| 'end';
export type AlignInline = 'start' | 'center' | 'end' | 'stretch';
export type AlignItems = 'center' | 'start' | 'stretch' | 'end' | 'baseline';
export type AutoFlow = 'column' | 'row' | 'dense' | 'row dense' | 'column dense';
export type Direction = 'column' | 'row';
export type Grow = 'hug' | 'fill';
export type JustifyContent =
	| 'center'
	| 'start'
	| 'space-around'
	| 'space-between'
	| 'space-evenly'
	| 'stretch'
	| 'end';
export type JustifyItems = 'center' | 'start' | 'stretch' | 'end';
export type Spread = 'space-between';
export type Wrap = 'wrap' | 'nowrap';

// NOTE: Separated as tokens as these should be rare and hardcoded, not generated, because generation can lead to bundle bloat.
export type BleedSpaceToken = 'space.025' | 'space.050' | 'space.100' | 'space.150' | 'space.200';
export type PositiveSpaceToken =
	| 'space.0'
	| 'space.025'
	| 'space.050'
	| 'space.075'
	| 'space.100'
	| 'space.150'
	| 'space.200'
	| 'space.250'
	| 'space.300'
	| 'space.400'
	| 'space.500'
	| 'space.600'
	| 'space.800'
	| 'space.1000';
export type PaddingToken = PositiveSpaceToken;
export type GapToken = PositiveSpaceToken;

export type SurfaceColorToken =
	| 'utility.elevation.surface.current'
	| 'elevation.surface'
	| 'elevation.surface.overlay'
	| 'elevation.surface.raised'
	| 'elevation.surface.sunken';

export type BackgroundColorToken =
	| 'color.background.accent.lime.subtlest'
	| 'color.background.accent.lime.subtlest.hovered'
	| 'color.background.accent.lime.subtlest.pressed'
	| 'color.background.accent.lime.subtler'
	| 'color.background.accent.lime.subtler.hovered'
	| 'color.background.accent.lime.subtler.pressed'
	| 'color.background.accent.lime.subtle'
	| 'color.background.accent.lime.subtle.hovered'
	| 'color.background.accent.lime.subtle.pressed'
	| 'color.background.accent.lime.bolder'
	| 'color.background.accent.lime.bolder.hovered'
	| 'color.background.accent.lime.bolder.pressed'
	| 'color.background.accent.red.subtlest'
	| 'color.background.accent.red.subtlest.hovered'
	| 'color.background.accent.red.subtlest.pressed'
	| 'color.background.accent.red.subtler'
	| 'color.background.accent.red.subtler.hovered'
	| 'color.background.accent.red.subtler.pressed'
	| 'color.background.accent.red.subtle'
	| 'color.background.accent.red.subtle.hovered'
	| 'color.background.accent.red.subtle.pressed'
	| 'color.background.accent.red.bolder'
	| 'color.background.accent.red.bolder.hovered'
	| 'color.background.accent.red.bolder.pressed'
	| 'color.background.accent.orange.subtlest'
	| 'color.background.accent.orange.subtlest.hovered'
	| 'color.background.accent.orange.subtlest.pressed'
	| 'color.background.accent.orange.subtler'
	| 'color.background.accent.orange.subtler.hovered'
	| 'color.background.accent.orange.subtler.pressed'
	| 'color.background.accent.orange.subtle'
	| 'color.background.accent.orange.subtle.hovered'
	| 'color.background.accent.orange.subtle.pressed'
	| 'color.background.accent.orange.bolder'
	| 'color.background.accent.orange.bolder.hovered'
	| 'color.background.accent.orange.bolder.pressed'
	| 'color.background.accent.yellow.subtlest'
	| 'color.background.accent.yellow.subtlest.hovered'
	| 'color.background.accent.yellow.subtlest.pressed'
	| 'color.background.accent.yellow.subtler'
	| 'color.background.accent.yellow.subtler.hovered'
	| 'color.background.accent.yellow.subtler.pressed'
	| 'color.background.accent.yellow.subtle'
	| 'color.background.accent.yellow.subtle.hovered'
	| 'color.background.accent.yellow.subtle.pressed'
	| 'color.background.accent.yellow.bolder'
	| 'color.background.accent.yellow.bolder.hovered'
	| 'color.background.accent.yellow.bolder.pressed'
	| 'color.background.accent.green.subtlest'
	| 'color.background.accent.green.subtlest.hovered'
	| 'color.background.accent.green.subtlest.pressed'
	| 'color.background.accent.green.subtler'
	| 'color.background.accent.green.subtler.hovered'
	| 'color.background.accent.green.subtler.pressed'
	| 'color.background.accent.green.subtle'
	| 'color.background.accent.green.subtle.hovered'
	| 'color.background.accent.green.subtle.pressed'
	| 'color.background.accent.green.bolder'
	| 'color.background.accent.green.bolder.hovered'
	| 'color.background.accent.green.bolder.pressed'
	| 'color.background.accent.teal.subtlest'
	| 'color.background.accent.teal.subtlest.hovered'
	| 'color.background.accent.teal.subtlest.pressed'
	| 'color.background.accent.teal.subtler'
	| 'color.background.accent.teal.subtler.hovered'
	| 'color.background.accent.teal.subtler.pressed'
	| 'color.background.accent.teal.subtle'
	| 'color.background.accent.teal.subtle.hovered'
	| 'color.background.accent.teal.subtle.pressed'
	| 'color.background.accent.teal.bolder'
	| 'color.background.accent.teal.bolder.hovered'
	| 'color.background.accent.teal.bolder.pressed'
	| 'color.background.accent.blue.subtlest'
	| 'color.background.accent.blue.subtlest.hovered'
	| 'color.background.accent.blue.subtlest.pressed'
	| 'color.background.accent.blue.subtler'
	| 'color.background.accent.blue.subtler.hovered'
	| 'color.background.accent.blue.subtler.pressed'
	| 'color.background.accent.blue.subtle'
	| 'color.background.accent.blue.subtle.hovered'
	| 'color.background.accent.blue.subtle.pressed'
	| 'color.background.accent.blue.bolder'
	| 'color.background.accent.blue.bolder.hovered'
	| 'color.background.accent.blue.bolder.pressed'
	| 'color.background.accent.purple.subtlest'
	| 'color.background.accent.purple.subtlest.hovered'
	| 'color.background.accent.purple.subtlest.pressed'
	| 'color.background.accent.purple.subtler'
	| 'color.background.accent.purple.subtler.hovered'
	| 'color.background.accent.purple.subtler.pressed'
	| 'color.background.accent.purple.subtle'
	| 'color.background.accent.purple.subtle.hovered'
	| 'color.background.accent.purple.subtle.pressed'
	| 'color.background.accent.purple.bolder'
	| 'color.background.accent.purple.bolder.hovered'
	| 'color.background.accent.purple.bolder.pressed'
	| 'color.background.accent.magenta.subtlest'
	| 'color.background.accent.magenta.subtlest.hovered'
	| 'color.background.accent.magenta.subtlest.pressed'
	| 'color.background.accent.magenta.subtler'
	| 'color.background.accent.magenta.subtler.hovered'
	| 'color.background.accent.magenta.subtler.pressed'
	| 'color.background.accent.magenta.subtle'
	| 'color.background.accent.magenta.subtle.hovered'
	| 'color.background.accent.magenta.subtle.pressed'
	| 'color.background.accent.magenta.bolder'
	| 'color.background.accent.magenta.bolder.hovered'
	| 'color.background.accent.magenta.bolder.pressed'
	| 'color.background.accent.gray.subtlest'
	| 'color.background.accent.gray.subtlest.hovered'
	| 'color.background.accent.gray.subtlest.pressed'
	| 'color.background.accent.gray.subtler'
	| 'color.background.accent.gray.subtler.hovered'
	| 'color.background.accent.gray.subtler.pressed'
	| 'color.background.accent.gray.subtle'
	| 'color.background.accent.gray.subtle.hovered'
	| 'color.background.accent.gray.subtle.pressed'
	| 'color.background.accent.gray.bolder'
	| 'color.background.accent.gray.bolder.hovered'
	| 'color.background.accent.gray.bolder.pressed'
	| 'color.background.disabled'
	| 'color.background.input'
	| 'color.background.input.hovered'
	| 'color.background.input.pressed'
	| 'color.background.inverse.subtle'
	| 'color.background.inverse.subtle.hovered'
	| 'color.background.inverse.subtle.pressed'
	| 'color.background.neutral'
	| 'color.background.neutral.hovered'
	| 'color.background.neutral.pressed'
	| 'color.background.neutral.subtle'
	| 'color.background.neutral.subtle.hovered'
	| 'color.background.neutral.subtle.pressed'
	| 'color.background.neutral.bold'
	| 'color.background.neutral.bold.hovered'
	| 'color.background.neutral.bold.pressed'
	| 'color.background.selected'
	| 'color.background.selected.hovered'
	| 'color.background.selected.pressed'
	| 'color.background.selected.bold'
	| 'color.background.selected.bold.hovered'
	| 'color.background.selected.bold.pressed'
	| 'color.background.brand.subtlest'
	| 'color.background.brand.subtlest.hovered'
	| 'color.background.brand.subtlest.pressed'
	| 'color.background.brand.bold'
	| 'color.background.brand.bold.hovered'
	| 'color.background.brand.bold.pressed'
	| 'color.background.brand.boldest'
	| 'color.background.brand.boldest.hovered'
	| 'color.background.brand.boldest.pressed'
	| 'color.background.danger'
	| 'color.background.danger.hovered'
	| 'color.background.danger.pressed'
	| 'color.background.danger.bold'
	| 'color.background.danger.bold.hovered'
	| 'color.background.danger.bold.pressed'
	| 'color.background.warning'
	| 'color.background.warning.hovered'
	| 'color.background.warning.pressed'
	| 'color.background.warning.bold'
	| 'color.background.warning.bold.hovered'
	| 'color.background.warning.bold.pressed'
	| 'color.background.success'
	| 'color.background.success.hovered'
	| 'color.background.success.pressed'
	| 'color.background.success.bold'
	| 'color.background.success.bold.hovered'
	| 'color.background.success.bold.pressed'
	| 'color.background.discovery'
	| 'color.background.discovery.hovered'
	| 'color.background.discovery.pressed'
	| 'color.background.discovery.bold'
	| 'color.background.discovery.bold.hovered'
	| 'color.background.discovery.bold.pressed'
	| 'color.background.information'
	| 'color.background.information.hovered'
	| 'color.background.information.pressed'
	| 'color.background.information.bold'
	| 'color.background.information.bold.hovered'
	| 'color.background.information.bold.pressed'
	| 'color.blanket'
	| 'color.blanket.selected'
	| 'color.blanket.danger'
	| 'color.skeleton'
	| 'color.skeleton.subtle'
	| 'elevation.surface'
	| 'elevation.surface.hovered'
	| 'elevation.surface.pressed'
	| 'elevation.surface.overlay'
	| 'elevation.surface.overlay.hovered'
	| 'elevation.surface.overlay.pressed'
	| 'elevation.surface.raised'
	| 'elevation.surface.raised.hovered'
	| 'elevation.surface.raised.pressed'
	| 'elevation.surface.sunken'
	| 'utility.elevation.surface.current';
export type TextAlign = 'center' | 'end' | 'start';
export type TextColor =
	| 'color.text'
	| 'color.text.accent.lime'
	| 'color.text.accent.lime.bolder'
	| 'color.text.accent.red'
	| 'color.text.accent.red.bolder'
	| 'color.text.accent.orange'
	| 'color.text.accent.orange.bolder'
	| 'color.text.accent.yellow'
	| 'color.text.accent.yellow.bolder'
	| 'color.text.accent.green'
	| 'color.text.accent.green.bolder'
	| 'color.text.accent.teal'
	| 'color.text.accent.teal.bolder'
	| 'color.text.accent.blue'
	| 'color.text.accent.blue.bolder'
	| 'color.text.accent.purple'
	| 'color.text.accent.purple.bolder'
	| 'color.text.accent.magenta'
	| 'color.text.accent.magenta.bolder'
	| 'color.text.accent.gray'
	| 'color.text.accent.gray.bolder'
	| 'color.text.disabled'
	| 'color.text.inverse'
	| 'color.text.selected'
	| 'color.text.brand'
	| 'color.text.danger'
	| 'color.text.warning'
	| 'color.text.warning.inverse'
	| 'color.text.success'
	| 'color.text.discovery'
	| 'color.text.information'
	| 'color.text.subtlest'
	| 'color.text.subtle'
	| 'color.link'
	| 'color.link.pressed'
	| 'color.link.visited'
	| 'color.link.visited.pressed';
export type FontSize = 'small' | 'medium' | 'UNSAFE_small' | 'large';
export type FontWeight = 'bold' | 'medium' | 'regular' | 'semibold';
