/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Czech
export default {
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Nápověda k syntaxi',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Vyhledat pomocí AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Vyberte schéma.',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Vyberte schéma.',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'Je nutné vybrat schéma',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Další informace o vyhledávání pomocí AQL',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Chcete-li vyhledávat, začněte psát nebo použijte dotaz AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'Vyhledat objekty',
  'linkDataSource.assets.configmodal.cancelButtonText': 'Zrušit',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Vložit objekt} few {Vložit objekty} many {Vložit objekty} other {Vložit objekty}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Vložit objekty z:',
  'linkDataSource.assets.configmodal.updateObjectsButtonText': 'Aktualizovat tabulku',
  'linkDataSource.basic-filter.assignee.label': 'Pověřená osoba',
  'linkDataSource.basic-filter.dropdown.select.assignee.unassigned': 'Nepřiřazeno',
  'linkDataSource.basic-filter.dropdown.select.placeholder': 'Vyhledat',
  'linkDataSource.basic-filter.error-message': 'Něco se pokazilo',
  'linkDataSource.basic-filter.footer.pagination-details': '{currentDisplayCount} z {totalCount}',
  'linkDataSource.basic-filter.loading-message': 'Načítání…',
  'linkDataSource.basic-filter.no-options-message': 'Nebyly nalezeny žádné shody',
  'linkDataSource.basic-filter.project.label': 'Projekt',
  'linkDataSource.basic-filter.showMoreButton': 'Zobrazit více',
  'linkDataSource.basic-filter.status.label': 'Stav',
  'linkDataSource.basic-filter.type.label': 'Typ',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'Vaše vyhledávání vrátilo příliš mnoho výsledků.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2': 'Zkuste to znovu s konkrétnějšími klíčovými slovy.',
  'linkDataSource.column-picker.search': 'Vyhledat pole',
  'linkDataSource.column-picker.tooltip': 'Konfigurovat sloupce',
  'linkDataSource.datasource.table.authConnectButtonText': 'Připojit',
  'linkDataSource.datasource.table.authScreenDescriptionText':
    'Připojte svůj účet {providerName} a spolupracujte pomocí všech produktů Atlassian.',
  'linkDataSource.datasource.table.authScreenHeaderText': 'Připojte svůj účet {providerName}',
  'linkDataSource.datasource.table.learnMoreAboutSmartLinks': 'Další informace o chytrých odkazech',
  'linkDataSource.jira-issues.accessInstructions': 'Chcete-li požádat o přístup, obraťte se na správce webu.',
  'linkDataSource.jira-issues.accessRequired': 'K tomuto obsahu nemáte přístup',
  'linkDataSource.jira-issues.accessRequiredWithSite': 'K následujícímu webu nemáte přístup:',
  'linkDataSource.jira-issues.checkConnection':
    'Zkontrolujte připojení a obnovte stránku nebo to zkuste znovu později.',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete tento dotaz v Jira</a> a zkontrolujte jej.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'U tohoto dotazu nemůžete přepnout na základní režim.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Základní',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': 'Vyhledat požadavky pomocí klíčového slova',
  'linkDataSource.jira-issues.configmodal.cancelButtonText': 'Zrušit',
  'linkDataSource.jira-issues.configmodal.chooseSite': 'Vyberte web.',
  'linkDataSource.jira-issues.configmodal.inlineLinkViewModeDescription':
    'Zobrazit počet výsledků vyhledávání nebo jako vložený chytrý odkaz',
  'linkDataSource.jira-issues.configmodal.inlineLinkViewModeLabel': 'Vložený odkaz',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Vložit požadavky',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Vložit požadavky Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Vložit požadavky Jira z:',
  'linkDataSource.jira-issues.configmodal.issue':
    '{totalCount, plural, one {požadavek} few {požadavky} many {požadavku} other {požadavků}}',
  'linkDataSource.jira-issues.configmodal.tableViewModeDescription': 'Zobrazit výsledky vyhledávání Jira jako tabulku',
  'linkDataSource.jira-issues.configmodal.tableViewModeLabel': 'Tabulka',
  'linkDataSource.jira-issues.no.jira.sites.access.description': 'Chcete-li požádat o přístup, obraťte se na správce.',
  'linkDataSource.jira-issues.no.jira.sites.access.title': 'Nemáte přístup k žádným webům Jira',
  'linkDataSource.jira-issues.noResultsFound': 'Nebyly nalezeny žádné výsledky',
  'linkDataSource.jira-issues.refresh': 'Obnovit',
  'linkDataSource.jira-issues.unableToLoadItems': 'Načtení položek se nezdařilo',
  'linkDataSource.jira-issues.unableToLoadResults': 'Načtení výsledků se nezdařilo',
  'linkDataSource.modal-initial-state.beta': 'Beta',
  'linkDataSource.modal-initial-state.learnMoreLink': 'Jak vyhledávat pomocí JQL',
  'linkDataSource.modal-initial-state.searchDescription-basic':
    'Vyhledejte požadavky, které chcete vložit, pomocí klíčového slova.',
  'linkDataSource.modal-initial-state.searchDescription-jql':
    'Vyhledávejte požadavky pomocí JQL (Jira Query Language).',
  'linkDataSource.modal-initial-state.searchTitle': 'Vyhledejte požadavky Jira',
  'linkDataSource.render-type.boolean.false': 'Ne',
  'linkDataSource.render-type.boolean.true': 'Ano',
  'linkDataSource.render-type.user.default.display.name': 'Nepřiřazeno',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Synchronizováno právě teď',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Synchronizováno {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, one {položka} few {položky} many {položky} other {položek}}',
  'linkDataSource.table-footer.loading': 'Načítání…',
  'linkDataSource.table-footer.refresh': 'Obnovit',
};
