/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Czech
export default {
  '1M7iXg': 'Editor dotazů JQL',
  'linkDataSource.accessInstructions': 'Chcete-li požádat o přístup, obraťte se na správce webu.',
  'linkDataSource.accessRequired': 'K tomuto obsahu nemáte přístup',
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Nápověda k syntaxi',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Vyhledat pomocí AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Vyberte schéma.',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Vyberte schéma.',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'Je nutné vybrat schéma',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Další informace o vyhledávání pomocí AQL',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLinkOld':
    'Další informace o vyhledávání pomocí AQL',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Chcete-li vyhledávat, začněte psát nebo použijte dotaz AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle':
    'Vyhledat objekty nebo typy objektů',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Vložit objekt} few {Vložit objekty} many {Vložit objekty} other {Vložit objekty}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Vložit objekty z:',
  'linkDataSource.assets.configmodal.updateObjectsButtonText': 'Aktualizovat tabulku',
  'linkDataSource.basic-filter.assignee.label': 'Pověřená osoba',
  'linkDataSource.basic-filter.assignee.searchPlaceholder': 'Vyhledat pověřenou osobu',
  'linkDataSource.basic-filter.dropdown.select.assignee.unassigned': 'Nepřiřazeno',
  'linkDataSource.basic-filter.dropdown.select.placeholder': 'Vyhledat',
  'linkDataSource.basic-filter.error-description': 'Zkontrolujte připojení a obnovte stránku',
  'linkDataSource.basic-filter.errorMessage': 'Při pokusu o načtení výsledků se vyskytl problém.',
  'linkDataSource.basic-filter.errorMessageOld': 'Něco se pokazilo',
  'linkDataSource.basic-filter.footer.pagination-details': '{currentDisplayCount} z {totalCount}',
  'linkDataSource.basic-filter.loading-message': 'Načítání…',
  'linkDataSource.basic-filter.no-options-description': 'Zkuste to znovu s jiným termínem.',
  'linkDataSource.basic-filter.no-options-message': 'Vašemu vyhledávání neodpovídají žádné výsledky',
  'linkDataSource.basic-filter.no-options-message-old': 'Nebyly nalezeny žádné shody',
  'linkDataSource.basic-filter.project.label': 'Projekt',
  'linkDataSource.basic-filter.project.label-galaxia': 'Prostor',
  'linkDataSource.basic-filter.project.searchPlaceholder': 'Vyhledat projekty',
  'linkDataSource.basic-filter.project.searchPlaceholder-galaxia': 'Vyhledat prostory',
  'linkDataSource.basic-filter.showMoreButton': 'Zobrazit více',
  'linkDataSource.basic-filter.status.label': 'Stav',
  'linkDataSource.basic-filter.status.searchPlaceholder': 'Vyhledat stav',
  'linkDataSource.basic-filter.type.label': 'Typ práce',
  'linkDataSource.basic-filter.type.labelOld': 'Typ',
  'linkDataSource.basic-filter.type.searchPlaceholder': 'Vyhledat typ požadavku',
  'linkDataSource.checkConnection': 'Zkontrolujte připojení a obnovte stránku nebo to zkuste znovu později.',
  'linkDataSource.clol-basic-filter.editedOrCreatedBy.label': 'Upraveno nebo vytvořeno uživatelem',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'Vaše vyhledávání vrátilo příliš mnoho výsledků.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2': 'Zkuste to znovu s konkrétnějšími klíčovými slovy.',
  'linkDataSource.column-picker.search': 'Vyhledat pole',
  'linkDataSource.column-picker.tooltip': 'Konfigurovat sloupce',
  'linkDataSource.configmodal.basicTextSearchPlaceholder': 'Vyhledat požadavky pomocí klíčového slova',
  'linkDataSource.configmodal.basicTextSearchPlaceholder-issue-term-refresh':
    'Vyhledat požadavky pomocí klíčového slova',
  'linkDataSource.configmodal.cancelButtonText': 'Zrušit',
  'linkDataSource.confluence-search.checkConnectionWithSource':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete tento projekt v Confluence</a> a zkontrolujte jej.',
  'linkDataSource.confluence-search.checkConnectionWithSource-galaxia':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete tento prostor Jira v Confluence</a> a zkontrolujte jej.',
  'linkDataSource.confluence-search.configmodal.cancelButtonText': 'Zrušit',
  'linkDataSource.confluence-search.configmodal.date.range.after.label': 'po {date}',
  'linkDataSource.confluence-search.configmodal.date.range.any.time': 'Kdykoliv',
  'linkDataSource.confluence-search.configmodal.date.range.before.label': 'před {date}',
  'linkDataSource.confluence-search.configmodal.date.range.custom': 'Vlastní',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.after.end':
    'Datum Od musí být před datem Do.',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.after.today':
    'Datum Od nesmí být v budoucnosti.',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.to.after.today':
    'Datum Do nesmí být v budoucnosti.',
  'linkDataSource.confluence-search.configmodal.date.range.error': 'Chyba rozsahu dat',
  'linkDataSource.confluence-search.configmodal.date.range.from': 'Od',
  'linkDataSource.confluence-search.configmodal.date.range.input.placeholder': 'Vyberte datum.',
  'linkDataSource.confluence-search.configmodal.date.range.last.month': 'Posledních 30 dní',
  'linkDataSource.confluence-search.configmodal.date.range.last.week': 'Posledních 7 dní',
  'linkDataSource.confluence-search.configmodal.date.range.last.year': 'Poslední rok',
  'linkDataSource.confluence-search.configmodal.date.range.title': 'Naposledy aktualizováno',
  'linkDataSource.confluence-search.configmodal.date.range.to': 'Do',
  'linkDataSource.confluence-search.configmodal.date.range.to.Label': 'do',
  'linkDataSource.confluence-search.configmodal.date.range.today': 'Dnes',
  'linkDataSource.confluence-search.configmodal.date.range.update.button': 'Aktualizovat',
  'linkDataSource.confluence-search.configmodal.date.range.yesterday': 'Včera',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitle': 'Vložit seznam Confluence',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitleManySites': 'Vložit seznam Confluence z:',
  'linkDataSource.confluence-search.configmodal.insertResultsButtonText': 'Vložit výsledky',
  'linkDataSource.confluence-search.configmodal.placeholder.issues': '### Výsledky',
  'linkDataSource.confluence-search.configmodal.searchLabel':
    'Zadejte klíčová slova k vyhledání stránek, příloh a dalších položek.',
  'linkDataSource.confluence-search.no.confluence.sites.access.description':
    'Chcete-li požádat o přístup, obraťte se na správce.',
  'linkDataSource.confluence-search.no.confluence.sites.access.title': 'Nemáte přístup k žádným webům Confluence',
  'linkDataSource.datasource.table.authConnectButtonText': 'Připojit',
  'linkDataSource.datasource.table.authScreenDescriptionText':
    'Připojte svůj účet {providerName} a spolupracujte pomocí všech produktů Atlassian.',
  'linkDataSource.datasource.table.authScreenDescriptionText-appify':
    'Připojte svůj účet {providerName} a spolupracujte pomocí všech aplikací Atlassian.',
  'linkDataSource.datasource.table.authScreenHeaderText': 'Připojte svůj účet {providerName}',
  'linkDataSource.datasource.table.learnMoreAboutSmartLinks': 'Další informace o chytrých odkazech',
  'linkDataSource.issue-line-table.error-403-description': 'K úpravě této položky potřebujete správná oprávnění.',
  'linkDataSource.issue-line-table.error-403-title': 'Změny nebyly uloženy',
  'linkDataSource.issue-line-table.error-generic-description':
    'Při pokusu o dokončení aktualizace se vyskytl problém. Počkejte pár minut a zkuste to znovu. Pokud se problém opakuje, kontaktujte podporu.',
  'linkDataSource.issue-line-table.error-generic-title': 'Něco se pokazilo',
  'linkDataSource.issue-line-table.fetch-action-error-generic-description':
    'Počkejte pár minut a zkuste to znovu. Zkontrolujte nastavení projektu, a pokud se problém opakuje, kontaktujte podporu.',
  'linkDataSource.issue-line-table.fetch-action-error-generic-description-galaxia':
    'Počkejte pár minut a zkuste to znovu. Zkontrolujte nastavení prostoru, a pokud se problém opakuje, kontaktujte podporu.',
  'linkDataSource.issue-line-table.fetch-action-error-generic-title': 'Při načítání možností došlo k problémům',
  'linkDataSource.issue-line-table.unwrap-text': 'Zrušit zalamování textu',
  'linkDataSource.issue-line-table.wrap-text': 'Zalomit text',
  'linkDataSource.issueLikeTable.renderType.dateRange.fullRange': '{start} - {end}',
  'linkDataSource.issueLikeTable.renderType.dateRange.quarterRange': '{startMonth}–{endMonth}, {year}',
  'linkDataSource.issueLikeTable.renderType.dateRange.quarterRangeOverYears':
    '{startMonth}–{endMonth}, {startYear}–{endYear}',
  'linkDataSource.accessRequiredWithSite': 'Nemáte přístup k webu',
  'linkDataSource.jira-issues.checkConnection.confluence':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete toto vyhledávání v Confluence</a> a zkontrolujte jej.',
  'linkDataSource.jira-issues.checkConnection.jira':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete toto vyhledávání v Jira</a> a zkontrolujte jej.',
  'linkDataSource.checkConnectionWithSource':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete tento dotaz v Jira</a> a zkontrolujte jej.',
  'linkDataSource.jira-issues.checkConnectionWithSource.visual-refresh-sllv':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete tento projekt v Jira</a> a zkontrolujte jej.',
  'linkDataSource.jira-issues.checkConnectionWithSource.visual-refresh-sllv-galaxia':
    'Zkontrolujte připojení a obnovte stránku nebo <a>otevřete tento prostor v Jira</a> a zkontrolujte jej.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'U tohoto dotazu nemůžete přepnout na základní režim.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Základní',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder-issue-term-refresh':
    'Vyhledat požadavky pomocí klíčového slova',
  'linkDataSource.site-selector.configmodal.chooseSite': 'Vyberte web',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Vložit požadavky',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText-issue-term-sllv': 'Vložit výsledky',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Vložit požadavky Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle-issue-term-refresh': 'Vložit požadavky Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Vložit požadavky Jira z:',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites-issue-term-refresh': 'Vložit požadavky Jira z:',
  'linkDataSource.jira-issues.configmodal.placeholder.issues-issue-term-refresh': '### požadavky/ů',
  'linkDataSource.jira-issues.configmodal.viewModeInlineLinkDescription':
    'Zobrazit počet výsledků vyhledávání nebo jako vložený chytrý odkaz',
  'linkDataSource.jira-issues.configmodal.viewModeInlineLinkDescriptionOld':
    'Zobrazit počet výsledků vyhledávání jako vložený chytrý odkaz',
  'linkDataSource.jira-issues.configmodal.viewModeInlineLinkLabel': 'Vložený odkaz',
  'linkDataSource.jira-issues.configmodal.viewModeListDescription': 'Zobrazit počet výsledků vyhledávání jako seznam',
  'linkDataSource.jira-issues.configmodal.viewModeListDescriptionOld': 'Zobrazit výsledky vyhledávání jako seznam',
  'linkDataSource.jira-issues.configmodal.viewModeListLabel': 'Sloupec',
  'linkDataSource.jira-issues.learnMoreLink': 'Další informace o vyhledávání pomocí JQL',
  'linkDataSource.no.jira.sites.access.description': 'Chcete-li požádat o přístup, obraťte se na správce.',
  'linkDataSource.no.jira.sites.access.title': 'Nemáte přístup k žádným webům Jira',
  'linkDataSource.noResultsFound': 'Vašemu vyhledávání neodpovídají žádné výsledky',
  'linkDataSource.jira-issues.noResultsFound.description': 'Zkuste to znovu s jiným termínem.',
  'linkDataSource.refresh': 'Obnovit',
  'linkDataSource.jira-issues.searchDescription-basic':
    'Vyhledejte požadavky, které chcete vložit, pomocí klíčového slova.',
  'linkDataSource.jira-issues.searchDescription-jql': 'Vyhledávejte požadavky pomocí JQL (Jira Query Language).',
  'linkDataSource.jira-issues.searchJiraTitle': 'Vyhledat požadavky Jira',
  'linkDataSource.unableToLoadResults': 'Při pokusu o načtení výsledků se vyskytl problém.',
  'linkDataSource.modal-initial-state.beta': 'Beta',
  'linkDataSource.modal-initial-state.confluenceSearchTitle': 'Vyhledat stránky Confluence',
  'linkDataSource.modal-initial-state.jiraSearchTitle': 'Vyhledat požadavky Jira',
  'linkDataSource.modal-initial-state.learnMoreLinkOld': 'Jak vyhledávat pomocí JQL',
  'linkDataSource.modal-initial-state.searchDescription-basic-issue-term-refresh':
    'Vyhledejte požadavky, které chcete vložit, pomocí klíčového slova.',
  'linkDataSource.modal-initial-state.searchDescription-basic.Sllv':
    'Chcete-li vyhledávat, začněte psát nebo použijte dotaz JQL.',
  'linkDataSource.modal-initial-state.searchDescription-confluence':
    'Vyhledejte stránky, které chcete vložit, pomocí klíčového slova.',
  'linkDataSource.modal-initial-state.searchDescription-jql-issue-term-refresh':
    'Vyhledávejte požadavky pomocí JQL (Jira Query Language).',
  'linkDataSource.modal-initial-state.searchTitle-issue-term-refresh': 'Vyhledat požadavky Jira',
  'linkDataSource.render-type.boolean.false': 'Ne',
  'linkDataSource.render-type.boolean.true': 'Ano',
  'linkDataSource.render-type.user.default.display.name': 'Nepřiřazeno',
  'linkDataSource.search.configmodal.issueCountText':
    '{searchCount, plural, one {{searchCount,number} požadavek} few {{searchCount,number} požadavky} many {{searchCount,number} požadavku} other {{searchCount,number} požadavků}}',
  'linkDataSource.search.configmodal.issueCountText-issue-term-refresh':
    '{searchCount, plural, one {{searchCount,number} požadavek} few {{searchCount,number} požadavky} many {{searchCount,number} požadavku} other {{searchCount,number} požadavků}}',
  'linkDataSource.search.configmodal.itemCountText':
    '{searchCount, plural, one {{searchCount,number} položka} few {{searchCount,number} položky} many {{searchCount,number} položky} other {{searchCount,number} položek}}',
  'linkDataSource.search.configmodal.resultCountText':
    '{searchCount, plural, one {{searchCount,number} výsledek} few {{searchCount,number} výsledky} many {{searchCount,number} výsledku} other {{searchCount,number} výsledků}}',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Synchronizováno právě teď',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Synchronizováno {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, one {položka} few {položky} many {položky} other {položek}}',
  'linkDataSource.table-footer.loading': 'Načítání…',
  'linkDataSource.table-footer.power-by-jsm': 'Využívá technologii Aktiva v Jira Service Management',
  'linkDataSource.table-footer.powered-by-assets': 'Využívá Aktiva',
  'linkDataSource.table-footer.refresh': 'Obnovit',
  'linkDataSource.unableToLoadItems': 'Načtení položek se nezdařilo',
};
