/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//German (Germany)
export default {
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Syntaxhilfe',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Mit AQL suchen',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Schema auswählen',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Schema auswählen',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'Schema erforderlich',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Weitere Informationen zur Suche mit AQL',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Um zu suchen, beginnen Sie mit der Eingabe, oder verwenden Sie AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'Objekte suchen',
  'linkDataSource.assets.configmodal.cancelButtonText': 'Abbrechen',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Objekt einfügen} other {Objekte einfügen}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Objekte einfügen aus',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'Ihre Suche brachte zu viele Ergebnisse.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2':
    'Versuchen Sie es erneut mit konkreteren Stichwörtern.',
  'linkDataSource.column-picker.search': 'Nach Feldern suchen',
  'linkDataSource.column-picker.tooltip': 'Spalten konfigurieren',
  'linkDataSource.jira-issues.accessInstructions':
    'Wenden Sie sich an Ihren Site-Administrator, um Zugriff zu beantragen.',
  'linkDataSource.jira-issues.accessRequired': 'Sie haben keinen Zugriff auf diesen Inhalt',
  'linkDataSource.jira-issues.accessRequiredWithSite': 'Sie haben auf folgende Site keinen Zugriff:',
  'linkDataSource.jira-issues.checkConnection':
    'Überprüfen Sie Ihre Verbindung und aktualisieren Sie dann die Seite oder versuchen Sie es später erneut.',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    'Überprüfen Sie Ihre Verbindung und aktualisieren Sie die Seite oder <a>öffnen Sie diese Abfrage in Jira</a>, um sie zu überprüfen.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'Für diese Anfrage können Sie nicht in den Standardmodus wechseln.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Standard',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': 'Mit Stichwörtern nach Vorgängen suchen',
  'linkDataSource.jira-issues.configmodal.cancelButtonText': 'Abbrechen',
  'linkDataSource.jira-issues.configmodal.chooseSite': 'Site wählen',
  'linkDataSource.jira-issues.configmodal.countViewModeLabel': 'Anzahlansicht',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Vorgänge einfügen',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Jira-Vorgänge einfügen',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Jira-Vorgänge von folgender Site einfügen:',
  'linkDataSource.jira-issues.configmodal.issue': '{totalCount, plural, one {Vorgang} other {Vorgänge}}',
  'linkDataSource.jira-issues.configmodal.issueViewModeLabel': 'Vorgangsansicht',
  'linkDataSource.jira-issues.no.jira.sites.access.description':
    'Wenden Sie sich an Ihren Administrator, um Zugriff anzufordern.',
  'linkDataSource.jira-issues.no.jira.sites.access.title': 'Sie haben keinen Zugriff auf Jira-Sites',
  'linkDataSource.jira-issues.noResultsFound': 'Keine Ergebnisse gefunden',
  'linkDataSource.jira-issues.refresh': 'Aktualisieren',
  'linkDataSource.jira-issues.unableToLoadItems': 'Elemente konnten nicht geladen werden',
  'linkDataSource.jira-issues.unableToLoadResults': 'Ergebnisse konnten nicht geladen werden',
  'linkDataSource.modal-initial-state.beta': 'Beta',
  'linkDataSource.modal-initial-state.learnMoreLink': 'Weitere Informationen zur Suche mit JQL',
  'linkDataSource.modal-initial-state.searchTitle': 'Nach Jira-Vorgängen suchen',
  'linkDataSource.render-type.boolean.false': 'Nein',
  'linkDataSource.render-type.boolean.true': 'Ja',
  'linkDataSource.render-type.user.default.display.name': 'Nicht zugewiesen',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Gerade synchronisiert',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Synchronisiert am {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, one {Element} other {Elemente}}',
  'linkDataSource.table-footer.loading': 'Wird geladen …',
  'linkDataSource.table-footer.refresh': 'Aktualisieren',
};
