/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Spanish (International)
export default {
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Ayuda de Sintaxis',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Buscar con AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Seleccionar esquema',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Seleccionar esquema',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'El esquema es obligatorio',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Obtén más información sobre cómo realizar búsquedas con AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Empieza a escribir o utiliza AQL para buscar.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'Buscar objetos',
  'linkDataSource.assets.configmodal.cancelButtonText': 'Cancelar',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Insertar objeto} other {Insertar objetos}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Insertar objetos de',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'Tu búsqueda ha devuelto demasiados resultados.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2':
    'Vuelve a intentarlo con palabras clave más específicas.',
  'linkDataSource.column-picker.search': 'Buscar campos',
  'linkDataSource.column-picker.tooltip': 'Configurar columnas',
  'linkDataSource.jira-issues.accessInstructions':
    'Para solicitar acceso, ponte en contacto con tu administrador del sitio.',
  'linkDataSource.jira-issues.accessRequired': 'No tienes acceso a este sitio',
  'linkDataSource.jira-issues.accessRequiredWithSite': 'No tienes acceso al siguiente sitio:',
  'linkDataSource.jira-issues.checkConnection':
    'Comprueba tu conexión y, luego, actualiza o vuelve a intentarlo más tarde.',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    'Comprueba la conexión y actualiza, o bien <a>abre esta consulta en Jira</a> para revisarla.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'No puedes cambiar a Básica esta consulta.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Básica',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': 'Buscar incidencias por palabra clave',
  'linkDataSource.jira-issues.configmodal.cancelButtonText': 'Cancelar',
  'linkDataSource.jira-issues.configmodal.chooseSite': 'Elegir sitio',
  'linkDataSource.jira-issues.configmodal.countViewModeLabel': 'Vista de recuento',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Insertar incidencias',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Insertar incidencias de Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Insertar incidencias de Jira desde',
  'linkDataSource.jira-issues.configmodal.issue': '{totalCount, plural, one {incidencia} other {incidencias}}',
  'linkDataSource.jira-issues.configmodal.issueViewModeLabel': 'Vista de la incidencia',
  'linkDataSource.jira-issues.noResultsFound': 'No se han encontrado resultados',
  'linkDataSource.jira-issues.refresh': 'Actualizar',
  'linkDataSource.jira-issues.unableToLoadItems': 'No se han podido cargar los elementos',
  'linkDataSource.jira-issues.unableToLoadResults': 'No se pueden cargar los resultados',
  'linkDataSource.modal-initial-state.beta': 'Beta',
  'linkDataSource.modal-initial-state.learnMoreLink': 'Más información sobre cómo buscar con JQL',
  'linkDataSource.modal-initial-state.searchDescription': 'Utiliza JQL (Jira Query Language) para buscar incidencias.',
  'linkDataSource.modal-initial-state.searchTitle': 'Buscar incidencias de Jira',
  'linkDataSource.render-type.boolean.false': 'No',
  'linkDataSource.render-type.boolean.true': 'Sí',
  'linkDataSource.render-type.user.default.display.name': 'Sin asignar',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Sincronización hace un momento',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Última sincronización: {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, one {elemento} other {elementos}}',
  'linkDataSource.table-footer.loading': 'Cargando...',
  'linkDataSource.table-footer.refresh': 'Actualizar',
};
