/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Korean
export default {
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': '구문 도움말',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'AQL로 검색',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': '스키마 선택',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': '스키마 선택',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': '스키마가 필요합니다',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'AQL을 사용한 검색에 대해 자세히 알아보세요.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    '입력을 시작하거나 AQL을 사용하여 검색합니다.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': '개체 검색',
  'linkDataSource.assets.configmodal.cancelButtonText': '취소',
  'linkDataSource.assets.configmodal.insertIssuesButtonText': '{objectsCount, plural, other {개체 삽입}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': '다음의 개체 삽입',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': '검색 결과가 너무 많습니다.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2': '더 구체적인 키워드로 다시 시도하세요.',
  'linkDataSource.column-picker.search': '필드 검색',
  'linkDataSource.column-picker.tooltip': '열 구성',
  'linkDataSource.jira-issues.accessInstructions': '액세스 권한을 요청하려면 사이트 관리자에게 문의하세요.',
  'linkDataSource.jira-issues.accessRequired': '이 콘텐츠에 대한 액세스 권한이 없습니다',
  'linkDataSource.jira-issues.accessRequiredWithSite': '다음 사이트에 대한 액세스 권한이 없습니다.',
  'linkDataSource.jira-issues.checkConnection': '연결을 확인하고 새로 고치거나 나중에 다시 시도하세요.',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    '연결을 확인하고 새로 고치거나 <a>Jira에서 이 쿼리를 열어</a> 검토하세요.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText': '이 쿼리는 기본으로 전환할 수 없습니다.',
  'linkDataSource.jira-issues.configmodal.basicModeText': '기본',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': '키워드로 이슈 검색',
  'linkDataSource.jira-issues.configmodal.cancelButtonText': '취소',
  'linkDataSource.jira-issues.configmodal.chooseSite': '사이트 선택',
  'linkDataSource.jira-issues.configmodal.countViewModeLabel': '개수 보기',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': '이슈 삽입',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Jira 이슈 삽입',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': '다음의 Jira 이슈 삽입',
  'linkDataSource.jira-issues.configmodal.issue': '{totalCount, plural, other {이슈}}',
  'linkDataSource.jira-issues.configmodal.issueViewModeLabel': '이슈 보기',
  'linkDataSource.jira-issues.no.jira.sites.access.description': '액세스를 요청하려면 관리자에게 문의하세요.',
  'linkDataSource.jira-issues.no.jira.sites.access.title': 'Jira 사이트에 대한 액세스 권한이 없습니다',
  'linkDataSource.jira-issues.noResultsFound': '결과 없음',
  'linkDataSource.jira-issues.refresh': '새로 고침',
  'linkDataSource.jira-issues.unableToLoadItems': '항목을 로드할 수 없음',
  'linkDataSource.jira-issues.unableToLoadResults': '결과를 로드할 수 없음',
  'linkDataSource.modal-initial-state.beta': '베타',
  'linkDataSource.modal-initial-state.learnMoreLink': 'JQL로 검색하는 방법 알아보기',
  'linkDataSource.modal-initial-state.searchTitle': 'Jira 이슈 검색',
  'linkDataSource.render-type.boolean.false': '아니요',
  'linkDataSource.render-type.boolean.true': '예',
  'linkDataSource.render-type.user.default.display.name': '할당되지 않음',
  'linkDataSource.table-footer.date_formatter.under_one_minute': '방금 동기화',
  'linkDataSource.table-footer.date_formatter.under_over_minute': '{date}에 동기화',
  'linkDataSource.table-footer.item': '{itemCount, plural, other {항목}}',
  'linkDataSource.table-footer.loading': '로드 중...',
  'linkDataSource.table-footer.refresh': '새로 고침',
};
