/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Dutch (Netherlands)
export default {
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Syntaxhulp',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Zoeken via AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Selecteer schema',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Selecteer schema',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'Er is een schema nodig',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Meer informatie over zoeken met AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Begin met typen of gebruik een AQL om te zoeken.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'Objecten zoeken',
  'linkDataSource.assets.configmodal.cancelButtonText': 'Annuleren',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Object invoegen} other {Objecten invoegen}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Objecten invoegen van',
  'linkDataSource.assets.configmodal.updateObjectsButtonText': 'Tabel bijwerken',
  'linkDataSource.basic-filter.assignee.label': 'Uitvoerder',
  'linkDataSource.basic-filter.dropdown.select.assignee.unassigned': 'Niet toegewezen',
  'linkDataSource.basic-filter.dropdown.select.placeholder': 'Zoeken',
  'linkDataSource.basic-filter.error-message': 'Er is iets misgegaan',
  'linkDataSource.basic-filter.footer.pagination-details': '{currentDisplayCount} van {totalCount}',
  'linkDataSource.basic-filter.loading-message': 'Laden ...',
  'linkDataSource.basic-filter.no-options-message': 'Geen overeenkomsten gevonden',
  'linkDataSource.basic-filter.project.label': 'Project',
  'linkDataSource.basic-filter.showMoreButton': 'Meer tonen',
  'linkDataSource.basic-filter.status.label': 'Status',
  'linkDataSource.basic-filter.type.label': 'Type',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'Je zoekopdracht leverde teveel resultaten op.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2': 'Probeer het opnieuw met specifiekere trefwoorden.',
  'linkDataSource.column-picker.search': 'Zoek naar velden',
  'linkDataSource.column-picker.tooltip': 'Kolommen configureren',
  'linkDataSource.datasource.table.authConnectButtonText': 'Koppelen',
  'linkDataSource.datasource.table.authScreenDescriptionText':
    'Koppel je {providerName}-account om samen te werken op verschillende Atlassian-producten.',
  'linkDataSource.datasource.table.authScreenHeaderText': 'Koppel je {providerName}-account',
  'linkDataSource.datasource.table.learnMoreAboutSmartLinks': 'Meer informatie over Smart Links.',
  'linkDataSource.jira-issues.accessInstructions': 'Neem contact op met je sitebeheerder om toegang aan te vragen.',
  'linkDataSource.jira-issues.accessRequired': 'Je hebt geen toegang tot deze inhoud',
  'linkDataSource.jira-issues.accessRequiredWithSite': 'Je hebt geen toegang tot de volgende site:',
  'linkDataSource.jira-issues.checkConnection':
    'Controleer je verbinding en vernieuw de pagina of probeer het later nogmaals.',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    'Controleer je verbinding en ververs de pagina of <a>open deze zoekopdracht in Jira</a> ter controle.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'Je kunt niet overschakelen naar basis voor deze query.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Basis',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': 'Zoek naar issues met trefwoorden',
  'linkDataSource.jira-issues.configmodal.cancelButtonText': 'Annuleren',
  'linkDataSource.jira-issues.configmodal.chooseSite': 'Site kiezen',
  'linkDataSource.jira-issues.configmodal.inlineLinkViewModeDescription':
    'Het aantal zoekresultaten weergeven of als een inline Smart Link',
  'linkDataSource.jira-issues.configmodal.inlineLinkViewModeLabel': 'Inline-link',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Issues invoegen',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Jira-issues invoegen',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Jira-issues invoegen van',
  'linkDataSource.jira-issues.configmodal.issue': '{totalCount, plural, one {issue} other {issues}}',
  'linkDataSource.jira-issues.configmodal.tableViewModeDescription': 'Jira-zoekresultaten als tabel weergeven',
  'linkDataSource.jira-issues.configmodal.tableViewModeLabel': 'Tabel',
  'linkDataSource.jira-issues.no.jira.sites.access.description':
    'Neem contact op met je beheerder om toegang aan te vragen.',
  'linkDataSource.jira-issues.no.jira.sites.access.title': 'Je hebt geen toegang tot Jira-sites',
  'linkDataSource.jira-issues.noResultsFound': 'Geen resultaten gevonden',
  'linkDataSource.jira-issues.refresh': 'Vernieuwen',
  'linkDataSource.jira-issues.unableToLoadItems': 'Kan items niet laden',
  'linkDataSource.jira-issues.unableToLoadResults': 'Resultaten kunnen niet worden geladen',
  'linkDataSource.modal-initial-state.beta': 'Bèta',
  'linkDataSource.modal-initial-state.learnMoreLink': 'Meer informatie over zoeken met JQL',
  'linkDataSource.modal-initial-state.searchDescription-basic': 'Zoek met trefwoorden om issues toe te voegen.',
  'linkDataSource.modal-initial-state.searchDescription-jql':
    'Gebruik JQL ( Jira Query Language) om te zoeken naar issues.',
  'linkDataSource.modal-initial-state.searchTitle': 'Zoek naar Jira-issues',
  'linkDataSource.render-type.boolean.false': 'Nee',
  'linkDataSource.render-type.boolean.true': 'Ja',
  'linkDataSource.render-type.user.default.display.name': 'Niet-toegewezen',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Zojuist gesynchroniseerd',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Gesynchroniseerd op {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, one {item} other {items}}',
  'linkDataSource.table-footer.loading': 'Laden...',
  'linkDataSource.table-footer.refresh': 'Vernieuwen',
};
