/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Dutch (Netherlands)
export default {
  'linkDataSource.accessInstructions': 'Neem contact op met je sitebeheerder om toegang aan te vragen.',
  'linkDataSource.accessRequired': 'Je hebt geen toegang tot deze inhoud',
  'linkDataSource.accessRequiredWithSite': 'Je hebt geen toegang tot de volgende site:',
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Syntaxhulp',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Zoeken via AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Selecteer schema',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Selecteer schema',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'Er is een schema nodig',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Meer informatie over zoeken met AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Begin met typen of gebruik een AQL om te zoeken.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'Objecten zoeken',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Object invoegen} other {Objecten invoegen}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Objecten invoegen van',
  'linkDataSource.assets.configmodal.updateObjectsButtonText': 'Tabel bijwerken',
  'linkDataSource.basic-filter.assignee.label': 'Uitvoerder',
  'linkDataSource.basic-filter.dropdown.select.assignee.unassigned': 'Niet toegewezen',
  'linkDataSource.basic-filter.dropdown.select.placeholder': 'Zoeken',
  'linkDataSource.basic-filter.error-message': 'Er is iets misgegaan',
  'linkDataSource.basic-filter.footer.pagination-details': '{currentDisplayCount} van {totalCount}',
  'linkDataSource.basic-filter.loading-message': 'Laden ...',
  'linkDataSource.basic-filter.no-options-message': 'Geen overeenkomsten gevonden',
  'linkDataSource.basic-filter.project.label': 'Project',
  'linkDataSource.basic-filter.showMoreButton': 'Meer tonen',
  'linkDataSource.basic-filter.status.label': 'Status',
  'linkDataSource.basic-filter.type.label': 'Type',
  'linkDataSource.checkConnection': 'Controleer je verbinding en vernieuw de pagina of probeer het later nogmaals.',
  'linkDataSource.clol-basic-filter.editedOrCreatedBy.label': 'Bewerkt of aangemaakt door',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'Je zoekopdracht leverde teveel resultaten op.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2': 'Probeer het opnieuw met specifiekere trefwoorden.',
  'linkDataSource.column-picker.search': 'Zoek naar velden',
  'linkDataSource.column-picker.tooltip': 'Kolommen configureren',
  'linkDataSource.configmodal.basicTextSearchPlaceholder': 'Zoek naar issues met trefwoorden',
  'linkDataSource.configmodal.cancelButtonText': 'Annuleren',
  'linkDataSource.confluence-search.configmodal.cancelButtonText': 'Annuleren',
  'linkDataSource.confluence-search.configmodal.date.range.after.label': 'na {date}',
  'linkDataSource.confluence-search.configmodal.date.range.any.time': 'Willekeurig',
  'linkDataSource.confluence-search.configmodal.date.range.before.label': 'voor {date}',
  'linkDataSource.confluence-search.configmodal.date.range.custom': 'Aangepast',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.after.end':
    'De begindatum moet eerder zijn dan de einddatum',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.after.today':
    'De begindatum kan niet in de toekomst liggen',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.to.after.today':
    'De einddatum kan niet in de toekomst liggen',
  'linkDataSource.confluence-search.configmodal.date.range.from': 'Vanaf',
  'linkDataSource.confluence-search.configmodal.date.range.input.placeholder': 'Kies een datum',
  'linkDataSource.confluence-search.configmodal.date.range.last.month': 'Afgelopen 30 dagen',
  'linkDataSource.confluence-search.configmodal.date.range.last.week': 'Afgelopen 7 dagen',
  'linkDataSource.confluence-search.configmodal.date.range.last.year': 'Afgelopen jaar',
  'linkDataSource.confluence-search.configmodal.date.range.title': 'Voor het laatst bijgewerkt',
  'linkDataSource.confluence-search.configmodal.date.range.to': 'tot',
  'linkDataSource.confluence-search.configmodal.date.range.to.Label': 'tot',
  'linkDataSource.confluence-search.configmodal.date.range.today': 'Vandaag',
  'linkDataSource.confluence-search.configmodal.date.range.update.button': 'Bijwerken',
  'linkDataSource.confluence-search.configmodal.date.range.yesterday': 'Gisteren',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitle': 'Confluence-lijst invoegen',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitleManySites': 'Confluence-lijst invoegen van',
  'linkDataSource.confluence-search.configmodal.insertResultsButtonText': 'Resultaten invoegen',
  'linkDataSource.confluence-search.configmodal.placeholder.issues': '### resultaten',
  'linkDataSource.confluence-search.configmodal.searchLabel':
    'Voer zoektermen in om pagina’s, bijlagen en meer te vinden',
  'linkDataSource.confluence-search.no.confluence.sites.access.description':
    'Neem contact op met je beheerder om toegang aan te vragen.',
  'linkDataSource.confluence-search.no.confluence.sites.access.title': 'Je hebt geen toegang tot Confluence-sites',
  'linkDataSource.datasource.table.authConnectButtonText': 'Koppelen',
  'linkDataSource.datasource.table.authScreenDescriptionText':
    'Koppel je {providerName}-account om samen te werken op verschillende Atlassian-producten.',
  'linkDataSource.datasource.table.authScreenHeaderText': 'Koppel je {providerName}-account',
  'linkDataSource.datasource.table.learnMoreAboutSmartLinks': 'Meer informatie over Smart Links.',
  'linkDataSource.issue-line-table.error-403-description': 'Je hebt de juiste rechten nodig om dit item te bewerken.',
  'linkDataSource.issue-line-table.error-403-title': 'Wijzigingen niet opgeslagen',
  'linkDataSource.issue-line-table.error-generic-description':
    'We hadden een probleem toen we de update probeerden te voltooien. Wacht een paar minuten en probeer het opnieuw. Neem contact op met de klantenservice als dit steeds gebeurt.',
  'linkDataSource.issue-line-table.error-generic-title': 'Er is iets misgegaan',
  'linkDataSource.issue-line-table.fetch-action-error-generic-description':
    'Wacht een paar minuten en probeer het opnieuw. Controleer je projectinstellingen of neem contact op met support als dit blijft gebeuren.',
  'linkDataSource.issue-line-table.fetch-action-error-generic-title':
    'Er is een probleem opgetreden bij het ophalen van de opties',
  'linkDataSource.issue-line-table.unwrap-text': 'Tekst niet teruglopen',
  'linkDataSource.issue-line-table.wrap-text': 'Tekst teruglopen',
  'linkDataSource.checkConnectionWithSource':
    'Controleer je verbinding en ververs de pagina of <a>open deze zoekopdracht in Jira</a> ter controle.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'Je kunt niet overschakelen naar basis voor deze query.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Basis',
  'linkDataSource.site-selector.configmodal.chooseSite': 'Site kiezen',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Issues invoegen',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Jira-issues invoegen',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Jira-issues invoegen van',
  'linkDataSource.jira-issues.configmodal.viewModeInlineLinkDescription':
    'Het aantal zoekresultaten weergeven als een inline Smart Link',
  'linkDataSource.jira-issues.configmodal.viewModeInlineLinkLabel': 'Inline-link',
  'linkDataSource.jira-issues.configmodal.viewModeListDescription': 'De zoekresultaten weergeven als een lijst',
  'linkDataSource.jira-issues.configmodal.viewModeListLabel': 'Lijst',
  'linkDataSource.jira-issues.learnMoreLink': 'Meer informatie over zoeken met JQL',
  'linkDataSource.no.jira.sites.access.description': 'Neem contact op met je beheerder om toegang aan te vragen.',
  'linkDataSource.no.jira.sites.access.title': 'Je hebt geen toegang tot Jira-sites',
  'linkDataSource.noResultsFound': 'Geen resultaten gevonden',
  'linkDataSource.refresh': 'Vernieuwen',
  'linkDataSource.jira-issues.searchDescription-basic': 'Zoek met trefwoorden om issues toe te voegen.',
  'linkDataSource.jira-issues.searchDescription-jql': 'Gebruik JQL ( Jira Query Language) om te zoeken naar issues.',
  'linkDataSource.jira-issues.searchJiraTitle': 'Zoek naar Jira-issues',
  'linkDataSource.unableToLoadItems': 'Kan items niet laden',
  'linkDataSource.unableToLoadResults': 'Resultaten kunnen niet worden geladen',
  'linkDataSource.modal-initial-state.beta': 'Bèta',
  'linkDataSource.modal-initial-state.confluenceSearchTitle': "Zoeken naar Confluence-pagina's",
  'linkDataSource.modal-initial-state.jiraSearchTitle': 'Zoek naar Jira-issues',
  'linkDataSource.modal-initial-state.searchDescription-confluence':
    "Zoek met trefwoorden naar pagina's om in te voegen.",
  'linkDataSource.render-type.boolean.false': 'Nee',
  'linkDataSource.render-type.boolean.true': 'Ja',
  'linkDataSource.render-type.user.default.display.name': 'Niet-toegewezen',
  'linkDataSource.search.configmodal.issueCountText':
    '{searchCount, plural, one {{searchCount,number} issue} other {{searchCount,number} issues}}',
  'linkDataSource.search.configmodal.itemCountText':
    '{searchCount, plural, one {{searchCount,number} item} other {{searchCount,number} items}}',
  'linkDataSource.search.configmodal.resultCountText':
    '{searchCount, plural, one {{searchCount,number} resultaat} other {{searchCount,number} resultaten}}',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Zojuist gesynchroniseerd',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Gesynchroniseerd op {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, one {item} other {items}}',
  'linkDataSource.table-footer.loading': 'Laden...',
  'linkDataSource.table-footer.power-by-jsm': 'Aangestuurd door Assets in Jira Service Management',
  'linkDataSource.table-footer.refresh': 'Vernieuwen',
};
