/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Polish (Poland)
export default {
  'linkDataSource.accessInstructions': 'Aby poprosić o dostęp, skontaktuj się z administratorem witryny.',
  'linkDataSource.accessRequired': 'Nie masz dostępu do tej treści',
  'linkDataSource.accessRequiredWithSite': 'Nie masz dostępu do następującej witryny:',
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Pomoc dotycząca składni',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Wyszukaj za pomocą AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Wybierz schemat',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Wybierz schemat',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'Schemat jest wymagany',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Dowiedz się więcej o wyszukiwaniu przy użyciu zapytań AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Zacznij wpisywać lub użyj języka AQL, aby wyszukać.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'Wyszukaj obiekty',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Wstaw obiekt} few {Wstaw obiekty} many {Wstaw obiekty} other {Wstaw obiekty}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Wstawianie obiektów z',
  'linkDataSource.assets.configmodal.updateObjectsButtonText': 'Aktualizuj tabelę',
  'linkDataSource.basic-filter.assignee.label': 'Osoba przypisana',
  'linkDataSource.basic-filter.dropdown.select.assignee.unassigned': 'Nie przypisano',
  'linkDataSource.basic-filter.dropdown.select.placeholder': 'Szukaj',
  'linkDataSource.basic-filter.error-message': 'Coś poszło nie tak',
  'linkDataSource.basic-filter.footer.pagination-details': '{currentDisplayCount} z {totalCount}',
  'linkDataSource.basic-filter.loading-message': 'Ładowanie...',
  'linkDataSource.basic-filter.no-options-message': 'Nie znaleziono dopasowań',
  'linkDataSource.basic-filter.project.label': 'Projekt',
  'linkDataSource.basic-filter.showMoreButton': 'Pokaż więcej',
  'linkDataSource.basic-filter.status.label': 'Status',
  'linkDataSource.basic-filter.type.label': 'Typ',
  'linkDataSource.checkConnection': 'Sprawdź połączenie i odśwież stronę lub spróbuj ponownie później.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'Wyszukiwanie zwróciło zbyt wiele wyników.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2':
    'Spróbuj ponownie z bardziej szczegółowymi słowami kluczowymi.',
  'linkDataSource.column-picker.search': 'Wyszukaj pola',
  'linkDataSource.column-picker.tooltip': 'Konfiguruj kolumny',
  'linkDataSource.configmodal.basicTextSearchPlaceholder': 'Wyszukaj zgłoszenia według słów kluczowych',
  'linkDataSource.configmodal.cancelButtonText': 'Anuluj',
  'linkDataSource.configmodal.inlineLinkViewModeDescription':
    'Wyświetl liczbę wyników wyszukiwania lub jako śródwierszowe inteligentne łącze',
  'linkDataSource.configmodal.inlineLinkViewModeLabel': 'Łącze śródwierszowe',
  'linkDataSource.configmodal.tableViewModeDescription': 'Wyświetl wyniki wyszukiwania w formie tabeli',
  'linkDataSource.configmodal.tableViewModeLabel': 'Tabela',
  'linkDataSource.confluence-search.configmodal.cancelButtonText': 'Anuluj',
  'linkDataSource.confluence-search.configmodal.date.range.any.time': 'Kiedykolwiek',
  'linkDataSource.confluence-search.configmodal.date.range.custom': 'Niestandardowa',
  'linkDataSource.confluence-search.configmodal.date.range.last.month': 'Ostatnie 30 dni',
  'linkDataSource.confluence-search.configmodal.date.range.last.week': 'Ostatnie 7 dni',
  'linkDataSource.confluence-search.configmodal.date.range.last.year': 'Ostatni rok',
  'linkDataSource.confluence-search.configmodal.date.range.title': 'Ostatnia aktualizacja',
  'linkDataSource.confluence-search.configmodal.date.range.today': 'Dzisiaj',
  'linkDataSource.confluence-search.configmodal.date.range.yesterday': 'Wczoraj',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitle': 'Wstawianie listy Confluence',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitleManySites': 'Wstaw listę Confluence z',
  'linkDataSource.confluence-search.configmodal.insertResultsButtonText': 'Wstaw wyniki',
  'linkDataSource.confluence-search.configmodal.placeholder.issues': 'Liczba wyników: ###',
  'linkDataSource.confluence-search.configmodal.resultsCountText':
    '{totalCount, plural, one {wynik} few {wyniki} many {wyników} other {wyniku}}',
  'linkDataSource.confluence-search.configmodal.searchLabel':
    'Wprowadź słowa kluczowe, aby znaleźć strony, załączniki i nie tylko',
  'linkDataSource.confluence-search.no.confluence.sites.access.description':
    'Aby poprosić o dostęp, skontaktuj się z administratorem.',
  'linkDataSource.confluence-search.no.confluence.sites.access.title': 'Nie masz dostępu do żadnych witryn Confluence',
  'linkDataSource.datasource.table.authConnectButtonText': 'Połącz',
  'linkDataSource.datasource.table.authScreenDescriptionText':
    'Połącz swoje konto {providerName}, aby współpracować w różnych produktach Atlassian.',
  'linkDataSource.datasource.table.authScreenHeaderText': 'Połącz konto {providerName}',
  'linkDataSource.datasource.table.learnMoreAboutSmartLinks': 'Dowiedz się więcej o inteligentnych łączach.',
  'linkDataSource.issue-line-table.unwrap-text': 'Cofnij zawijanie tekstu',
  'linkDataSource.issue-line-table.wrap-text': 'Zawijaj tekst',
  'linkDataSource.jira-issues.accessInstructions': 'Aby poprosić o dostęp, skontaktuj się z administratorem witryny.',
  'linkDataSource.jira-issues.accessRequired': 'Nie masz dostępu do tej treści',
  'linkDataSource.jira-issues.accessRequiredWithSite': 'Nie masz dostępu do następującej witryny:',
  'linkDataSource.jira-issues.checkConnection': 'Sprawdź połączenie i odśwież stronę lub spróbuj ponownie później.',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    'Sprawdź i odśwież połączenie lub <a>otwórz to zapytanie w systemie Jira</a>, aby je przejrzeć.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'Nie można przełączyć na tryb podstawowy w przypadku tego zapytania.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Podstawowe',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': 'Wyszukaj zgłoszenia według słów kluczowych',
  'linkDataSource.jira-issues.configmodal.chooseSite': 'Wybierz witrynę',
  'linkDataSource.jira-issues.configmodal.inlineLinkViewModeDescription':
    'Wyświetl liczbę wyników wyszukiwania lub jako śródwierszowe inteligentne łącze',
  'linkDataSource.jira-issues.configmodal.inlineLinkViewModeLabel': 'Łącze śródwierszowe',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Wstaw zgłoszenia',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Wstaw zgłoszenia Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Wstaw zgłoszenia Jira z witryny',
  'linkDataSource.jira-issues.configmodal.issue':
    '{totalCount, plural, one {zgłoszenie} few {zgłoszenia} many {zgłoszeń} other {zgłoszenia}}',
  'linkDataSource.jira-issues.configmodal.tableViewModeDescription':
    'Wyświetl wyniki wyszukiwania Jira w formie tabeli',
  'linkDataSource.jira-issues.configmodal.tableViewModeLabel': 'Tabela',
  'linkDataSource.jira-issues.learnMoreLink': 'Dowiedz się, jak wyszukiwać przy użyciu zapytań JQL',
  'linkDataSource.jira-issues.no.jira.sites.access.description':
    'Aby poprosić o dostęp, skontaktuj się z administratorem.',
  'linkDataSource.jira-issues.no.jira.sites.access.title': 'Nie masz dostępu do żadnej witryny Jira',
  'linkDataSource.jira-issues.noResultsFound': 'Nie znaleziono wyników',
  'linkDataSource.jira-issues.refresh': 'Odśwież',
  'linkDataSource.jira-issues.searchDescription-basic': 'Wyszukaj zgłoszenia do wstawienia według słowa kluczowego.',
  'linkDataSource.jira-issues.searchDescription-jql':
    'Użyj zapytań w języku JQL (Jira Query Language), aby wyszukiwać zgłoszenia.',
  'linkDataSource.jira-issues.searchJiraTitle': 'Wyszukaj zgłoszenia Jira',
  'linkDataSource.jira-issues.unableToLoadItems': 'Nie można załadować elementów',
  'linkDataSource.jira-issues.unableToLoadResults': 'Nie można załadować wyników',
  'linkDataSource.modal-initial-state.beta': 'Beta',
  'linkDataSource.modal-initial-state.confluenceSearchTitle': 'Wyszukaj strony Confluence',
  'linkDataSource.modal-initial-state.jiraSearchTitle': 'Wyszukaj zgłoszenia Jira',
  'linkDataSource.modal-initial-state.learnMoreLink': 'Dowiedz się, jak wyszukiwać przy użyciu zapytań JQL',
  'linkDataSource.modal-initial-state.searchDescription-basic':
    'Wyszukaj zgłoszenia do wstawienia według słowa kluczowego.',
  'linkDataSource.modal-initial-state.searchDescription-confluence':
    'Wyszukaj strony do wstawienia według słowa kluczowego.',
  'linkDataSource.modal-initial-state.searchDescription-jql':
    'Użyj zapytań w języku JQL (Jira Query Language), aby wyszukiwać zgłoszenia.',
  'linkDataSource.modal-initial-state.searchTitle': 'Wyszukaj zgłoszenia Jira',
  'linkDataSource.no.jira.sites.access.description': 'Aby poprosić o dostęp, skontaktuj się z administratorem.',
  'linkDataSource.no.jira.sites.access.title': 'Nie masz dostępu do żadnej witryny Jira',
  'linkDataSource.noResultsFound': 'Nie znaleziono wyników',
  'linkDataSource.refresh': 'Odśwież',
  'linkDataSource.render-type.boolean.false': 'Nie',
  'linkDataSource.render-type.boolean.true': 'Tak',
  'linkDataSource.render-type.user.default.display.name': 'Nieprzydzielone',
  'linkDataSource.site-selector.configmodal.chooseSite': 'Wybierz witrynę',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Właśnie zsynchronizowano',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Zsynchronizowano {date}',
  'linkDataSource.table-footer.item':
    '{itemCount, plural, one {element} few {elementy} many {elementów} other {elementu}}',
  'linkDataSource.table-footer.loading': 'Ładowanie…',
  'linkDataSource.table-footer.power-by-jsm': 'Obsługiwane przez Zasoby w Jira Service Management',
  'linkDataSource.table-footer.refresh': 'Odśwież',
  'linkDataSource.unableToLoadItems': 'Nie można załadować elementów',
  'linkDataSource.unableToLoadResults': 'Nie można załadować wyników',
};
