/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Portuguese (Brazil)
export default {
  'linkDataSource.accessInstructions': 'Para pedir acesso, entre em contato com o administrador do site.',
  'linkDataSource.accessRequired': 'Você não tem acesso a este conteúdo',
  'linkDataSource.accessRequiredWithSite': 'Você não tem acesso ao seguinte site:',
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'Ajuda de sintaxe',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'Pesquisar via AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'Selecionar esquema',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'Selecionar esquema',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'O esquema é obrigatório',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'Saiba mais sobre como pesquisar com AQL.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'Comece a digitar ou use o AQL para pesquisar.',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'Pesquisar objetos',
  'linkDataSource.assets.configmodal.insertIssuesButtonText':
    '{objectsCount, plural, one {Inserir objeto} other {Inserir objetos}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'Inserir objetos de',
  'linkDataSource.assets.configmodal.updateObjectsButtonText': 'Atualizar tabela',
  'linkDataSource.basic-filter.assignee.label': 'Responsável',
  'linkDataSource.basic-filter.dropdown.select.assignee.unassigned': 'Sem responsável',
  'linkDataSource.basic-filter.dropdown.select.placeholder': 'Pesquisar',
  'linkDataSource.basic-filter.error-message': 'Algo deu errado',
  'linkDataSource.basic-filter.footer.pagination-details': '{currentDisplayCount} de {totalCount}',
  'linkDataSource.basic-filter.loading-message': 'Carregando...',
  'linkDataSource.basic-filter.no-options-message': 'Nenhuma correspondência encontrada',
  'linkDataSource.basic-filter.project.label': 'Projeto',
  'linkDataSource.basic-filter.showMoreButton': 'Ver mais',
  'linkDataSource.basic-filter.status.label': 'Status',
  'linkDataSource.basic-filter.type.label': 'Tipo',
  'linkDataSource.checkConnection': 'Verifique a conexão e atualize, ou tente de novo mais tarde.',
  'linkDataSource.clol-basic-filter.editedOrCreatedBy.label': 'Editado ou criado por',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'A pesquisa retornou muitos resultados.',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2':
    'Tente de novo com palavras-chave mais específicas.',
  'linkDataSource.column-picker.search': 'Pesquisar campos',
  'linkDataSource.column-picker.tooltip': 'Configurar colunas',
  'linkDataSource.configmodal.basicTextSearchPlaceholder': 'Pesquise itens por palavra-chave',
  'linkDataSource.configmodal.cancelButtonText': 'Cancelar',
  'linkDataSource.confluence-search.configmodal.cancelButtonText': 'Cancelar',
  'linkDataSource.confluence-search.configmodal.date.range.after.label': 'depois de {date}',
  'linkDataSource.confluence-search.configmodal.date.range.any.time': 'A qualquer momento',
  'linkDataSource.confluence-search.configmodal.date.range.before.label': 'antes de {date}',
  'linkDataSource.confluence-search.configmodal.date.range.custom': 'Personalizado',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.after.end':
    'A data "De" deve ser anterior à data "Até"',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.after.today':
    'A data "De" não pode estar no futuro',
  'linkDataSource.confluence-search.configmodal.date.range.custom.invalid.to.after.today':
    'A data "Até" não pode estar no futuro',
  'linkDataSource.confluence-search.configmodal.date.range.from': 'De',
  'linkDataSource.confluence-search.configmodal.date.range.input.placeholder': 'Escolha uma data',
  'linkDataSource.confluence-search.configmodal.date.range.last.month': 'Últimos 30 dias',
  'linkDataSource.confluence-search.configmodal.date.range.last.week': 'Últimos 7 dias',
  'linkDataSource.confluence-search.configmodal.date.range.last.year': 'Ano passado',
  'linkDataSource.confluence-search.configmodal.date.range.title': 'Última atualização',
  'linkDataSource.confluence-search.configmodal.date.range.to': 'Até',
  'linkDataSource.confluence-search.configmodal.date.range.to.Label': 'até',
  'linkDataSource.confluence-search.configmodal.date.range.today': 'Hoje',
  'linkDataSource.confluence-search.configmodal.date.range.update.button': 'Atualizar',
  'linkDataSource.confluence-search.configmodal.date.range.yesterday': 'Ontem',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitle': 'Insira a lista do Confluence',
  'linkDataSource.confluence-search.configmodal.insertConfluenceTitleManySites': 'Insira a lista do Confluence de',
  'linkDataSource.confluence-search.configmodal.insertResultsButtonText': 'Inserir resultados',
  'linkDataSource.confluence-search.configmodal.placeholder.issues': '### resultados',
  'linkDataSource.confluence-search.configmodal.resultsCountText':
    '{totalCount, plural, one {resultado} other {resultados}}',
  'linkDataSource.confluence-search.configmodal.searchLabel':
    'Digite palavras-chave para encontrar páginas, anexos e mais',
  'linkDataSource.confluence-search.no.confluence.sites.access.description':
    'Para solicitar acesso, entre em contato com o administrador.',
  'linkDataSource.confluence-search.no.confluence.sites.access.title':
    'Você não tem acesso a nenhum site do Confluence',
  'linkDataSource.datasource.table.authConnectButtonText': 'Conectar',
  'linkDataSource.datasource.table.authScreenDescriptionText':
    'Conecte a conta {providerName} para colaborar no trabalho em todos os produtos da Atlassian.',
  'linkDataSource.datasource.table.authScreenHeaderText': 'Conectar a conta do {providerName}',
  'linkDataSource.datasource.table.learnMoreAboutSmartLinks': 'Saiba mais sobre os links inteligentes.',
  'linkDataSource.issue-line-table.unwrap-text': 'Não quebrar linha',
  'linkDataSource.issue-line-table.wrap-text': 'Quebrar linha',
  'linkDataSource.checkConnectionWithSource':
    'Verifique a conexão e atualize, ou <a>abra essa consulta no Jira</a> para revisar.',
  'linkDataSource.jira-issues.configmodal.basicModeSwitchDisabledTooltipText':
    'Não é possível mudar para o básico nessa consulta.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Básico',
  'linkDataSource.site-selector.configmodal.chooseSite': 'Escolha o site',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Inserir itens',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Inserir itens no Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Inserir itens do Jira de',
  'linkDataSource.jira-issues.configmodal.issue': '{totalCount, plural, one {item} other {itens}}',
  'linkDataSource.jira-issues.configmodal.viewModeInlineLinkDescription':
    'Mostrar o número de resultados da pesquisa como link inteligente em linha',
  'linkDataSource.jira-issues.configmodal.viewModeInlineLinkLabel': 'Link em linha',
  'linkDataSource.jira-issues.configmodal.viewModeListDescription': 'Mostrar resultados da pesquisa em uma lista',
  'linkDataSource.jira-issues.configmodal.viewModeListLabel': 'Lista',
  'linkDataSource.jira-issues.learnMoreLink': 'Saiba como pesquisar com JQL',
  'linkDataSource.no.jira.sites.access.description': 'Para solicitar acesso, entre em contato com o administrador.',
  'linkDataSource.no.jira.sites.access.title': 'Você não tem acesso a nenhum site do Jira',
  'linkDataSource.noResultsFound': 'Nenhum resultado foi encontrado',
  'linkDataSource.refresh': 'Atualizar',
  'linkDataSource.jira-issues.searchDescription-basic': 'Use palavras-chave para pesquisar os itens a serem inseridos.',
  'linkDataSource.jira-issues.searchDescription-jql': 'Use JQL (Linguagem de Consulta do Jira) para pesquisar itens.',
  'linkDataSource.jira-issues.searchJiraTitle': 'Pesquisar itens do Jira',
  'linkDataSource.unableToLoadItems': 'Não foi possível carregar os itens',
  'linkDataSource.unableToLoadResults': 'Não é possível carregar os resultados',
  'linkDataSource.modal-initial-state.beta': 'Beta',
  'linkDataSource.modal-initial-state.confluenceSearchTitle': 'Pesquisar páginas do Confluence',
  'linkDataSource.modal-initial-state.jiraSearchTitle': 'Pesquisar itens do Jira',
  'linkDataSource.modal-initial-state.searchDescription-confluence':
    'Pesquise por palavra-chave as páginas a serem inseridas.',
  'linkDataSource.render-type.boolean.false': 'Não',
  'linkDataSource.render-type.boolean.true': 'Sim',
  'linkDataSource.render-type.user.default.display.name': 'Sem responsável',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Sincronizado agora',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Sincronizado em {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, one {item} other {itens}}',
  'linkDataSource.table-footer.loading': 'Carregando...',
  'linkDataSource.table-footer.power-by-jsm': 'Desenvolvido por Recursos no Jira Service Management',
  'linkDataSource.table-footer.refresh': 'Atualizar',
};
