/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Swedish
export default {
  'linkDataSource.column-picker.search': 'Sök efter fält',
  'linkDataSource.jira-issues.checkConnection': 'Kontrollera din anslutning och uppdatera, eller försök igen senare.',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    'Kontrollera din anslutning och uppdatera, eller <a>öppna den här frågan i Jira</a> för att granska.',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'Grundläggande',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': 'Sök',
  'linkDataSource.jira-issues.configmodal.cancelButtonText': 'Avbryt',
  'linkDataSource.jira-issues.configmodal.countViewModeLabel': 'Antal-vy',
  'linkDataSource.jira-issues.configmodal.dropdownChevronLabel': 'Välj Jira-webbplats',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'Infoga ärende',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'Infoga Jira-ärenden',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'Infoga Jira-ärenden från {siteName}',
  'linkDataSource.jira-issues.configmodal.issueViewModeLabel': 'Ärendevyn',
  'linkDataSource.jira-issues.configmodal.selectedJiraSiteLabel': '{siteName} är vald',
  'linkDataSource.jira-issues.noResultsFound': 'Inga resultat hittades',
  'linkDataSource.jira-issues.refresh': 'Uppdatera',
  'linkDataSource.jira-issues.unableToLoadIssues': 'Det gick inte att läsa in ärenden',
  'linkDataSource.jira-issues.unableToLoadResults': 'Det gick inte att läsa in resultat',
  'linkDataSource.render-type.boolean.false': 'Nej',
  'linkDataSource.render-type.boolean.true': 'Ja',
  'linkDataSource.render-type.user.default.display.name': 'Ej tilldelad',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'Synkroniserades just nu',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'Synkroniserades {date}',
  'linkDataSource.table-footer.loading': 'Läser in ...',
  'linkDataSource.table-footer.refresh': 'Uppdatera',
};
