/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Thai (Thailand)
export default {
  'linkDataSource.assets.configModal.aqlSearchInput.helpTooltipText': 'การช่วยเหลือด้านโครงสร้าง',
  'linkDataSource.assets.configModal.aqlSearchInput.placeholder': 'ค้นหาผ่าน AQL',
  'linkDataSource.assets.configModal.objectSchemaSelect.label': 'เลือกรายละเอียดเรื่อง',
  'linkDataSource.assets.configModal.objectSchemaSelect.placeholder': 'เลือกรายละเอียดเรื่อง',
  'linkDataSource.assets.configModal.objectSchemaSelect.schemaRequired': 'ต้องระบุรายละเอียดเรื่อง',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.learnMoreLink':
    'เรียนรู้เพิ่มเติมเกี่ยวกับการค้นหาด้วย AQL',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchDescription':
    'เริ่มพิมพ์หรือใช้ AQL เพื่อค้นหา',
  'linkDataSource.assets.configModal.renderAssetsContent.initialStateView.searchTitle': 'ค้นหาวัตถุ',
  'linkDataSource.assets.configmodal.cancelButtonText': 'ยกเลิก',
  'linkDataSource.assets.configmodal.insertIssuesButtonText': '{objectsCount, plural, other {แทรกเรื่อง}}',
  'linkDataSource.assets.configmodal.insertObjectsTitle': 'แทรกเรื่องจาก',
  'linkDataSource.column-picker.no-all-items-shown-message.line-1': 'การค้นหาของคุณมีการแสดงผลลัพธ์มากเกินไป',
  'linkDataSource.column-picker.no-all-items-shown-message.line-2': 'ลองอีกครั้งด้วยคำค้นหาหลักที่เจาะจงมากขึ้น',
  'linkDataSource.column-picker.search': 'ค้นหาฟิลด์',
  'linkDataSource.jira-issues.accessInstructions': 'หากต้องการส่งคำขอการเข้าถึง โปรดติดต่อผู้ดูแลของคุณ',
  'linkDataSource.jira-issues.accessRequired': 'คุณไม่มีสิทธิ์การเข้าถึงเว็บไซต์นี้',
  'linkDataSource.jira-issues.accessRequiredWithSite': 'คุณไม่มีสิทธิ์การเข้าถึง {siteName}',
  'linkDataSource.jira-issues.checkConnection': 'ตรวจสอบการเชื่อมต่อของคุณและรีเฟรช หรือลองอีกครั้งในภายหลัง',
  'linkDataSource.jira-issues.checkConnectionWithSource':
    'ตรวจสอบการเชื่อมต่อของคุณและรีเฟรช หรือ <a>เปิดคำถามนี้ใน Jira</a> เพื่อตรวจสอบ',
  'linkDataSource.jira-issues.configmodal.basicModeText': 'พื้นฐาน',
  'linkDataSource.jira-issues.configmodal.basicTextSearchPlaceholder': 'ค้นหา',
  'linkDataSource.jira-issues.configmodal.cancelButtonText': 'ยกเลิก',
  'linkDataSource.jira-issues.configmodal.countViewModeLabel': 'มุมมองจำนวน',
  'linkDataSource.jira-issues.configmodal.dropdownChevronLabel': 'เลือกเว็บไซต์ Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesButtonText': 'แทรกปัญหา',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitle': 'แทรกปัญหา Jira',
  'linkDataSource.jira-issues.configmodal.insertIssuesTitleManySites': 'แทรกปัญหา Jira จาก {siteName}',
  'linkDataSource.jira-issues.configmodal.issue': '{totalCount, plural, other {ปัญหา}}',
  'linkDataSource.jira-issues.configmodal.issueViewModeLabel': 'มุมมองของปัญหา',
  'linkDataSource.jira-issues.configmodal.selectedJiraSiteLabel': 'เลือก {siteName} แล้ว',
  'linkDataSource.jira-issues.noResultsFound': 'ไม่พบผลลัพธ์',
  'linkDataSource.jira-issues.refresh': 'รีเฟรช',
  'linkDataSource.jira-issues.unableToLoadItems': 'ไม่สามารถโหลดรายการได้',
  'linkDataSource.jira-issues.unableToLoadResults': 'ไม่สามารถโหลดผลลัพธ์ได้',
  'linkDataSource.modal-initial-state.learnMoreLink': 'เรียนรู้เพิ่มเติมเกี่ยวกับการค้นหาด้วย JQL',
  'linkDataSource.modal-initial-state.searchDescription': 'เริ่มพิมพ์หรือใช้ JQL ในการค้นหา',
  'linkDataSource.modal-initial-state.searchTitle': 'ค้นหาปัญหา Jira',
  'linkDataSource.render-type.boolean.false': 'ไม่ใช่',
  'linkDataSource.render-type.boolean.true': 'ใช่',
  'linkDataSource.render-type.user.default.display.name': 'ยังไม่ได้มอบหมาย',
  'linkDataSource.table-footer.date_formatter.under_one_minute': 'เพิ่งซิงค์',
  'linkDataSource.table-footer.date_formatter.under_over_minute': 'ซิงค์เมื่อ {date}',
  'linkDataSource.table-footer.item': '{itemCount, plural, other {รายการ}}',
  'linkDataSource.table-footer.loading': 'กำลังโหลด...',
  'linkDataSource.table-footer.refresh': 'รีเฟรช',
};
