/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Croatian (Croatia) [hr-HR]
export default {
  'focused-task-close-account.delete-account.overview.inline-dialog.content-created-issue-refresh.admin':
    'Na primjer, stranice, radne stavke i komentari koje su izradili u proizvodima.',
};
