/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Icelandic
export default {
  'focused-task-close-account.deactivate-account': 'Gera reikning óvirkan',
  'focused-task-close-account.delete-account': 'Eyða reikningi',
  'focused-task-close-account.learnMore': 'Fáðu að vita meira ',
  'focused-task-close-account.cancel': 'Hætta við ',
  'focused-task-close-account.next': 'Næsta',
  'focused-task-close-account.previous': 'Fyrra',
  'focused-task-close-account.delete-account.overview.heading.self':
    'Þegar reikningnum þínum er eytt',
  'focused-task-close-account.delete-account.overview.heading.admin':
    'Eyða reikningi',
  'focused-task-close-account.delete-account.overview.first.line.self':
    'Þú er við það að eyða reikningnum þínum:',
  'focused-task-close-account.delete-account.overview.first.line.admin':
    'Þú er við það að eyða reikningi:',
  'focused-task-close-account.delete-account.overview.warning-section.body':
    'Eftir 14-daga greiðslufrest muntu ekki geta hætt við eyðingu reikningsins. Ef þú heldur að þú gætir þurft á honum að halda síðar, gerðu hann þá frekar óvirkan.',
  'focused-task-close-account.delete-account.overview.warning-section.deactivated.body':
    ' Eftir 14-daga greiðslufrest muntu ekki geta hætt við eyðingu reikningsins.',
  'focused-task-close-account.delete-account.overview.paragraph.about-to-delete.admin':
    'Þegar þú eyða reikningum:',
  'focused-task-close-account.delete-account.overview.paragraph.about-to-delete.self':
    'Þegar þú eyðir reikningum þínum:',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.admin':
    '{fullName} mun <b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu. Í augnablikinu hafa þeir aðgang að:',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.self':
    'Þú munt <b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu. Í augnablikinu hefur þú aðgang að:',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.admin.noSites':
    '{fullName} mun <b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu.  Í augnablikinu hafa þeir aðgang að neinni þjónustu nema þjónustu eins og Community og Marketplace.',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.self.noSites':
    'Þú munt<b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu. Í augnablikinu hefur þú ekki aðgang að neinni þjónustu nema þjónustu eins og Community og Marketplace.',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.footnote':
    'Önnur Atlassian reikningsþjónusta, eins og Atlassian Community og Marketplace.',
  'focused-task-close-account.delete-account.overview.paragraph.content-created.admin':
    'Innihaldið sem notandi hefur búið til mun vera áframhaldandi í Atlassian reikningsþjónustu.',
  'focused-task-close-account.delete-account.overview.paragraph.content-created.self':
    'Innihaldið sem þú hefur búið til mun vera áframhaldandi í Atlassian reikningsþjónustu.',
  'focused-task-close-account.delete-account.overview.inline-dialog.content-created.admin':
    'Til dæmis síður, málefni og athugasemdir sem þeir hafa búið til í vörum.',
  'focused-task-close-account.delete-account.overview.inline-dialog.content-created.self':
    'Til dæmis síður, málefni og athugasemdir sem þú hefur búið til í vörum.',
  'focused-task-close-account.delete-account.overview.paragraph.personal-data-will-be-deleted.admin':
    'Við munum <b>eyða persónuupplýsingunum þeirra</b>, eins og til dæmis fullu nafni og netfangi, af Atlassian reikningum innan 30 daga, að örfáum tilvikum undanskildum þar sem þær eru nauðsynlegar fyrir lögleg fyrirtæki og í lagalegum tilgangi.',
  'focused-task-close-account.delete-account.overview.paragraph.personal-data-will-be-deleted.self':
    'Við munum <b>eyða persónuupplýsingunum þínum</b>, eins og til dæmis fullu nafni og netfangi, af Atlassian reikningum innan 30 daga, að örfáum tilvikum undanskildum þar sem þær eru nauðsynlegar fyrir lögleg fyrirtæki og í lagalegum tilgangi.',
  'focused-task-close-account.delete-account.overview.paragraph.list-of-apps-with-personal-data.admin':
    'Við munum senda þér lista með tölvupósti af forritum sem gætu hafa geymt persónuupplýsingarnar þeirra. ',
  'focused-task-close-account.delete-account.overview.paragraph.list-of-apps-with-personal-data.self':
    'Við munum senda þér lista með tölvupósti af forritum sem gætu hafa geymt persónuupplýsingarnar þínar. ',
  'focused-task-close-account.delete-account.overview.paragraph.grace-period.admin':
    ' Eftir 14-daga greiðslufrest muntu ekki geta hætt við eyðingu reikningsins.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p1.admin':
    'Við geymum persónuupplýsingar í takmarkaðan tíma þegar um lögleg fyrirtæki eða lagalegan tilgang er að ræða. Sum þessara tilvika eru:',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p1.self':
    'Við geymum persónuupplýsingar í takmarkaðan tíma þegar um lögleg fyrirtæki eða lagalegan tilgang er að ræða. Sum þessara tilvika eru:',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li1.admin':
    'Upplýsingar sem tengjast vörukaupum sem okkur er áskilið að geyma fyrir fjárhagslegar skýrslugerðir.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li1.self':
    'Upplýsingar sem tengjast vörukaupum sem okkur er áskilið að geyma fyrir fjárhagslegar skýrslugerðir.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li2.admin':
    'Gögn sem sýna að við höfum eytt reikningi einhvers, sem við gætum þurft að gefa upp til eftirlitsaðila.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li2.self':
    'Gögn sem sýna að við höfum eytt reikningi einhvers, sem við gætum þurft að gefa upp til eftirlitsaðila.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li3.admin':
    'Gögn sem eru hluti af virkri málssókn, sem okkur er áskilið að geyma samkvæmt lögum.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li3.self':
    'Gögn sem eru hluti af virkri málssókn, sem okkur er áskilið að geyma samkvæmt lögum.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p2.admin':
    'Við eyðum ekki neinum persónuupplýsingum úr innihaldi sem búið til var af notendum, eins og nöfnum og netföngum sem þeir slógu inn á síðu eða málefni. Vörustjórnendurnir verða að eyða þeim upplýsingum handvirkt.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p2.self':
    'Við eyðum ekki neinum persónuupplýsingum úr innihaldi sem búið til var af þér eða öðrum aðilum, eins og nöfnum og netföngum sem slegin hafa verið inn á síðu eða málefni. Vörustjórnendurnir þínir verða að eyða þeim upplýsingum handvirkt.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p3.admin':
    'Notendur hafa rétt á því að leggja fram kvartanir til eftirlitsstofnunar landsins síns.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p3.self':
    'Þú hefur rétt á því að leggja fram kvartanir til eftirlitsstofnunar landsins þíns.',
  'focused-task-close-account.delete-account.overview.inline-dialog.data-apps.admin':
    'Þú og aðrir notendur gætuð hafa sett upp forrit sem bæta eiginleikum við Atlassian vörur. Þessi forrit gætu hafa geymt notendasíðuupplýsingar notandans.',
  'focused-task-close-account.delete-account.overview.inline-dialog.data-apps.self':
    'Þú og aðrir notendur gætuð hafa sett upp forrit sem bæta eiginleikum við Atlassian vörur. Þessi forrit gætu hafa geymt notendasíðuupplýsingar notandans.',
  'focused-task-close-account.deactivate-account.overview.heading.self':
    'Gera reikning óvirkan',
  'focused-task-close-account.deactivate-account.overview.heading.admin':
    'Gera reikning óvirkan',
  'focused-task-close-account.deactivate-account.overview.first.line.self':
    'Þú er við það að slökkva reikningi:',
  'focused-task-close-account.deactivate-account.overview.first.line.admin':
    'Þú er við það að slökkva reikningi:',
  'focused-task-close-account.deactivate-account.overview.last.line.self':
    'Þú getur endurvirkjað reikninginn hvenær sem er.',
  'focused-task-close-account.deactivate-account.overview.last.line.admin':
    'Þú getur endurvirkjað reikninginn hvenær sem er.',
  'focused-task-close-account.deactivate-account.overview.paragraph.about-to-deactivate.admin':
    'Þegar þú slökkva á reikningum:',
  'focused-task-close-account.deactivate-account.overview.paragraph.about-to-deactivate.self':
    'Þegar þú slökkva á reikningum:',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.admin':
    '{fullName} mun <b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu. Í augnablikinu hafa þeir aðgang að:',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.self':
    'Þú munt <b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu. Í augnablikinu hefur þú aðgang að:',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.admin.noSites':
    '{fullName} mun <b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu.  Í augnablikinu hafa þeir aðgang að neinni þjónustu nema þjónustu eins og Community og Marketplace.',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.self.noSites':
    'Þú munt<b>tafarlaust missa aðgang</b> að allri Atlassian reikningsþjónustu. Í augnablikinu hefur þú ekki aðgang að neinni þjónustu nema þjónustu eins og Community og Marketplace.',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.footnote':
    'Önnur Atlassian reikningsþjónusta, eins og Atlassian Community og Marketplace.',
  'focused-task-close-account.deactivate-account.overview.paragraph.personal-data.admin':
    'Persónuleg gögn, svo sem fullt nafn og netfang, og innihaldið sem notandi hefur búið til mun vera áframhaldandi í Atlassian reikningsþjónustu.',
  'focused-task-close-account.deactivate-account.overview.paragraph.personal-data.self':
    'Persónuleg gögn, svo sem fullt nafn og netfang, og innihaldið sem notandi hefur búið til mun vera áframhaldandi í Atlassian reikningsþjónustu.',
  'focused-task-close-account.deactivate-account.overview.paragraph.billing.admin':
    'Við munum ekki rukka þig lengur fyrir þær.',
  'focused-task-close-account.deactivate-account.overview.paragraph.billing.self':
    'Við munum ekki rukka þig lengur fyrir þær.',
  'focused-task-close-account.delete-account.content-preview.heading.admin':
    'Hvernig myndir þú vilja að notandinn sem eytt hefur verið myndi birtast?',
  'focused-task-close-account.delete-account.content-preview.heading.self':
    'Hvernig myndir þú vilja að reikningi sem eytt hefur verið myndi birtast?',
  'focused-task-close-account.delete-account.content-preview.paragraph.survey.admin':
    'Eftir að reikningi notandans hefur verið eytt mun viðkomandi birtast öðrum notendum sem „Fyrrum notandi“. Vinsamlegast gefðu þér smá stund til að svara spurningu könnunarinnar okkar.',
  'focused-task-close-account.delete-account.content-preview.paragraph.survey.self':
    'Eftir að reikningnum þínum hefur verið eytt muntu birtast öðrum notendum sem „Fyrrum notandi“. Vinsamlegast gefðu þér smá stund til að svara spurningu könnunarinnar okkar.',
  'focused-task-close-account.delete-account.content-preview.line.survey.admin':
    'Ef við gæfum þér val, hvernig myndir þú vilja að notandinn sem eytt hefur verið myndi birtast öðrum notendum?',
  'focused-task-close-account.delete-account.content-preview.line.survey.self':
    'Ef við gæfum þér val, hvernig myndir þú vilja birtast öðrum notendum?',
  'focused-task-close-account.delete-account.content-preview.footnote.admin':
    'Athugið: Með því að svara þessari könnun geturðu hjálpað okkur við að gera upplifunina betri fyrir alla notendur. Notandinn mun áfram birtast sem „Fyrrum notandi“ eftir að þú eyðir reikningi viðkomandi.',
  'focused-task-close-account.delete-account.content-preview.footnote.self':
    'Athugið: Með því að svara þessari könnun geturðu hjálpað okkur við að gera upplifunina betri fyrir alla notendur, þar á meðal fyrir þá sem eru að eyða reikningum sínum. Þú munt áfram birtast sem „Fyrrum notandi“ eftir að þú eyðir reikningnum þínum.',
  'focused-task-close-account.delete-account.content-preview.formerUser':
    'Fyrrum notandi',
  'focused-task-close-account.delete-account.drop-down-expand-button':
    '{num} meira',
  'focused-task-close-account.delete-account.drop-down-collapse-button':
    'Sýna minna ',
};
