/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Vietnamese
export default {
  'focused-task-close-account.cancel': 'Hủy',
  'focused-task-close-account.deactivate-account': 'Hủy kích hoạt tài khoản',
  'focused-task-close-account.deactivate-account.overview.first.line.admin':
    'Bạn sắp hủy kích hoạt tài khoản người dùng của:',
  'focused-task-close-account.deactivate-account.overview.first.line.self':
    'Bạn sắp hủy kích hoạt tai khoản người dùng của:',
  'focused-task-close-account.deactivate-account.overview.heading.admin':
    'Hủy kích hoạt tài khoản',
  'focused-task-close-account.deactivate-account.overview.heading.self':
    'Hủy kích hoạt tài khoản',
  'focused-task-close-account.deactivate-account.overview.last.line.admin':
    'Bạn có thể kích hoạt lại tài khoản bất cứ lúc nào.',
  'focused-task-close-account.deactivate-account.overview.last.line.self':
    'Bạn có thể kích hoạt lại tài khoản bất cứ lúc nào.',
  'focused-task-close-account.deactivate-account.overview.paragraph.about-to-deactivate.admin':
    'Khi bạn hủy kích hoạt tài khoản:',
  'focused-task-close-account.deactivate-account.overview.paragraph.about-to-deactivate.self':
    'Khi bạn hủy kích hoạt tài khoản:',
  'focused-task-close-account.deactivate-account.overview.paragraph.billing.admin':
    'Chúng tôi sẽ không còn tính phí các tài khoản này cho bạn nữa.',
  'focused-task-close-account.deactivate-account.overview.paragraph.billing.self':
    'Chúng tôi sẽ không còn tính phí các tài khoản này cho bạn nữa.',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.admin':
    '{fullName} sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Họ hiện có quyền truy cập vào:',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.admin.noSites':
    '{fullName} sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Hiện tại, họ không có quyền truy cập vào bất kỳ dịch vụ nào, ngoại trừ các dịch vụ như Community và Marketplace.',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.footnote':
    'Các dịch vụ tài khoản Atlassian khác, như Atlassian Community và Marketplace.',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.self':
    'Bạn sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Bạn hiện có quyền truy cập vào:',
  'focused-task-close-account.deactivate-account.overview.paragraph.loseAccess.self.noSites':
    'Bạn sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Hiện tại, bạn không có quyền truy cập vào bất kỳ dịch vụ nào, ngoại trừ các dịch vụ như Community và Marketplace.',
  'focused-task-close-account.deactivate-account.overview.paragraph.personal-data.admin':
    'Dữ liệu cá nhân của tài khoản, chẳng hạn như tên đầy đủ và địa chỉ email của tài khoản cũng như nội dung tài khoản đã tạo sẽ vẫn còn trong các dịch vụ tài khoản Atlassian.',
  'focused-task-close-account.deactivate-account.overview.paragraph.personal-data.self':
    'Dữ liệu cá nhân của tài khoản, chẳng hạn như tên đầy đủ và địa chỉ email của tài khoản cũng như nội dung tài khoản đã tạo sẽ vẫn còn trong các dịch vụ tài khoản Atlassian.',
  'focused-task-close-account.delete-account': 'Xóa tài khoản',
  'focused-task-close-account.delete-account.content-preview.footnote.admin':
    'Lưu ý: Việc trả lời cuộc khảo sát này sẽ giúp chúng tôi tạo ra trải nghiệm tốt hơn cho tất cả người dùng. Người dùng vẫn sẽ xuất hiện dưới dạng “Người dùng trước đây” sau khi bạn xóa tài khoản của họ.',
  'focused-task-close-account.delete-account.content-preview.footnote.self':
    'Lưu ý: Việc trả lời cuộc khảo sát này sẽ giúp chúng tôi tạo ra trải nghiệm tốt hơn cho tất cả người dùng. Bạn vẫn sẽ xuất hiện dưới dạng “Người dùng trước đây” sau khi bạn xóa tài khoản của mình.',
  'focused-task-close-account.delete-account.content-preview.formerUser':
    'Người dùng cũ',
  'focused-task-close-account.delete-account.content-preview.heading.admin':
    'Bạn muốn người dùng đã bị xóa xuất hiện như thế nào?',
  'focused-task-close-account.delete-account.content-preview.heading.self':
    'Bạn muốn tài khoản đã bị xóa của mình xuất hiện như thế nào?',
  'focused-task-close-account.delete-account.content-preview.line.survey.admin':
    'Nếu chúng tôi cho bạn lựa chọn, bạn muốn người dùng đã bị xóa xuất hiện như thế nào trước những người dùng khác?',
  'focused-task-close-account.delete-account.content-preview.line.survey.self':
    'Nếu chúng tôi cho bạn lựa chọn, bạn muốn xuất hiện như thế nào trước những người dùng khác?',
  'focused-task-close-account.delete-account.content-preview.paragraph.survey.admin':
    'Sau khi tài khoản người dùng bị xóa, họ sẽ xuất hiện trước những người dùng khác là “Người dùng trước đây”. Vui lòng dành chút thời gian trả lời câu hỏi khảo sát của chúng tôi.',
  'focused-task-close-account.delete-account.content-preview.paragraph.survey.self':
    'Sau khi tài khoản của bạn bị xóa, bạn sẽ xuất hiện trước những người dùng khác là “Người dùng trước đây”. Vui lòng dành chút thời gian trả lời câu hỏi khảo sát của chúng tôi.',
  'focused-task-close-account.delete-account.drop-down-collapse-button':
    'Hiển thị ít hơn',
  'focused-task-close-account.delete-account.drop-down-expand-button':
    'hơn {num}',
  'focused-task-close-account.delete-account.overview.first.line.admin':
    'Bạn sắp xóa tài khoản của:',
  'focused-task-close-account.delete-account.overview.first.line.self':
    'Bạn sắp xóa tài khoản của mình:',
  'focused-task-close-account.delete-account.overview.heading.admin':
    'Xóa tài khoản',
  'focused-task-close-account.delete-account.overview.heading.self':
    'Xóa tài khoản của bạn',
  'focused-task-close-account.delete-account.overview.inline-dialog.content-created.admin':
    'Ví dụ: các trang, các vấn đề và nhận xét mà họ đã tạo ra trong sản phẩm.',
  'focused-task-close-account.delete-account.overview.inline-dialog.content-created.self':
    'Ví dụ: các trang, các vấn đề và nhận xét mà bạn đã tạo ra trong sản phẩm.',
  'focused-task-close-account.delete-account.overview.inline-dialog.data-apps.admin':
    'Bạn hoặc những người dùng khác có thể đã cài đặt các ứng dụng bổ sung các tính năng vào sản phẩm Atlassian. Những ứng dụng này có thể đã lưu thông tin hồ sơ người dùng.',
  'focused-task-close-account.delete-account.overview.inline-dialog.data-apps.self':
    'Bạn hoặc những người dùng khác có thể đã cài đặt các ứng dụng bổ sung các tính năng vào sản phẩm Atlassian. Những ứng dụng này có thể đã lưu thông tin hồ sơ của bạn.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li1.admin':
    'Thông tin liên quan đến việc mua hàng mà chúng tôi bắt buộc phải lưu giữ lại để lập báo cáo tài chính.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li1.self':
    'Thông tin liên quan đến việc mua hàng mà chúng tôi bắt buộc phải lưu giữ lại để lập báo cáo tài chính.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li2.admin':
    'Hồ sơ cho thấy rằng chúng tôi đã xóa tài khoản của ai đó mà chúng tôi có thể cần cung cấp cho cơ quan quản lý.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li2.self':
    'Hồ sơ cho thấy rằng chúng tôi đã xóa tài khoản của ai đó mà chúng tôi có thể cần cung cấp cho cơ quan quản lý.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li3.admin':
    'Dữ liệu được sử dụng cho vụ kiện đang diễn ra mà chúng tôi bắt buộc phải giữ lại theo yêu cầu của pháp luật.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.li3.self':
    'Dữ liệu được sử dụng cho vụ kiện đang diễn ra mà chúng tôi bắt buộc phải giữ lại theo yêu cầu của pháp luật.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p1.admin':
    'Chúng tôi lưu giữ dữ liệu cá nhân trong khoảng thời gian giới hạn khi chúng tôi có hoạt động kinh doanh chính đáng hoặc mục đích hợp pháp. Một số ví dụ bao gồm:',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p1.self':
    'Chúng tôi lưu giữ dữ liệu cá nhân trong khoảng thời gian giới hạn khi chúng tôi có hoạt động kinh doanh chính đáng hoặc mục đích hợp pháp. Một số ví dụ bao gồm:',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p2.admin':
    'Chúng tôi không xóa bất kỳ dữ liệu cá nhân nào khỏi nội dung do người dùng tạo, như tên hoặc địa chỉ email mà họ đã nhập vào trang hoặc ấn phẩm. Quản trị viên sản phẩm cần xóa dữ liệu đó theo cách thủ công.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p2.self':
    'Chúng tôi không xóa bất kỳ dữ liệu cá nhân nào khỏi nội dung mà bạn hoặc người khác đã tạo, như tên hoặc địa chỉ email đã được nhập vào trang hoặc ấn phẩm. Quản trị viên sản phẩm của bạn cần xóa dữ liệu đó theo cách thủ công.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p3.admin':
    'Người dùng có quyền gửi khiếu nại cho cơ quan quản lý tại quốc gia của họ.',
  'focused-task-close-account.delete-account.overview.inline-dialog.personal-data-will-be-deleted.p3.self':
    'Bạn có quyền gửi khiếu nại cho cơ quan quản lý tại quốc gia của bạn.',
  'focused-task-close-account.delete-account.overview.paragraph.about-to-delete.admin':
    'Khi bạn xóa tài khoản:',
  'focused-task-close-account.delete-account.overview.paragraph.about-to-delete.self':
    'Khi bạn xóa tài khoản của mình:',
  'focused-task-close-account.delete-account.overview.paragraph.content-created.admin':
    'Nội dung mà họ đã tạo sẽ vẫn có trong dịch vụ tài khoản Atlassian.',
  'focused-task-close-account.delete-account.overview.paragraph.content-created.self':
    'Nội dung mà bạn đã tạo sẽ vẫn có trong dịch vụ tài khoản Atlassian.',
  'focused-task-close-account.delete-account.overview.paragraph.grace-period.admin':
    'Sau thời gian ân hạn 14 ngày, bạn sẽ không thể hủy xóa tài khoản.',
  'focused-task-close-account.delete-account.overview.paragraph.list-of-apps-with-personal-data.admin':
    'Chúng tôi sẽ gửi cho bạn danh sách các ứng dụng có thể đã lưu dữ liệu cá nhân của họ qua email.',
  'focused-task-close-account.delete-account.overview.paragraph.list-of-apps-with-personal-data.self':
    'Chúng tôi sẽ gửi cho bạn danh sách các ứng dụng có thể đã lưu dữ liệu cá nhân của bạn qua email.',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.admin':
    '{fullName} sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Họ hiện có quyền truy cập vào:',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.admin.noSites':
    '{fullName} sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Hiện tại, họ không có quyền truy cập vào bất kỳ dịch vụ nào, ngoại trừ các dịch vụ như Community và Marketplace.',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.footnote':
    'Các dịch vụ tài khoản Atlassian khác, như Atlassian Community và Marketplace.',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.self':
    'Bạn sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Bạn hiện có quyền truy cập vào:',
  'focused-task-close-account.delete-account.overview.paragraph.loseAccess.self.noSites':
    'Bạn sẽ <b>ngay lập tức mất quyền truy cập</b> vào tất cả các dịch vụ tài khoản Atlassian. Hiện tại, bạn không có quyền truy cập vào bất kỳ dịch vụ nào, ngoại trừ các dịch vụ như Community và Marketplace.',
  'focused-task-close-account.delete-account.overview.paragraph.personal-data-will-be-deleted.admin':
    'Chúng tôi sẽ <b>xóa dữ liệu cá nhân của họ</b>, như họ tên và địa chỉ email, khỏi dịch vụ tài khoản Atlassian trong vòng 30 ngày, trừ một số trường hợp bắt buộc phải lưu giữ cho các hoạt động kinh doanh chính đáng hoặc mục đích hợp pháp.',
  'focused-task-close-account.delete-account.overview.paragraph.personal-data-will-be-deleted.self':
    'Chúng tôi sẽ <b>xóa dữ liệu cá nhân của bạn</b>, như họ tên và địa chỉ email, khỏi dịch vụ tài khoản Atlassian trong vòng 30 ngày, trừ một số trường hợp bắt buộc phải lưu giữ cho các hoạt động kinh doanh chính đáng hoặc mục đích hợp pháp.',
  'focused-task-close-account.delete-account.overview.warning-section.body':
    'Sau thời gian ân hạn 14 ngày, bạn sẽ không thể hủy xóa tài khoản. Nếu bạn cho rằng sau này bạn sẽ cần đến tài khoản này thì thay vì xóa, hãy hủy kích hoạt tài khoản.',
  'focused-task-close-account.delete-account.overview.warning-section.deactivated.body':
    'Sau thời gian ân hạn 14 ngày, bạn sẽ không thể hủy xóa tài khoản.',
  'focused-task-close-account.learnMore': 'Tìm hiểu thêm',
  'focused-task-close-account.next': 'Tiếp theo',
  'focused-task-close-account.previous': 'Trước',
};
