// eslint-disable-next-line import/no-extraneous-dependencies
import { type UNSAFE_IconMetadata } from '@af/icon-build-process';

const iconMetadata: UNSAFE_IconMetadata = {
  add: {
    oldName: 'AddIcon',
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage:
      'Reserved for creating and adding an object as a secondary action within a Menu Item.',
    tags: 'create, plus',
  },
  'check-circle': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for Helper Messages in Forms.',
    tags: 'tick, yes, success, filled',
  },
  'check-mark': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'TBD',
    tags: 'Known uses: table cells, checkboxes.',
  },
  'chevron-down': {
    oldName: 'ChevronDownIcon',
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for dropdown menus, selects, accordions, and expands.',
    tags: 'accordion, down',
  },
  'chevron-left': {
    oldName: 'ChevronLeftIcon',
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for collapse side nav and to indicate previous in dates.',
    tags: 'less than, <, previous',
  },
  'chevron-right': {
    oldName: 'ChevronRightIcon',
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for menu fly-outs and to indicate next in dates.',
    tags: 'greater than, >, next',
  },
  'chevron-up': {
    oldName: 'ChevronUpIcon',
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for accordions.',
    tags: 'up, accordion',
  },
  cross: {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Known uses: remove tag.',
    tags: 'remove, clear, x',
  },
  'cross-circle': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for Helper Messages in Forms.',
    tags: 'x, exit, clear, no, filled, form',
  },
  error: {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for Helper Messages in Forms.',
    tags: 'filled, status, form, helper',
  },
  information: {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for Helper Messages in Forms.',
    tags: 'info, filled, helper, tip, form',
  },
  'link-external': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage:
      'Reserved for links that open up a new tab as a secondary/tertiary action.',
    tags: 'new tab, new window, open in, url, hyperlink, www, http, https, website, external, shortcut, diagonal arrow, secondary, tertiary',
  },
  'lock-locked': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage:
      'Reserved for indicating something is locked in the side navigation Menu Item.',
    tags: 'secondary, tertiary, permissions, no access, restricted, security, secure, forbidden, authentication',
  },
  'lock-unlocked': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage:
      'Reserved for indicating something is locked in the side navigation Menu Item.',
    tags: 'secondary, tertiary, open permissions, unrestricted access, security, insecure, authentication',
  },
  'show-more-horizontal': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for secondary/tertiary more action menus.',
    tags: 'ellipses, three dots, meatball, more actions, secondary, tertiary',
  },
  'show-more-vertical': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage:
      'Reserved for secondary/tertiary action menus, traditionally on mobile.',
    tags: 'three dots, kebab, more actions, secondary, tertiary',
  },
  'star-starred': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage:
      'Reserved for starred or favourited objects as a secondary/tertiary action.',
    tags: 'favourite, star, starred, filled, menu, secondary, tertiary',
  },
  'star-unstarred': {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage:
      'Reserved for starring or favoriting objects as a secondary/tertiary action.',
    tags: 'favourite, star, form, secondary, tertiary',
  },
  warning: {
    categorization: 'Multi-purpose',
    location: 'ADS',
    type: 'Utility',
    team: 'ADS',
    usage: 'Reserved for Helper Messages in Forms.',
    tags: 'alert, danger, triangle, filled, secondary, tertiary',
  },
};

export default iconMetadata;
