import { type IconMetadata } from '@af/icon-build-process';

const metadata: IconMetadata = {
	add: {
		keywords: ['create', 'plus'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7367',
		usage:
			'Reserved for creating and adding an object as a secondary/tertiary action in a menu item.',
		replacement: {
			name: 'add',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'arrow-down': {
		keywords: ['down', 'bottom', 'sorting'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '15144:15529',
		usage: 'Know uses: sorting table headers or Bitbucket code difference.',
		replacement: {
			name: 'arrow-down',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'arrow-left': {
		keywords: ['back', 'previous'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '15144:15527',
		usage: 'Known uses: back to previous screen, previous slide.',
		replacement: {
			name: 'arrow-left',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'arrow-right': {
		keywords: ['forward', 'next', 'link'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '15144:15528',
		usage: 'Known uses: link to nested menu item, a linked menu item, next slide.',
		replacement: {
			name: 'arrow-right',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'arrow-up': {
		keywords: ['improvement', 'jira status'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '15144:15526',
		usage: 'Known uses: back to top.',
		replacement: {
			name: 'arrow-up',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'check-circle': {
		keywords: ['tick', 'yes', 'checkmark'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7365',
		usage: '📦 @atlaskit/icon/utility/check-circle',
		replacement: {
			name: 'check-circle',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'check-mark': {
		keywords: ['tick'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10271:13763',
		usage: '📦 @atlaskit/icon/utility/check-mark',
		replacement: {
			name: 'check-mark',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'chevron-double-left': {
		keywords: ['calendar year', '<<', 'less than', 'previous'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '31300:8198',
		usage: 'Reserved for calendar year button.',
		slackChannel: '#help-design-system',
		replacement: {
			name: 'chevron-double-left',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'chevron-double-right': {
		keywords: ['calendar year', '>>', 'greater than', 'next'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '31300:11074',
		usage: 'Reserved for calendar year button.',
		slackChannel: '#help-design-system',
		replacement: {
			name: 'chevron-double-right',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'chevron-down': {
		keywords: ['accordion', 'down'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7369',
		usage: 'Reserved for dropdown menus, selects, accordions, and expands.',
		replacement: {
			name: 'chevron-down',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'chevron-left': {
		keywords: ['less than', '<', 'previous'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7368',
		usage: 'Reserved for collapse side nav and to indicate previous in dates.',
		replacement: {
			name: 'chevron-left',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'chevron-right': {
		keywords: ['greater than', '>', 'next'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7366',
		usage: 'Reserved for menu fly outs and to indicate next in dates.',
		replacement: {
			name: 'chevron-right',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'chevron-up': {
		keywords: ['up', 'accordion'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7371',
		usage: 'Reserved for accordions.',
		replacement: {
			name: 'chevron-up',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	cross: {
		keywords: ['remove', 'clear', 'x'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10522:17206',
		usage: 'Known uses: remove tag.',
		replacement: {
			name: 'cross',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'cross-circle': {
		keywords: ['x', 'exit', 'clear', 'no', 'filled', 'form'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7364',
		usage: 'Reserved for Helper Messages in Forms.',
		replacement: {
			name: 'cross-circle',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'drag-handle': {
		keywords: ['drag handler', 'drag dots', 'reorder', 'move'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '15317:13062',
		usage: 'Reserved for draggable elements.',
		replacement: {
			name: 'drag-handle-vertical',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'drag-handle-horizontal': {
		keywords: ['drag', 'drag handler', 'reorder columns', 'move'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '37548:2891',
		usage: 'Reserved for dragging elements along a horizontal axis.',
		slackChannel: '#icon-contributions',
		replacement: {
			name: 'drag-handle-horizontal',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'drag-handle-vertical': {
		keywords: ['drag', 'drag handler', 'move', 'reorder rows'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '37548:2047',
		usage: 'Reserved for dragging elements along a vertical axis.',
		slackChannel: '#icon-contributions',
		replacement: {
			name: 'drag-handle-vertical',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	error: {
		keywords: ['filled', 'status', 'form', 'helper'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7362',
		usage: 'Reserved for Helper Messages in Forms.',
		replacement: {
			name: 'status-error',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	information: {
		keywords: ['info', 'filled', 'helper', 'tip', 'form'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7363',
		usage: 'Reserved for Helper Messages in Forms.',
		replacement: {
			name: 'status-information',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'link-external': {
		keywords: [
			'new tab',
			'new window',
			'open in',
			'url',
			'hyperlink',
			'www',
			'http',
			'https',
			'website',
			'external',
			'shortcut',
			'diagonal arrow',
			'secondary',
			'tertiary',
		],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10130:11770',
		usage: 'Reserved for links that open up a new tab as a secondary/tertiary action.',
		replacement: {
			name: 'link-external',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'lock-locked': {
		keywords: [
			'secondary',
			'tertiary',
			'permissions',
			'no access',
			'restricted',
			'security',
			'secure',
			'forbidden',
			'authentication',
		],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10252:13024',
		usage: 'Reserved for indicating something is locked in the side navigation Menu Item.',
		replacement: {
			name: 'lock-locked',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'lock-unlocked': {
		keywords: [
			'secondary',
			'tertiary',
			'open permissions',
			'unrestricted access',
			'security',
			'insecure',
			'authentication',
		],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10252:13023',
		usage: 'Reserved for indicating something is locked in the side navigation Menu Item.',
		replacement: {
			name: 'lock-unlocked',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'show-more-horizontal': {
		keywords: ['ellipses', 'three dots', 'meatball', 'more actions', 'secondary', 'tertiary'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10060:11268',
		usage: 'Reserved for secondary/tertiary more action menus.',
		replacement: {
			name: 'show-more-horizontal',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'show-more-vertical': {
		keywords: ['three dots', 'kebab', 'more actions', 'secondary', 'tertiary'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10060:11267',
		usage: 'Reserved for secondary/tertiary action menus, traditionally on mobile.',
		replacement: {
			name: 'show-more-vertical',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'star-starred': {
		keywords: ['favourite', 'star', 'starred', 'filled', 'menu', 'secondary', 'tertiary'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10069:11366',
		usage: 'Reserved for starred or favourited objects as a secondary/tertiary action.',
		replacement: {
			name: 'star-starred',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	'star-unstarred': {
		keywords: ['favourite', 'star', 'form', 'secondary', 'tertiary'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10069:11367',
		usage: 'Reserved for starring or favoriting objects as a secondary/tertiary action.',
		replacement: {
			name: 'star-unstarred',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	success: {
		keywords: ['tick', 'yes', 'success', 'filled'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '15049:30793',
		usage: 'Reserved for Helper Messages in Forms.',
		replacement: {
			name: 'status-success',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
	warning: {
		keywords: ['alert', 'danger', 'triangle', 'filled', 'secondary', 'tertiary'],
		categorization: 'utility',
		location: '@atlaskit/icon',
		team: 'Design System Team',
		type: 'utility',
		status: 'deprecated',
		id: '10003:7370',
		usage: 'Reserved for Helper Messages in Forms.',
		replacement: {
			name: 'status-warning',
			type: 'core',
			location: '@atlaskit/icon',
		},
	},
};

export default metadata;
