// eslint-disable-next-line import/no-extraneous-dependencies
import { type UNSAFE_IconMetadata } from '@af/icon-build-process';

const iconMetadata: UNSAFE_IconMetadata = {
	add: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for creating and adding an object.',
		tags: 'create, plus',
	},
	alert: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'Jira',
		usage: 'Reserved for alerts in JSM and Compass.',
		tags: 'alert, event, operations',
	},
	'align-center': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Editor',
		usage: 'Known uses: align text center, align center.',
		tags: 'alignment, text, content',
	},
	'align-left': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Editor',
		usage: 'Known uses: align text left, align content left, summary.',
		tags: 'alignment, text, content, summary',
	},
	'align-right': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Editor',
		usage: 'Known uses: align text right, align content right.',
		tags: 'alignment, text, content',
	},
	'angle-brackets': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Known uses: code or source code in Bitbucket and Jira.',
		tags: 'code, <>, </>, syntax',
	},
	app: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'ADS',
		usage: 'Reserved for marketplace apps and integrations across products.',
		tags: 'add-on, add on, plugin, external app, third-party app',
	},
	apps: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'ADS',
		usage: 'Reserved for adding or viewing apps.',
		tags: 'third-party, applications',
	},
	'archive-box': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: archiving pages, storage.',
		tags: 'file box',
	},
	'arrow-down': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Know uses: sorting table headers or Bitbucket code difference.',
		tags: 'down, bottom, sorting',
	},
	'arrow-left': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: back to previous screen, previous slide.',
		tags: 'back, previous',
	},
	'arrow-right': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: link to nested menu item, a linked menu item, next slide.',
		tags: 'forward, next, link',
	},
	'arrow-up': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: back to top.',
		tags: 'improvement',
	},
	'arrow-up-right': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: open a link in a new page (but not a new tab).',
		tags: 'expand, open, diagonal arrow',
	},
	'atlassian-intelligence': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'ADS',
		usage: 'Reserved for Atlassian Intelligence products or experiences.',
		tags: 'AI',
	},
	attachment: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for attaching files to issues or other objects.',
		tags: 'paperclip, attach',
	},
	audio: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		tags: 'music, musical note',
	},
	automation: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Automation',
		usage: 'Reserved to represent an Automation.',
		tags: 'lightning bolt, automation rule',
	},
	backlog: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for backlogs in Jira.',
		tags: 'rows',
	},
	board: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for boards in Jira.',
		tags: 'columns, active sprint',
	},
	boards: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved as the icon to represent multiple boards.',
	},
	'book-with-bookmark': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Known uses: knowledge bases, articles, and other representations of books or info.',
		tags: 'knowledge base, article',
	},
	branch: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for branches in Bitbucket and Jira',
		tags: 'git branch, bitbucket branch, branches',
	},
	briefcase: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Atlas',
		usage: 'Known uses: Job title in Atlas, Operations in JSM.',
		tags: 'suitcase, toolbox, operations, business',
	},
	bug: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Known uses: Request types in JSM, bugs in Jira.',
		tags: 'bug report, test',
	},
	'bulleted-list': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Editor',
		usage: 'Known uses: bulleted lists, view all.',
		tags: 'bullets, unordered list',
	},
	calendar: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: date metadata, date input field, calendar view.',
		tags: 'date, month, day, year',
	},
	camera: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Known uses: upload photo in Trello, photos.',
	},
	capture: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
	},
	changes: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for changes in Jira.',
		tags: 'horizontal arrows',
	},
	'chart-bar': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Analytics',
		usage: 'Known uses: Reports in JSM, Space Analytics in Confluence, and other graph charts.',
		tags: 'graph, bar, analytics, report',
	},
	'chart-matrix': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Analytics',
		usage: 'Known uses: Matrix view in in JPD, and other matrix charts.',
		tags: 'dot chart, graph, matrix',
	},
	'chart-pie': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Analytics',
		usage: 'Known uses: pie charts.',
		tags: 'segment, chart, graph, pie',
	},
	'chart-trend': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Analytics',
		usage: 'Known uses: charts, reports in Jira, and sprint insights.',
		tags: 'reports, graph, impact effort,',
	},
	'check-circle': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: success section messages or a list of done items.',
		tags: 'tick, yes, success, filled',
	},
	'check-mark': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: table cells, checkboxes.',
		tags: 'tick',
	},
	'checkbox-checked': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for interactive checkbox experiences. Consider using the checkbox component.',
		tags: 'filled, checked, select all',
	},
	'checkbox-indeterminate': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for interactive checkbox experiences. Consider using the checkbox component.',
		tags: 'filled, mixed',
	},
	'checkbox-unchecked': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for interactive checkbox experiences. Consider using the checkbox component.',
		tags: 'unchecked',
	},
	'child-issues': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Jira',
		usage: 'Reserved for child issues in Jira.',
	},
	clock: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: recent, time input, sprint time remaining.',
		tags: 'time, recent, history',
	},
	close: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for closing an element.',
		tags: 'cross, x',
	},
	'cloud-arrow-up': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: deployments in Jira.',
		tags: 'deployments, up arrow',
	},
	collapse: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Editor',
		usage: 'Reserved for contracting or reducing the width of an element.',
		tags: 'contract, width, horizontal arrows',
	},
	comment: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for comments on objects.',
		tags: 'speech bubble',
	},
	'comment-add': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for adding a comment to an object.',
		tags: 'speech bubble, plus',
	},
	commit: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Jira',
		usage: 'Reserved for commits in Jira or Bitbucket.',
		tags: 'git commit, bitbucket commit',
	},
	compass: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Global noun',
		usage: 'Known uses: templates.',
		tags: 'template',
	},
	component: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for components in Jira and Compass.',
		tags: 'lego, brick, block',
	},
	copy: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for copying data such as text, code or other objects.',
		tags: 'copy, object',
	},
	'credit-card': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: billing in Admin, invoices in PPC, payments.',
		tags: 'payment, invoice',
	},
	'cross-circle': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: clear text field, error status icon.',
		tags: 'x, exit, clear, no, filled',
	},
	customize: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: modify a sidebar order, change view, settings.',
		tags: 'customise, configure, modify, preferences, settings, sliders',
	},
	dashboard: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for dashboards in Jira.',
		tags: 'activity, view',
	},
	database: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'ADS',
		usage: 'Reserved for databases in Confluence.',
		tags: 'spreadsheet, table, data, cells',
	},
	decision: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for decisions.',
		tags: 'fork, diagonal arrow',
	},
	delete: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for removing or deleting an object.',
		tags: 'trash, bin, remove',
	},
	department: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Atlas',
		usage: 'Reserved for departments, reporting lines, or other tree chart representations.',
		tags: 'organization, organisation, org chart, hierarchy',
	},
	'device-mobile': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Known uses: call, contact us.',
		tags: 'iphone, mobile phone, cell phone',
	},
	download: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for file downloads.',
		tags: 'down arrow, file download',
	},
	'drag-handle': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for draggable elements.',
		tags: 'drag handler, drag dots, reorder, move',
	},
	edit: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for editing objects.',
		tags: 'pencil, pencil on page',
	},
	email: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for when an email-related things.',
		tags: 'envelope, message',
	},
	emoji: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Editor',
		usage: "Reserved for Editor as a category for Emoji's.",
		tags: 'smiley face, emoticon',
	},
	'emoji-add': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Editor',
		usage: 'Reserved for adding an emoji reaction.',
		tags: 'smiley face, emoticon, plus',
	},
	epic: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for epics in Jira.',
		tags: 'lightning bolt, filled',
	},
	error: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for when there is an error.',
		tags: 'filled, status',
	},
	expand: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for expanding a object or panel.',
		tags: 'diagonal, resize',
	},
	'eye-open': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage:
			'Known uses: watch page in Confluence, show password in text field, and following in Atlas.',
		tags: 'watch, visible, visbility, permissions',
	},
	'eye-open-filled': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: watched pages in Confluence.',
		tags: 'watching, visible, visbility, permissions, filled',
	},
	feed: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Atlas',
		usage: 'Reserved for update feeds in Atlassian Home.',
		tags: "feed, updates, release notes, what's new",
	},
	feedback: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Known uses: customer feedback.',
		tags: 'diagonal arrow, chat bubble',
	},
	filter: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for filterting data or objects.',
		tags: 'funnel, refine',
	},
	flag: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Editor',
		usage: 'Known uses: flags in Editor, feature flags.',
		tags: 'important, emoji category',
	},
	flask: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Known uses: labs in Jira.',
		tags: 'labs, test, erlenmeyer flask, beaker',
	},
	'folder-closed': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for folders in Confluence.',
		tags: 'directory',
	},
	'folder-open': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for open folders in Confluence.',
		tags: 'directory',
	},
	'fullscreen-enter': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Media',
		usage: 'Reserved for full screen videos or objects.',
		tags: 'full screen',
	},
	'fullscreen-exit': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Media',
		usage: 'Reserved for return screen videos or objects.',
		tags: 'un-full screen, un-fullscreen',
	},
	globe: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: public link in Confluence share dialog, global rules in Automation.',
		tags: 'world',
	},
	goal: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Atlas',
		usage: 'Reserved for goals in Atlas.',
		tags: 'target',
	},
	grid: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: spaces in Confluence, and grid view, all content in Confluence.',
		tags: 'view all content, tile view, layout, grid, tiles',
	},
	hashtag: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: topics in Atlas, tags.',
		tags: 'tag, topic, pound',
	},
	heart: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Editor',
		usage: 'Known uses: emoji symbols in Editor.',
		tags: 'like, love, emoji category',
	},
	home: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage:
			'Reserved for home in navigation. When a user clicks on this, they should return to the homepage.',
		tags: 'house, building',
	},
	image: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: images, image upload.',
		tags: 'picture, asset',
	},
	inbox: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Unknown',
		usage: "Known uses: 'Your work' in Confluence, inbox, mail.",
		tags: 'document tray, work, letter, post',
	},
	incident: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for incidents in Jira.',
		tags: 'witches hat, traffic cone',
	},
	information: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: helper message under textfield, information state insection messages.',
		tags: 'info, filled, helper, tip',
	},
	issue: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for issues in Jira.',
	},
	issues: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for multiple issues in Jira.',
		tags: 'multiple issues',
	},
	lightbulb: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Platform',
		team: 'ADS',
		usage: 'Known uses: learnings in Atlas, initiatives in Jira.',
		tags: 'idea, initiative, tip, learnings',
	},
	link: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for links, urls, or copy link.',
		tags: 'url, hyperlink, website, www, http,',
	},
	'link-broken': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for removing a link.',
		tags: 'unlink, remove link, break link, url, hyperlink, website, www, https',
	},
	'link-external': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for links that open up a new tab.',
		tags: 'new tab, new window, open in, url, hyperlink, www, http, https, website, external, shortcut, diagonal arrow',
	},
	'lobby-bell': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		team: 'Editor',
		type: 'Platform',
		usage: 'Known uses: risks in Atlas.',
		tags: 'ding, risks',
	},
	location: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: location in Atlas.',
		tags: 'map, pin, address',
	},
	'lock-locked': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: secure password in textfields, locked page in Confluence.',
		tags: 'permissions, no access, restricted, security, secure, forbidden, authentication',
	},
	'lock-unlocked': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: unlocked page in Confluence.',
		tags: 'open permissions, unrestricted access, security, insecure, authentication',
	},
	'log-in': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for login.',
		tags: 'sign in, enter, account',
	},
	'log-out': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for logout.',
		tags: 'sign out, exit, account',
	},
	marketplace: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for Atlassian Marketplace.',
		tags: 'app store, storefront, stand, third-party developer',
	},
	maximize: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Media',
		usage: 'Reserved for maximizing screens, panels, or objects.',
		tags: 'resize, diagonal arrows, bigger',
	},
	megaphone: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: feedback in products.',
		tags: 'announcement, bullhorn, feedback, news',
	},
	mention: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Editor',
		usage: 'Reserved for user mentions.',
		tags: 'at symbol, @, tag, username',
	},
	microphone: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Known uses: record sounds in Trello.',
		tags: 'mic, mic on, voice, speak',
	},
	minimize: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: minimize modal window, minimize panel, minimize video screen.',
		tags: 'minimise, resize, diagonal arrows',
	},
	node: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Confluence',
		usage: 'Reserved for a non-expandable item in a page tree.',
		tags: 'page, dot, page tree, navigation',
	},
	'office-building': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: office in Atlas, company.',
		tags: 'organization, organisation, business',
	},
	page: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'ADS',
		usage: 'Reserved for pages in Confluence.',
		tags: 'feed, document',
	},
	pages: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for multipe pages in Confluence.',
		tags: 'feeds, documents',
	},
	person: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: representing a person or user, owner, contributor.',
		tags: 'user, customer',
	},
	'person-add': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for adding a user to an object.',
		tags: 'user, customer, plus',
	},
	'person-added': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for a user added to an object.',
		tags: 'user, customer, check, tick',
	},
	'person-avatar': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for user avatar.',
		tags: 'user, customer',
	},
	'person-offboard': {
		categorization: 'Single-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		tags: 'user, customer, right arrow',
	},
	phone: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Known uses: call us, phone number input.',
		tags: 'call, dial out',
	},
	pin: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Known uses: pinning Jira issue fields.',
		tags: 'push pin, thumbtack, tack',
	},
	'pin-filled': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Known uses: pinned Jira issue fields.',
		tags: 'push pin, thumbtack, tack, filled',
	},
	shortcut: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for shortcuts in Jira.',
		tags: 'add shortcut, square, plus',
	},
	'power-plug': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Unknown',
		usage: 'Known uses: plugins, add ons.',
		tags: 'plug-in, add-on, socket',
	},
	premium: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Growth',
		usage: 'Reserved for premium features.',
		tags: 'AI, sparkles, stars, new, feature',
	},
	'presenter-mode': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Confluence',
		usage: 'Reserved for presenter mode in Confluence.',
		tags: 'pointer, cursor, presentation, present',
	},
	printer: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: print page, print-friendly view.',
		tags: 'print',
	},
	'priority-blocker': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for blocker issue priority.',
		tags: 'blocked, showstopper',
	},
	'priority-critical': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for critial issue priority.',
		tags: 'issue, priority',
	},
	'priority-high': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for high issue priority.',
		tags: 'issue, priority',
	},
	'priority-highest': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for highest issue priority.',
		tags: 'issue, priority',
	},
	'priority-low': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for low issue priority.',
		tags: 'issue, priority',
	},
	'priority-lowest': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for lowest issue priority.',
		tags: 'issue, priority',
	},
	'priority-major': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for major issue priority.',
		tags: 'issue, priority',
	},
	'priority-medium': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		team: 'Jira',
		type: 'Platform',
		usage: 'Reserved for medium issue priority.',
		tags: 'issue, priority',
	},
	'priority-minor': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		team: 'Jira',
		type: 'Platform',
		usage: 'Reserved for minor issue priority.',
		tags: 'issue, priority',
	},
	'priority-trivial': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		team: 'Jira',
		type: 'Platform',
		usage: 'Reserved for trivial issue priority.',
		tags: 'issue, priority',
	},
	problem: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for problem issue priority.',
		tags: 'stop, issue, priority',
	},
	project: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Atlas',
		usage: 'Reserved for projects in Jira.',
		tags: 'rocket, rocketship, spaceship',
	},
	'pull-request': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for pull requests in Jira or Bitbucket.',
		tags: 'git pull request, bitbucket pull request',
	},
	'question-circle': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Known uses: help, tip.',
		tags: 'help, answers, faq',
	},
	'quotation-mark': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Jira',
		usage: 'Known uses: blockquote, comment, testimonial, blogs in Confluence.',
		tags: 'quote, testimonial, blockquote',
	},
	redo: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Reserved for redo in Editor.',
		tags: 'editor, redo, backwards',
	},
	release: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Jira',
		usage: 'Reserved for releases in Jira.',
		tags: 'ship, boat',
	},
	retry: {
		categorization: 'Single-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Reserved for retry.',
		tags: 'try again,',
	},
	roadmap: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'ADS',
		usage: 'Reserved for roadmaps in Jira or Trello.',
	},
	'ai-agent': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Rovo',
		usage: 'Reserved for Rovo Agent.',
		tags: 'Rovo, AI, chat agent',
	},
	'ai-chat': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Rovo',
		usage: 'Reserved for Rovo Chat.',
		tags: 'Rovo, AI, chat agent',
	},
	scorecard: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Analytics',
		usage: 'Reserved for Scorecard in Analytics.',
		tags: 'tick, check, circle, unfinished',
	},
	screen: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: assets in Jira.',
		tags: 'display, monitor, desktop',
	},
	search: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for searching objects.',
		tags: 'magnifying glass',
	},
	send: {
		categorization: 'Single-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Reserved for sending messages in Rovo Chat.',
		tags: 'submit, paper airplane, paper aeroplane',
	},
	settings: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for any object or user settings.',
		tags: 'system preferences, gear, cog',
	},
	shapes: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Whiteboards',
		usage: 'Reserved for shapes in Whiteboards.',
		tags: 'objects, whiteboard, asset, graphic',
	},
	share: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for sharing an object.',
		tags: 'share, access',
	},
	shield: {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Admin',
		usage: 'Reserved for classifications in Enterprise Trust.',
		tags: 'security, secure, safety, defence, protection, guard',
	},
	'show-more-horizontal': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for more action menus.',
		tags: 'ellipses, three dots, more actions',
	},
	'show-more-vertical': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for more action menus, traditionally on mobile.',
		tags: 'three dots, more actions',
	},
	'sidebar-collapse': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for collapsing the navigation sidebar.',
		tags: 'navigation, close sidebar',
	},
	'sidebar-expand': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for expanding the navigation sidebar.',
		tags: 'navigation, open sidebar',
	},
	snippet: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'BitBucket',
		usage: 'Reserved for snippets in Bitbucket.',
		tags: 'scissors, cut',
	},
	spreadsheet: {
		categorization: 'Single-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Reserved for spreadsheets.',
		tags: 'table, cells, data',
	},
	sprint: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'ADS',
		usage: 'Reserved for sprints in Jira.',
		tags: 'loop, iterate',
	},
	'star-starred': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for starred or favourited objects.',
		tags: 'favourite, star, starred, filled',
	},
	'star-unstarred': {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for starring or favoriting objects.',
		tags: 'favourite, star',
	},
	stopwatch: {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Known uses: timer in Confluence Whiteboards',
		tags: 'timer',
	},
	story: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for stories in Jira.',
		tags: 'bookmark, issue',
	},
	subtasks: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for subtasks in Jira.',
		tags: 'issue, todo, checklist',
	},
	tag: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for tags in Atlas.',
		tags: 'label, topic',
	},
	task: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for tasks in Jira.',
		tags: 'todo, list',
	},
	tasks: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for multiple tasks in Jira.',
		tags: 'todo, list',
	},
	teams: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Atlas',
		usage: 'Reserved for teams in Atlassian.',
		tags: 'infinite love, people, persons, customers, users',
	},
	'text-style': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Editor',
		usage: 'Reserved for text styles in Editor.',
		tags: 'characters, font, letters, type, typography',
	},
	'thumbs-down': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		team: 'ADS',
		type: 'Core',
		usage: 'Known uses: voting, feedback in AI.',
		tags: 'vote, downvote, dislike, feedback, hand',
	},
	'thumbs-up': {
		categorization: 'Multi-purpose',
		location: 'ADS',
		type: 'Platform',
		team: 'ADS',
		usage: 'Known uses: voting options in Jira, like',
		tags: 'vote, upvote, like, feedback, hand',
	},
	timeline: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Global noun',
		team: 'Jira',
		usage: 'Reserved for timelines in Jira or Trello.',
		tags: 'gantt, calendar',
	},
	transition: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Automation',
		usage: 'Reserved for transitions in Analytics.',
		tags: 'connector, movement',
	},
	undo: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Editor',
		usage: 'Reserved for undo in Editor.',
		tags: 'backward, mistake, correct',
	},
	upload: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for upload in Editor.',
		tags: 'stream, file',
	},
	video: {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Reserved for video in Media.',
		tags: 'media, movie',
	},
	'video-next': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Reserved for next video in Media.',
		tags: 'skip, next, media, forward',
	},
	'video-pause': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Reserved for pause video in Media.',
		tags: 'media, video',
	},
	'video-play': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Reserved for play video in Media.',
		tags: 'media, video',
	},
	'video-previous': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		usage: 'Reserved for previous video in Media.',
		tags: 'media, video, back, previous',
	},
	'volume-high': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		tags: 'louder, volume up',
	},
	'volume-low': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		tags: 'quiter, volume down',
	},
	'volume-muted': {
		categorization: 'Multi-purpose',
		location: 'Icon contributions',
		type: 'Platform',
		team: 'Media',
		tags: 'volume off, no volume',
	},
	warning: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Core',
		team: 'ADS',
		usage: 'Reserved for warning system status.',
		tags: 'alert, danger, triangle, filled',
	},
	whiteboard: {
		categorization: 'Single-purpose',
		location: 'ADS',
		type: 'Global noun',
		team: 'Whiteboards',
		usage: 'Reserved for whiteboards in Confluence.',
		tags: 'shapes, canvas',
	},
	'zoom-in': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Media',
		usage: 'Reserved for zooming in of an object or view.',
		tags: 'magnify, magnifying glass',
	},
	'zoom-out': {
		categorization: 'Single-purpose',
		location: 'Icon contributions',
		type: 'Core',
		team: 'Media',
		usage: 'Reserved for zooming out of an object or view.',
		tags: 'minify, magnifying glass',
	},
};
export default iconMetadata;
