/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'pt.profile-card.closed.account': 'Smazaný účet',
  'pt.profile-card.closed.account.has.date.a.few.months':
    'Účet uživatele je smazaný již několik měsíců.',
  'pt.profile-card.closed.account.has.date.last.month':
    'Účet uživatele byl minulý měsíc smazán.',
  'pt.profile-card.closed.account.has.date.more.than.a.year':
    'Účet uživatele je smazaný více než rok.',
  'pt.profile-card.closed.account.has.date.several.months':
    'Účet uživatele je smazaný již několik měsíců.',
  'pt.profile-card.closed.account.has.date.this.month':
    'Účet uživatele byl tento měsíc smazán.',
  'pt.profile-card.closed.account.has.date.this.week':
    'Účet uživatele byl smazán tento týden.',
  'pt.profile-card.closed.account.no.date': 'Účet uživatele byl smazán.',
  'pt.profile-card.disabled.account.default.name': 'Bývalý uživatel',
  'pt.profile-card.general.msg.disabled.user':
    'S touto osobou již nemůžete spolupracovat.',
  'pt.profile-card.inactive.account': 'Deaktivovaný účet',
  'pt.profile-card.inactive.account.has.date.a.few.months':
    'Účet uživatele je deaktivovaný již několik měsíců.',
  'pt.profile-card.inactive.account.has.date.last.month':
    'Účet uživatele byl deaktivován minulý měsíc.',
  'pt.profile-card.inactive.account.has.date.more.than.a.year':
    'Účet uživatele je deaktivovaný více než rok.',
  'pt.profile-card.inactive.account.has.date.several.months':
    'Účet uživatele je deaktivovaný již několik měsíců.',
  'pt.profile-card.inactive.account.has.date.this.month':
    'Účet uživatele byl tento měsíc deaktivován.',
  'pt.profile-card.inactive.account.has.date.this.week':
    'Účet uživatele byl deaktivován tento týden.',
  'pt.profile-card.inactive.account.no.date': 'Účet uživatele byl deaktivován.',
  'pt.team-profile-card.error.refresh-button': 'Zkusit znovu',
  'pt.team-profile-card.error.suggestion':
    'Chvíli počkejte a pak to zkuste znovu.',
  'pt.team-profile-card.error.title':
    'Při pokusu o načtení informací o tomto týmu se vyskytly problémy',
  'pt.team-profile-card.team.action.view-profile': 'Zobrazit profil',
  'pt.team-profile-card.team.member.count':
    '{count, plural, one {Tým • {count} člen} few {Tým • {count} členové} many {Tým • {count} člena} other {Tým • {count} členů}}',
  'pt.team-profile-card.team.member.count-including-you':
    '{count, plural, one {Tým • {count} člen včetně vás} few {Tým • {count} členové včetně vás} many {Tým • {count} člena včetně vás} other {Tým • {count} členů včetně vás}}',
  'pt.team-profile-card.team.member.many': 'Tým • 50 a více členů',
  'pt.team-profile-card.team.member.many-including-you':
    'Tým • 50 a více členů včetně vás',
};
