/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//English (United Kingdom)
export default {
  'profilecard.agent-profile-card.delete-agent-error-flag-description':
    'Something went wrong while deleting the agent. Try again in a few moments.',
  'profilecard.agent-profile-card.delete-agent-error-flag-title': 'Failed to delete Agent',
  'profilecard.agent-profile-card.delete-agent-success-flag-description': 'You deleted {agentName}',
  'profilecard.agent-profile-card.delete-agent-success-flag-title': 'Agent deleted',
  'profilecard.agent-profile.agent-delete-confirm.cancel-text': 'Cancel',
  'profilecard.agent-profile.agent-delete-confirm.confirm-text': 'Delete',
  'profilecard.agent-profile.delete-agent-confirm-body':
    'Are you sure you want to delete this agent? This action cannot be undone.',
  'profilecard.agent-profile.delete-agent-confirm-title': 'Delete "{agentName}"?',
  'profilecard.agent-profile.delete-agent-error': 'Could not delete agent',
  'profilecard.agent-profile.delete-agent-error.agent-in-use': 'Agent is currently in use. Try again later.',
  'profilecard.agent-profile.delete-agent-error.agent-not-found': 'That agent could not be found.',
  'profilecard.agent-profile.delete-agent-error.incorrect-owner':
    'You cannot delete agents you have not created yourself. Please contact the agent owner.',
  'profilecard.agent-profile.delete-agent-success': 'Agent has been deleted!',
  'profilecard.user.trigger.aria-label': 'More information about {fullName}',
  'profilecard.user.trigger.fallback-aria-label': 'More information about this user',
  'pt.profile-card.closed.account': 'Account deleted',
  'pt.profile-card.closed.account.has.date.a.few.months': 'Their account has been deleted for a few months.',
  'pt.profile-card.closed.account.has.date.last.month': 'Their account was deleted last month.',
  'pt.profile-card.closed.account.has.date.more.than.a.year': 'Their account has been deleted for more than a year.',
  'pt.profile-card.closed.account.has.date.several.months': 'Their account has been deleted for several months.',
  'pt.profile-card.closed.account.has.date.this.month': 'Their account was deleted this month.',
  'pt.profile-card.closed.account.has.date.this.week': 'Their account was deleted this week.',
  'pt.profile-card.closed.account.no.date': 'Their account has been deleted.',
  'pt.profile-card.disabled.account.default.name': 'Former user',
  'pt.profile-card.general.msg.disabled.user': 'You can no longer collaborate with this person.',
  'pt.profile-card.give-kudos': 'Give kudos',
  'pt.profile-card.inactive.account': 'Account deactivated',
  'pt.profile-card.inactive.account.has.date.a.few.months': 'Their account has been deactivated for a few months.',
  'pt.profile-card.inactive.account.has.date.last.month': 'Their account was deactivated last month.',
  'pt.profile-card.inactive.account.has.date.more.than.a.year':
    'Their account has been deactivated for more than a year.',
  'pt.profile-card.inactive.account.has.date.several.months': 'Their account has been deactivated for several months.',
  'pt.profile-card.inactive.account.has.date.this.month': 'Their account was deactivated this month.',
  'pt.profile-card.inactive.account.has.date.this.week': 'Their account was deactivated this week.',
  'pt.profile-card.inactive.account.no.date': 'Their account has been deactivated.',
  'pt.profile-card.more-icon-label': 'More',
  'pt.team-profile-card.directReports.heading': 'Direct reports',
  'pt.team-profile-card.error.refresh-button': 'Try again',
  'pt.team-profile-card.error.suggestion': 'Wait a few moments, then try again.',
  'pt.team-profile-card.error.title': 'We’re having trouble retrieving this teams information',
  'pt.team-profile-card.forbidden-error-state.description': 'You don’t have access to view this team.',
  'pt.team-profile-card.forbidden-error-state.title': 'We can’t show you this team',
  'pt.team-profile-card.manager.heading': 'Manager',
  'pt.team-profile-card.team.action.view-profile': 'View profile',
  'pt.team-profile-card.team.member.count': 'Team • {count} {count, plural, one {member} other {members}}',
  'pt.team-profile-card.team.member.count-including-you':
    'Team • {count} {count, plural, one {member} other {members}}, including you',
  'pt.team-profile-card.team.member.many': 'Team • 50+ members',
  'pt.team-profile-card.team.member.many-including-you': 'Team • 50+ members, including you',
  'ptc-directory.agent-profile.action.dropdown.chat-to-agent.nonfinal': 'Chat to Agent',
  'ptc-directory.agent-profile.action.dropdown.copy-link.nonfinal': 'Copy link',
  'ptc-directory.agent-profile.action.dropdown.delete.nonfinal': 'Delete Agent',
  'ptc-directory.agent-profile.action.dropdown.duplicate.nonfinal': 'Duplicate Agent',
  'ptc-directory.agent-profile.action.dropdown.edit.nonfinal': 'Edit Agent',
};
