/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'pt.profile-card.closed.account': '削除済みアカウント',
  'pt.profile-card.closed.account.has.date.a.few.months':
    'アカウントは 2〜3 か月前に削除されました。',
  'pt.profile-card.closed.account.has.date.last.month':
    'アカウントは先月削除されました。',
  'pt.profile-card.closed.account.has.date.more.than.a.year':
    'アカウントは 1 年以上前に削除されました。',
  'pt.profile-card.closed.account.has.date.several.months':
    'アカウントは数か月前に削除されました。',
  'pt.profile-card.closed.account.has.date.this.month':
    'アカウントは今月削除されました。',
  'pt.profile-card.closed.account.has.date.this.week':
    'アカウントは今週削除されました。',
  'pt.profile-card.closed.account.no.date': 'アカウントは削除されています。',
  'pt.profile-card.disabled.account.default.name': '元ユーザー',
  'pt.profile-card.general.msg.disabled.user':
    'もうこの人とコラボレーションすることはできません。',
  'pt.profile-card.inactive.account': '無効なアカウント',
  'pt.profile-card.inactive.account.has.date.a.few.months':
    'アカウントは 2〜3 か月前に無効になりました。',
  'pt.profile-card.inactive.account.has.date.last.month':
    'アカウントは先月無効になりました。',
  'pt.profile-card.inactive.account.has.date.more.than.a.year':
    'アカウントは 1 年以上前に無効になりました。',
  'pt.profile-card.inactive.account.has.date.several.months':
    'アカウントは数か月前に無効になりました。',
  'pt.profile-card.inactive.account.has.date.this.month':
    'アカウントは今月無効になりました。',
  'pt.profile-card.inactive.account.has.date.this.week':
    'アカウントは今週無効になりました。',
  'pt.profile-card.inactive.account.no.date':
    'アカウントは無効になっています。',
};
