/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'pt.profile-card.closed.account': 'Konto zostało usunięte',
  'pt.profile-card.closed.account.has.date.a.few.months':
    'Jej konto zostało usunięte przynajmniej kilka miesięcy temu.',
  'pt.profile-card.closed.account.has.date.last.month':
    'Jej konto usunięte w zeszłym miesiącu.',
  'pt.profile-card.closed.account.has.date.more.than.a.year':
    'Jej konto zostało usunięte przynajmniej rok temu.',
  'pt.profile-card.closed.account.has.date.several.months':
    'Jej konto zostało usunięte wiele miesięcy temu.',
  'pt.profile-card.closed.account.has.date.this.month':
    'Jej konto zostało usunięte w tym miesiącu.',
  'pt.profile-card.closed.account.has.date.this.week':
    'Jej konto zostało usunięte w tym tygodniu.',
  'pt.profile-card.closed.account.no.date': 'Jej konto zostało usunięte.',
  'pt.profile-card.disabled.account.default.name': 'Były użytkownik',
  'pt.profile-card.general.msg.disabled.user':
    'Nie możesz już współpracować z tą osobą.',
  'pt.profile-card.inactive.account': 'Konto zdezaktywowane',
  'pt.profile-card.inactive.account.has.date.a.few.months':
    'Jej konto zostało zdezaktywowane przynajmniej kilka miesięcy temu.',
  'pt.profile-card.inactive.account.has.date.last.month':
    'Jej konto zdezaktywowane w zeszłym miesiącu.',
  'pt.profile-card.inactive.account.has.date.more.than.a.year':
    'Jej konto zostało zdezaktywowane przynajmniej rok temu.',
  'pt.profile-card.inactive.account.has.date.several.months':
    'Jej konto zostało zdezaktywowane wiele miesięcy temu.',
  'pt.profile-card.inactive.account.has.date.this.month':
    'Jej konto zdezaktywowane w tym miesiącu.',
  'pt.profile-card.inactive.account.has.date.this.week':
    'Jej konto zostało zdezaktywowane w tym tygodniu.',
  'pt.profile-card.inactive.account.no.date':
    'Jej konto zostało zdezaktywowane pomyślnie.',
};
