/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Slovak
export default {
  'pt.profile-card.closed.account': 'Účet odstránený',
  'pt.profile-card.closed.account.has.date.a.few.months':
    'Jej účet je už niekoľko mesiacov odstránený.',
  'pt.profile-card.closed.account.has.date.last.month':
    'Jej účet bol minulý mesiac odstránený.',
  'pt.profile-card.closed.account.has.date.more.than.a.year':
    'Jej účet je už viac ako rok odstránený.',
  'pt.profile-card.closed.account.has.date.several.months':
    'Jej účet je už niekoľko mesiacov odstránený.',
  'pt.profile-card.closed.account.has.date.this.month':
    'Jej účet bol tento mesiac odstránený.',
  'pt.profile-card.closed.account.has.date.this.week':
    'Jej účet bol tento týždeň odstránený.',
  'pt.profile-card.closed.account.no.date': 'Jej účet bol odstránený.',
  'pt.profile-card.disabled.account.default.name': 'Bývalý používateľ',
  'pt.profile-card.general.msg.disabled.user':
    'S touto osobou už nemôžete spolupracovať.',
  'pt.profile-card.inactive.account': 'Účet deaktivovaný',
  'pt.profile-card.inactive.account.has.date.a.few.months':
    'Jej účet je už niekoľko mesiacov deaktivovaný.',
  'pt.profile-card.inactive.account.has.date.last.month':
    'Jej účet bol minulý mesiac deaktivovaný.',
  'pt.profile-card.inactive.account.has.date.more.than.a.year':
    'Jej účet je už viac ako rok deaktivovaný.',
  'pt.profile-card.inactive.account.has.date.several.months':
    'Jej účet je už niekoľko mesiacov deaktivovaný.',
  'pt.profile-card.inactive.account.has.date.this.month':
    'Jej účet bol tento mesiac deaktivovaný.',
  'pt.profile-card.inactive.account.has.date.this.week':
    'Jej účet bol tento týždeň deaktivovaný.',
  'pt.profile-card.inactive.account.no.date': 'Jej účet bol deaktivovaný.',
};
