/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Turkish (Turkey)
export default {
  'people-and-teams.team-profile-card.large-member-count': 'Katkıda bulunan takım • {memberCount} üye',
  'people-and-teams.team-profile-card.member-count':
    '{count, plural, one {Katkıda bulunan takım • {count,number} üye} other {Katkıda bulunan takım • {count,number} üye}}',
  'people-and-teams.team-profile-card.team-connections': 'Takım bağlantıları',
  'people-and-teams.team-profile-card.team-connections-header': 'Çalışma alanlarımız',
  'people-and-teams.team-profile-card.team-profile-description': 'Takım profili',
  'people-and-teams.team-profile-card.view-profile': 'Profili görüntüle',
  'profilecard.agent-profile-card.delete-agent-error-flag-description':
    'Temsilci silinirken bir hata oluştu. Birkaç dakika sonra tekrar deneyin.',
  'profilecard.agent-profile-card.delete-agent-error-flag-title': 'Temsilci silinemedi',
  'profilecard.agent-profile-card.delete-agent-success-flag-description': '{agentName} adlı temsilciyi sildiniz',
  'profilecard.agent-profile-card.delete-agent-success-flag-title': 'Temsilci silindi',
  'profilecard.agent-profile.agent-delete-confirm.cancel-text': 'İptal',
  'profilecard.agent-profile.agent-delete-confirm.confirm-text': 'Sil',
  'profilecard.agent-profile.delete-agent-confirm-body':
    'Bu temsilciyi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
  'profilecard.agent-profile.delete-agent-confirm-title': '"{agentName}" silinsin mi?',
  'profilecard.agent-profile.delete-agent-error': 'Temsilci silinemedi',
  'profilecard.agent-profile.delete-agent-error.agent-in-use':
    'Temsilci şu anda kullanılıyor. Daha sonra yeniden deneyin.',
  'profilecard.agent-profile.delete-agent-error.agent-not-found': 'Bu temsilci bulunamadı.',
  'profilecard.agent-profile.delete-agent-error.incorrect-owner':
    'Kendi oluşturmadığınız temsilcileri silemezsiniz. Lütfen temsilcinin sahibiyle iletişime geçin.',
  'profilecard.agent-profile.delete-agent-success': 'Temsilci silindi!',
  'profilecard.user.trigger.aria-label': '{fullName} hakkında daha fazla bilgi',
  'profilecard.user.trigger.fallback-aria-label': 'Bu kullanıcı hakkında daha fazla bilgi',
  'pt.profile-card.closed.account': 'Hesap silindi',
  'pt.profile-card.closed.account.has.date.a.few.months': 'Bu kullanıcının hesabı birkaç ay önce silindi.',
  'pt.profile-card.closed.account.has.date.last.month': 'Bu kullanıcının hesabı geçen ay silindi.',
  'pt.profile-card.closed.account.has.date.more.than.a.year':
    'Bu kullanıcının hesabı bir yıldan uzun bir süre önce silindi.',
  'pt.profile-card.closed.account.has.date.several.months': 'Bu kullanıcının hesabı birkaç ay önce silindi.',
  'pt.profile-card.closed.account.has.date.this.month': 'Bu kullanıcının hesabı bu ay silindi.',
  'pt.profile-card.closed.account.has.date.this.week': 'Bu kullanıcının hesabı bu hafta silindi.',
  'pt.profile-card.closed.account.no.date': 'Bu kullanıcının hesabı silindi.',
  'pt.profile-card.disabled.account.default.name': 'Eski kullanıcı',
  'pt.profile-card.general.msg.disabled.user': 'Artık bu kişiyle iş birliği yapamazsınız.',
  'pt.profile-card.give-kudos': 'Tebrik et',
  'pt.profile-card.inactive.account': 'Hesap devre dışı bırakıldı',
  'pt.profile-card.inactive.account.has.date.a.few.months':
    'Bu kullanıcının hesabı birkaç ay önce devre dışı bırakıldı.',
  'pt.profile-card.inactive.account.has.date.last.month': 'Bu kullanıcının hesabı geçen ay devre dışı bırakıldı.',
  'pt.profile-card.inactive.account.has.date.more.than.a.year':
    'Bu kullanıcının hesabı bir yıldan uzun bir süre önce devre dışı bırakıldı.',
  'pt.profile-card.inactive.account.has.date.several.months':
    'Bu kullanıcının hesabı birkaç ay önce devre dışı bırakıldı.',
  'pt.profile-card.inactive.account.has.date.this.month': 'Bu kullanıcının hesabı bu ay devre dışı bırakıldı.',
  'pt.profile-card.inactive.account.has.date.this.week': 'Bu kullanıcının hesabı bu hafta devre dışı bırakıldı.',
  'pt.profile-card.inactive.account.no.date': 'Bu kullanıcının hesabı devre dışı bırakıldı.',
  'pt.profile-card.more-icon-label': 'Daha fazlası',
  'pt.team-profile-card.aria-label': 'Bu takım hakkında daha fazla bilgi',
  'pt.team-profile-card.directReports.heading': 'Astlar',
  'pt.team-profile-card.error.refresh-button': 'Yeniden deneyin',
  'pt.team-profile-card.error.suggestion': 'Lütfen birkaç dakika bekleyip yeniden deneyin.',
  'pt.team-profile-card.error.title': 'Bu takımın bilgileri alınırken bir sorunla karşılaşıldı',
  'pt.team-profile-card.forbidden-error-state.description': 'Bu takımı görüntüleme erişiminiz yok.',
  'pt.team-profile-card.forbidden-error-state.title': 'Bu takım size gösterilemiyor',
  'pt.team-profile-card.manager.heading': 'Yönetici',
  'pt.team-profile-card.team.action.view-profile': 'Profili görüntüle',
  'pt.team-profile-card.team.member.count': '{count, plural, one {Takım • {count} üye} other {Takım • {count} üye}}',
  'pt.team-profile-card.team.member.count-including-you':
    '{count, plural, one {Takım • Siz de dahil olmak üzere {count} üye} other {Takım • Siz de dahil olmak üzere {count} üye}}',
  'pt.team-profile-card.team.member.many': "Takım • 50'den fazla üye",
  'pt.team-profile-card.team.member.many-including-you': "Takım • Siz de dahil olmak üzere 50'den fazla üye",
  'pt.team.profile-card.members.more-icon-label': '{count, plural, one {+{count} üye daha} other {+{count} üye daha}}',
  'pt.user-profile-card.reporting-lines.more-icon-label':
    '{count, plural, one {+{count} profil daha} other {+{count} profil daha}}',
  'team-profile-card.team-actions.give-kudos': 'Tebrik et',
  'team-profile-card.team-actions.more-actions.show-more-icon-label': 'Daha fazla göster',
};
