/* eslint-disable @atlaskit/editor/no-re-export */
export {
	RESIZE_HANDLE_AREA_DECORATION_GAP,
	ShadowEvent,
	TableCssClassName,
	TableDecorations,
} from '../types/index';
export type {
	AlignmentOptions,
	Cell,
	CellColumnPositioning,
	CellHoverMeta,
	CellTransform,
	ColumnResizingPluginAction,
	ColumnResizingPluginState,
	DraggableBehaviour,
	DraggableData,
	DraggableSourceData,
	DraggableTargetData,
	DraggableType,
	HandleTypes,
	InsertRowMethods,
	InsertRowOptions,
	InvalidNodeAttr,
	MessageDescriptor,
	PermittedLayoutsDescriptor,
	PluginConfig,
	PluginInjectionAPI,
	PluginInjectionAPIWithA11y,
	ReportInvalidNodeAttrs,
	RowInsertPosition,
	TableDirection,
	TablePluginAction,
	TablePluginState,
	TableSharedState,
	TableSharedStateInternal,
	ToolbarMenuConfig,
	ToolbarMenuContext,
	ToolbarMenuState,
	WidthToWidest,
} from '../types/index';
