/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//
export default {
  'link-create.unknown-error.description':
    '⁣⁢Refresh the page, or contact <a>Atlassian Support</a> if this keeps happening.⁠⁮⁫‌⁭؜⁡⁯‍⁮⁫⁭‌⁮⁯⁡؜⁠‌؜⁠⁯⁣⁤',
  'link-create.unknown-error.heading': '⁣⁢Something went wrong⁮⁯‍⁮⁪⁪‍⁡⁭⁡‌‌⁠⁫⁠⁮⁪⁬⁬‌⁡⁬⁬⁣⁤',
  'linkCreate.createForm.button.close': '⁣⁢Close‌‌‌⁡⁯⁯⁯‍⁡⁬⁬⁮⁮⁬⁭⁭⁪⁭⁡؜‌‍⁣⁤',
  'linkCreate.createForm.button.create': '⁣⁢Create‍⁡⁯‌⁬؜⁬⁡⁪؜⁯⁪⁫‍⁮⁯⁯⁫‌⁭‌⁬⁣⁤',
  'linkCreate.modal.heading': '⁣⁢Create new‌‌⁭⁯⁪⁠⁡⁯⁬؜‌⁮⁭⁪⁭⁠⁫⁠⁣⁤',
};
