/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//French (France)
export default {
  'link-create.unknown-error.description':
    'Actualisez la page ou contactez le <a>support Atlassian</a> si le problème se reproduit.',
  'link-create.unknown-error.heading': 'Une erreur est survenue',
  'linkCreate.createForm.button.close': 'Fermer',
  'linkCreate.createForm.button.create': 'Créer',
  'linkCreate.modal.heading': 'Créer',
};
