/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Portuguese (Brazil)
export default {
  'link-create.unknown-error.description':
    'Atualize a página ou fale com o <a>Suporte da Atlassian</a> se o erro persistir.',
  'link-create.unknown-error.heading': 'Algo deu errado',
  'linkCreate.createForm.button.close': 'Fechar',
  'linkCreate.createForm.button.create': 'Criar',
  'linkCreate.modal.heading': 'Criar novo',
};
