/**
 * THIS FILE WAS CREATED VIA CODEGEN DO NOT MODIFY {@see http://go/af-codegen}
 *
 * DEPRECATED, PLEASE DO NOT USE.
 * Default values can now be based on either light or legacy-light themes, whereas this only contains light theme values.
 *
 * Token names mapped to their value in the default Atlassian themes ('light').
 * These default values are used by the Babel plugin to optionally provide automatic fallbacks.
 *
 * @codegen <<SignedSource::2502bf5f723d604cd04596897e52d47f>>
 * @codegenCommand yarn build tokens
 */
const defaultTokenValues = {
  'color.text': '#172B4D',
  'color.text.accent.lime': '#4C6B1F',
  'color.text.accent.lime.bolder': '#37471F',
  'color.text.accent.red': '#AE2A19',
  'color.text.accent.red.bolder': '#601E16',
  'color.text.accent.orange': '#974F0C',
  'color.text.accent.orange.bolder': '#5F3811',
  'color.text.accent.yellow': '#7F5F01',
  'color.text.accent.yellow.bolder': '#533F04',
  'color.text.accent.green': '#216E4E',
  'color.text.accent.green.bolder': '#164B35',
  'color.text.accent.teal': '#206B74',
  'color.text.accent.teal.bolder': '#1D474C',
  'color.text.accent.blue': '#0055CC',
  'color.text.accent.blue.bolder': '#09326C',
  'color.text.accent.purple': '#5E4DB2',
  'color.text.accent.purple.bolder': '#352C63',
  'color.text.accent.magenta': '#943D73',
  'color.text.accent.magenta.bolder': '#50253F',
  'color.text.accent.gray': '#44546F',
  'color.text.accent.gray.bolder': '#091E42',
  'color.text.disabled': '#091E424F',
  'color.text.inverse': '#FFFFFF',
  'color.text.selected': '#0C66E4',
  'color.text.brand': '#0C66E4',
  'color.text.danger': '#AE2A19',
  'color.text.warning': '#974F0C',
  'color.text.warning.inverse': '#172B4D',
  'color.text.success': '#216E4E',
  'color.text.discovery': '#5E4DB2',
  'color.text.information': '#0055CC',
  'color.text.subtlest': '#626F86',
  'color.text.subtle': '#44546F',
  'color.link': '#0C66E4',
  'color.link.pressed': '#0055CC',
  'color.icon': '#44546F',
  'color.icon.accent.lime': '#6A9A23',
  'color.icon.accent.red': '#E34935',
  'color.icon.accent.orange': '#D97008',
  'color.icon.accent.yellow': '#B38600',
  'color.icon.accent.green': '#22A06B',
  'color.icon.accent.teal': '#1D9AAA',
  'color.icon.accent.blue': '#1D7AFC',
  'color.icon.accent.purple': '#8270DB',
  'color.icon.accent.magenta': '#CD519D',
  'color.icon.accent.gray': '#758195',
  'color.icon.disabled': '#091E424F',
  'color.icon.inverse': '#FFFFFF',
  'color.icon.selected': '#0C66E4',
  'color.icon.brand': '#0C66E4',
  'color.icon.danger': '#E34935',
  'color.icon.warning': '#D97008',
  'color.icon.warning.inverse': '#172B4D',
  'color.icon.success': '#22A06B',
  'color.icon.discovery': '#8270DB',
  'color.icon.information': '#1D7AFC',
  'color.icon.subtle': '#626F86',
  'color.border': '#091E4224',
  'color.border.accent.lime': '#6A9A23',
  'color.border.accent.red': '#E34935',
  'color.border.accent.orange': '#D97008',
  'color.border.accent.yellow': '#B38600',
  'color.border.accent.green': '#22A06B',
  'color.border.accent.teal': '#1D9AAA',
  'color.border.accent.blue': '#1D7AFC',
  'color.border.accent.purple': '#8270DB',
  'color.border.accent.magenta': '#CD519D',
  'color.border.accent.gray': '#758195',
  'color.border.disabled': '#091E420F',
  'color.border.focused': '#388BFF',
  'color.border.input': '#091E4224',
  'color.border.inverse': '#FFFFFF',
  'color.border.selected': '#0C66E4',
  'color.border.brand': '#0C66E4',
  'color.border.danger': '#E34935',
  'color.border.warning': '#D97008',
  'color.border.success': '#22A06B',
  'color.border.discovery': '#8270DB',
  'color.border.information': '#1D7AFC',
  'color.border.bold': '#758195',
  'color.background.accent.lime.subtlest': '#EEFBDA',
  'color.background.accent.lime.subtler': '#D3F1A7',
  'color.background.accent.lime.subtle': '#94C748',
  'color.background.accent.lime.bolder': '#5B7F24',
  'color.background.accent.red.subtlest': '#FFEDEB',
  'color.background.accent.red.subtler': '#FFD2CC',
  'color.background.accent.red.subtle': '#F87462',
  'color.background.accent.red.bolder': '#CA3521',
  'color.background.accent.orange.subtlest': '#FFF4E5',
  'color.background.accent.orange.subtler': '#FFE2BD',
  'color.background.accent.orange.subtle': '#FAA53D',
  'color.background.accent.orange.bolder': '#B65C02',
  'color.background.accent.yellow.subtlest': '#FFF7D6',
  'color.background.accent.yellow.subtler': '#F8E6A0',
  'color.background.accent.yellow.subtle': '#E2B203',
  'color.background.accent.yellow.bolder': '#946F00',
  'color.background.accent.green.subtlest': '#DFFCF0',
  'color.background.accent.green.subtler': '#BAF3DB',
  'color.background.accent.green.subtle': '#4BCE97',
  'color.background.accent.green.bolder': '#1F845A',
  'color.background.accent.teal.subtlest': '#E3FAFC',
  'color.background.accent.teal.subtler': '#C1F0F5',
  'color.background.accent.teal.subtle': '#60C6D2',
  'color.background.accent.teal.bolder': '#1D7F8C',
  'color.background.accent.blue.subtlest': '#E9F2FF',
  'color.background.accent.blue.subtler': '#CCE0FF',
  'color.background.accent.blue.subtle': '#579DFF',
  'color.background.accent.blue.bolder': '#0C66E4',
  'color.background.accent.purple.subtlest': '#F3F0FF',
  'color.background.accent.purple.subtler': '#DFD8FD',
  'color.background.accent.purple.subtle': '#9F8FEF',
  'color.background.accent.purple.bolder': '#6E5DC6',
  'color.background.accent.magenta.subtlest': '#FFECF8',
  'color.background.accent.magenta.subtler': '#FDD0EC',
  'color.background.accent.magenta.subtle': '#E774BB',
  'color.background.accent.magenta.bolder': '#AE4787',
  'color.background.accent.gray.subtlest': '#F1F2F4',
  'color.background.accent.gray.subtler': '#DCDFE4',
  'color.background.accent.gray.subtle': '#8590A2',
  'color.background.accent.gray.bolder': '#626F86',
  'color.background.disabled': '#091E4208',
  'color.background.input': '#FFFFFF',
  'color.background.input.hovered': '#F7F8F9',
  'color.background.input.pressed': '#FFFFFF',
  'color.background.inverse.subtle': '#00000029',
  'color.background.inverse.subtle.hovered': '#0000003D',
  'color.background.inverse.subtle.pressed': '#00000052',
  'color.background.neutral': '#091E420F',
  'color.background.neutral.hovered': '#091E4224',
  'color.background.neutral.pressed': '#091E424F',
  'color.background.neutral.subtle': '#00000000',
  'color.background.neutral.subtle.hovered': '#091E420F',
  'color.background.neutral.subtle.pressed': '#091E4224',
  'color.background.neutral.bold': '#44546F',
  'color.background.neutral.bold.hovered': '#2C3E5D',
  'color.background.neutral.bold.pressed': '#172B4D',
  'color.background.selected': '#E9F2FF',
  'color.background.selected.hovered': '#CCE0FF',
  'color.background.selected.pressed': '#85B8FF',
  'color.background.selected.bold': '#0C66E4',
  'color.background.selected.bold.hovered': '#0055CC',
  'color.background.selected.bold.pressed': '#09326C',
  'color.background.brand.subtlest': '#E9F2FF',
  'color.background.brand.subtlest.hovered': '#CCE0FF',
  'color.background.brand.subtlest.pressed': '#85B8FF',
  'color.background.brand.bold': '#0C66E4',
  'color.background.brand.bold.hovered': '#0055CC',
  'color.background.brand.bold.pressed': '#09326C',
  'color.background.brand.boldest': '#092957',
  'color.background.brand.boldest.hovered': '#09326C',
  'color.background.brand.boldest.pressed': '#0055CC',
  'color.background.danger': '#FFEDEB',
  'color.background.danger.hovered': '#FFD2CC',
  'color.background.danger.pressed': '#FF9C8F',
  'color.background.danger.bold': '#CA3521',
  'color.background.danger.bold.hovered': '#AE2A19',
  'color.background.danger.bold.pressed': '#601E16',
  'color.background.warning': '#FFF7D6',
  'color.background.warning.hovered': '#F8E6A0',
  'color.background.warning.pressed': '#F5CD47',
  'color.background.warning.bold': '#E2B203',
  'color.background.warning.bold.hovered': '#CF9F02',
  'color.background.warning.bold.pressed': '#B38600',
  'color.background.success': '#DFFCF0',
  'color.background.success.hovered': '#BAF3DB',
  'color.background.success.pressed': '#7EE2B8',
  'color.background.success.bold': '#1F845A',
  'color.background.success.bold.hovered': '#216E4E',
  'color.background.success.bold.pressed': '#164B35',
  'color.background.discovery': '#F3F0FF',
  'color.background.discovery.hovered': '#DFD8FD',
  'color.background.discovery.pressed': '#B8ACF6',
  'color.background.discovery.bold': '#6E5DC6',
  'color.background.discovery.bold.hovered': '#5E4DB2',
  'color.background.discovery.bold.pressed': '#352C63',
  'color.background.information': '#E9F2FF',
  'color.background.information.hovered': '#CCE0FF',
  'color.background.information.pressed': '#85B8FF',
  'color.background.information.bold': '#0C66E4',
  'color.background.information.bold.hovered': '#0055CC',
  'color.background.information.bold.pressed': '#09326C',
  'color.blanket': '#091E427D',
  'color.blanket.selected': '#388BFF14',
  'color.blanket.danger': '#EF5C4814',
  'color.interaction.hovered': '#00000029',
  'color.interaction.pressed': '#00000052',
  'color.skeleton': '#091E420F',
  'color.skeleton.subtle': '#091E4208',
  'color.chart.categorical.1': '#1D9AAA',
  'color.chart.categorical.1.hovered': '#1D7F8C',
  'color.chart.categorical.2': '#5E4DB2',
  'color.chart.categorical.2.hovered': '#352C63',
  'color.chart.categorical.3': '#D97008',
  'color.chart.categorical.3.hovered': '#B65C02',
  'color.chart.categorical.4': '#943D73',
  'color.chart.categorical.4.hovered': '#50253F',
  'color.chart.categorical.5': '#09326C',
  'color.chart.categorical.5.hovered': '#092957',
  'color.chart.categorical.6': '#8F7EE7',
  'color.chart.categorical.6.hovered': '#8270DB',
  'color.chart.categorical.7': '#50253F',
  'color.chart.categorical.7.hovered': '#421F34',
  'color.chart.categorical.8': '#974F0C',
  'color.chart.categorical.8.hovered': '#5F3811',
  'color.chart.lime.bold': '#6A9A23',
  'color.chart.lime.bold.hovered': '#5B7F24',
  'color.chart.lime.bolder': '#5B7F24',
  'color.chart.lime.bolder.hovered': '#4C6B1F',
  'color.chart.lime.boldest': '#4C6B1F',
  'color.chart.lime.boldest.hovered': '#37471F',
  'color.chart.neutral': '#8590A2',
  'color.chart.neutral.hovered': '#758195',
  'color.chart.red.bold': '#EF5C48',
  'color.chart.red.bold.hovered': '#E34935',
  'color.chart.red.bolder': '#E34935',
  'color.chart.red.bolder.hovered': '#CA3521',
  'color.chart.red.boldest': '#AE2A19',
  'color.chart.red.boldest.hovered': '#601E16',
  'color.chart.orange.bold': '#D97008',
  'color.chart.orange.bold.hovered': '#B65C02',
  'color.chart.orange.bolder': '#B65C02',
  'color.chart.orange.bolder.hovered': '#974F0C',
  'color.chart.orange.boldest': '#974F0C',
  'color.chart.orange.boldest.hovered': '#5F3811',
  'color.chart.yellow.bold': '#B38600',
  'color.chart.yellow.bold.hovered': '#946F00',
  'color.chart.yellow.bolder': '#946F00',
  'color.chart.yellow.bolder.hovered': '#7F5F01',
  'color.chart.yellow.boldest': '#7F5F01',
  'color.chart.yellow.boldest.hovered': '#533F04',
  'color.chart.green.bold': '#22A06B',
  'color.chart.green.bold.hovered': '#1F845A',
  'color.chart.green.bolder': '#1F845A',
  'color.chart.green.bolder.hovered': '#216E4E',
  'color.chart.green.boldest': '#216E4E',
  'color.chart.green.boldest.hovered': '#164B35',
  'color.chart.teal.bold': '#1D9AAA',
  'color.chart.teal.bold.hovered': '#1D7F8C',
  'color.chart.teal.bolder': '#1D7F8C',
  'color.chart.teal.bolder.hovered': '#206B74',
  'color.chart.teal.boldest': '#206B74',
  'color.chart.teal.boldest.hovered': '#1D474C',
  'color.chart.blue.bold': '#388BFF',
  'color.chart.blue.bold.hovered': '#1D7AFC',
  'color.chart.blue.bolder': '#1D7AFC',
  'color.chart.blue.bolder.hovered': '#0C66E4',
  'color.chart.blue.boldest': '#0055CC',
  'color.chart.blue.boldest.hovered': '#09326C',
  'color.chart.purple.bold': '#8F7EE7',
  'color.chart.purple.bold.hovered': '#8270DB',
  'color.chart.purple.bolder': '#8270DB',
  'color.chart.purple.bolder.hovered': '#6E5DC6',
  'color.chart.purple.boldest': '#5E4DB2',
  'color.chart.purple.boldest.hovered': '#352C63',
  'color.chart.magenta.bold': '#DA62AC',
  'color.chart.magenta.bold.hovered': '#CD519D',
  'color.chart.magenta.bolder': '#CD519D',
  'color.chart.magenta.bolder.hovered': '#AE4787',
  'color.chart.magenta.boldest': '#943D73',
  'color.chart.magenta.boldest.hovered': '#50253F',
  'color.chart.gray.bold': '#8590A2',
  'color.chart.gray.bold.hovered': '#758195',
  'color.chart.gray.bolder': '#758195',
  'color.chart.gray.bolder.hovered': '#626F86',
  'color.chart.gray.boldest': '#44546F',
  'color.chart.gray.boldest.hovered': '#2C3E5D',
  'color.chart.brand': '#1D7AFC',
  'color.chart.brand.hovered': '#0C66E4',
  'color.chart.danger': '#EF5C48',
  'color.chart.danger.hovered': '#E34935',
  'color.chart.danger.bold': '#AE2A19',
  'color.chart.danger.bold.hovered': '#601E16',
  'color.chart.warning': '#B38600',
  'color.chart.warning.hovered': '#946F00',
  'color.chart.warning.bold': '#7F5F01',
  'color.chart.warning.bold.hovered': '#533F04',
  'color.chart.success': '#22A06B',
  'color.chart.success.hovered': '#1F845A',
  'color.chart.success.bold': '#216E4E',
  'color.chart.success.bold.hovered': '#164B35',
  'color.chart.discovery': '#8F7EE7',
  'color.chart.discovery.hovered': '#8270DB',
  'color.chart.discovery.bold': '#5E4DB2',
  'color.chart.discovery.bold.hovered': '#352C63',
  'color.chart.information': '#388BFF',
  'color.chart.information.hovered': '#1D7AFC',
  'color.chart.information.bold': '#0055CC',
  'color.chart.information.bold.hovered': '#09326C',
  'elevation.surface': '#FFFFFF',
  'elevation.surface.hovered': '#F1F2F4',
  'elevation.surface.pressed': '#DCDFE4',
  'elevation.surface.overlay': '#FFFFFF',
  'elevation.surface.overlay.hovered': '#F1F2F4',
  'elevation.surface.overlay.pressed': '#DCDFE4',
  'elevation.surface.raised': '#FFFFFF',
  'elevation.surface.raised.hovered': '#F1F2F4',
  'elevation.surface.raised.pressed': '#DCDFE4',
  'elevation.surface.sunken': '#F7F8F9',
  'elevation.shadow.overflow': '0px 0px 8px #091E4229, 0px 0px 1px #091E421F',
  'elevation.shadow.overflow.perimeter': '#091e421f',
  'elevation.shadow.overflow.spread': '#091e4229',
  'elevation.shadow.overlay': '0px 8px 12px #091E4226, 0px 0px 1px #091E424F',
  'elevation.shadow.raised': '0px 1px 1px #091E4240, 0px 0px 1px #091E424F',
  'opacity.disabled': '0.4',
  'opacity.loading': '0.2',
  'utility.UNSAFE.transparent': 'transparent',
  'utility.elevation.surface.current': '#FFFFFF',
  'border.radius.050': '0.125rem',
  'border.radius': '0.25rem',
  'border.radius.100': '0.25rem',
  'border.radius.200': '0.5rem',
  'border.radius.300': '0.75rem',
  'border.radius.400': '1rem',
  'border.radius.circle': '2002rem',
  'border.width': '0.0625rem',
  'border.width.0': '0rem',
  'border.width.indicator': '0.1875rem',
  'border.width.outline': '0.125rem',
  'space.0': '0rem',
  'space.025': '0.125rem',
  'space.050': '0.25rem',
  'space.075': '0.375rem',
  'space.100': '0.5rem',
  'space.150': '0.75rem',
  'space.200': '1rem',
  'space.250': '1.25rem',
  'space.300': '1.5rem',
  'space.400': '2rem',
  'space.500': '2.5rem',
  'space.600': '3rem',
  'space.800': '4rem',
  'space.1000': '5rem',
  'font.body':
    'normal 400 0.875rem/1.25rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.body.lg':
    'normal 400 1rem/1.5rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.body.sm':
    'normal 400 0.6875rem/1.25rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.code':
    'normal 400 0.875em/1 ui-monospace, Menlo, "Segoe UI Mono", "Ubuntu Mono", monospace',
  'font.heading.lg':
    'normal 500 1.5rem/1.75rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.heading.md':
    'normal 500 1.25rem/1.5rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.heading.sm':
    'normal 600 1rem/1.25rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.heading.xl':
    'normal 600 1.8125rem/2rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.heading.xs':
    'normal 600 0.875rem/1rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.heading.xxl':
    'normal 500 2.1875rem/2.5rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.heading.xxs':
    'normal 600 0.75rem/1rem ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.letterSpacing.0': '0',
  'font.letterSpacing.100': '-0.003em',
  'font.letterSpacing.200': '-0.006em',
  'font.letterSpacing.300': '-0.008em',
  'font.letterSpacing.400': '-0.01em',
  'font.ui':
    'normal 400 0.875rem/1 ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.ui.sm':
    'normal 400 0.6875rem/1 ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.family.code':
    'ui-monospace, Menlo, "Segoe UI Mono", "Ubuntu Mono", monospace',
  'font.family.monospace':
    'ui-monospace, Menlo, "Segoe UI Mono", "Ubuntu Mono", monospace',
  'font.family.product':
    'ui-sans-serif, "Segoe UI", system-ui, Ubuntu, "Helvetica Neue", sans-serif',
  'font.family.sans':
    '-apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
  'font.family.brand': 'Charlie Sans',
  'font.size.050': '0.6875rem',
  'font.size.075': '0.75rem',
  'font.size.100': '0.875rem',
  'font.size.200': '1rem',
  'font.size.300': '1.25rem',
  'font.size.400': '1.5rem',
  'font.size.500': '1.8125rem',
  'font.size.600': '2.1875rem',
  'font.weight.bold': '700',
  'font.weight.medium': '500',
  'font.weight.regular': '400',
  'font.weight.semibold': '600',
  'font.lineHeight.1': '1',
  'font.lineHeight.100': '1rem',
  'font.lineHeight.200': '1.25rem',
  'font.lineHeight.300': '1.5rem',
  'font.lineHeight.400': '1.75rem',
  'font.lineHeight.500': '2rem',
  'font.lineHeight.600': '2.5rem',
} as const;

export default defaultTokenValues;
