// THIS IS AN AUTO-GENERATED FILE DO NOT MODIFY DIRECTLY
// Re-generate by running `yarn build tokens`.

/**
 * A map of token names to their value in the default Atlassian theme ('light')
 */
const defaultTokenValues = {
  'color.accent.boldBlue': '#579DFF',
  'color.accent.boldGreen': '#4BCE97',
  'color.accent.boldOrange': '#FAA53D',
  'color.accent.boldPurple': '#9F8FEF',
  'color.accent.boldRed': '#F87462',
  'color.accent.boldTeal': '#60C6D2',
  'color.accent.subtleBlue': '#CCE0FF',
  'color.accent.subtleGreen': '#BAF3DB',
  'color.accent.subtleMagenta': '#FDD0EC',
  'color.accent.subtleOrange': '#FFE2BD',
  'color.accent.subtlePurple': '#DFD8FD',
  'color.accent.subtleRed': '#FFD2CC',
  'color.accent.subtleTeal': '#C1F0F5',
  'color.background.sunken': '#091E4208',
  'color.background.default': '#FFFFFF',
  'color.background.card': '#FFFFFF',
  'color.background.overlay': '#FFFFFF',
  'color.background.selected.resting': '#E9F2FF',
  'color.background.selected.hover': '#CCE0FF',
  'color.background.selected.pressed': '#85B8FF',
  'color.background.blanket': '#091E427A',
  'color.background.disabled': '#091E420F',
  'color.background.boldBrand.resting': '#0C66E4',
  'color.background.boldBrand.hover': '#0055CC',
  'color.background.boldBrand.pressed': '#09326C',
  'color.background.subtleBrand.resting': '#E9F2FF',
  'color.background.subtleBrand.hover': '#CCE0FF',
  'color.background.subtleBrand.pressed': '#85B8FF',
  'color.background.boldDanger.resting': '#CA3521',
  'color.background.boldDanger.hover': '#AE2A19',
  'color.background.boldDanger.pressed': '#601E16',
  'color.background.subtleDanger.resting': '#FFEDEB',
  'color.background.subtleDanger.hover': '#FFD2CC',
  'color.background.subtleDanger.pressed': '#FF9C8F',
  'color.background.boldWarning.resting': '#E2B203',
  'color.background.boldWarning.hover': '#CF9F02',
  'color.background.boldWarning.pressed': '#B38600',
  'color.background.subtleWarning.resting': '#FFF7D6',
  'color.background.subtleWarning.hover': '#F8E6A0',
  'color.background.subtleWarning.pressed': '#F5CD47',
  'color.background.boldSuccess.resting': '#1F845A',
  'color.background.boldSuccess.hover': '#216E4E',
  'color.background.boldSuccess.pressed': '#164B35',
  'color.background.subtleSuccess.resting': '#DFFCF0',
  'color.background.subtleSuccess.hover': '#BAF3DB',
  'color.background.subtleSuccess.pressed': '#7EE2B8',
  'color.background.boldDiscovery.resting': '#6E5DC6',
  'color.background.boldDiscovery.hover': '#5E4DB2',
  'color.background.boldDiscovery.pressed': '#352C63',
  'color.background.subtleDiscovery.resting': '#F3F0FF',
  'color.background.subtleDiscovery.hover': '#DFD8FD',
  'color.background.subtleDiscovery.pressed': '#B8ACF6',
  'color.background.boldNeutral.resting': '#44546F',
  'color.background.boldNeutral.hover': '#2C3E5D',
  'color.background.boldNeutral.pressed': '#172B4D',
  'color.background.transparentNeutral.hover': '#091E420F',
  'color.background.transparentNeutral.pressed': '#091E4224',
  'color.background.subtleNeutral.resting': '#091E420F',
  'color.background.subtleNeutral.hover': '#091E4224',
  'color.background.subtleNeutral.pressed': '#091E424F',
  'color.background.subtleBorderedNeutral.resting': '#091E4208',
  'color.background.subtleBorderedNeutral.pressed': '#091E420F',
  'color.border.focus': '#388BFF',
  'color.border.neutral': '#091E4224',
  'color.iconBorder.brand': '#1D7AFC',
  'color.iconBorder.danger': '#E34935',
  'color.iconBorder.warning': '#D97008',
  'color.iconBorder.success': '#22A06B',
  'color.iconBorder.discovery': '#8270DB',
  'color.overlay.hover': '#091E424F',
  'color.overlay.pressed': '#091E427A',
  'color.text.selected': '#0C66E4',
  'color.text.highEmphasis': '#172B4D',
  'color.text.mediumEmphasis': '#44546F',
  'color.text.lowEmphasis': '#626F86',
  'color.text.onBold': '#FFFFFF',
  'color.text.onBoldWarning': '#172B4D',
  'color.text.link.resting': '#0C66E4',
  'color.text.link.pressed': '#0055CC',
  'color.text.brand': '#0055CC',
  'color.text.warning': '#974F0C',
  'color.text.danger': '#AE2A19',
  'color.text.success': '#216E4E',
  'color.text.discovery': '#5E4DB2',
  'color.text.disabled': '#8993A5',
  'shadow.card': '0px 1px 1px #091E4240, 0px 0px 1px #091E424F',
  'shadow.overlay': '0px 8px 12px #091E4226, 0px 0px 1px #091E424F',
  'utility.UNSAFE_util.transparent': 'transparent',
  'utility.UNSAFE_util.MISSING_TOKEN': '#FA11F2',
} as const;

export default defaultTokenValues;
