export const mainResponse = {
  macros: [
    {
      aliases: [],
      buttons: [],
      hidden: false,
      anyParameterRequired: true,
      icon: null,
      description: "Displays a user's profile details.",
      pluginKey: 'confluence.macros.profile',
      autoconvertData: null,
      title: 'User Profile',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'profile',
      gadgetUrl: null,
      categories: ['confluence-content'],
      defaultLayout: null,
      alwaysShowConfig: false,
    },
    {
      aliases: [],
      buttons: [],
      hidden: false,
      anyParameterRequired: false,
      icon: {
        width: 80,
        location:
          '/download/resources/com.atlassian.confluence.plugins.confluence-inline-tasks/tasks-report-image-resources/task-report.png',
        height: 80,
        relative: true,
      },
      description:
        'Create a report of tasks from specific locations, people, status and more.',
      pluginKey: 'com.atlassian.confluence.plugins.confluence-inline-tasks',
      autoconvertData: null,
      title: 'Task report',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'tasks-report-macro',
      gadgetUrl: null,
      categories: ['confluence-content'],
      defaultLayout: null,
      alwaysShowConfig: false,
    },
    {
      aliases: [],
      buttons: [],
      hidden: true,
      anyParameterRequired: true,
      icon: null,
      description: 'View file macro',
      pluginKey: 'com.atlassian.confluence.plugins.confluence-view-file-macro',
      autoconvertData: null,
      title:
        'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.label',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'view-file',
      gadgetUrl: null,
      categories: [],
      defaultLayout: null,
      alwaysShowConfig: false,
    },
    {
      aliases: [],
      buttons: [],
      hidden: false,
      anyParameterRequired: true,
      icon: {
        width: 80,
        location:
          '/download/resources/confluence.extra.jira/images/jira-chart-macro-icon.png',
        height: 80,
        relative: true,
      },
      description: 'Display JIRA information on your page as a chart.',
      pluginKey: 'confluence.extra.jira',
      autoconvertData: null,
      title: 'JIRA Charts',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'jirachart',
      gadgetUrl: null,
      categories: ['development'],
      defaultLayout: null,
      alwaysShowConfig: false,
    },
  ],
  insertTitle: 'Insert \u2018{0}\u2019 Macro',
  editTitle: 'Edit \u2018{0}\u2019 Macro',
  categories: [
    { displayName: 'Formatting', name: 'formatting' },
    { displayName: 'Confluence content', name: 'confluence-content' },
    { displayName: 'Media', name: 'media' },
    { displayName: 'Visuals & images', name: 'visuals' },
    { displayName: 'Navigation', name: 'navigation' },
    { displayName: 'External content', name: 'external-content' },
    { displayName: 'Communication', name: 'communication' },
    { displayName: 'Reporting', name: 'reporting' },
    { displayName: 'Administration', name: 'admin' },
    { displayName: 'Development', name: 'development' },
    { displayName: 'Hidden', name: 'hidden-macros' },
  ],
  title: 'Select macro',
};

export const details = {
  profile: {
    details: {
      aliases: [],
      buttons: [],
      hidden: false,
      icon: null,
      description: "Displays a user's profile details.",
      pluginKey: 'confluence.macros.profile',
      autoconvertData: null,
      title: 'User Profile',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'profile',
      categories: ['confluence-content'],
      defaultLayout: null,
      formDetails: {
        macroName: 'profile',
        documentationUrl:
          'https://confluence.atlassian.com/display/ConfCloud/User+Profile+Macro',
        schemaVersion: 1,
        freeform: false,
        notationHelp: null,
        excludedSchemaMigrationPoints: [],
        showDefaultParamInPlaceholder: true,
        documentationLink:
          'https://confluence.atlassian.com/display/ConfCloud/User+Profile+Macro',
        body: {
          bodyType: 'NONE',
          hidden: false,
          description: 'confluence.macros.profile.profile.body.desc',
          outputType: 'BLOCK',
          label: 'confluence.macros.profile.profile.body.label',
        },
        parameters: [
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName: 'User',
            multiple: false,
            description: 'confluence.macros.profile.profile.param.user.desc',
            pluginKey: 'confluence.macros.profile',
            type: { name: 'username' },
            required: true,
            macroName: 'profile',
            name: 'user',
            options: {},
            enumValues: null,
          },
        ],
      },
    },
  },
  'view-file': {
    details: {
      aliases: [],
      buttons: [],
      hidden: true,
      icon: null,
      description: 'View file macro',
      pluginKey: 'com.atlassian.confluence.plugins.confluence-view-file-macro',
      autoconvertData: null,
      title:
        'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.label',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'view-file',
      categories: [],
      defaultLayout: null,
      formDetails: {
        macroName: 'view-file',
        documentationUrl:
          'https://confluence.atlassian.com/display/ConfCloud/Excerpt+Macro',
        schemaVersion: 1,
        freeform: false,
        notationHelp: null,
        excludedSchemaMigrationPoints: [],
        showDefaultParamInPlaceholder: true,
        documentationLink:
          'https://confluence.atlassian.com/display/ConfCloud/Excerpt+Macro',
        body: {
          bodyType: 'NONE',
          hidden: false,
          description:
            'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.body.desc',
          outputType: 'INLINE',
          label:
            'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.body.label',
        },
        parameters: [
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.page.label',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.page.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-view-file-macro',
            type: { name: 'confluence-content' },
            required: false,
            macroName: 'view-file',
            name: 'page',
            options: { includeDatePath: 'true', derived: 'name' },
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.space.label',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.space.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-view-file-macro',
            type: { name: 'spacekey' },
            required: false,
            macroName: 'view-file',
            name: 'space',
            options: { derived: 'name' },
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.date.label',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.date.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-view-file-macro',
            type: { name: 'date' },
            required: false,
            macroName: 'view-file',
            name: 'date',
            options: { derived: 'name' },
            enumValues: null,
          },
          {
            aliases: [''],
            hidden: false,
            defaultValue: null,
            displayName:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.name.label',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-view-file-macro.view-file.param.name.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-view-file-macro',
            type: { name: 'full_attachment' },
            required: true,
            macroName: 'view-file',
            name: 'name',
            options: {},
            enumValues: null,
          },
        ],
      },
    },
  },
  jirachart: {
    details: {
      aliases: [],
      buttons: [],
      hidden: false,
      icon: {
        width: 80,
        location:
          '/download/resources/confluence.extra.jira/images/jira-chart-macro-icon.png',
        height: 80,
        relative: true,
      },
      description: 'Display JIRA information on your page as a chart.',
      pluginKey: 'confluence.extra.jira',
      autoconvertData: null,
      title: 'JIRA Charts',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'jirachart',
      categories: ['development'],
      defaultLayout: null,
      formDetails: {
        macroName: 'jirachart',
        documentationUrl: 'https://confluence.atlassian.com/display/ConfCloud/',
        schemaVersion: 1,
        freeform: false,
        notationHelp: null,
        excludedSchemaMigrationPoints: [],
        showDefaultParamInPlaceholder: true,
        documentationLink:
          'https://confluence.atlassian.com/display/ConfCloud/',
        body: {
          bodyType: 'NONE',
          hidden: false,
          description: 'confluence.extra.jira.jirachart.body.desc',
          outputType: 'BLOCK',
          label: 'confluence.extra.jira.jirachart.body.label',
        },
        parameters: [
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName: 'confluence.extra.jira.jirachart.param.server.label',
            multiple: false,
            description: 'confluence.extra.jira.jirachart.param.server.desc',
            pluginKey: 'confluence.extra.jira',
            type: { name: 'string' },
            required: true,
            macroName: 'jirachart',
            name: 'server',
            options: {
              showValueInPlaceholder: 'false',
              showKeyInPlaceholder: 'false',
            },
            enumValues: null,
          },
        ],
      },
    },
  },
  'tasks-report-macro': {
    details: {
      aliases: [],
      buttons: [],
      hidden: false,
      icon: {
        width: 80,
        location:
          '/download/resources/com.atlassian.confluence.plugins.confluence-inline-tasks/tasks-report-image-resources/task-report.png',
        height: 80,
        relative: true,
      },
      description:
        'Create a report of tasks from specific locations, people, status and more.',
      pluginKey: 'com.atlassian.confluence.plugins.confluence-inline-tasks',
      autoconvertData: null,
      title: 'Task report',
      bodyDeprecated: false,
      alternateId: null,
      macroName: 'tasks-report-macro',
      categories: ['confluence-content'],
      defaultLayout: null,
      formDetails: {
        macroName: 'tasks-report-macro',
        documentationUrl: null,
        schemaVersion: 1,
        freeform: false,
        notationHelp: null,
        excludedSchemaMigrationPoints: [],
        showDefaultParamInPlaceholder: true,
        documentationLink: null,
        body: {
          bodyType: 'NONE',
          hidden: false,
          description:
            'com.atlassian.confluence.plugins.confluence-inline-tasks.tasks-report-macro.body.desc',
          outputType: 'BLOCK',
          label:
            'com.atlassian.confluence.plugins.confluence-inline-tasks.tasks-report-macro.body.label',
        },
        parameters: [
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName: 'Space(s) and page(s)',
            multiple: true,
            description: 'Only show tasks from these spaces or pages',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'string' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'spaceAndPage',
            options: {},
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName: 'Label(s)',
            multiple: true,
            description: 'Only show tasks on pages with this label',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'label' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'labels',
            options: {},
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName: 'Assigned to',
            multiple: true,
            description: 'Only show tasks assigned to these people',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'username' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'assignees',
            options: {},
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName: 'Created by',
            multiple: true,
            description: 'Only show tasks created by these people',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'username' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'creators',
            options: {},
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: null,
            displayName: 'Created after',
            multiple: false,
            description:
              'Only show tasks created on or after this date. Dates must be entered as dd-mm-yyyy.',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'date' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'createddateFrom',
            options: {},
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: 'incomplete',
            displayName: 'Task status',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-inline-tasks.tasks-report-macro.param.status.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'enum' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'status',
            options: {},
            enumValues: ['complete', 'incomplete'],
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: '20',
            displayName: 'Number of tasks per page',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-inline-tasks.tasks-report-macro.param.pageSize.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'enum' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'pageSize',
            options: {},
            enumValues: ['10', '20', '40'],
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: 'description,duedate,assignee,location',
            displayName: 'Columns to display',
            multiple: false,
            description:
              'Allowed columns are description, duedate, assignee, location, completedate, labels',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'string' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'columns',
            options: {},
            enumValues: null,
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: 'due date',
            displayName: 'Sort by',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-inline-tasks.tasks-report-macro.param.sortBy.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'enum' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'sortBy',
            options: {},
            enumValues: ['due date', 'assignee', 'page title'],
          },
          {
            aliases: [],
            hidden: false,
            defaultValue: 'false',
            displayName: 'Reverse sort',
            multiple: false,
            description:
              'com.atlassian.confluence.plugins.confluence-inline-tasks.tasks-report-macro.param.reverseSort.desc',
            pluginKey:
              'com.atlassian.confluence.plugins.confluence-inline-tasks',
            type: { name: 'boolean' },
            required: false,
            macroName: 'tasks-report-macro',
            name: 'reverseSort',
            options: {},
            enumValues: null,
          },
        ],
      },
    },
  },
};
