export const selectOptions = [
	{ label: 'Brand', value: 'brand' },
	{ label: 'Legacy', value: 'legacy' },
] as const;

export const appOrder = [
	'Jira',
	'Confluence',
	'Loom',
	'Loom Internal',
	'Rovo',
	'Focus',
	'Align',
	'Talent',
	'Bitbucket',
	'Compass',
	'Statuspage',
	'Jira Service Management',
	'Assets',
	'Opsgenie',
	'Jira Product Discovery',
	'Jira Customer Service',
	'Trello',
	'Guard',
	'Guard Detect',
	'Home',
	'Company Hub',
	'Projects',
	'Goals',
	'Teams',
	'Chat',
	'Search',
	'Studio',
	'Analytics',
	'Admin',
	'More Atlassian rows',
	'Custom Link',
];
