export const selectOptions = [
	{ label: 'Brand', value: 'brand' },
	{ label: 'Legacy', value: 'legacy' },
] as const;

export const appOrder = [
	'More Atlassian Apps',
	'Jira',
	'Confluence',
	'Loom',
	'Loom Internal',
	'Rovo',
	'Focus',
	'Align',
	'Talent',
	'Bitbucket',
	'Compass',
	'Statuspage',
	'Jira Service Management',
	'Assets',
	'Opsgenie',
	'Customer Service Management',
	'Jira Product Discovery',
	'Trello',
	'Guard',
	'Guard Detect',
	'Home',
	'Company Hub',
	'Projects',
	'Goals',
	'Teams',
	'Chat',
	'Search',
	'Studio',
	'Analytics',
	'Admin',
	'Custom Link',
];
