export const selectOptions = [
	{ label: 'Brand', value: 'brand' },
	{ label: 'Neutral', value: 'neutral' },
	{ label: 'Inverse', value: 'inverse' },
	{ label: 'Legacy', value: 'legacy' },
] as const;

export const appOrder = [
	'More Atlassian Apps',
	'Jira',
	'Confluence',
	'Loom',
	'Loom Internal',
	'Rovo',
	'Focus',
	'Align',
	'Talent',
	'Bitbucket',
	'Compass',
	'Statuspage',
	'Jira Service Management',
	'Assets',
	'Opsgenie',
	'Customer Service Management',
	'Jira Product Discovery',
	'Trello',
	'Guard',
	'Guard Detect',
	'Home',
	'Company Hub',
	'Projects',
	'Goals',
	'Teams',
	'Chat',
	'Search',
	'Studio',
	'Analytics',
	'Admin',
	'Jira Data Center',
	'Confluence Data Center',
	'Bitbucket Data Center',
	'Bamboo',
	'Crowd',
	'Custom Link',
];
