import { CURRENT_SURFACE_CSS_VAR } from '@atlaskit/tokens';

const namedColors = new Set([
  'black',
  'silver',
  'gray',
  'white',
  'maroon',
  'red',
  'purple',
  'fuchsia',
  'green',
  'lime',
  'olive',
  'yellow',
  'navy',
  'blue',
  'teal',
  'aqua',
  'orange',
  'aliceblue',
  'antiquewhite',
  'aquamarine',
  'azure',
  'beige',
  'bisque',
  'blanchedalmond',
  'blueviolet',
  'brown',
  'burlywood',
  'cadetblue',
  'chartreuse',
  'chocolate',
  'coral',
  'cornflowerblue',
  'cornsilk',
  'crimson',
  'cyan',
  'darkblue',
  'darkcyan',
  'darkgoldenrod',
  'darkgray',
  'darkgreen',
  'darkgrey',
  'darkkhaki',
  'darkmagenta',
  'darkolivegreen',
  'darkorange',
  'darkorchid',
  'darkred',
  'darksalmon',
  'darkseagreen',
  'darkslateblue',
  'darkslategray',
  'darkslategrey',
  'darkturquoise',
  'darkviolet',
  'deeppink',
  'deepskyblue',
  'dimgray',
  'dimgrey',
  'dodgerblue',
  'firebrick',
  'floralwhite',
  'forestgreen',
  'gainsboro',
  'ghostwhite',
  'gold',
  'goldenrod',
  'greenyellow',
  'grey',
  'honeydew',
  'hotpink',
  'indianred',
  'indigo',
  'ivory',
  'khaki',
  'lavender',
  'lavenderblush',
  'lawngreen',
  'lemonchiffon',
  'lightblue',
  'lightcoral',
  'lightcyan',
  'lightgoldenrodyellow',
  'lightgray',
  'lightgreen',
  'lightgrey',
  'lightpink',
  'lightsalmon',
  'lightseagreen',
  'lightskyblue',
  'lightslategray',
  'lightslategrey',
  'lightsteelblue',
  'lightyellow',
  'limegreen',
  'linen',
  'magenta',
  'mediumaquamarine',
  'mediumblue',
  'mediumorchid',
  'mediumpurple',
  'mediumseagreen',
  'mediumslateblue',
  'mediumspringgreen',
  'mediumturquoise',
  'mediumvioletred',
  'midnightblue',
  'mintcream',
  'mistyrose',
  'moccasin',
  'navajowhite',
  'oldlace',
  'olivedrab',
  'orangered',
  'orchid',
  'palegoldenrod',
  'palegreen',
  'paleturquoise',
  'palevioletred',
  'papayawhip',
  'peachpuff',
  'peru',
  'pink',
  'plum',
  'powderblue',
  'rosybrown',
  'royalblue',
  'saddlebrown',
  'salmon',
  'sandybrown',
  'seagreen',
  'seashell',
  'sienna',
  'skyblue',
  'slateblue',
  'slategray',
  'slategrey',
  'snow',
  'springgreen',
  'steelblue',
  'tan',
  'thistle',
  'tomato',
  'turquoise',
  'violet',
  'wheat',
  'whitesmoke',
  'yellowgreen',
  'rebeccapurple',
]);

const legacyColors = new Set([
  'R50',
  'R75',
  'R100',
  'R200',
  'R300',
  'R400',
  'R500',
  'Y50',
  'Y75',
  'Y100',
  'Y200',
  'Y300',
  'Y400',
  'Y500',
  'G50',
  'G75',
  'G100',
  'G200',
  'G300',
  'G400',
  'G500',
  'B50',
  'B75',
  'B100',
  'B200',
  'B300',
  'B400',
  'B500',
  'P50',
  'P75',
  'P100',
  'P200',
  'P300',
  'P400',
  'P500',
  'T50',
  'T75',
  'T100',
  'T200',
  'T300',
  'T400',
  'T500',
  'N0',
  'N10',
  'N20',
  'N30',
  'N40',
  'N50',
  'N60',
  'N70',
  'N80',
  'N90',
  'N100',
  'N200',
  'N300',
  'N400',
  'N500',
  'N600',
  'N700',
  'N800',
  'N900',
  'N10A',
  'N20A',
  'N30A',
  'N40A',
  'N50A',
  'N60A',
  'N70A',
  'N80A',
  'N90A',
  'N100A',
  'N200A',
  'N300A',
  'N400A',
  'N500A',
  'N600A',
  'N700A',
  'N800A',
  'DN900',
  'DN800',
  'DN700',
  'DN600',
  'DN500',
  'DN400',
  'DN300',
  'DN200',
  'DN100',
  'DN90',
  'DN80',
  'DN70',
  'DN60',
  'DN50',
  'DN40',
  'DN30',
  'DN20',
  'DN10',
  'DN0',
  'DN800A',
  'DN700A',
  'DN600A',
  'DN500A',
  'DN400A',
  'DN300A',
  'DN200A',
  'DN100A',
  'DN90A',
  'DN80A',
  'DN70A',
  'DN60A',
  'DN50A',
  'DN40A',
  'DN30A',
  'DN20A',
  'DN10A',
  // Legacy Trello colors:
  'AtlassianBlue50',
  'AtlassianBlue200',
  'AtlassianBlue300',
  'AtlassianBlue400',
  'TrelloBlue25',
  'TrelloBlue50',
  'TrelloBlue100',
  'TrelloBlue200',
  'TrelloBlue300',
  'TrelloBlue400',
  'TrelloBlue500',
  'TrelloBlue600',
  'TrelloBlue700',
  'TrelloBlue800',
  'TrelloBlue900',
  'Green50',
  'Green100',
  'Green200',
  'Green300',
  'Green400',
  'Green500',
  'Green600',
  'Green700',
  'Green800',
  'Green900',
  'Orange50',
  'Orange100',
  'Orange200',
  'Orange300',
  'Orange400',
  'Orange500',
  'Orange600',
  'Orange700',
  'Orange800',
  'Orange900',
  'Red50',
  'Red100',
  'Red200',
  'Red300',
  'Red400',
  'Red500',
  'Red600',
  'Red700',
  'Red800',
  'Red900',
  'Yellow50',
  'Yellow100',
  'Yellow200',
  'Yellow300',
  'Yellow400',
  'Yellow500',
  'Yellow600',
  'Yellow700',
  'Yellow800',
  'Yellow900',
  'Purple50',
  'Purple100',
  'Purple200',
  'Purple300',
  'Purple400',
  'Purple500',
  'Purple600',
  'Purple700',
  'Purple800',
  'Purple900',
  'VioletMbgAlert',
  'Pink50',
  'Pink100',
  'Pink200',
  'Pink300',
  'Pink400',
  'Pink500',
  'Pink600',
  'Pink700',
  'Pink800',
  'Pink900',
  'Sky25',
  'Sky50',
  'Sky100',
  'Sky200',
  'Sky300',
  'Sky400',
  'Sky500',
  'Sky600',
  'Sky700',
  'Sky800',
  'Sky900',
  'Lime50',
  'Lime100',
  'Lime200',
  'Lime300',
  'Lime400',
  'Lime500',
  'Lime600',
  'Lime700',
  'Lime800',
  'Lime900',
  'BusinessBlue50',
  'BusinessBlue100',
  'BusinessBlue200',
  'BusinessBlue300',
  'BusinessBlue400',
  'BusinessBlue500',
  'BusinessBlue600',
  'BusinessBlue700',
  'BusinessBlue800',
  'BusinessBlue900',
  'Opacity1',
  'Opacity2',
  'Opacity3',
  'Opacity4',
  'Opacity5',
  'Opacity6',
  'Opacity7',
  'Opacity8',
  'Opacity9',
  'OpacityDark1',
  'OpacityDark2',
  'OpacityDark3',
  'OpacityDark4',
  'OpacityDark5',
  'OpacityDark6',
  'OpacityDark7',
  'OpacityDark8',
  'OpacityDark9',
  'Black',
]);

const legacyColorMixins = new Set([
  'background',
  'backgroundActive',
  'backgroundHover',
  'backgroundOnLayer',
  'text',
  'textHover',
  'textActive',
  'subtleText',
  'placeholderText',
  'heading',
  'subtleHeading',
  'codeBlock',
  'link',
  'linkHover',
  'linkActive',
  'linkOutline',
  'primary',
  'blue',
  'teal',
  'purple',
  'red',
  'yellow',
  'green',
  'skeleton',
]);

const includesWholeWord = (value: string, options: Set<string>) => {
  const values = value
    .replace(/[^a-zA-Z ]/g, ' ')
    .trim()
    .split(/(?:,|\.| )+/);
  return values.some((value) => options.has(value));
};

export const isLegacyColor = (value: string) => legacyColors.has(value);
export const isLegacyNamedColor = (value: string) =>
  legacyColorMixins.has(value);

export const includesHardCodedColor = (raw: string): boolean => {
  const value = raw.toLowerCase();

  if (
    /#(?:[a-f0-9]{3}|[a-f0-9]{6}|[a-f0-9]{8})\b|((?:rgb|hsl)a?|(lch|lab|color))\([^\)]*\)/.exec(
      value.toLowerCase(),
    )
  ) {
    return true;
  }

  if (includesWholeWord(value, namedColors)) {
    return true;
  }

  return false;
};

export const isHardCodedColor = (value: string): boolean => {
  if (includesWholeWord(value.toLowerCase(), namedColors)) {
    return true;
  }

  if (
    value.startsWith('rgb(') ||
    value.startsWith('rgba(') ||
    value.startsWith('hsl(') ||
    value.startsWith('hsla(') ||
    value.startsWith('lch(') ||
    value.startsWith('lab(') ||
    value.startsWith('color(')
  ) {
    return true;
  }

  if (
    value.startsWith('#') &&
    // short hex, hex, or hex with alpha
    (value.length === 4 || value.length === 7 || value.length === 9)
  ) {
    return true;
  }

  return false;
};

const validColorPropertyNames = new Set([
  'color',
  'background',
  'background-color',
  'border',
  'border-left',
  'border-right',
  'border-top',
  'border-bottom',
  'border-color',
  'border-left-color',
  'border-right-color',
  'border-top-color',
  'border-bottom-color',
  'outline',
  'outline-color',
  'box-shadow',
]);

const kebabize = (str: string) =>
  str.replace(
    /[A-Z]+(?![a-z])|[A-Z]/g,
    ($, ofs) => (ofs ? '-' : '') + $.toLowerCase(),
  );

export const isColorCssPropertyName = (value: string): boolean =>
  validColorPropertyNames.has(kebabize(value));

export const isCurrentSurfaceCustomPropertyName = (value: string): boolean =>
  value === 'CURRENT_SURFACE_CSS_VAR' || value === CURRENT_SURFACE_CSS_VAR;
