/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'fabric.status.color.blue': 'Bleu',
  'fabric.status.color.green': 'Vert',
  'fabric.status.color.grey': 'Gris',
  'fabric.status.color.purple': 'Violet',
  'fabric.status.color.red': 'Rouge',
  'fabric.status.color.yellow': 'Jaune',
};
