/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'fabric.status.color.blue': 'Kék',
  'fabric.status.color.green': 'Zöld',
  'fabric.status.color.grey': 'Szürke',
  'fabric.status.color.purple': 'Lila',
  'fabric.status.color.red': 'Piros',
  'fabric.status.color.yellow': 'Sárga',
};
