/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Vietnamese (Vietnam)
export default {
  'fabric.status.color.blue': 'Xanh lam',
  'fabric.status.color.green': 'Xanh lục',
  'fabric.status.color.grey': 'Xám',
  'fabric.status.color.purple': 'Tím',
  'fabric.status.color.red': 'Đỏ',
  'fabric.status.color.yellow': 'Vàng',
  'fabric.status.input.label': 'Đặt trạng thái',
};
