/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Japanese
export default {
  'fabric.editor.alignCenter': '中央揃え',
  'fabric.editor.alignLeft': '左揃え',
  'fabric.editor.alignRight': '右揃え',
  'fabric.editor.alignment': 'テキストの配置',
  'fabric.editor.chromeCollapsedPlaceholder': '文字を入力…',
  'fabric.editor.closeFindReplaceDialog': '閉じる',
  'fabric.editor.configFailedToLoad': '読み込めませんでした',
  'fabric.editor.configPanel.cancel': 'キャンセル',
  'fabric.editor.configPanel.close': '閉じる',
  'fabric.editor.configPanel.customSelect.createOption': '作成',
  'fabric.editor.configPanel.dateRange.custom.from': '開始日',
  'fabric.editor.configPanel.dateRange.custom.to': '終了日',
  'fabric.editor.configPanel.dateRange.grouping.collapse': '折りたたむ',
  'fabric.editor.configPanel.dateRange.grouping.expand': '展開',
  'fabric.editor.configPanel.dateRange.option.custom': 'カスタム',
  'fabric.editor.configPanel.documentation': 'ドキュメント',
  'fabric.editor.configPanel.errorBoundary.title': '問題が発生しました。',
  'fabric.editor.configPanel.fieldTypeError.isMultipleAndRadio':
    '「isMultiple」と「style: radio」を組み合わせることはできません',
  'fabric.editor.configPanel.formType.addField': 'フィールドを追加',
  'fabric.editor.configPanel.formType.removeField': 'フィールドを削除',
  'fabric.editor.configPanel.invalid': '無効なフィールド',
  'fabric.editor.configPanel.required': '必須フィールド',
  'fabric.editor.configPanel.submit': '送信',
  'fabric.editor.decisionPlaceholder': '決定事項を追加…',
  'fabric.editor.edit': '編集',
  'fabric.editor.editorAssistiveLabel': 'メイン コンテンツ領域。入力を開始してテキストを入力します。',
  'fabric.editor.editors': '編集者',
  'fabric.editor.extension.confirmDeleteLinkedModalMessage':
    '{nodeName} を削除すると、接続されているすべてが破棄されます。',
  'fabric.editor.extension.confirmDeleteLinkedModalOKButton': '削除',
  'fabric.editor.extension.deleteElementTitle': '要素を削除',
  'fabric.editor.extensions.config-panel.save-indicator': 'すべての変更は常に自動保存されます',
  'fabric.editor.find': '検索',
  'fabric.editor.findNext': '次を検索',
  'fabric.editor.findPrevious': '前を検索',
  'fabric.editor.findReplaceToolbarButton': '検索と置換',
  'fabric.editor.floatingToolbar.confirmModalCheckboxLabel': '接続されている要素も削除',
  'fabric.editor.headingLink.toolbarHelpTitle': 'ヘルプ ダイアログを開く',
  'fabric.editor.indent': 'インデント',
  'fabric.editor.matchCase': '大文字/小文字を区別',
  'fabric.editor.noResultsFound': '該当する結果がありません',
  'fabric.editor.outdent': 'インデント解除',
  'fabric.editor.replace': '置換',
  'fabric.editor.replaceAll': 'すべて置換',
  'fabric.editor.replaceWith': '次で置換',
  'fabric.editor.resultsCount': '{totalResultsCount} 件中 {selectedMatchPosition} 件',
  'fabric.editor.selectLanguage': '言語を選択',
  'fabric.editor.taskPlaceholder': 'アクションを入力し、「@」を使用して担当者を割り当てます。',
};
