/* prettier-ignore */
/**
 * NOTE:
 *
 * This file is automatically generated by Traduki 2.0.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
//Ukrainian (Ukraine)
export default {
  'fabric.editor.alignCenter': 'Вирівнювання по центру',
  'fabric.editor.alignLeft': 'Вирівнювання по лівому краю',
  'fabric.editor.alignRight': 'Вирівнювання по правому краю',
  'fabric.editor.alignment': 'Вирівнювання тексту',
  'fabric.editor.chromeCollapsedPlaceholder': 'Введіть текст…',
  'fabric.editor.closeFindReplaceDialog': 'Закрити',
  'fabric.editor.configFailedToLoad': 'Помилка завантаження',
  'fabric.editor.configPanel.cancel': 'Скасувати',
  'fabric.editor.configPanel.close': 'Закрити',
  'fabric.editor.configPanel.customSelect.createOption': 'Створити',
  'fabric.editor.configPanel.dateRange.custom.from': 'З',
  'fabric.editor.configPanel.dateRange.custom.to': 'по',
  'fabric.editor.configPanel.dateRange.grouping.collapse': 'Згорнути',
  'fabric.editor.configPanel.dateRange.grouping.expand': 'Розгорнути',
  'fabric.editor.configPanel.dateRange.option.custom': 'Користувацькі',
  'fabric.editor.configPanel.documentation': 'Документація',
  'fabric.editor.configPanel.errorBoundary.title': 'Сталася помилка.',
  'fabric.editor.configPanel.fieldTypeError.isMultipleAndRadio': "Не можна поєднати об'єкт isMultiple зі стилем radio",
  'fabric.editor.configPanel.formType.addField': 'Додати поле',
  'fabric.editor.configPanel.formType.removeField': 'Видалити поле',
  'fabric.editor.configPanel.invalid': 'Недопустиме значення поля',
  'fabric.editor.configPanel.required': 'Обов’язкове поле',
  'fabric.editor.configPanel.submit': 'Надіслати',
  'fabric.editor.decisionPlaceholder': 'Додати рішення...',
  'fabric.editor.edit': 'Редагувати',
  'fabric.editor.editorAssistiveLabel': 'Основна область вмісту: почніть вводити текст.',
  'fabric.editor.editors': 'Редактори',
  'fabric.editor.extension.confirmDeleteLinkedModalMessage':
    'Видалення розширення {nodeName} порушить роботу всього, що з ним пов’язано.',
  'fabric.editor.extension.confirmDeleteLinkedModalOKButton': 'Видалити',
  'fabric.editor.extension.deleteElementTitle': 'Видалення елемента',
  'fabric.editor.extensions.config-panel.save-indicator': 'Усі зміни завжди зберігаються автоматично',
  'fabric.editor.find': 'Знайти',
  'fabric.editor.findNext': 'Знайти наступне',
  'fabric.editor.findPrevious': 'Знайти попереднє',
  'fabric.editor.findReplaceToolbarButton': 'Знайти й замінити',
  'fabric.editor.floatingToolbar.confirmModalCheckboxLabel': 'Видалити пов’язані елементи',
  'fabric.editor.headingLink.toolbarHelpTitle': 'Відкрити довідку',
  'fabric.editor.indent': 'Відступ вправо',
  'fabric.editor.matchCase': 'Враховувати регістр',
  'fabric.editor.noResultsFound': 'Немає результатів',
  'fabric.editor.outdent': 'Відступ вліво',
  'fabric.editor.replace': 'Замінити',
  'fabric.editor.replaceAll': 'Замінити всі',
  'fabric.editor.replaceWith': 'Замінити на',
  'fabric.editor.resultsCount': '{selectedMatchPosition} з {totalResultsCount}',
  'fabric.editor.selectLanguage': 'Вибір мови',
  'fabric.editor.taskPlaceholder': 'Вкажіть задачу. Призначте її комусь за допомогою символу «@».',
};
