export { Provider } from './provider';
export type {
  CollabParticipant,
  CollabEventInitData,
  CollabEventRemoteData,
  CollabEventConnectionData,
  CollabEventConnectingData,
  CollabEventDisconnectedData,
  CollabEventPresenceData,
  CollabEventTelepointerData,
  CollabEventLocalStepData,
  ResolvedEditorState,
  CollabConnectedPayload,
  CollabDisconnectedPayload,
  CollabInitPayload,
  CollabDataPayload,
  CollabTelepointerPayload,
  CollabPresencePayload,
  CollabMetadataPayload,
  CollabLocalStepsPayload,
  CollabEvents,
  CollabSendableSelection,
  CollabEditProvider,
  SyncUpErrorFunction,
  NewCollabSyncUpErrorAttributes,
  Socket,
  ProviderParticipant,
} from './types';
export type { ProviderError } from './errors/error-types';
export { PROVIDER_ERROR_CODE } from './errors/error-types';
