/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.elements.user-picker.email.add': 'Přidat uživatele',
  'fabric.elements.user-picker.email.add.potential':
    'Zadejte e-mailovou adresu osoby, kterou chcete pozvat',
  'fabric.elements.user-picker.email.select.to.add':
    'Vyberte adresu osoby, kterou chcete pozvat',
  'fabric.elements.user-picker.group.byline':
    'Skupina spravovaná administrátorem',
  'fabric.elements.user-picker.multi.remove-item': 'Odstranit',
  'fabric.elements.user-picker.placeholder': 'Zadejte osoby nebo týmy...',
  'fabric.elements.user-picker.placeholder.add-more': 'přidat více lidí...',
  'fabric.elements.user-picker.single.clear': 'Vymazat',
  'fabric.elements.user-picker.team.member.50plus': '50+ členů',
  'fabric.elements.user-picker.team.member.50plus.including.you':
    'Přes 50 členů, včetně vás',
  'fabric.elements.user-picker.team.member.count':
    '{count, plural, one {{count} člen} few {{count} členové} many {{count} člena} other {{count} členů}}',
  'fabric.elements.user-picker.team.member.count.including.you':
    '{count, plural, one {{count} člen (včetně vás)} few {{count} členové (včetně vás)} many {{count} člena (včetně vás)} other {{count} členů (včetně vás)}}',
};
