/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Swedish
export default {
  'fabric.elements.user-picker.email.add': 'Lägg till användare',
  'fabric.elements.user-picker.email.add.potential':
    'Ange e-postadress för inbjudan',
  'fabric.elements.user-picker.email.select.to.add': 'Välj för att bjuda in',
  'fabric.elements.user-picker.group.byline': 'Administratörshanterad grupp',
  'fabric.elements.user-picker.multi.remove-item': 'Ta bort',
  'fabric.elements.user-picker.placeholder': 'Ange personer eller team ...',
  'fabric.elements.user-picker.placeholder.add-more':
    'lägg till fler personer ...',
  'fabric.elements.user-picker.single.clear': 'Rensa',
  'fabric.elements.user-picker.team.member.50plus': '50+ medlemmar',
  'fabric.elements.user-picker.team.member.50plus.including.you':
    '50+ medlemmar, inklusive dig',
  'fabric.elements.user-picker.team.member.count':
    '{count, plural, one {{count} medlem} other {{count} medlemmar}}',
  'fabric.elements.user-picker.team.member.count.including.you':
    '{count, plural, one {{count} medlem, inklusive du} other {{count} medlemmar, inklusive du}}',
};
