/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Turkish
export default {
  'fabric.elements.user-picker.email.add': 'Kullanıcı ekleyin',
  'fabric.elements.user-picker.email.add.potential': 'Bir e-posta adresi girin',
  'fabric.elements.user-picker.email.select.to.add': 'Bir e-posta adresi seçin',
  'fabric.elements.user-picker.external.sourced.from': 'Bulunduğu yer:',
  'fabric.elements.user-picker.github.provider': 'GitHub',
  'fabric.elements.user-picker.google.provider': 'Google',
  'fabric.elements.user-picker.group.byline':
    'Yönetici tarafından yönetilen grup',
  'fabric.elements.user-picker.guest.lozenge.text': 'KONUK',
  'fabric.elements.user-picker.guest.lozenge.tooltip.group':
    'Konuk gruplar yalnızca bazı alanlara erişebilir ve kullanıcı bilgilerine erişimleri de kısıtlıdır.',
  'fabric.elements.user-picker.guest.lozenge.tooltip.user':
    'Konuklar yalnızca bazı alanlara erişebilir ve kullanıcı bilgilerine erişimleri de kısıtlıdır.',
  'fabric.elements.user-picker.member.lozenge.text': 'ÜYE',
  'fabric.elements.user-picker.microsoft.provider': 'Microsoft',
  'fabric.elements.user-picker.multi.remove-item': 'Kaldır',
  'fabric.elements.user-picker.placeholder': 'Kişi veya takım girin...',
  'fabric.elements.user-picker.placeholder.add-more':
    'daha fazla kişi ekleyin...',
  'fabric.elements.user-picker.single.clear': 'Temizle',
  'fabric.elements.user-picker.slack.provider': 'Slack',
  'fabric.elements.user-picker.team.member.50plus': "Takım • 50'den fazla üye",
  'fabric.elements.user-picker.team.member.50plus.including.you':
    "Takım • Siz de dahil olmak üzere 50'den fazla üye",
  'fabric.elements.user-picker.team.member.count':
    '{count, plural, one {Takım • {count} üye} other {Takım • {count} üye}}',
  'fabric.elements.user-picker.team.member.count.including.you':
    '{count, plural, one {Takım • Siz de dahil olmak üzere {count} üye} other {Takım • Siz de dahil olmak üzere {count} üye}}',
};
