/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Chinese
export default {
  'fabric.elements.user-picker.email.add': '添加用户',
  'fabric.elements.user-picker.email.add.potential': '输入电子邮件地址',
  'fabric.elements.user-picker.email.select.to.add': '选择电子邮件地址',
  'fabric.elements.user-picker.external.sourced.from': '发现位置：',
  'fabric.elements.user-picker.github.provider': 'GitHub',
  'fabric.elements.user-picker.google.provider': 'Google',
  'fabric.elements.user-picker.group.byline': '管理员管理的群组',
  'fabric.elements.user-picker.guest.lozenge.text': '访客',
  'fabric.elements.user-picker.guest.lozenge.tooltip.group':
    '访客群组只能访问特定的空间，并对用户信息具有有限的访问权限。',
  'fabric.elements.user-picker.guest.lozenge.tooltip.user':
    '访客只能访问特定的空间，并对用户信息具有有限的访问权限。',
  'fabric.elements.user-picker.member.lozenge.text': '成员',
  'fabric.elements.user-picker.microsoft.provider': 'Microsoft',
  'fabric.elements.user-picker.multi.remove-item': '删除',
  'fabric.elements.user-picker.placeholder': '输入人员或团队…',
  'fabric.elements.user-picker.placeholder.add-more': '添加更多人员...',
  'fabric.elements.user-picker.single.clear': '清除',
  'fabric.elements.user-picker.slack.provider': 'Slack',
  'fabric.elements.user-picker.team.member.50plus': '团队 • 50 多名成员',
  'fabric.elements.user-picker.team.member.50plus.including.you':
    '团队 • 50 多名成员，包括您',
  'fabric.elements.user-picker.team.member.count':
    '{count, plural, other {团队 • {count} 名成员}}',
  'fabric.elements.user-picker.team.member.count.including.you':
    '{count, plural, other {团队 • {count} 名成员，包括您}}',
};
