/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// undefined
export default {
  'fabric.elements.user-picker.email.add': '新增使用者',
  'fabric.elements.user-picker.email.add.potential': '輸入電子郵件以傳送邀請',
  'fabric.elements.user-picker.email.select.to.add': '選取以傳送邀請',
  'fabric.elements.user-picker.external.sourced.from': '尋找位置：',
  'fabric.elements.user-picker.google.provider': 'Google',
  'fabric.elements.user-picker.group.byline': '由系統管理員所管理的群組',
  'fabric.elements.user-picker.microsoft.provider': 'Microsoft',
  'fabric.elements.user-picker.multi.remove-item': '移除',
  'fabric.elements.user-picker.placeholder': '輸入人員或團隊...',
  'fabric.elements.user-picker.placeholder.add-more': '新增更多人員...',
  'fabric.elements.user-picker.single.clear': '清除',
  'fabric.elements.user-picker.slack.provider': 'Slack',
  'fabric.elements.user-picker.team.member.50plus': '50 位以上的成員',
  'fabric.elements.user-picker.team.member.50plus.including.you':
    '超過 50 位成員 (包括你)',
  'fabric.elements.user-picker.team.member.count':
    '{count, plural, other {{count} 位成員}}',
  'fabric.elements.user-picker.team.member.count.including.you':
    '{count, plural, other {{count} 位成員 (包括您)}}',
};
