import { wb, type WorkbenchExample } from '@atlassian/workbench';

import BoxBasicExample from './01-box-basic';
import BoxBasicCompiledExample from './01-box-basic-compiled';
import BoxCompiledVrExample from './02-box-compiled.vr.ap';
import BoxVrExample from './02-box.vr.ap';
import BoxPaddingCompiledVrExample from './03-box-padding-compiled.vr.ap';
import BoxPaddingVrExample from './03-box-padding.vr.ap';
import BoxBorderExample from './04-box-border';
import BoxBorderCompiledExample from './04-box-border-compiled';
import BoxColorCompiledVrExample from './05-box-color-compiled.vr.ap';
import BoxColorVrExample from './05-box-color.vr.ap';
import BoxFlexExample from './06-box-flex';
import BoxFlexCompiledExample from './06-box-flex-compiled';
import BoxCustomStylesCompiledVrExample from './07-box-custom-styles-compiled.vr.ap';
import BoxCustomStylesVrExample from './07-box-custom-styles.vr.ap';
import BoxSurfaceDetectionCompiledVrExample from './08-box-surface-detection-compiled.vr.ap';
import BoxSurfaceDetectionVrExample from './08-box-surface-detection.vr.ap';
import BoxClassnameExample from './09-box-classname';
import BoxClassnameCompiledExample from './09-box-classname-compiled';
import InlineBasicCompiledVrExample from './10-inline-basic-compiled.vr.ap';
import InlineBasicVrExample from './10-inline-basic.vr.ap';
import InlineExample from './11-inline';
import InlineSeparatorCompiledVrExample from './12-inline-separator-compiled.vr.ap';
import InlineSeparatorVrExample from './12-inline-separator.vr.ap';
import InlineSpaceCompiledVrExample from './12-inline-space-compiled.vr.ap';
import InlineSpaceVrExample from './12-inline-space.vr.ap';
import InlineAlignBlockCompiledVrExample from './13-inline-align-block-compiled.vr.ap';
import InlineAlignBlockVrExample from './13-inline-align-block.vr.ap';
import InlineAlignInlineCompiledVrExample from './14-inline-align-inline-compiled.vr.ap';
import InlineAlignInlineVrExample from './14-inline-align-inline.vr.ap';
import InlineSpreadCompiledVrExample from './15-inline-spread-compiled.vr.ap';
import InlineSpreadVrExample from './15-inline-spread.vr.ap';
import InlineShouldWrapCompiledVrExample from './16-inline-should-wrap-compiled.vr.ap';
import InlineShouldWrapVrExample from './16-inline-should-wrap.vr.ap';
import InlineGrowCompiledVrExample from './17-inline-grow-compiled.vr.ap';
import InlineGrowVrExample from './17-inline-grow.vr.ap';
import StackBasicCompiledVrExample from './20-stack-basic-compiled.vr.ap';
import StackBasicVrExample from './20-stack-basic.vr.ap';
import StackExample from './21-stack';
import StackCompiledExample from './21-stack-compiled';
import StackSpaceCompiledVrExample from './22-stack-space-compiled.vr.ap';
import StackSpaceVrExample from './22-stack-space.vr.ap';
import StackAlignBlockCompiledVrExample from './23-stack-align-block-compiled.vr.ap';
import StackAlignBlockVrExample from './23-stack-align-block.vr.ap';
import StackAlignInlineCompiledVrExample from './24-stack-align-inline-compiled.vr.ap';
import StackAlignInlineVrExample from './24-stack-align-inline.vr.ap';
import StackSpreadCompiledVrExample from './25-stack-spread-compiled.vr.ap';
import StackSpreadVrExample from './25-stack-spread.vr.ap';
import StackGrowCompiledVrExample from './26-stack-grow-compiled.vr.ap';
import StackGrowVrExample from './26-stack-grow.vr.ap';
import ClassnameBasicVrExample from './30-classname-basic.vr.ap';
import BoxAsExample from './31-box-as';
import XcssTypingExample from './31-xcss-typing';
import XcssMarginVrExample from './32-xcss-margin.vr.ap';
import XcssMediaQueriesExample from './40-xcss-media-queries';
import PressableDefaultCompiledVrExample from './41-pressable-default-compiled.vr.ap';
import PressableDefaultVrExample from './41-pressable-default.vr.ap';
import PressableStyledCompiledVrExample from './42-pressable-styled-compiled.vr.ap';
import PressableStyledVrExample from './42-pressable-styled.vr.ap';
import PressableCompiledGlobalStylesExample from './43-pressable-compiled-global-styles';
import PressableDisabledWithTooltipExample from './43-pressable-disabled-with-tooltip';
import AnchorDefaultCompiledVrExample from './44-anchor-default-compiled.vr.ap';
import AnchorDefaultVrExample from './44-anchor-default.vr.ap';
import AnchorStyledCompiledVrExample from './45-anchor-styled-compiled.vr.ap';
import AnchorStyledVrExample from './45-anchor-styled.vr.ap';
import AnchorConfiguredExample from './46-anchor-configured';
import AnchorNewWindowCompiledVrExample from './47-anchor-new-window-compiled.vr.ap';
import AnchorNewWindowVrExample from './47-anchor-new-window.vr.ap';
import AnchorPositioningVrExample from './48-anchor-positioning.vr.ap';
import AnchorCompiledGlobalStylesExample from './49-anchor-compiled-global-styles';
import UseMediaQueryCompiledVrExample from './50-use-media-query-compiled.vr.ap';
import UseMediaQueryVrExample from './50-use-media-query.vr.ap';
import ResponsiveShowHideCompiledVrExample from './51-responsive-show-hide-compiled.vr.ap';
import ResponsiveShowHideVrExample from './51-responsive-show-hide.vr.ap';
import GridExample from './60-grid';
import GridCompiledExample from './60-grid-compiled';
import FlexCompiledVrExample from './61-flex-compiled.vr.ap';
import FlexVrExample from './61-flex.vr.ap';
import GridGapCompiledVrExample from './62-grid-gap-compiled.vr.ap';
import GridGapVrExample from './62-grid-gap.vr.ap';
import BleedCompiledVrExample from './63-bleed-compiled.vr.ap';
import BleedVrExample from './63-bleed.vr.ap';
import TextCompiledVrExample from './70-text-compiled.vr.ap';
import TextVrExample from './70-text.vr.ap';
import TextColorCompiledVrExample from './71-text-color-compiled.vr.ap';
import TextColorVrExample from './71-text-color.vr.ap';
import TextTruncationCompiledVrExample from './72-text-truncation-compiled.vr.ap';
import TextTruncationVrExample from './72-text-truncation.vr.ap';
import MetricTextCompiledVrExample from './73-metric-text-compiled.vr.ap';
import MetricTextVrExample from './73-metric-text.vr.ap';
import FocusableVrExample from './80-focusable.vr.ap';

const BoxBasic: WorkbenchExample = wb(BoxBasicExample);

export default BoxBasic;
export const BoxBasicCompiled: WorkbenchExample = wb(BoxBasicCompiledExample);
export const BoxCompiledVr: WorkbenchExample = wb(BoxCompiledVrExample);
export const BoxVr: WorkbenchExample = wb(BoxVrExample);
export const BoxPaddingCompiledVr: WorkbenchExample = wb(BoxPaddingCompiledVrExample);
export const BoxPaddingVr: WorkbenchExample = wb(BoxPaddingVrExample);
export const BoxBorder: WorkbenchExample = wb(BoxBorderExample);
export const BoxBorderCompiled: WorkbenchExample = wb(BoxBorderCompiledExample);
export const BoxColorCompiledVr: WorkbenchExample = wb(BoxColorCompiledVrExample);
export const BoxColorVr: WorkbenchExample = wb(BoxColorVrExample);
export const BoxFlex: WorkbenchExample = wb(BoxFlexExample);
export const BoxFlexCompiled: WorkbenchExample = wb(BoxFlexCompiledExample);
export const BoxCustomStylesCompiledVr: WorkbenchExample = wb(BoxCustomStylesCompiledVrExample);
export const BoxCustomStylesVr: WorkbenchExample = wb(BoxCustomStylesVrExample);
export const BoxSurfaceDetectionCompiledVr: WorkbenchExample = wb(
	BoxSurfaceDetectionCompiledVrExample,
);
export const BoxSurfaceDetectionVr: WorkbenchExample = wb(BoxSurfaceDetectionVrExample);
export const BoxClassname: WorkbenchExample = wb(BoxClassnameExample);
export const BoxClassnameCompiled: WorkbenchExample = wb(BoxClassnameCompiledExample);
export const InlineBasicCompiledVr: WorkbenchExample = wb(InlineBasicCompiledVrExample);
export const InlineBasicVr: WorkbenchExample = wb(InlineBasicVrExample);
export const Inline: WorkbenchExample = wb(InlineExample);
export const InlineSeparatorCompiledVr: WorkbenchExample = wb(InlineSeparatorCompiledVrExample);
export const InlineSeparatorVr: WorkbenchExample = wb(InlineSeparatorVrExample);
export const InlineSpaceCompiledVr: WorkbenchExample = wb(InlineSpaceCompiledVrExample);
export const InlineSpaceVr: WorkbenchExample = wb(InlineSpaceVrExample);
export const InlineAlignBlockCompiledVr: WorkbenchExample = wb(InlineAlignBlockCompiledVrExample);
export const InlineAlignBlockVr: WorkbenchExample = wb(InlineAlignBlockVrExample);
export const InlineAlignInlineCompiledVr: WorkbenchExample = wb(InlineAlignInlineCompiledVrExample);
export const InlineAlignInlineVr: WorkbenchExample = wb(InlineAlignInlineVrExample);
export const InlineSpreadCompiledVr: WorkbenchExample = wb(InlineSpreadCompiledVrExample);
export const InlineSpreadVr: WorkbenchExample = wb(InlineSpreadVrExample);
export const InlineShouldWrapCompiledVr: WorkbenchExample = wb(InlineShouldWrapCompiledVrExample);
export const InlineShouldWrapVr: WorkbenchExample = wb(InlineShouldWrapVrExample);
export const InlineGrowCompiledVr: WorkbenchExample = wb(InlineGrowCompiledVrExample);
export const InlineGrowVr: WorkbenchExample = wb(InlineGrowVrExample);
export const StackBasicCompiledVr: WorkbenchExample = wb(StackBasicCompiledVrExample);
export const StackBasicVr: WorkbenchExample = wb(StackBasicVrExample);
export const Stack: WorkbenchExample = wb(StackExample);
export const StackCompiled: WorkbenchExample = wb(StackCompiledExample);
export const StackSpaceCompiledVr: WorkbenchExample = wb(StackSpaceCompiledVrExample);
export const StackSpaceVr: WorkbenchExample = wb(StackSpaceVrExample);
export const StackAlignBlockCompiledVr: WorkbenchExample = wb(StackAlignBlockCompiledVrExample);
export const StackAlignBlockVr: WorkbenchExample = wb(StackAlignBlockVrExample);
export const StackAlignInlineCompiledVr: WorkbenchExample = wb(StackAlignInlineCompiledVrExample);
export const StackAlignInlineVr: WorkbenchExample = wb(StackAlignInlineVrExample);
export const StackSpreadCompiledVr: WorkbenchExample = wb(StackSpreadCompiledVrExample);
export const StackSpreadVr: WorkbenchExample = wb(StackSpreadVrExample);
export const StackGrowCompiledVr: WorkbenchExample = wb(StackGrowCompiledVrExample);
export const StackGrowVr: WorkbenchExample = wb(StackGrowVrExample);
export const ClassnameBasicVr: WorkbenchExample = wb(ClassnameBasicVrExample);
export const BoxAs: WorkbenchExample = wb(BoxAsExample);
export const XcssTyping: WorkbenchExample = wb(XcssTypingExample);
export const XcssMarginVr: WorkbenchExample = wb(XcssMarginVrExample);
export const XcssMediaQueries: WorkbenchExample = wb(XcssMediaQueriesExample);
export const PressableDefaultCompiledVr: WorkbenchExample = wb(PressableDefaultCompiledVrExample);
export const PressableDefaultVr: WorkbenchExample = wb(PressableDefaultVrExample);
export const PressableStyledCompiledVr: WorkbenchExample = wb(PressableStyledCompiledVrExample);
export const PressableStyledVr: WorkbenchExample = wb(PressableStyledVrExample);
export const PressableCompiledGlobalStyles: WorkbenchExample = wb(
	PressableCompiledGlobalStylesExample,
);
export const PressableDisabledWithTooltip: WorkbenchExample = wb(
	PressableDisabledWithTooltipExample,
);
export const AnchorDefaultCompiledVr: WorkbenchExample = wb(AnchorDefaultCompiledVrExample);
export const AnchorDefaultVr: WorkbenchExample = wb(AnchorDefaultVrExample);
export const AnchorStyledCompiledVr: WorkbenchExample = wb(AnchorStyledCompiledVrExample);
export const AnchorStyledVr: WorkbenchExample = wb(AnchorStyledVrExample);
export const AnchorConfigured: WorkbenchExample = wb(AnchorConfiguredExample);
export const AnchorNewWindowCompiledVr: WorkbenchExample = wb(AnchorNewWindowCompiledVrExample);
export const AnchorNewWindowVr: WorkbenchExample = wb(AnchorNewWindowVrExample);
export const AnchorPositioningVr: WorkbenchExample = wb(AnchorPositioningVrExample);
export const AnchorCompiledGlobalStyles: WorkbenchExample = wb(AnchorCompiledGlobalStylesExample);
export const UseMediaQueryCompiledVr: WorkbenchExample = wb(UseMediaQueryCompiledVrExample);
export const UseMediaQueryVr: WorkbenchExample = wb(UseMediaQueryVrExample);
export const ResponsiveShowHideCompiledVr: WorkbenchExample = wb(
	ResponsiveShowHideCompiledVrExample,
);
export const ResponsiveShowHideVr: WorkbenchExample = wb(ResponsiveShowHideVrExample);
export const Grid: WorkbenchExample = wb(GridExample);
export const GridCompiled: WorkbenchExample = wb(GridCompiledExample);
export const FlexCompiledVr: WorkbenchExample = wb(FlexCompiledVrExample);
export const FlexVr: WorkbenchExample = wb(FlexVrExample);
export const GridGapCompiledVr: WorkbenchExample = wb(GridGapCompiledVrExample);
export const GridGapVr: WorkbenchExample = wb(GridGapVrExample);
export const BleedCompiledVr: WorkbenchExample = wb(BleedCompiledVrExample);
export const BleedVr: WorkbenchExample = wb(BleedVrExample);
export const TextCompiledVr: WorkbenchExample = wb(TextCompiledVrExample);
export const TextVr: WorkbenchExample = wb(TextVrExample);
export const TextColorCompiledVr: WorkbenchExample = wb(TextColorCompiledVrExample);
export const TextColorVr: WorkbenchExample = wb(TextColorVrExample);
export const TextTruncationCompiledVr: WorkbenchExample = wb(TextTruncationCompiledVrExample);
export const TextTruncationVr: WorkbenchExample = wb(TextTruncationVrExample);
export const MetricTextCompiledVr: WorkbenchExample = wb(MetricTextCompiledVrExample);
export const MetricTextVr: WorkbenchExample = wb(MetricTextVrExample);
export const FocusableVr: WorkbenchExample = wb(FocusableVrExample);
