/**
 * THIS FILE WAS CREATED VIA CODEGEN DO NOT MODIFY {@see http://go/af-codegen}
 *
 * Token names mapped to their value in the default Atlassian themes ('light spacing').
 * These default values are used by the Babel plugin to optionally provide automatic fallbacks.
 *
 * @codegen <<SignedSource::05c2fcc3d0dba0931605dc98f7540009>>
 * @codegenCommand yarn build tokens
 */
const defaultTokenValues = {
  'spacing.scale.0': '0px',
  'spacing.scale.100': '8px',
  'spacing.scale.150': '12px',
  'spacing.scale.200': '16px',
  'spacing.scale.250': '20px',
  'spacing.scale.300': '24px',
  'spacing.scale.400': '32px',
  'spacing.scale.500': '40px',
  'spacing.scale.600': '48px',
  'spacing.scale.025': '2px',
  'spacing.scale.050': '4px',
  'spacing.scale.075': '6px',
  'spacing.scaleLinear.0': '0px',
  'spacing.scaleLinear.100': '2px',
  'spacing.scaleLinear.200': '4px',
  'spacing.scaleLinear.300': '6px',
  'spacing.scaleLinear.400': '8px',
  'spacing.scaleLinear.500': '12px',
  'spacing.scaleLinear.600': '16px',
  'spacing.scaleLinear.700': '20px',
  'spacing.scaleLinear.800': '24px',
  'spacing.scaleLinear.900': '32px',
  'spacing.scaleLinear.1000': '40px',
  'spacing.scaleLinear.1100': '48px',
  'spacing.pixel.0': '0px',
  'spacing.pixel.2': '2px',
  'spacing.pixel.4': '4px',
  'spacing.pixel.6': '6px',
  'spacing.pixel.8': '8px',
  'spacing.pixel.12': '12px',
  'spacing.pixel.16': '16px',
  'spacing.pixel.20': '20px',
  'spacing.pixel.24': '24px',
  'spacing.pixel.32': '32px',
  'spacing.pixel.40': '40px',
  'spacing.pixel.48': '48px',
  'spacing.size.none': '0px',
  'spacing.size.xxxxSmall': '2px',
  'spacing.size.xxxSmall': '4px',
  'spacing.size.xxSmall': '6px',
  'spacing.size.xsmall': '8px',
  'spacing.size.small': '12px',
  'spacing.size.medium': '16px',
  'spacing.size.large': '20px',
  'spacing.size.xlarge': '24px',
  'spacing.size.xxlarge': '32px',
  'spacing.size.xxxlarge': '40px',
  'spacing.size.xxxxlarge': '48px',
  'spacing.ecl.element.2': '2px',
  'spacing.ecl.element.4': '4px',
  'spacing.ecl.element.6': '6px',
  'spacing.ecl.element.8': '8px',
  'spacing.ecl.container.12': '12px',
  'spacing.ecl.container.16': '16px',
  'spacing.ecl.container.20': '20px',
  'spacing.ecl.container.24': '24px',
  'spacing.ecl.layout.32': '32px',
  'spacing.ecl.layout.40': '40px',
  'spacing.ecl.layout.64': '48px',
  'spacing.ccc.component.2': '2px',
  'spacing.ccc.component.4': '4px',
  'spacing.ccc.component.6': '6px',
  'spacing.ccc.component.8': '8px',
  'spacing.ccc.content.12': '12px',
  'spacing.ccc.content.16': '16px',
  'spacing.ccc.content.20': '20px',
  'spacing.ccc.content.24': '24px',
  'spacing.ccc.container.32': '32px',
  'spacing.ccc.container.40': '40px',
  'spacing.ccc.container.48': '48px',
  'spacing.gap.100': '8px',
  'spacing.gap.200': '16px',
  'spacing.gap.300': '24px',
  'spacing.inset.100': '8px',
  'spacing.inset.200': '16px',
  'spacing.inset.300': '24px',
} as const;

export default defaultTokenValues;
