// THIS FILE IS GENERATED via packages/editor/editor-plugins/scripts/update-editor-plugins.ts. DO NOT MODIFY IT MANUALLY.
// Disable no-re-export rule for entry point files
/* eslint-disable @atlaskit/editor/no-re-export */
export {
	RESIZE_HANDLE_AREA_DECORATION_GAP,
	TableCssClassName,
	TableDecorations,
} from '@atlaskit/editor-plugin-table/types';
export type {
	ActiveTableMenu,
	AlignmentOptions,
	Cell,
	CellColumnPositioning,
	CellHoverMeta,
	CellTransform,
	ColumnResizingPluginAction,
	ColumnResizingPluginState,
	DraggableBehaviour,
	DraggableData,
	DraggableSourceData,
	DraggableTargetData,
	DraggableType,
	HandleTypes,
	InsertRowMethods,
	InsertRowOptions,
	InvalidNodeAttr,
	MessageDescriptor,
	PermittedLayoutsDescriptor,
	PluginConfig,
	PluginInjectionAPI,
	PluginInjectionAPIWithA11y,
	ReportInvalidNodeAttrs,
	RowInsertPosition,
	TableDirection,
	TablePluginAction,
	TablePluginState,
	TableSharedState,
	TableSharedStateInternal,
	ToolbarMenuConfig,
	ToolbarMenuContext,
	ToolbarMenuState,
	WidthToWidest,
} from '@atlaskit/editor-plugin-table/types';
