/**
 * THIS FILE WAS CREATED VIA CODEGEN DO NOT MODIFY {@see http://go/af-codegen}
 *
 * Extract component prop types from UIKit 2 components - BannerProps
 *
 * @codegen <<SignedSource::32a3f367a074a452bcac5a7bb21de36b>>
 * @codegenCommand yarn workspace @atlaskit/forge-react-types codegen
 * @codegenDependency ../../../../forge-ui/src/components/UIKit/banner/index.tsx <<SignedSource::9e531cb603b63fc5517ef7c0efe867f1>>
 */
/* eslint @repo/internal/codegen/signed-source-integrity: "warn" */

import React from 'react';
import PlatformBanner from '@atlaskit/banner';

type PlatformBannerProps = React.ComponentProps<typeof PlatformBanner>;

// TODO: File had to be manually updated as code gen is not correctly creating the Icon type
export type Icon =
	| 'activity'
	| 'add'
	| 'add-circle'
	| 'add-item'
	| 'addon'
	| 'app-access'
	| 'app-switcher'
	| 'archive'
	| 'arrow-down'
	| 'arrow-down-circle'
	| 'arrow-left'
	| 'arrow-left-circle'
	| 'arrow-right'
	| 'arrow-right-circle'
	| 'arrow-up'
	| 'arrow-up-circle'
	| 'attachment'
	| 'audio'
	| 'audio-circle'
	| 'backlog'
	| 'billing'
	| 'billing-filled'
	| 'bitbucket-branches'
	| 'bitbucket-builds'
	| 'bitbucket-clone'
	| 'bitbucket-commits'
	| 'bitbucket-compare'
	| 'bitbucket-forks'
	| 'bitbucket-output'
	| 'bitbucket-pipelines'
	| 'bitbucket-pullrequests'
	| 'bitbucket-repos'
	| 'bitbucket-snippets'
	| 'bitbucket-source'
	| 'board'
	| 'book'
	| 'bucket'
	| 'calendar'
	| 'calendar-filled'
	| 'camera'
	| 'camera-filled'
	| 'camera-rotate'
	| 'camera-take-photo'
	| 'canvas'
	| 'check'
	| 'check-circle'
	| 'check-circle-outline'
	| 'chevron-down'
	| 'chevron-down-circle'
	| 'chevron-left'
	| 'chevron-left-circle'
	| 'chevron-right'
	| 'chevron-right-circle'
	| 'chevron-up'
	| 'chevron-up-circle'
	| 'child-issues'
	| 'code'
	| 'comment'
	| 'component'
	| 'copy'
	| 'creditcard'
	| 'creditcard-filled'
	| 'cross'
	| 'cross-circle'
	| 'customer'
	| 'dashboard'
	| 'decision'
	| 'department'
	| 'detail-view'
	| 'documents'
	| 'download'
	| 'drag-handler'
	| 'drop-down-arrow'
	| 'edit'
	| 'edit-filled'
	| 'email'
	| 'emoji'
	| 'emoji-add'
	| 'emoji-atlassian'
	| 'emoji-custom'
	| 'emoji-flags'
	| 'emoji-food'
	| 'emoji-frequent'
	| 'emoji-keyboard'
	| 'emoji-nature'
	| 'emoji-objects'
	| 'emoji-people'
	| 'emoji-productivity'
	| 'emoji-symbols'
	| 'emoji-travel'
	| 'error'
	| 'expand'
	| 'export'
	| 'feedback'
	| 'file'
	| 'followers'
	| 'following'
	| 'gif'
	| 'googledrive'
	| 'graph-bar'
	| 'graph-line'
	| 'gsuite'
	| 'hipchat-audio-only'
	| 'hipchat-chevron-double-down'
	| 'hipchat-chevron-double-up'
	| 'hipchat-chevron-down'
	| 'hipchat-chevron-up'
	| 'hipchat-dial-out'
	| 'hipchat-lobby'
	| 'hipchat-media-attachment-count'
	| 'hipchat-outgoing-sound'
	| 'hipchat-sd-video'
	| 'hipchat-upload'
	| 'hipchat-video'
	| 'home'
	| 'home-circle'
	| 'image'
	| 'image-border'
	| 'image-resize'
	| 'info'
	| 'invite-team'
	| 'issue'
	| 'issue-raise'
	| 'jira-capture'
	| 'jira-draft'
	| 'jira-epic'
	| 'jira-failed-build-status'
	| 'jira-labs'
	| 'jira-subtask'
	| 'jira-test-session'
	| 'label'
	| 'lightbulb'
	| 'lightbulb-filled'
	| 'like'
	| 'link'
	| 'list'
	| 'location'
	| 'lock'
	| 'lock-circle'
	| 'lock-filled'
	| 'media-services-actual-size'
	| 'media-services-add-comment'
	| 'media-services-annotate'
	| 'media-services-arrow'
	| 'media-services-blur'
	| 'media-services-brush'
	| 'media-services-button'
	| 'media-services-code'
	| 'media-services-collapse'
	| 'media-services-color'
	| 'media-services-document'
	| 'media-services-embed-link'
	| 'media-services-expand'
	| 'media-services-external-link'
	| 'media-services-fit-to-page'
	| 'media-services-full-screen'
	| 'media-services-grid'
	| 'media-services-image'
	| 'media-services-line'
	| 'media-services-no-image'
	| 'media-services-open-mediaviewer'
	| 'media-services-oval'
	| 'media-services-pdf'
	| 'media-services-preselect'
	| 'media-services-presentation'
	| 'media-services-rectangle'
	| 'media-services-scale-large'
	| 'media-services-scale-small'
	| 'media-services-spreadsheet'
	| 'media-services-text'
	| 'media-services-triangle'
	| 'media-services-unknown'
	| 'media-services-video'
	| 'media-services-zip'
	| 'media-services-zoom-in'
	| 'media-services-zoom-out'
	| 'mention'
	| 'menu'
	| 'menu-expand'
	| 'mobile'
	| 'more'
	| 'more-vertical'
	| 'notification'
	| 'notification-all'
	| 'notification-direct'
	| 'office-building'
	| 'office-building-filled'
	| 'open'
	| 'overview'
	| 'page'
	| 'page-filled'
	| 'people'
	| 'people-group'
	| 'person'
	| 'person-circle'
	| 'person-with-circle'
	| 'person-with-cross'
	| 'person-with-tick'
	| 'portfolio'
	| 'premium'
	| 'presences-busy'
	| 'presences-offline'
	| 'presences-online'
	| 'priority-blocker'
	| 'priority-critical'
	| 'priority-high'
	| 'priority-highest'
	| 'priority-low'
	| 'priority-lowest'
	| 'priority-major'
	| 'priority-medium'
	| 'priority-minor'
	| 'priority-trivial'
	| 'priority-undefined'
	| 'question'
	| 'question-circle'
	| 'queues'
	| 'quote'
	| 'radio'
	| 'recent'
	| 'redo'
	| 'refresh'
	| 'roadmap'
	| 'room-menu'
	| 'schedule'
	| 'schedule-filled'
	| 'screen'
	| 'search'
	| 'send'
	| 'settings'
	| 'share'
	| 'ship'
	| 'shortcut'
	| 'sign-in'
	| 'sign-out'
	| 'sprint'
	| 'star'
	| 'star-filled'
	| 'star-large'
	| 'status-information'
	| 'status-error'
	| 'status-warning'
	| 'stopwatch'
	| 'subtask'
	| 'suitcase'
	| 'switch'
	| 'table'
	| 'tag'
	| 'task'
	| 'teams'
	| 'thumbs-down'
	| 'thumbs-up'
	| 'trash'
	| 'tray'
	| 'undo'
	| 'unlink'
	| 'unlock'
	| 'upload'
	| 'user-avatar-circle'
	| 'vid-audio-muted'
	| 'vid-audio-on'
	| 'vid-camera-off'
	| 'vid-camera-on'
	| 'vid-connection-circle'
	| 'vid-full-screen-off'
	| 'vid-full-screen-on'
	| 'vid-hang-up'
	| 'vid-hd-circle'
	| 'vid-minus'
	| 'vid-pause'
	| 'vid-play'
	| 'vid-raised-hand'
	| 'vid-share-screen'
	| 'vid-speaking-circle'
	| 'vid-volume-full'
	| 'vid-volume-half'
	| 'vid-volume-muted'
	| 'warning'
	| 'watch'
	| 'watch-filled'
	| 'world'
	| 'world-small';

type IconType = Icon;

export type BannerProps = Pick<PlatformBannerProps, 'appearance' | 'children' | 'testId'> & {
	/**
	 * Places an icon within the banner, before the banner's text.
	 */
	icon?: IconType;
};

/**
 * A banner displays a prominent message at the top of the screen.
 *
 * @see [Banner](https://developer.atlassian.com/platform/forge/ui-kit/components/banner/) in UI Kit documentation for more information
 */
export type TBanner<T> = (props: BannerProps) => T;
