import { changeImportEntryPoint } from '@atlaskit/codemod-utils';

export const updateImportEntryPointsForJiraSchema = [
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'createJIRASchema',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithLists',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithMentions',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithEmojis',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithLinks',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithAdvancedTextFormattingMarks',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithCodeBlock',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithBlockQuotes',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithMedia',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithSubSupMark',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithTextColor',
    '@atlaskit/adf-schema/schema-jira',
  ),
  changeImportEntryPoint(
    '@atlaskit/adf-schema',
    'isSchemaWithTables',
    '@atlaskit/adf-schema/schema-jira',
  ),
];
